"""
Single source of truth for restd module coverage spreadsheet.
Consumed by build_workbook_v2.py.

Per the spreadsheet style guide, every public symbol of every covered
std header is one Symbol record here. Pending Dependencies and Coverage
Failures sheets are auto-derived from the depends_on and failure_reason
fields below.
"""
from collections import namedtuple

Symbol = namedtuple("Symbol", [
    "name", "group",
    "std_in", "restd_min",
    "constexpr_in_std", "constexpr_in_restd",
    "intrinsic_required", "intrinsic_names", "detection_macro",
    "t_alias_in", "v_var_in", "deprecated_in",
    "notes", "depends_on", "failure_reason",
])

def S(name, group, std_in=None, restd_min=None,
      constexpr_in_std=None, constexpr_in_restd=None,
      intrinsic_required=False, intrinsic_names="", detection_macro="",
      t_alias_in=None, v_var_in=None, deprecated_in=None,
      notes="", depends_on=(), failure_reason=None):
    return Symbol(name, group, std_in, restd_min,
                  constexpr_in_std, constexpr_in_restd,
                  intrinsic_required, intrinsic_names, detection_macro,
                  t_alias_in, v_var_in, deprecated_in,
                  notes, tuple(depends_on), failure_reason)


SYMBOLS_ANY = [
    S(
        'any', 'Class',
        std_in='C++17',
        restd_min='C++11',
        constexpr_in_std='C++17',
        constexpr_in_restd='C++14',
        notes='Type-erased value container. SBO path is constexpr on C++14+ for trivial fundamentals; heap path is runtime only.',
        failure_reason='Requires variadic templates + rvalue refs for the forwarding ctors and SFINAE-dispatched storage category. C++98/03 path is planned but not yet shipped (see RESTD_AGENT_README known issues).',
    ),
    S(
        'any_cast', 'Free functions',
        std_in='C++17',
        restd_min='C++11',
        notes='Three overloads (T, T&, T*); the pointer form is noexcept.',
    ),
    S(
        'make_any', 'Free functions',
        std_in='C++17',
        restd_min='C++11',
        notes='Forwarding factory. Requires variadic templates + perfect forwarding.',
    ),
    S(
        'swap (any)', 'Free functions',
        std_in='C++17',
        restd_min='C++11',
        notes='ADL-friendly swap overload.',
    ),
    S(
        'bad_any_cast', 'Exception',
        std_in='C++17',
        restd_min='C++98',
        notes='Inherits std::bad_cast. Gated on D_ENV_CPP98_HAS_TYPEINFO.',
    ),
]

SYMBOLS_TUPLE = [
    S(
        'tuple_size', 'Helper traits',
        std_in='C++11',
        restd_min='C++11',
        v_var_in='C++17',
        notes='Cv-qualified passthrough specialisations per LWG 2762.',
    ),
    S(
        'tuple_element', 'Helper traits',
        std_in='C++11',
        restd_min='C++11',
        t_alias_in='C++14',
        notes='Recursive partial specialisations; cv-qualified passthrough per LWG 2762.',
    ),
    S(
        'tuple', 'Tuple class',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++11',
        notes='Recursive-inheritance design with EBO for empty element types. Members: ctor, op=, swap.',
        failure_reason='Requires variadic templates and rvalue references (C++11+). No portable C++98/03 implementation is planned; the restd::pair already covers two-element aggregation on that tier.',
    ),
    S(
        'get<I>(tuple)', 'Element access',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++11',
        notes='Index-based access. Four value-category overloads.',
    ),
    S(
        'get<T>(tuple)', 'Element access',
        std_in='C++14',
        restd_min='C++14',
        constexpr_in_std='C++14',
        notes='Type-based access. SFINAE-rejected if T appears 0 or >1 times in the element pack.',
    ),
    S(
        'make_tuple', 'Factories',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++11',
        notes='Decay-and-deduce factory. reference_wrapper unwrap pending restd::reference_wrapper.',
        depends_on=('reference_wrapper',),
    ),
    S(
        'tie', 'Factories',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++14',
        notes='Tuple of lvalue refs; pairs with the ignore object for destructuring.',
    ),
    S(
        'forward_as_tuple', 'Factories',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++14',
        notes='Tuple of forwarding refs. Result must be consumed before any temporaries die.',
    ),
    S(
        'tuple_cat', 'Concatenation',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++14',
        notes='Pair-wise reduction over an internal index_seq machinery (private until restd::utility lands).',
        depends_on=('index_sequence',),
    ),
    S(
        'apply', 'Apply / make_from_tuple',
        std_in='C++17',
        restd_min='C++11',
        constexpr_in_std='C++17',
        constexpr_in_restd='C++14',
        notes='Currently uses direct call syntax; pointer-to-member callables pending restd::invoke.',
        depends_on=('invoke',),
    ),
    S(
        'make_from_tuple', 'Apply / make_from_tuple',
        std_in='C++17',
        restd_min='C++11',
        constexpr_in_std='C++17',
        constexpr_in_restd='C++14',
        notes='Construct T from tuple elements as ctor args.',
    ),
    S(
        'operator==', 'Comparison',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++14',
        notes='Lexicographic equality across paired elements.',
    ),
    S(
        'operator!=', 'Comparison',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++14',
        deprecated_in='C++20',
        notes='Defaulted via op== since C++20; restd ships explicit overload for portability.',
    ),
    S(
        'operator<', 'Comparison',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++14',
        notes='Lexicographic less-than.',
    ),
    S(
        'operator<=', 'Comparison',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++14',
        deprecated_in='C++20',
        notes='Synthesised from op< since C++20; restd ships explicit overload.',
    ),
    S(
        'operator>', 'Comparison',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++14',
        deprecated_in='C++20',
        notes='Synthesised from op< since C++20; restd ships explicit overload.',
    ),
    S(
        'operator>=', 'Comparison',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++14',
        deprecated_in='C++20',
        notes='Synthesised from op< since C++20; restd ships explicit overload.',
    ),
    S(
        'operator<=>', 'Comparison',
        std_in='C++20',
        restd_min=None,
        constexpr_in_std='C++20',
        notes='C++20 spaceship. NOT yet implemented in restd.',
        depends_on=('three_way_comparable',),
        failure_reason='Requires the C++20 three_way_comparable concept and <compare> ordering categories. Pending restd::compare.',
    ),
    S(
        'swap (non-member)', 'Swap',
        std_in='C++11',
        restd_min='C++11',
        notes='ADL-friendly free swap delegating to the member swap.',
    ),
    S(
        'ignore', 'Ignore object',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++14',
        notes='Sink object whose op= discards any value. For use with tie().',
    ),
    S(
        'tuple(allocator_arg, ...)', 'Allocator interop',
        std_in='C++11',
        restd_min=None,
        notes='Allocator-extended ctor overloads.',
        depends_on=('allocator_arg_t', 'uses_allocator'),
        failure_reason='Pending restd::allocator_arg_t and uses_allocator infrastructure.',
    ),
    S(
        'uses_allocator<tuple,A>', 'Allocator interop',
        std_in='C++11',
        restd_min=None,
        v_var_in='C++17',
        notes='Allocator-aware trait specialisation.',
        depends_on=('uses_allocator',),
        failure_reason='Pending restd::uses_allocator.',
    ),
]

SYMBOLS_TYPE_TRAITS = [
    S(
        'integral_constant', 'Helper classes',
        std_in='C++11',
        restd_min='C++98',
        notes='Foundation: holds compile-time value. ::value out-of-class for ODR safety.',
    ),
    S(
        'true_type', 'Helper classes',
        std_in='C++11',
        restd_min='C++98',
        notes='Alias for integral_constant<bool,true>.',
    ),
    S(
        'false_type', 'Helper classes',
        std_in='C++11',
        restd_min='C++98',
        notes='Alias for integral_constant<bool,false>.',
    ),
    S(
        'bool_constant', 'Helper classes',
        std_in='C++17',
        restd_min='C++11',
        t_alias_in='C++11',
        notes='Requires alias templates. C++11+ only.',
        failure_reason='Alias templates introduced in C++11; cannot shim further.',
    ),
    S(
        'enable_if', 'SFINAE / Control',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Primary SFINAE primitive.',
    ),
    S(
        'conditional', 'SFINAE / Control',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Compile-time if/else type selector.',
    ),
    S(
        'type_identity', 'SFINAE / Control',
        std_in='C++20',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Trivial passthrough; blocks template argument deduction.',
    ),
    S(
        'void_t', 'SFINAE / Control',
        std_in='C++17',
        restd_min='C++11',
        t_alias_in='C++11',
        notes='Requires alias + variadic templates. C++11+.',
        failure_reason='Variadic templates are C++11.',
    ),
    S(
        'remove_const', 'CV / Pointer / Reference',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Strips top-level const.',
    ),
    S(
        'remove_volatile', 'CV / Pointer / Reference',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Strips top-level volatile.',
    ),
    S(
        'remove_cv', 'CV / Pointer / Reference',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Strips top-level cv.',
    ),
    S(
        'remove_pointer', 'CV / Pointer / Reference',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Strips one level of pointer (handles cv-qualified pointers).',
    ),
    S(
        'remove_reference', 'CV / Pointer / Reference',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Strips lvalue and rvalue refs (rvalue path C++11+).',
    ),
    S(
        'remove_cvref', 'CV / Pointer / Reference',
        std_in='C++20',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Composes remove_cv and remove_reference.',
    ),
    S(
        'add_const', 'CV / Pointer / Reference',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Adds top-level const.',
    ),
    S(
        'add_volatile', 'CV / Pointer / Reference',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Adds top-level volatile.',
    ),
    S(
        'add_cv', 'CV / Pointer / Reference',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Adds top-level cv.',
    ),
    S(
        'add_pointer', 'CV / Pointer / Reference',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Strips ref then adds *. void/cv-void handled.',
    ),
    S(
        'add_lvalue_reference', 'CV / Pointer / Reference',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Yields T&; void/cv-void passthrough.',
    ),
    S(
        'add_rvalue_reference', 'CV / Pointer / Reference',
        std_in='C++11',
        restd_min='C++11',
        t_alias_in='C++11',
        notes='Yields T&&. Pure passthrough on C++98/03 (no rvalue refs).',
        failure_reason='Rvalue references are C++11.',
    ),
    S(
        'remove_extent', 'Array modification',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Strips one array dimension.',
    ),
    S(
        'remove_all_extents', 'Array modification',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Recursively strips all array dimensions.',
    ),
    S(
        'make_signed', 'Sign modification',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Maps integral types to signed equivalents. Cv-preserving. Enum / floating-point not handled.',
        failure_reason='Enum mapping requires __underlying_type intrinsic; plain integers and char/wchar handled portably.',
    ),
    S(
        'make_unsigned', 'Sign modification',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++11',
        notes='Maps integral types to unsigned equivalents. Cv-preserving.',
    ),
    S(
        'is_void', 'Primary categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='Cv-stripped void detection.',
    ),
    S(
        'is_null_pointer', 'Primary categories',
        std_in='C++14',
        restd_min='C++11',
        v_var_in='C++17',
        notes='std::nullptr_t detection.',
        failure_reason='std::nullptr_t is C++11.',
    ),
    S(
        'is_integral', 'Primary categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='Explicit specs across C++98/11/20 tiers (long long, char16/32_t, char8_t).',
    ),
    S(
        'is_floating_point', 'Primary categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='float, double, long double + cv flavors.',
    ),
    S(
        'is_array', 'Primary categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='Bounded and unbounded.',
    ),
    S(
        'is_bounded_array', 'Primary categories',
        std_in='C++20',
        restd_min='C++98',
        v_var_in='C++20',
        notes='T[N] only.',
    ),
    S(
        'is_unbounded_array', 'Primary categories',
        std_in='C++20',
        restd_min='C++98',
        v_var_in='C++20',
        notes='T[] only.',
    ),
    S(
        'is_enum', 'Primary categories',
        std_in='C++11',
        restd_min='C++98',
        intrinsic_required=True,
        intrinsic_names='__is_enum',
        detection_macro='D_RESTD_HAS_IS_ENUM',
        v_var_in='C++17',
        notes='Compiler intrinsic. Falls back to false_type when absent.',
    ),
    S(
        'is_scoped_enum', 'Primary categories',
        std_in='C++23',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='__is_scoped_enum',
        detection_macro='D_RESTD_HAS_IS_SCOPED_ENUM',
        v_var_in='C++23',
        notes='Portable fallback via implicit-conversion-to-int probe.',
        failure_reason='Scoped enums are C++11.',
    ),
    S(
        'is_union', 'Primary categories',
        std_in='C++11',
        restd_min='C++98',
        intrinsic_required=True,
        intrinsic_names='__is_union',
        detection_macro='D_RESTD_HAS_IS_UNION',
        v_var_in='C++17',
        notes='No portable detection. Falls back to false_type.',
    ),
    S(
        'is_class', 'Primary categories',
        std_in='C++11',
        restd_min='C++98',
        intrinsic_required=True,
        intrinsic_names='__is_class',
        detection_macro='D_RESTD_HAS_IS_CLASS',
        v_var_in='C++17',
        notes='Compiler intrinsic preferred. SFINAE-on-pmf trick exists but fails for unions on some compilers.',
    ),
    S(
        'is_pointer', 'Primary categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='Cv-stripped.',
    ),
    S(
        'is_lvalue_reference', 'Primary categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
    ),
    S(
        'is_rvalue_reference', 'Primary categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='False on C++98/03 (no rvalue refs).',
    ),
    S(
        'is_function', 'Primary categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='Variadic specs on C++11+. Explicit arities 0-10 on C++98/03.',
    ),
    S(
        'is_member_pointer', 'Primary categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='Cv-stripped.',
    ),
    S(
        'is_member_object_pointer', 'Primary categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='is_member_pointer && !is_member_function_pointer.',
    ),
    S(
        'is_member_function_pointer', 'Primary categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='Cv-stripped, then is_function on pointee.',
    ),
    S(
        'is_reference', 'Composite categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='Composite of lvalue + rvalue reference.',
    ),
    S(
        'is_arithmetic', 'Composite categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='is_integral || is_floating_point.',
    ),
    S(
        'is_fundamental', 'Composite categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='arithmetic + void + nullptr_t (nullptr_t gated on C++11+).',
    ),
    S(
        'is_scalar', 'Composite categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='arithmetic + enum + pointer + member-pointer + nullptr_t.',
    ),
    S(
        'is_object', 'Composite categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='NOT function/reference/void.',
    ),
    S(
        'is_compound', 'Composite categories',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='!is_fundamental.',
    ),
    S(
        'is_const', 'Type properties',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
    ),
    S(
        'is_volatile', 'Type properties',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
    ),
    S(
        'is_signed', 'Type properties',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='Uses static_cast<T>(-1) < 0 probe; gated on arithmetic.',
    ),
    S(
        'is_unsigned', 'Type properties',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
        notes='Uses static_cast<T>(0) < static_cast<T>(-1) probe; gated on integral.',
    ),
    S(
        'is_trivial', 'Type properties (intrinsic)',
        std_in='C++11',
        restd_min='C++98',
        intrinsic_required=True,
        intrinsic_names='__is_trivial',
        detection_macro='D_RESTD_HAS_IS_TRIVIAL',
        v_var_in='C++17',
        deprecated_in='C++26',
        notes='Falls back to false_type.',
    ),
    S(
        'is_trivially_copyable', 'Type properties (intrinsic)',
        std_in='C++11',
        restd_min='C++98',
        intrinsic_required=True,
        intrinsic_names='__is_trivially_copyable',
        detection_macro='D_RESTD_HAS_IS_TRIVIALLY_COPYABLE',
        v_var_in='C++17',
        notes='No portable C++ detection exists.',
    ),
    S(
        'is_standard_layout', 'Type properties (intrinsic)',
        std_in='C++11',
        restd_min='C++98',
        intrinsic_required=True,
        intrinsic_names='__is_standard_layout',
        detection_macro='D_RESTD_HAS_IS_STANDARD_LAYOUT',
        v_var_in='C++17',
        notes='No portable detection.',
    ),
    S(
        'is_empty', 'Type properties (intrinsic)',
        std_in='C++11',
        restd_min='C++98',
        intrinsic_required=True,
        intrinsic_names='__is_empty',
        detection_macro='D_RESTD_HAS_IS_EMPTY',
        v_var_in='C++17',
        notes='EBO test possible but unreliable; intrinsic preferred.',
    ),
    S(
        'is_polymorphic', 'Type properties (intrinsic)',
        std_in='C++11',
        restd_min='C++98',
        intrinsic_required=True,
        intrinsic_names='__is_polymorphic',
        detection_macro='D_RESTD_HAS_IS_POLYMORPHIC',
        v_var_in='C++17',
    ),
    S(
        'is_abstract', 'Type properties (intrinsic)',
        std_in='C++11',
        restd_min='C++98',
        intrinsic_required=True,
        intrinsic_names='__is_abstract',
        detection_macro='D_RESTD_HAS_IS_ABSTRACT',
        v_var_in='C++17',
    ),
    S(
        'is_final', 'Type properties (intrinsic)',
        std_in='C++14',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='__is_final',
        detection_macro='D_RESTD_HAS_IS_FINAL',
        v_var_in='C++17',
        notes='final keyword is C++11; trait is C++14.',
        failure_reason='final keyword is C++11.',
    ),
    S(
        'is_aggregate', 'Type properties (intrinsic)',
        std_in='C++17',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='__is_aggregate',
        detection_macro='D_RESTD_HAS_IS_AGGREGATE',
        v_var_in='C++17',
        failure_reason='Intrinsic typically requires C++14+ compiler.',
    ),
    S(
        'has_virtual_destructor', 'Type properties (intrinsic)',
        std_in='C++11',
        restd_min='C++98',
        intrinsic_required=True,
        intrinsic_names='__has_virtual_destructor',
        detection_macro='D_RESTD_HAS_HAS_VIRTUAL_DESTRUCTOR',
        v_var_in='C++17',
    ),
    S(
        'has_unique_object_representations', 'Type properties (intrinsic)',
        std_in='C++17',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='__has_unique_object_representations',
        detection_macro='D_RESTD_HAS_HAS_UNIQUE_OBJECT_REPRESENTATIONS',
        v_var_in='C++17',
        failure_reason='Intrinsic requires C++14+ compiler.',
    ),
    S(
        'is_constructible', 'Supported ops: constructible',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='__is_constructible',
        detection_macro='D_RESTD_HAS_IS_CONSTRUCTIBLE',
        v_var_in='C++17',
        notes='Portable C++11+ SFINAE fallback.',
        failure_reason='Variadic templates required.',
    ),
    S(
        'is_trivially_constructible', 'Supported ops: constructible',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='__is_trivially_constructible',
        detection_macro='D_RESTD_HAS_IS_TRIVIALLY_CONSTRUCTIBLE',
        v_var_in='C++17',
        notes='Intrinsic-only. Falls back to false_type.',
        failure_reason='Variadic templates required.',
    ),
    S(
        'is_nothrow_constructible', 'Supported ops: constructible',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='__is_nothrow_constructible',
        detection_macro='D_RESTD_HAS_IS_NOTHROW_CONSTRUCTIBLE',
        v_var_in='C++17',
        notes='Intrinsic + portable noexcept-probe fallback.',
        failure_reason='noexcept and variadic templates required.',
    ),
    S(
        'is_default_constructible', 'Supported ops: constructible',
        std_in='C++11',
        restd_min='C++11',
        v_var_in='C++17',
        failure_reason='Variadic templates required.',
    ),
    S(
        'is_trivially_default_constructible', 'Supported ops: constructible',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='(via is_trivially_constructible)',
        detection_macro='(via D_RESTD_HAS_IS_TRIVIALLY_CONSTRUCTIBLE)',
        v_var_in='C++17',
        failure_reason='Variadic templates required.',
    ),
    S(
        'is_nothrow_default_constructible', 'Supported ops: constructible',
        std_in='C++11',
        restd_min='C++11',
        v_var_in='C++17',
        failure_reason='Variadic templates required.',
    ),
    S(
        'is_copy_constructible', 'Supported ops: constructible',
        std_in='C++11',
        restd_min='C++11',
        v_var_in='C++17',
        failure_reason='Variadic templates required.',
    ),
    S(
        'is_trivially_copy_constructible', 'Supported ops: constructible',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='(via is_trivially_constructible)',
        detection_macro='(via D_RESTD_HAS_IS_TRIVIALLY_CONSTRUCTIBLE)',
        v_var_in='C++17',
        failure_reason='Variadic templates required.',
    ),
    S(
        'is_nothrow_copy_constructible', 'Supported ops: constructible',
        std_in='C++11',
        restd_min='C++11',
        v_var_in='C++17',
        failure_reason='Variadic templates required.',
    ),
    S(
        'is_move_constructible', 'Supported ops: constructible',
        std_in='C++11',
        restd_min='C++11',
        v_var_in='C++17',
        failure_reason='Rvalue refs required.',
    ),
    S(
        'is_trivially_move_constructible', 'Supported ops: constructible',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='(via is_trivially_constructible)',
        detection_macro='(via D_RESTD_HAS_IS_TRIVIALLY_CONSTRUCTIBLE)',
        v_var_in='C++17',
        failure_reason='Rvalue refs required.',
    ),
    S(
        'is_nothrow_move_constructible', 'Supported ops: constructible',
        std_in='C++11',
        restd_min='C++11',
        v_var_in='C++17',
        failure_reason='Rvalue refs required.',
    ),
    S(
        'is_assignable', 'Supported ops: assignable',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='__is_assignable',
        detection_macro='D_RESTD_HAS_IS_ASSIGNABLE',
        v_var_in='C++17',
        failure_reason='decltype + declval required.',
    ),
    S(
        'is_trivially_assignable', 'Supported ops: assignable',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='__is_trivially_assignable',
        detection_macro='D_RESTD_HAS_IS_TRIVIALLY_ASSIGNABLE',
        v_var_in='C++17',
        failure_reason='decltype + declval required.',
    ),
    S(
        'is_nothrow_assignable', 'Supported ops: assignable',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='__is_nothrow_assignable',
        detection_macro='D_RESTD_HAS_IS_NOTHROW_ASSIGNABLE',
        v_var_in='C++17',
        failure_reason='noexcept + declval required.',
    ),
    S(
        'is_copy_assignable', 'Supported ops: assignable',
        std_in='C++11',
        restd_min='C++11',
        v_var_in='C++17',
        failure_reason='decltype + declval required.',
    ),
    S(
        'is_trivially_copy_assignable', 'Supported ops: assignable',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='(via is_trivially_assignable)',
        detection_macro='(via D_RESTD_HAS_IS_TRIVIALLY_ASSIGNABLE)',
        v_var_in='C++17',
        failure_reason='decltype + declval required.',
    ),
    S(
        'is_nothrow_copy_assignable', 'Supported ops: assignable',
        std_in='C++11',
        restd_min='C++11',
        v_var_in='C++17',
        failure_reason='noexcept + declval required.',
    ),
    S(
        'is_move_assignable', 'Supported ops: assignable',
        std_in='C++11',
        restd_min='C++11',
        v_var_in='C++17',
        failure_reason='Rvalue refs required.',
    ),
    S(
        'is_trivially_move_assignable', 'Supported ops: assignable',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='(via is_trivially_assignable)',
        detection_macro='(via D_RESTD_HAS_IS_TRIVIALLY_ASSIGNABLE)',
        v_var_in='C++17',
        failure_reason='Rvalue refs required.',
    ),
    S(
        'is_nothrow_move_assignable', 'Supported ops: assignable',
        std_in='C++11',
        restd_min='C++11',
        v_var_in='C++17',
        failure_reason='Rvalue refs required.',
    ),
    S(
        'is_destructible', 'Supported ops: destructible',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='__is_destructible',
        detection_macro='D_RESTD_HAS_IS_DESTRUCTIBLE',
        v_var_in='C++17',
        failure_reason='decltype + declval required.',
    ),
    S(
        'is_trivially_destructible', 'Supported ops: destructible',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='__is_trivially_destructible / __has_trivial_destructor',
        detection_macro='D_RESTD_HAS_IS_TRIVIALLY_DESTRUCTIBLE',
        v_var_in='C++17',
        failure_reason='Intrinsic required.',
    ),
    S(
        'is_nothrow_destructible', 'Supported ops: destructible',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='__is_nothrow_destructible',
        detection_macro='D_RESTD_HAS_IS_NOTHROW_DESTRUCTIBLE',
        v_var_in='C++17',
        failure_reason='noexcept + declval required.',
    ),
    S(
        'is_same', 'Type relationships',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
    ),
    S(
        'is_base_of', 'Type relationships',
        std_in='C++11',
        restd_min='C++98',
        intrinsic_required=True,
        intrinsic_names='__is_base_of',
        detection_macro='D_RESTD_HAS_IS_BASE_OF',
        v_var_in='C++17',
        notes='Portable fallback via pointer-conversion overload set.',
    ),
    S(
        'is_convertible', 'Type relationships',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='__is_convertible / __is_convertible_to',
        detection_macro='D_RESTD_HAS_IS_CONVERTIBLE',
        v_var_in='C++17',
        notes='C++11+ portable fallback via SFINAE; degrades to is_same on C++98/03.',
        failure_reason='Full convertibility detection requires declval + decltype.',
    ),
    S(
        'underlying_type', 'Enum support',
        std_in='C++11',
        restd_min='C++11',
        intrinsic_required=True,
        intrinsic_names='__underlying_type',
        detection_macro='D_RESTD_HAS_UNDERLYING_TYPE',
        t_alias_in='C++14',
        notes='INTRINSIC REQUIRED. Trait omitted when intrinsic absent.',
        failure_reason='No portable C++ implementation possible without the intrinsic.',
    ),
    S(
        'alignment_of', 'Transformations',
        std_in='C++11',
        restd_min='C++98',
        intrinsic_required=True,
        intrinsic_names='alignof / __alignof__ / __alignof',
        detection_macro='D_RESTD_HAS_ALIGNOF',
        v_var_in='C++17',
        notes='Uses alignof (C++11) or __alignof__ (GCC/Clang/Intel) or __alignof (MSVC).',
    ),
    S(
        'rank', 'Transformations',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
    ),
    S(
        'extent', 'Transformations',
        std_in='C++11',
        restd_min='C++98',
        v_var_in='C++17',
    ),
    S(
        'decay', 'Transformations',
        std_in='C++11',
        restd_min='C++98',
        t_alias_in='C++14',
        notes='Composes remove_reference + array/function-to-pointer + remove_cv.',
    ),
    S(
        'conjunction', 'Logical operators',
        std_in='C++17',
        restd_min='C++11',
        v_var_in='C++17',
        failure_reason='Variadic + alias templates required.',
    ),
    S(
        'disjunction', 'Logical operators',
        std_in='C++17',
        restd_min='C++11',
        v_var_in='C++17',
        failure_reason='Variadic + alias templates required.',
    ),
    S(
        'negation', 'Logical operators',
        std_in='C++17',
        restd_min='C++11',
        v_var_in='C++17',
        failure_reason='Alias templates required.',
    ),
    # ---- Newly shipped 2026-04-29/30 ----
    S(
        'aligned_storage', 'Transformations',
        std_in='C++11',
        restd_min='C++11',
        t_alias_in='C++14',
        deprecated_in='C++23',
        notes='POD storage struct of given size and alignment. Default alignment via local fundamental-types union (avoids std::max_align_t dependency). Deprecated by std in C++23 (P1413R3); restd retains.',
        failure_reason='Requires alignas / alignof / decltype (C++11+).',
    ),
    S(
        'aligned_union', 'Transformations',
        std_in='C++11',
        restd_min='C++11',
        t_alias_in='C++14',
        deprecated_in='C++23',
        notes='Storage for any of Types..., size = max(Len, sizeof(Types)...), alignment = max(alignof(Types)...). Exposes alignment_value member.',
        failure_reason='Requires alignas + variadic templates (C++11+).',
    ),
    S(
        'common_type', 'Transformations',
        std_in='C++11',
        restd_min='C++11',
        t_alias_in='C++14',
        notes='Conditional-expression-based common type. Includes the P0898R3 const-lvalue-ref fallback rule from C++20, applied on all C++11+ tiers.',
        failure_reason='Requires decltype + variadic templates (C++11+).',
    ),
    S(
        'basic_common_reference', 'Transformations',
        std_in='C++20',
        restd_min='C++11',
        notes='Customization-point primary template for common_reference. Empty body by default; users specialize. Backported to C++11+; needs only template-template parameters.',
        failure_reason='None on the trait itself (template-template parameters are C++98). Restd backports the trait\'s presence; the wider common_reference machinery is C++11+.',
    ),
    S(
        'common_reference', 'Transformations',
        std_in='C++20',
        restd_min='C++11',
        t_alias_in='C++20',
        notes='C++20 generalization of common_type that preserves reference qualifiers. Four-bullet chain: COMMON-REF, basic_common_reference, common_type, COND-RES.',
        failure_reason='Requires alias templates (gated on D_ENV_CPP_FEATURE_LANG_ALIAS_TEMPLATES; C++11+).',
    ),
    S(
        'invoke_result', 'Transformations',
        std_in='C++17',
        restd_min='C++11',
        t_alias_in='C++17',
        notes='Result type of INVOKE(F, Args...). Internal invoker dispatcher hosts the five INVOKE forms; reference_wrapper handling deferred until restd::reference_wrapper lands.',
        depends_on=('reference_wrapper',),
        failure_reason='Requires decltype + variadic templates + trailing return types + enable_if-in-return-position (C++11+). Reference_wrapper invocation form (1.5) pending.',
    ),
    S(
        'result_of', 'Transformations',
        std_in='C++11',
        restd_min='C++11',
        t_alias_in='C++14',
        deprecated_in='C++17',
        notes='Function-call-syntax sibling of invoke_result. Deprecated by std in C++17, removed in C++20; restd retains on all C++11+ tiers per project policy. Inherits SFINAE-friendliness from invoke_result.',
        failure_reason='Inherits invoke_result\'s C++11 floor (decltype + variadic templates).',
    ),
    S(
        'is_invocable', 'Type relationships',
        std_in='C++17',
        restd_min='C++11',
        v_var_in='C++17',
        notes='void_t SFINAE probe over invoke_result. Single source of truth for "is INVOKE well-formed".',
        failure_reason='Inherits invoke_result\'s C++11 floor.',
    ),
    S(
        'is_invocable_r', 'Type relationships',
        std_in='C++17',
        restd_min='C++11',
        v_var_in='C++17',
        notes='Two-step gate: is_invocable, then is_convertible to R (with R=void short-circuit).',
        failure_reason='Inherits invoke_result\'s C++11 floor.',
    ),
    S(
        'is_nothrow_invocable', 'Type relationships',
        std_in='C++17',
        restd_min='C++11',
        v_var_in='C++17',
        notes='Direct dispatcher noexcept-probe (invoke_result captures only type). Two-step gate via is_invocable.',
        failure_reason='Requires noexcept operator + invoke_result machinery (C++11+).',
    ),
    S(
        'is_nothrow_invocable_r', 'Type relationships',
        std_in='C++17',
        restd_min='C++11',
        v_var_in='C++17',
        notes='Three-piece check: is_invocable_r, dispatcher noexcept, is_nothrow_convertible (with R=void short-circuit).',
        failure_reason='Requires noexcept operator + invoke_result machinery (C++11+).',
    ),
    S(
        'is_nothrow_convertible', 'Type relationships',
        std_in='C++20',
        restd_min='C++11',
        v_var_in='C++20',
        notes='noexcept-of-conversion probe via internal noexcept "implicit_takes" function. Two-step gate via is_convertible. Backported to C++11+.',
        failure_reason='Requires noexcept operator (C++11+).',
    ),
    S(
        'is_swappable', 'Supported operations',
        std_in='C++17',
        restd_min='C++11',
        v_var_in='C++17',
        notes='Forwards add_lvalue_reference<T>::type to is_swappable_with on both sides; non-referenceable types yield false_type via SFINAE.',
        failure_reason='SFINAE probe requires decltype + declval + rvalue refs (C++11+); a static false_type fallback would be wrong for built-in types.',
    ),
    S(
        'is_swappable_with', 'Supported operations',
        std_in='C++17',
        restd_min='C++11',
        v_var_in='C++17',
        notes='Bidirectional swap-call SFINAE probe in a dedicated lookup namespace with `using restd::swap;`. Both directions must be well-formed.',
        failure_reason='SFINAE probe requires decltype + declval + rvalue refs (C++11+).',
    ),
    S(
        'is_nothrow_swappable', 'Supported operations',
        std_in='C++17',
        restd_min='C++11',
        v_var_in='C++17',
        notes='Forwards add_lvalue_reference<T>::type to is_nothrow_swappable_with.',
        failure_reason='Requires noexcept operator + is_swappable_with machinery (C++11+).',
    ),
    S(
        'is_nothrow_swappable_with', 'Supported operations',
        std_in='C++17',
        restd_min='C++11',
        v_var_in='C++17',
        notes='Two-step gate: is_swappable_with, then bidirectional noexcept(swap(...)) probe in the same lookup namespace.',
        failure_reason='Requires noexcept operator + is_swappable_with machinery (C++11+).',
    ),
]

# <utility> -- implemented in restd 2026-04-30
SYMBOLS_UTILITY = [
    S(
        'swap', 'Generic algorithms',
        std_in='C++98',
        restd_min='C++98',
        constexpr_in_std='C++20',
        constexpr_in_restd='C++14',
        notes='Three-tier impl: C++14+ constexpr move-based, C++11 move-based, C++98 copy-based. Conditional noexcept gated on variadic templates.',
    ),
    S(
        'swap (array overload)', 'Generic algorithms',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++20',
        constexpr_in_restd='C++14',
        notes='Element-wise swap on T[N]. Unqualified noexcept pending is_nothrow_swappable (C++17).',
    ),
    S(
        'move', 'Cast utilities',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++11',
        constexpr_in_restd='C++11',
        notes='Single-statement static_cast to remove_reference<T>::type&&. constexpr-eligible on C++11.',
    ),
    S(
        'forward', 'Cast utilities',
        std_in='C++11',
        restd_min='C++11',
        constexpr_in_std='C++11',
        constexpr_in_restd='C++11',
        notes='Two overloads (lvalue / rvalue). Rvalue overload static_asserts against forwarding rvalue as lvalue.',
    ),
    S(
        'declval', 'Unevaluated context',
        std_in='C++11',
        restd_min='C++11',
        notes='Declared-only. Return type via add_rvalue_reference, so declval<void>() yields void.',
    ),
    S(
        'pair', 'Pair',
        std_in='C++98',
        restd_min='C++98',
        constexpr_in_std='C++20',
        constexpr_in_restd='C++11',
        notes='Member-init-list ctors are constexpr on C++11+. Move ctor noexcept-conditional on is_nothrow_move_constructible (variadic-gated).',
    ),
    S(
        'operator== (pair)', 'Pair comparisons',
        std_in='C++98',
        restd_min='C++98',
        constexpr_in_std='C++14',
        constexpr_in_restd='C++11',
        notes='Lexicographic equality. constexpr in restd from C++11.',
    ),
    S(
        'operator!= (pair)', 'Pair comparisons',
        std_in='C++98',
        restd_min='C++98',
        constexpr_in_std='C++14',
        constexpr_in_restd='C++11',
        deprecated_in='C++20',
        notes='Defined as !(==). Synthesised from op== since C++20.',
    ),
    S(
        'operator< (pair)', 'Pair comparisons',
        std_in='C++98',
        restd_min='C++98',
        constexpr_in_std='C++14',
        constexpr_in_restd='C++11',
        notes='Lexicographic less-than. Implemented in terms of < only.',
    ),
    S(
        'operator<= (pair)', 'Pair comparisons',
        std_in='C++98',
        restd_min='C++98',
        constexpr_in_std='C++14',
        constexpr_in_restd='C++11',
        deprecated_in='C++20',
        notes='Defined as !(rhs < lhs). Synthesised from <=> since C++20.',
    ),
    S(
        'operator> (pair)', 'Pair comparisons',
        std_in='C++98',
        restd_min='C++98',
        constexpr_in_std='C++14',
        constexpr_in_restd='C++11',
        deprecated_in='C++20',
        notes='Defined as rhs < lhs. Synthesised from <=> since C++20.',
    ),
    S(
        'operator>= (pair)', 'Pair comparisons',
        std_in='C++98',
        restd_min='C++98',
        constexpr_in_std='C++14',
        constexpr_in_restd='C++11',
        deprecated_in='C++20',
        notes='Defined as !(lhs < rhs). Synthesised from <=> since C++20.',
    ),
    S(
        'swap (pair)', 'Pair',
        std_in='C++98',
        restd_min='C++98',
        notes='Member and non-member overloads. Member-wise via restd::swap. Unqualified noexcept pending is_nothrow_swappable.',
    ),
    S(
        'make_pair', 'Factories',
        std_in='C++98',
        restd_min='C++98',
        constexpr_in_std='C++14',
        constexpr_in_restd='C++11',
        notes='C++11+ uses perfect forwarding with restd::decay; C++98 uses pass-by-value. reference_wrapper unwrap pending restd::reference_wrapper.',
        depends_on=('reference_wrapper',),
    ),
    S(
        'piecewise_construct_t', 'Piecewise construction',
        std_in='C++11',
        restd_min=None,
        notes='Tag type. Pending restd::tuple.',
        depends_on=('tuple',),
        failure_reason='Pending restd::tuple -- piecewise_construct overload of pair takes two tuples of forwarded args.',
    ),
    S(
        'piecewise_construct', 'Piecewise construction',
        std_in='C++11',
        restd_min=None,
        notes='Tag constant. Pending restd::tuple.',
        depends_on=('tuple',),
        failure_reason='Pending restd::tuple.',
    ),
    S(
        'tuple_size<pair>', 'Tuple protocol',
        std_in='C++11',
        restd_min=None,
        notes='Specialisation. Pending restd::tuple.',
        depends_on=('tuple',),
        failure_reason='Pending restd::tuple to define the primary template.',
    ),
    S(
        'tuple_element<I,pair>', 'Tuple protocol',
        std_in='C++11',
        restd_min=None,
        notes='Specialisation. Pending restd::tuple.',
        depends_on=('tuple',),
        failure_reason='Pending restd::tuple to define the primary template.',
    ),
    S(
        'get<I>(pair)', 'Tuple protocol',
        std_in='C++11',
        restd_min=None,
        constexpr_in_std='C++14',
        notes='Index-based access. Four value-category overloads. Depends on tuple_element being defined.',
        depends_on=('tuple_element',),
        failure_reason='Pending tuple_element specialisation for pair.',
    ),
    S(
        'get<T>(pair)', 'Tuple protocol',
        std_in='C++14',
        restd_min=None,
        constexpr_in_std='C++14',
        notes='Type-based access. Pending tuple-protocol scaffolding.',
        depends_on=('tuple_element',),
        failure_reason='Pending tuple-protocol scaffolding.',
    ),
    S(
        'operator<=> (pair)', 'Pair comparisons',
        std_in='C++20',
        restd_min=None,
        constexpr_in_std='C++20',
        notes='C++20 spaceship. Pending restd::compare.',
        depends_on=('three_way_comparable',),
        failure_reason='Requires the C++20 three_way_comparable concept and <compare> ordering categories. Pending restd::compare.',
    ),
    S(
        'exchange', 'Object utilities',
        std_in='C++14',
        restd_min=None,
        constexpr_in_std='C++20',
        notes='Replace value, return old. Trivially implementable; deferred for grouping with optional/variant work.',
        failure_reason="Trivially implementable but not yet shipped. Slated for the same milestone as the rest of <utility>'s C++14+ tail.",
    ),
    S(
        'as_const', 'Object utilities',
        std_in='C++17',
        restd_min=None,
        constexpr_in_std='C++17',
        notes='Returns const T&. Trivial; deferred.',
        failure_reason='Trivial helper, slated alongside exchange.',
    ),
    S(
        'in_place_type_t<T>', 'In-place tags',
        std_in='C++17',
        restd_min=None,
        notes='Type-tagged variant of in_place. Used by variant. (in_place_t / in_place themselves now ship under <optional>.)',
        depends_on=('variant',),
        failure_reason='Slated alongside <variant>.',
    ),
    S(
        'in_place_type<T>', 'In-place tags',
        std_in='C++17',
        restd_min=None,
        notes='Tag template variable.',
        depends_on=('variant',),
        failure_reason='Slated alongside <variant>.',
    ),
    S(
        'in_place_index_t<I>', 'In-place tags',
        std_in='C++17',
        restd_min=None,
        notes='Index-tagged variant of in_place. Used by variant.',
        depends_on=('variant',),
        failure_reason='Slated alongside <variant>.',
    ),
    S(
        'in_place_index<I>', 'In-place tags',
        std_in='C++17',
        restd_min=None,
        notes='Tag template variable.',
        depends_on=('variant',),
        failure_reason='Slated alongside <variant>.',
    ),
    S(
        'integer_sequence<T,Is...>', 'Integer sequences',
        std_in='C++14',
        restd_min=None,
        constexpr_in_std='C++14',
        notes='Compile-time integer pack. Foundational for tuple_cat, apply, etc.',
        failure_reason='Required by tuple_cat / apply / make_from_tuple. Slated for the next utility milestone.',
    ),
    S(
        'index_sequence<Is...>', 'Integer sequences',
        std_in='C++14',
        restd_min=None,
        constexpr_in_std='C++14',
        notes='Alias for integer_sequence<size_t,...>.',
        failure_reason='Same milestone as integer_sequence.',
    ),
    S(
        'make_integer_sequence<T,N>', 'Integer sequences',
        std_in='C++14',
        restd_min=None,
        constexpr_in_std='C++14',
        notes='Generator alias. Best-quality impl uses __make_integer_seq intrinsic where available.',
        failure_reason='Same milestone as integer_sequence; intrinsic-accelerated path planned.',
    ),
    S(
        'make_index_sequence<N>', 'Integer sequences',
        std_in='C++14',
        restd_min=None,
        constexpr_in_std='C++14',
        notes='Generator alias.',
        failure_reason='Same milestone as integer_sequence.',
    ),
    S(
        'index_sequence_for<Ts...>', 'Integer sequences',
        std_in='C++14',
        restd_min=None,
        constexpr_in_std='C++14',
        notes='Alias for make_index_sequence<sizeof...(Ts)>.',
        failure_reason='Same milestone as integer_sequence.',
    ),
    S(
        'move_if_noexcept', 'Cast utilities',
        std_in='C++11',
        restd_min=None,
        constexpr_in_std='C++11',
        notes="Casts to const T& if T's move can throw and copy is available, else to T&&.",
        depends_on=('is_nothrow_move_constructible', 'is_copy_constructible'),
        failure_reason='Needs is_copy_constructible (not yet in restd::type_traits).',
    ),
    S(
        'forward_like', 'Cast utilities',
        std_in='C++23',
        restd_min=None,
        constexpr_in_std='C++23',
        notes='Forwards an object using the value category of a template parameter.',
        failure_reason='C++23 cast utility; not yet implemented.',
    ),
    S(
        'to_underlying', 'Enum utilities',
        std_in='C++23',
        restd_min=None,
        constexpr_in_std='C++23',
        notes='static_cast<underlying_type_t<E>>(e). Requires underlying_type intrinsic.',
        failure_reason='Trivially implementable on top of restd::underlying_type. Slated for the next utility milestone.',
    ),
    S(
        'cmp_equal', 'Integer comparisons',
        std_in='C++20',
        restd_min=None,
        constexpr_in_std='C++20',
        notes='Sign-aware integer comparison.',
        failure_reason='Family of six C++20 sign-aware comparators. Slated for the next utility milestone.',
    ),
    S(
        'cmp_not_equal', 'Integer comparisons',
        std_in='C++20',
        restd_min=None,
        constexpr_in_std='C++20',
        notes='Sign-aware integer comparison.',
        failure_reason='Same family as cmp_equal.',
    ),
    S(
        'cmp_less', 'Integer comparisons',
        std_in='C++20',
        restd_min=None,
        constexpr_in_std='C++20',
        notes='Sign-aware integer comparison.',
        failure_reason='Same family as cmp_equal.',
    ),
    S(
        'cmp_greater', 'Integer comparisons',
        std_in='C++20',
        restd_min=None,
        constexpr_in_std='C++20',
        notes='Sign-aware integer comparison.',
        failure_reason='Same family as cmp_equal.',
    ),
    S(
        'cmp_less_equal', 'Integer comparisons',
        std_in='C++20',
        restd_min=None,
        constexpr_in_std='C++20',
        notes='Sign-aware integer comparison.',
        failure_reason='Same family as cmp_equal.',
    ),
    S(
        'cmp_greater_equal', 'Integer comparisons',
        std_in='C++20',
        restd_min=None,
        constexpr_in_std='C++20',
        notes='Sign-aware integer comparison.',
        failure_reason='Same family as cmp_equal.',
    ),
    S(
        'in_range<R>(t)', 'Integer comparisons',
        std_in='C++20',
        restd_min=None,
        constexpr_in_std='C++20',
        notes='Range-checked integer cast probe.',
        failure_reason='Same family as cmp_equal.',
    ),
    S(
        'unreachable', 'Diagnostics',
        std_in='C++23',
        restd_min=None,
        notes='Marks code as unreachable; UB if reached. Wraps __builtin_unreachable / __assume.',
        failure_reason='C++23 utility; trivial wrapper around compiler intrinsics. Slated for the next utility milestone.',
    ),
]

# <optional> -- partial: tag types and exception shipped 2026-04-30; container pending
SYMBOLS_OPTIONAL = [
    S(
        'optional<T>', 'Optional class',
        std_in='C++17',
        restd_min=None,
        constexpr_in_std='C++23',
        notes='Engaged-or-empty wrapper. C++17 base, C++20 made most members constexpr, C++23 added monadic ops.',
        failure_reason="Requires variadic templates + rvalue references (C++11+) and constexpr-friendly storage. Tag and exception types have shipped (nullopt_t, nullopt, in_place_t, in_place, bad_optional_access); the container itself is slated for after <utility>'s tail.",
    ),
    S(
        'nullopt_t', 'Tags',
        std_in='C++17',
        restd_min='C++11',
        notes='Tag type for the empty optional state. Ships in restd/optional/nullopt.hpp.',
        failure_reason='Designated-init-style construction of nullopt requires C++11 brace-or-equal initializers.',
    ),
    S(
        'nullopt', 'Tags',
        std_in='C++17',
        restd_min='C++11',
        constexpr_in_std='C++17',
        constexpr_in_restd='C++11',
        notes='constexpr instance of nullopt_t. Std uses inline-variable from C++17; restd uses static-storage constexpr on C++11+.',
        failure_reason='Constexpr namespace-scope constants need C++11.',
    ),
    S(
        'bad_optional_access', 'Exception',
        std_in='C++17',
        restd_min='C++98',
        notes='Thrown by optional::value() when the optional is empty. Conditional inheritance of std::exception when D_ENV_CPP98_HAS_EXCEPTION; otherwise standalone (mirrors bad_any_cast). Ships in restd/optional/bad_optional_access.hpp.',
    ),
    S(
        'in_place_t', 'In-place tags',
        std_in='C++17',
        restd_min='C++11',
        notes='Tag type for in-place construction. Used by optional, variant, expected. Restd ships it under <optional> (file restd/optional/in_place.hpp); std groups it with <utility>.',
        failure_reason='Brace-or-equal initialization on C++11+.',
    ),
    S(
        'in_place', 'In-place tags',
        std_in='C++17',
        restd_min='C++11',
        constexpr_in_std='C++17',
        constexpr_in_restd='C++11',
        notes='constexpr instance of in_place_t. Lives in restd/optional/in_place.hpp alongside the tag type.',
        failure_reason='Constexpr namespace-scope constants need C++11.',
    ),
    S(
        'make_optional', 'Factories',
        std_in='C++17',
        restd_min=None,
        constexpr_in_std='C++17',
        notes='Two overloads: value forwarding, and in-place with args.',
        failure_reason='Pending optional<T> container. (in_place_t dependency is now satisfied.)',
    ),
    S(
        'swap (optional)', 'Free functions',
        std_in='C++17',
        restd_min=None,
        constexpr_in_std='C++20',
        notes='ADL-friendly non-member swap. Conditional noexcept on is_nothrow_swappable.',
        failure_reason='Pending optional<T>. (is_nothrow_swappable dependency is now satisfied.)',
    ),
    S(
        'operator== (optional)', 'Comparisons',
        std_in='C++17',
        restd_min=None,
        constexpr_in_std='C++17',
        notes='Compares both engaged-state and contained value. Heterogeneous overloads with U.',
        failure_reason='Slated to ship with optional.',
    ),
    S(
        'operator!= (optional)', 'Comparisons',
        std_in='C++17',
        restd_min=None,
        constexpr_in_std='C++17',
        deprecated_in='C++20',
        notes='Defined as !(==). Synthesised from <=> since C++20.',
        failure_reason='Slated to ship with optional.',
    ),
    S(
        'operator< (optional)', 'Comparisons',
        std_in='C++17',
        restd_min=None,
        constexpr_in_std='C++17',
        notes='Engaged optional > disengaged.',
        failure_reason='Slated to ship with optional.',
    ),
    S(
        'operator<= (optional)', 'Comparisons',
        std_in='C++17',
        restd_min=None,
        constexpr_in_std='C++17',
        deprecated_in='C++20',
        failure_reason='Slated to ship with optional.',
    ),
    S(
        'operator> (optional)', 'Comparisons',
        std_in='C++17',
        restd_min=None,
        constexpr_in_std='C++17',
        deprecated_in='C++20',
        failure_reason='Slated to ship with optional.',
    ),
    S(
        'operator>= (optional)', 'Comparisons',
        std_in='C++17',
        restd_min=None,
        constexpr_in_std='C++17',
        deprecated_in='C++20',
        failure_reason='Slated to ship with optional.',
    ),
    S(
        'operator<=> (optional)', 'Comparisons',
        std_in='C++20',
        restd_min=None,
        constexpr_in_std='C++20',
        notes='C++20 spaceship for optional. Pending restd::compare.',
        depends_on=('three_way_comparable',),
        failure_reason='Requires the C++20 three_way_comparable concept. Pending restd::compare.',
    ),
    S(
        'hash<optional<T>>', 'Hash support',
        std_in='C++17',
        restd_min=None,
        notes='Specialisation of std::hash for optional. Pending restd::hash.',
        depends_on=('hash',),
        failure_reason='Pending restd::hash.',
    ),
]

HEADERS = {
    "<any>": SYMBOLS_ANY,
    "<optional>": SYMBOLS_OPTIONAL,
    "<tuple>": SYMBOLS_TUPLE,
    "<type_traits>": SYMBOLS_TYPE_TRAITS,
    "<utility>": SYMBOLS_UTILITY,
}

HEADER_SUBTITLES = {
    "<any>": "Per-symbol coverage of the C++ <any> header (C++17).",
    "<optional>": "Per-symbol coverage of the C++ <optional> header (C++17).",
    "<tuple>": "Per-symbol coverage of the C++ <tuple> header (C++11).",
    "<type_traits>": "Per-symbol coverage of the C++ <type_traits> header.",
    "<utility>": "Per-symbol coverage of the C++ <utility> header (C++98 / C++11+).",
}

# Priority-ordered roadmap. Lower number = sooner. Final row is the meta REMINDER.
ROADMAP = [
    # (priority, std_header, summary, blockers, est_min_cpp)
    # Priorities 1, 2, and 3a are now complete (Group B swap/convertibility variants;
    # Group C invocation surface; aligned_storage / aligned_union). Removed from
    # roadmap; their symbols appear on the <type_traits> data sheet as shipped.
    (3, "<type_traits>", "C++20 layout-compat family (is_layout_compatible, is_pointer_interconvertible_base_of, is_pointer_interconvertible_with_class).", "Compiler intrinsic-backed; needs __is_layout_compatible / __is_pointer_interconvertible_* probes.", "C++20"),
    (4, "<type_traits>", "C++23 reference-from-temporary detection (reference_constructs_from_temporary, reference_converts_from_temporary).", "—", "C++23 (intrinsic only)"),
    (5, "<utility>", "Tail of <utility>: exchange, as_const, integer_sequence/index_sequence family, move_if_noexcept, to_underlying, cmp_* / in_range, unreachable, forward_like. (in_place_t / in_place have shipped under <optional>; the <utility> in_place_type and in_place_index families remain.)", "is_copy_constructible (for move_if_noexcept).", "C++11 / C++14 / C++20 / C++23 (per symbol)"),
    (6, "<functional>", "invoke, reference_wrapper, ref/cref, function, bind, plus the standard arithmetic / comparison / logical function objects.", "restd::invoke unblocks tuple::apply, invoke_result's reference_wrapper form (1.5).", "C++11"),
    (7, "<memory>", "allocator, allocator_traits, allocator_arg_t, uses_allocator, addressof, pointer_traits, unique_ptr, shared_ptr, weak_ptr, make_unique, make_shared, destroy_at, construct_at.", "Unblocks tuple::allocator-extended ctors.", "C++11"),
    (8, "<optional>", "optional<T> container itself, plus make_optional, comparisons, swap, hash specialisation. Tag types and exception (nullopt_t / nullopt / in_place_t / in_place / bad_optional_access) have already shipped.", "—", "C++11"),
    (9, "<variant>", "variant<Ts...>, monostate, bad_variant_access, visit, holds_alternative, get<I>/get<T>, variant_size, variant_alternative.", "Heaviest unimplemented module; requires careful constexpr work.", "C++11"),
    (10, "<expected>", "expected<T,E>, unexpected<E>, bad_expected_access, in_place_t / unexpect_t tags. C++23.", "Builds on the in_place tags.", "C++11 (back-port of C++23 surface)"),
    (11, "<tuple>", "Full tuple implementation. operator<=> blocked on restd::compare; allocator-aware ctors blocked on restd::memory.", "restd::compare, restd::memory, restd::reference_wrapper, restd::utility integer_sequence", "C++11"),
    (12, "<compare>", "Three-way comparison ordering categories (strong_ordering, weak_ordering, partial_ordering). Concept three_way_comparable.", "Unblocks operator<=> on every comparable restd type.", "C++20"),
    (13, "<algorithm>", "The C++98 algorithms first (find, sort, transform, accumulate, ...), then C++17/20/23 additions.", "—", "C++98"),
    (14, "<array>", "array<T,N> with the C++14 constexpr surface and C++17 deduction guides.", "—", "C++98 (interface), C++14 (constexpr)"),
    (15, "<string_view>", "basic_string_view + char_traits enough to support it.", "—", "C++11 (back-port of C++17 surface)"),
    (16, "<span>", "span<T,N>. Trivially constexpr.", "—", "C++11 (back-port of C++20 surface)"),
    # Final entry: REMINDER about deferred Master / Index sheets.
    (99, "(meta)", "REMINDER: deferred Master and Index sheets. Add when ~5+ headers are covered. Master concatenates every per-header sheet body with header rows reprinted between sections; Index lists every (symbol, header) pair flattened and sorted alphabetically by symbol.", "—", "—"),
]

LEGEND_SHEETS = [
    ("Legend", "You are here. Colour key + column meanings."),
    ("<any>",        "Per-symbol coverage of the C++ <any> header (C++17)."),
    ("<optional>",   "Per-symbol coverage of the C++ <optional> header (C++17). Tag types and exception shipped; container itself pending."),
    ("<tuple>",      "Per-symbol coverage of the C++ <tuple> header. Planned; not yet implemented in restd."),
    ("<type_traits>","Per-symbol coverage of the C++ <type_traits> header."),
    ("<utility>",    "Per-symbol coverage of the C++ <utility> header. Foundational symbols shipped 2026-04-30; tail (exchange, as_const, integer_sequence family, etc.) deferred."),
    ("Pending Dependencies", "Symbols that need other restd modules before they reach full coverage. Auto-derived from the depends_on field in coverage_data.py."),
    ("Coverage Failures",    "Detailed list of every symbol that does not reach C++98+ coverage, with the reason."),
    ("Roadmap",              "Priority-ordered plan for remaining work. The final entry is a REMINDER about deferred Master and Index sheets."),
]
