/*******************************************************************************
* djinterp [c]                                                      elementary.h
*
* Elementary functions: the C core's square root, arc-cosine, sine and
* cosine, for float, double and long double.
*   GENERATED by tools/gen_c_math_float.py from one text for the three
* families: edit the generator, not this file.
*
*   Each function comes twice. The _c form is pure arithmetic, so the same
* text is a constant expression from C++14; the plain form calls the C
* library (std:: in C++, which has the float and long double overloads from
* C++98), fast at run time. sqrt_c is correctly rounded, so the two square
* roots agree bit for bit; acos_c, sin_c and cos_c are within an ulp or two
* of the library's. A face picks one by level -- from C++20 by
* std::is_constant_evaluated -- and, for the square root, cannot be seen to
* have picked.
*
*
* path:      /inc/djinterp/c/math/elementary.h
* link(s):   TBA
* author(s): Samuel 'teer' Neal-Blim                         created: 2026.10.04
*                                                            revised: 2026.10.04
*******************************************************************************/

/*
TABLE OF CONTENTS
=================
1.  THE FLOAT FAMILY (_f)
    ---------------------
    1.  Internal helpers
    2.  Square root
    3.  Arc-cosine
    4.  Sine and cosine
2.  THE DOUBLE FAMILY (_d)
    ----------------------
    1.  Internal helpers
    2.  Square root
    3.  Arc-cosine
    4.  Sine and cosine
3.  THE LONG DOUBLE FAMILY (_ld)
    ----------------------------
    1.  Internal helpers
    2.  Square root
    3.  Arc-cosine
    4.  Sine and cosine
4.  ONE NAME FOR EVERY FAMILY (C++)
    -------------------------------
*/

#ifndef DJINTERP_C_MATH_ELEMENTARY_H
#define DJINTERP_C_MATH_ELEMENTARY_H 1

// std
#ifdef __cplusplus
    #include <cmath>         // std::sqrt, std::acos, std::sin, std::cos
#endif  // __cplusplus
#include <math.h>            // sqrtf ... cosl, HUGE_VAL, NAN
// djinterp
#include "./float_order.h"   // d_math_*_next_up, d_internal_math_*_binade_of
#include "./math_common.h"   // D_MATH_FN


// every family's arc-cosine takes its half-angle root in long double
D_MATH_FN long double
d_math_ld_sqrt_c(
    long double _x
);

//==============================================================================
// 1.  THE FLOAT FAMILY (_f)
//==============================================================================


// 1.1    Internal helpers
//------------------------------------------------------------------------------

// d_internal_math_f_pair
//   struct: a value as an unevaluated sum, high + low, the low part below the
// high part's rounding.
struct d_internal_math_f_pair
{
    float high;
    float low;
};

// d_internal_math_f_nan
//   a quiet NaN: a constant expression where the build defines NAN.
D_MATH_FN float
d_internal_math_f_nan(void)
{
#if defined(NAN)
    return (float)NAN;
#else
    return (float)(HUGE_VAL - HUGE_VAL);
#endif
}

// d_internal_math_f_square_exact
//   _c * _c exactly, as high + low: Dekker's product, the factors split by
// Veltkamp's constant 2^ceil(P/2) + 1. _c must be normal and its square
// finite.
D_MATH_FN struct d_internal_math_f_pair
d_internal_math_f_square_exact(
    float _c
)
{
    struct d_internal_math_f_pair result = { (float)0, (float)0 };
    const float split = d_internal_math_f_pow2((FLT_MANT_DIG + 1) / 2) + (float)1;
    const float t     = split * _c;
    const float hi    = t - (t - _c);
    const float lo    = _c - hi;

    result.high = _c * _c;
    result.low  = (((hi * hi) - result.high) + (((float)2 * hi) * lo)) +
                  (lo * lo);

    return result;
}

// d_internal_math_f_wide
//   struct: an unsigned integer of two d_math_umax limbs, high * 2^bits + low.
struct d_internal_math_f_wide
{
    d_math_umax high;
    d_math_umax low;
};

// d_internal_math_f_limb_bits
//   the bits of d_math_umax.
D_MATH_FN int
d_internal_math_f_limb_bits(void)
{
    return (int)(sizeof(d_math_umax) * 8u);
}

// d_internal_math_f_wide_shift
//   _value * 2^_shift as two limbs, for 0 < _shift < the limb's bits.
D_MATH_FN struct d_internal_math_f_wide
d_internal_math_f_wide_shift(
    d_math_umax _value,
    int         _shift
)
{
    const int bits = d_internal_math_f_limb_bits();
    struct d_internal_math_f_wide result = { 0u, 0u };

    result.high = _value >> ((bits - _shift) % bits);
    result.low  = _value << (_shift % bits);

    return result;
}

// d_internal_math_f_wide_square
//   _a * _a as two limbs: _a split into half-limbs, so each partial product
// fits one limb, and the cross term added twice with its carries.
D_MATH_FN struct d_internal_math_f_wide
d_internal_math_f_wide_square(
    d_math_umax _a
)
{
    const int         half  = d_internal_math_f_limb_bits() / 2;
    const d_math_umax mask  = (((d_math_umax)1) << half) - 1u;
    const d_math_umax ah    = _a >> half;
    const d_math_umax al    = _a & mask;
    const d_math_umax cross = ah * al;
    const d_math_umax lo_in = cross << half;
    const d_math_umax hi_in = cross >> half;
    struct d_internal_math_f_wide result = { 0u, 0u };
    int pass = 0;

    result.high = ah * ah;
    result.low  = al * al;

    // the cross term twice, each time with the carry out of the low limb
    for (pass = 0; pass < 2; ++pass)
    {
        result.low  += lo_in;
        result.high += hi_in + ((result.low < lo_in) ? 1u : 0u);
    }

    return result;
}

// d_internal_math_f_wide_less
//   whether _a < _b.
D_MATH_FN bool
d_internal_math_f_wide_less(
    struct d_internal_math_f_wide _a,
    struct d_internal_math_f_wide _b
)
{
    return ( (_a.high < _b.high) ||
             ( (_a.high == _b.high) &&
               (_a.low < _b.low) ) );
}

// d_internal_math_f_sqrt_settle
//   the last bit of the root of _m in [1, 4), settled in integers: with S =
// 2^(P-1), the root is R / S for an integer R, the midpoint above it is
// (2R + 1) / 2S, and sqrt(m) passes it exactly when 4 S M > (2R + 1)^2, M =
// m S being an integer too. Integer arithmetic is the same under every
// floating-point evaluation method -- an x87's excess precision, which
// breaks Dekker's product, included -- and in constant evaluation.
D_MATH_FN float
d_internal_math_f_sqrt_settle(
    float _m,
    float _root
)
{
    const float         scale = d_internal_math_f_pow2(FLT_MANT_DIG - 1);
    const d_math_umax s     = (d_math_umax)scale;
    const d_math_umax m     = (d_math_umax)(_m * scale);
    const struct d_internal_math_f_wide four_s_m =
        d_internal_math_f_wide_shift(m, FLT_MANT_DIG + 1);
    d_math_umax       r     = (_root >= (float)2) ? ((2u * s) - 1u)
                                                : (d_math_umax)(_root * scale);
    int               tries = 0;

    // up while the root lies past the midpoint above...
    for (tries = 0;
         ( (tries < 4) &&
           (d_internal_math_f_wide_less(
                d_internal_math_f_wide_square((2u * r) + 1u),
                four_s_m)) );
         ++tries)
    {
        ++r;
    }

    // ...down while it lies short of the midpoint below (from 1 it cannot)
    for (tries = 0;
         ( (tries < 4) &&
           (r > s) &&
           (d_internal_math_f_wide_less(
                four_s_m,
                d_internal_math_f_wide_square((2u * r) - 1u))) );
         ++tries)
    {
        --r;
    }

    return ((float)r / scale);
}

// d_internal_math_f_sqrt_unit
//   the correctly rounded square root of _m in [1, 4): Newton's iteration
// from a line within 6% of it -- six steps pass any precision to a quad's --
// then the last bit settled. Where two limbs hold (2^(P+1))^2 -- float, and
// double with a 64-bit d_math_umax -- it is settled in integers
// (sqrt_settle), exact however the build evaluates floating point; otherwise
// by the residual m - root^2, taken exactly by Dekker's product, against the
// midpoints with the root's neighbours (a long double: its own evaluation
// format, so no excess precision intervenes).
D_MATH_FN float
d_internal_math_f_sqrt_unit(
    float _m
)
{
    float root  = (float)0.6 + ((float)0.4 * _m);
    int i     = 0;
    int tries = 0;

    // Newton's iteration
    for (i = 0; i < 6; ++i)
    {
        root = (float)0.5 * (root + (_m / root));
    }

    // the last bit, in integers where they reach
    if (((2 * FLT_MANT_DIG) + 2) <= (2 * d_internal_math_f_limb_bits()))
    {
        return d_internal_math_f_sqrt_settle(_m, root);
    }

    // the last bit: up past the upper midpoint, down past the lower one
    for (tries = 0; tries < 3; ++tries)
    {
        const struct d_internal_math_f_pair square =
            d_internal_math_f_square_exact(root);
        const float residual = (_m - square.high) - square.low;
        const struct d_internal_math_f_binade b =
            d_internal_math_f_binade_of(root);
        const float above = b.power * FLT_EPSILON;
        const float below = (root == b.power) ? (above / (float)2) : above;

        if ((residual - (root * above)) > ((above * above) / (float)4))
        {
            root = d_math_f_next_up(root);
        }
        else if ((residual + (root * below)) < ((below * below) / (float)4))
        {
            root = d_math_f_next_down(root);
        }
        else
        {
            break;
        }
    }

    return root;
}

// d_internal_math_f_asin_small
//   arcsine of |_y| <= 1/2 by its series, sum of b_n y^(2n+1) / (2n + 1)
// with b_n = b_(n-1) (2n - 1) / (2n), summed in long double, compensated,
// until a term no longer moves the sum.
D_MATH_FN long double
d_internal_math_f_asin_small(
    long double _y
)
{
    const long double y2   = _y * _y;
    long double       sum  = _y;
    long double       comp = 0.0L;
    long double       pw   = _y;
    long double       b    = 1.0L;
    int               n    = 1;

    // Kahan's compensated sum: each term's lost low part carried into the
    // next, so the sum's error stays near one rounding however many terms
    for (n = 1; n < 120; ++n)
    {
        const long double before = sum;

        b  *= (long double)((2 * n) - 1) / (long double)(2 * n);
        pw *= y2;

        {
            const long double term   = (b * pw) / (long double)((2 * n) + 1);
            const long double adjust = term - comp;
            const long double next   = sum + adjust;

            comp = (next - sum) - adjust;
            sum  = next;
        }

        // the term no longer reaches the sum's last digit
        if (sum == before)
        {
            break;
        }
    }

    return sum;
}

// 1.2    Square root
//------------------------------------------------------------------------------
// sqrt_c is the correctly rounded square root in pure arithmetic, so the same
// text is a constant expression from C++14, and it agrees with sqrt, the C
// library's (correctly rounded too, by IEEE 754), bit for bit: a face may use
// either and not know which ran. -0 stays -0, a negative or NaN gives NaN,
// +inf stays +inf.

D_MATH_FN float
d_math_f_sqrt_c(
    float _x
)
{
    // NaN, zero (of either sign) and +inf are their own roots
    if ( (_x != _x) ||
         (_x == (float)0) ||
         (_x > FLT_MAX) )
    {
        return _x;
    }

    // a negative value has none
    if (_x < (float)0)
    {
        return d_internal_math_f_nan();
    }

    {
        // a subnormal is first scaled into the normal range by an even power
        const int lift  = (_x < FLT_MIN) ? (((FLT_MANT_DIG + 1) / 2) * 2) : 0;
        const float value = (lift > 0) ? (_x * d_internal_math_f_pow2(lift))
                                     : _x;
        const struct d_internal_math_f_binade b =
            d_internal_math_f_binade_of(value);
        // value = m * 4^k with m in [1, 4); k = floor(E / 2)
        const int k = (b.exponent >= 0) ? (b.exponent / 2)
                                        : -((1 - b.exponent) / 2);
        const float m = value / d_internal_math_f_pow2(2 * k);

        return ( d_internal_math_f_sqrt_unit(m) *
                 d_internal_math_f_pow2(k - (lift / 2)) );
    }
}

D_MATH_FN_RT float
d_math_f_sqrt(
    float _x
)
{
#ifdef __cplusplus
    return std::sqrt(_x);
#else
    return sqrtf(_x);
#endif
}

// 1.3    Arc-cosine
//------------------------------------------------------------------------------
// acos_c is the arc-cosine in pure arithmetic, a constant expression from
// C++14: the arcsine series near 0 and the half-angle identity toward +-1,
// summed in long double, within an ulp or two of acos, the C library's. A
// value outside [-1, 1], or NaN, gives NaN, as acos does.

D_MATH_FN float
d_math_f_acos_c(
    float _x
)
{
    const long double pi = 3.141592653589793238462643383279502884197L;
    const long double x  = (long double)_x;

    // outside the domain, and NaN
    if (!( (_x >= (float)-1) &&
           (_x <= (float)1) ))
    {
        return d_internal_math_f_nan();
    }

    // near 0: pi/2 - asin(x)
    if ( (x <= 0.5L) &&
         (x >= -0.5L) )
    {
        return (float)((pi / 2.0L) - d_internal_math_f_asin_small(x));
    }

    // toward +1: 2 asin(sqrt((1 - x) / 2))
    if (x > 0.5L)
    {
        return (float)(2.0L * d_internal_math_f_asin_small(
                                d_math_ld_sqrt_c((1.0L - x) / 2.0L)));
    }

    // toward -1: pi - 2 asin(sqrt((1 + x) / 2))
    return (float)(pi - (2.0L * d_internal_math_f_asin_small(
                                  d_math_ld_sqrt_c((1.0L + x) / 2.0L))));
}

D_MATH_FN_RT float
d_math_f_acos(
    float _x
)
{
#ifdef __cplusplus
    return std::acos(_x);
#else
    return acosf(_x);
#endif
}

// 1.4    Sine and cosine
//------------------------------------------------------------------------------
// sin_c and cos_c are pure arithmetic, constant expressions from C++14:
// the argument reduced by the nearest multiple of pi/2 (Cody and Waite's
// three-part pi/2, fdlibm's 33-bit pieces, exact in any format of 53 bits
// or more), then the Taylor series on [-pi/4, pi/4], in long double --
// within an ulp of sin and cos for float and double, two for long double,
// for |x| below 2^20; past that the reduction keeps fewer bits than the C
// library's exact one. sin and cos are the library's. NaN and an infinity
// give NaN; -0 stays -0 for sin.

// d_internal_math_f_trig
//   sin(_x) when _cosine is false, cos(_x) when it is true, in long double:
// the reduced argument kept as r + rlo, every step of the reduction an exact
// product or a two-sum, and each series summed with Kahan's compensation;
// the low part enters at the end, sin(r + rlo) = sin r + rlo cos r.
D_MATH_FN long double
d_internal_math_f_trig(
    long double _x,
    bool        _cosine
)
{
    const long double two_over_pi = 0.636619772367581343075535053490057448L;
    const long double pio2_1      = 1.57079632673412561417e+00L;
    const long double pio2_2      = 6.07710050630396597660e-11L;
    const long double pio2_3      = 2.02226624871116645580e-21L;
    const long double pio2_3t     = 8.47842766036889956997e-32L;
    // 1.5 * 2^63: adding and subtracting it rounds a long double of smaller
    // magnitude to an integer (2^62 suffices where long double is double)
    const long double magic       = 1.38350580552821637120e+19L;
    const long double turns       = _x * two_over_pi;
    const long double n           = ( (turns < 4.0e18L) &&
                                      (turns > -4.0e18L) )
                                        ? ((turns + magic) - magic)
                                        : 0.0L;
    // the reduction: x - n pi/2, three exact products, each difference's
    // error kept (two-sum: the first operand is the larger)
    const long double a           = _x - (n * pio2_1);
    const long double b           = n * pio2_2;
    const long double r1          = a - b;
    const long double e1          = (a - r1) - b;
    const long double c           = n * pio2_3;
    const long double r2          = r1 - c;
    const long double e2          = (r1 - r2) - c;
    const long double low         = (e1 + e2) - (n * pio2_3t);
    const long double r           = r2 + low;
    const long double rlo         = low - (r - r2);
    // the quadrant, n mod 4, in [0, 4)
    const long double fourths     = n / 4.0L;
    const long double whole       = ((fourths + magic) - magic);
    long double       quadrant    = n - (4.0L * whole);
    const long double r2sq        = r * r;
    long double       sin_sum     = r;
    long double       sin_comp    = 0.0L;
    long double       cos_sum     = 1.0L;
    long double       cos_comp    = 0.0L;
    long double       sin_term    = r;
    long double       cos_term    = 1.0L;
    int               k           = 1;

    // the rounding of n / 4 may land a quadrant of -1 or 4
    quadrant = (quadrant < 0.0L) ? (quadrant + 4.0L)
                                 : ((quadrant >= 4.0L) ? (quadrant - 4.0L)
                                                       : quadrant);

    // the series on [-pi/4, pi/4], twelve terms past a quad's precision,
    // each sum compensated
    for (k = 1; k < 13; ++k)
    {
        sin_term = -sin_term * r2sq /
                   (long double)((2 * k) * ((2 * k) + 1));
        cos_term = -cos_term * r2sq /
                   (long double)(((2 * k) - 1) * (2 * k));

        {
            const long double ys = sin_term - sin_comp;
            const long double ts = sin_sum + ys;
            const long double yc = cos_term - cos_comp;
            const long double tc = cos_sum + yc;

            sin_comp = (ts - sin_sum) - ys;
            sin_sum  = ts;
            cos_comp = (tc - cos_sum) - yc;
            cos_sum  = tc;
        }
    }

    // the reduced argument's low part: sin(r + rlo) = sin r + rlo cos r,
    // cos(r + rlo) = cos r - rlo sin r
    {
        const long double s = sin_sum + (rlo * cos_sum);
        const long double co = cos_sum - (rlo * sin_sum);

        // cos x = sin(x + pi/2): a quarter turn more
        if (_cosine)
        {
            quadrant = (quadrant >= 3.0L) ? (quadrant - 3.0L)
                                          : (quadrant + 1.0L);
        }

        return (quadrant == 0.0L) ?  s  :
               (quadrant == 1.0L) ?  co :
               (quadrant == 2.0L) ? -s  :
                                    -co;
    }
}

D_MATH_FN float
d_math_f_sin_c(
    float _x
)
{
    // NaN and the infinities
    if (!( (_x <= FLT_MAX) &&
           (_x >= -FLT_MAX) ))
    {
        return d_internal_math_f_nan();
    }

    // zero, of either sign, is its own sine
    if (_x == (float)0)
    {
        return _x;
    }

    return (float)d_internal_math_f_trig((long double)_x, false);
}

D_MATH_FN float
d_math_f_cos_c(
    float _x
)
{
    // NaN and the infinities
    if (!( (_x <= FLT_MAX) &&
           (_x >= -FLT_MAX) ))
    {
        return d_internal_math_f_nan();
    }

    return (float)d_internal_math_f_trig((long double)_x, true);
}

D_MATH_FN_RT float
d_math_f_sin(
    float _x
)
{
#ifdef __cplusplus
    return std::sin(_x);
#else
    return sinf(_x);
#endif
}

D_MATH_FN_RT float
d_math_f_cos(
    float _x
)
{
#ifdef __cplusplus
    return std::cos(_x);
#else
    return cosf(_x);
#endif
}

//==============================================================================
// 2.  THE DOUBLE FAMILY (_d)
//==============================================================================


// 2.1    Internal helpers
//------------------------------------------------------------------------------

// d_internal_math_d_pair
//   struct: a value as an unevaluated sum, high + low, the low part below the
// high part's rounding.
struct d_internal_math_d_pair
{
    double high;
    double low;
};

// d_internal_math_d_nan
//   a quiet NaN: a constant expression where the build defines NAN.
D_MATH_FN double
d_internal_math_d_nan(void)
{
#if defined(NAN)
    return (double)NAN;
#else
    return (double)(HUGE_VAL - HUGE_VAL);
#endif
}

// d_internal_math_d_square_exact
//   _c * _c exactly, as high + low: Dekker's product, the factors split by
// Veltkamp's constant 2^ceil(P/2) + 1. _c must be normal and its square
// finite.
D_MATH_FN struct d_internal_math_d_pair
d_internal_math_d_square_exact(
    double _c
)
{
    struct d_internal_math_d_pair result = { (double)0, (double)0 };
    const double split = d_internal_math_d_pow2((DBL_MANT_DIG + 1) / 2) + (double)1;
    const double t     = split * _c;
    const double hi    = t - (t - _c);
    const double lo    = _c - hi;

    result.high = _c * _c;
    result.low  = (((hi * hi) - result.high) + (((double)2 * hi) * lo)) +
                  (lo * lo);

    return result;
}

// d_internal_math_d_wide
//   struct: an unsigned integer of two d_math_umax limbs, high * 2^bits + low.
struct d_internal_math_d_wide
{
    d_math_umax high;
    d_math_umax low;
};

// d_internal_math_d_limb_bits
//   the bits of d_math_umax.
D_MATH_FN int
d_internal_math_d_limb_bits(void)
{
    return (int)(sizeof(d_math_umax) * 8u);
}

// d_internal_math_d_wide_shift
//   _value * 2^_shift as two limbs, for 0 < _shift < the limb's bits.
D_MATH_FN struct d_internal_math_d_wide
d_internal_math_d_wide_shift(
    d_math_umax _value,
    int         _shift
)
{
    const int bits = d_internal_math_d_limb_bits();
    struct d_internal_math_d_wide result = { 0u, 0u };

    result.high = _value >> ((bits - _shift) % bits);
    result.low  = _value << (_shift % bits);

    return result;
}

// d_internal_math_d_wide_square
//   _a * _a as two limbs: _a split into half-limbs, so each partial product
// fits one limb, and the cross term added twice with its carries.
D_MATH_FN struct d_internal_math_d_wide
d_internal_math_d_wide_square(
    d_math_umax _a
)
{
    const int         half  = d_internal_math_d_limb_bits() / 2;
    const d_math_umax mask  = (((d_math_umax)1) << half) - 1u;
    const d_math_umax ah    = _a >> half;
    const d_math_umax al    = _a & mask;
    const d_math_umax cross = ah * al;
    const d_math_umax lo_in = cross << half;
    const d_math_umax hi_in = cross >> half;
    struct d_internal_math_d_wide result = { 0u, 0u };
    int pass = 0;

    result.high = ah * ah;
    result.low  = al * al;

    // the cross term twice, each time with the carry out of the low limb
    for (pass = 0; pass < 2; ++pass)
    {
        result.low  += lo_in;
        result.high += hi_in + ((result.low < lo_in) ? 1u : 0u);
    }

    return result;
}

// d_internal_math_d_wide_less
//   whether _a < _b.
D_MATH_FN bool
d_internal_math_d_wide_less(
    struct d_internal_math_d_wide _a,
    struct d_internal_math_d_wide _b
)
{
    return ( (_a.high < _b.high) ||
             ( (_a.high == _b.high) &&
               (_a.low < _b.low) ) );
}

// d_internal_math_d_sqrt_settle
//   the last bit of the root of _m in [1, 4), settled in integers: with S =
// 2^(P-1), the root is R / S for an integer R, the midpoint above it is
// (2R + 1) / 2S, and sqrt(m) passes it exactly when 4 S M > (2R + 1)^2, M =
// m S being an integer too. Integer arithmetic is the same under every
// floating-point evaluation method -- an x87's excess precision, which
// breaks Dekker's product, included -- and in constant evaluation.
D_MATH_FN double
d_internal_math_d_sqrt_settle(
    double _m,
    double _root
)
{
    const double         scale = d_internal_math_d_pow2(DBL_MANT_DIG - 1);
    const d_math_umax s     = (d_math_umax)scale;
    const d_math_umax m     = (d_math_umax)(_m * scale);
    const struct d_internal_math_d_wide four_s_m =
        d_internal_math_d_wide_shift(m, DBL_MANT_DIG + 1);
    d_math_umax       r     = (_root >= (double)2) ? ((2u * s) - 1u)
                                                : (d_math_umax)(_root * scale);
    int               tries = 0;

    // up while the root lies past the midpoint above...
    for (tries = 0;
         ( (tries < 4) &&
           (d_internal_math_d_wide_less(
                d_internal_math_d_wide_square((2u * r) + 1u),
                four_s_m)) );
         ++tries)
    {
        ++r;
    }

    // ...down while it lies short of the midpoint below (from 1 it cannot)
    for (tries = 0;
         ( (tries < 4) &&
           (r > s) &&
           (d_internal_math_d_wide_less(
                four_s_m,
                d_internal_math_d_wide_square((2u * r) - 1u))) );
         ++tries)
    {
        --r;
    }

    return ((double)r / scale);
}

// d_internal_math_d_sqrt_unit
//   the correctly rounded square root of _m in [1, 4): Newton's iteration
// from a line within 6% of it -- six steps pass any precision to a quad's --
// then the last bit settled. Where two limbs hold (2^(P+1))^2 -- float, and
// double with a 64-bit d_math_umax -- it is settled in integers
// (sqrt_settle), exact however the build evaluates floating point; otherwise
// by the residual m - root^2, taken exactly by Dekker's product, against the
// midpoints with the root's neighbours (a long double: its own evaluation
// format, so no excess precision intervenes).
D_MATH_FN double
d_internal_math_d_sqrt_unit(
    double _m
)
{
    double root  = (double)0.6 + ((double)0.4 * _m);
    int i     = 0;
    int tries = 0;

    // Newton's iteration
    for (i = 0; i < 6; ++i)
    {
        root = (double)0.5 * (root + (_m / root));
    }

    // the last bit, in integers where they reach
    if (((2 * DBL_MANT_DIG) + 2) <= (2 * d_internal_math_d_limb_bits()))
    {
        return d_internal_math_d_sqrt_settle(_m, root);
    }

    // the last bit: up past the upper midpoint, down past the lower one
    for (tries = 0; tries < 3; ++tries)
    {
        const struct d_internal_math_d_pair square =
            d_internal_math_d_square_exact(root);
        const double residual = (_m - square.high) - square.low;
        const struct d_internal_math_d_binade b =
            d_internal_math_d_binade_of(root);
        const double above = b.power * DBL_EPSILON;
        const double below = (root == b.power) ? (above / (double)2) : above;

        if ((residual - (root * above)) > ((above * above) / (double)4))
        {
            root = d_math_d_next_up(root);
        }
        else if ((residual + (root * below)) < ((below * below) / (double)4))
        {
            root = d_math_d_next_down(root);
        }
        else
        {
            break;
        }
    }

    return root;
}

// d_internal_math_d_asin_small
//   arcsine of |_y| <= 1/2 by its series, sum of b_n y^(2n+1) / (2n + 1)
// with b_n = b_(n-1) (2n - 1) / (2n), summed in long double, compensated,
// until a term no longer moves the sum.
D_MATH_FN long double
d_internal_math_d_asin_small(
    long double _y
)
{
    const long double y2   = _y * _y;
    long double       sum  = _y;
    long double       comp = 0.0L;
    long double       pw   = _y;
    long double       b    = 1.0L;
    int               n    = 1;

    // Kahan's compensated sum: each term's lost low part carried into the
    // next, so the sum's error stays near one rounding however many terms
    for (n = 1; n < 120; ++n)
    {
        const long double before = sum;

        b  *= (long double)((2 * n) - 1) / (long double)(2 * n);
        pw *= y2;

        {
            const long double term   = (b * pw) / (long double)((2 * n) + 1);
            const long double adjust = term - comp;
            const long double next   = sum + adjust;

            comp = (next - sum) - adjust;
            sum  = next;
        }

        // the term no longer reaches the sum's last digit
        if (sum == before)
        {
            break;
        }
    }

    return sum;
}

// 2.2    Square root
//------------------------------------------------------------------------------
// sqrt_c is the correctly rounded square root in pure arithmetic, so the same
// text is a constant expression from C++14, and it agrees with sqrt, the C
// library's (correctly rounded too, by IEEE 754), bit for bit: a face may use
// either and not know which ran. -0 stays -0, a negative or NaN gives NaN,
// +inf stays +inf.

D_MATH_FN double
d_math_d_sqrt_c(
    double _x
)
{
    // NaN, zero (of either sign) and +inf are their own roots
    if ( (_x != _x) ||
         (_x == (double)0) ||
         (_x > DBL_MAX) )
    {
        return _x;
    }

    // a negative value has none
    if (_x < (double)0)
    {
        return d_internal_math_d_nan();
    }

    {
        // a subnormal is first scaled into the normal range by an even power
        const int lift  = (_x < DBL_MIN) ? (((DBL_MANT_DIG + 1) / 2) * 2) : 0;
        const double value = (lift > 0) ? (_x * d_internal_math_d_pow2(lift))
                                     : _x;
        const struct d_internal_math_d_binade b =
            d_internal_math_d_binade_of(value);
        // value = m * 4^k with m in [1, 4); k = floor(E / 2)
        const int k = (b.exponent >= 0) ? (b.exponent / 2)
                                        : -((1 - b.exponent) / 2);
        const double m = value / d_internal_math_d_pow2(2 * k);

        return ( d_internal_math_d_sqrt_unit(m) *
                 d_internal_math_d_pow2(k - (lift / 2)) );
    }
}

D_MATH_FN_RT double
d_math_d_sqrt(
    double _x
)
{
#ifdef __cplusplus
    return std::sqrt(_x);
#else
    return sqrt(_x);
#endif
}

// 2.3    Arc-cosine
//------------------------------------------------------------------------------
// acos_c is the arc-cosine in pure arithmetic, a constant expression from
// C++14: the arcsine series near 0 and the half-angle identity toward +-1,
// summed in long double, within an ulp or two of acos, the C library's. A
// value outside [-1, 1], or NaN, gives NaN, as acos does.

D_MATH_FN double
d_math_d_acos_c(
    double _x
)
{
    const long double pi = 3.141592653589793238462643383279502884197L;
    const long double x  = (long double)_x;

    // outside the domain, and NaN
    if (!( (_x >= (double)-1) &&
           (_x <= (double)1) ))
    {
        return d_internal_math_d_nan();
    }

    // near 0: pi/2 - asin(x)
    if ( (x <= 0.5L) &&
         (x >= -0.5L) )
    {
        return (double)((pi / 2.0L) - d_internal_math_d_asin_small(x));
    }

    // toward +1: 2 asin(sqrt((1 - x) / 2))
    if (x > 0.5L)
    {
        return (double)(2.0L * d_internal_math_d_asin_small(
                                d_math_ld_sqrt_c((1.0L - x) / 2.0L)));
    }

    // toward -1: pi - 2 asin(sqrt((1 + x) / 2))
    return (double)(pi - (2.0L * d_internal_math_d_asin_small(
                                  d_math_ld_sqrt_c((1.0L + x) / 2.0L))));
}

D_MATH_FN_RT double
d_math_d_acos(
    double _x
)
{
#ifdef __cplusplus
    return std::acos(_x);
#else
    return acos(_x);
#endif
}

// 2.4    Sine and cosine
//------------------------------------------------------------------------------
// sin_c and cos_c are pure arithmetic, constant expressions from C++14:
// the argument reduced by the nearest multiple of pi/2 (Cody and Waite's
// three-part pi/2, fdlibm's 33-bit pieces, exact in any format of 53 bits
// or more), then the Taylor series on [-pi/4, pi/4], in long double --
// within an ulp of sin and cos for float and double, two for long double,
// for |x| below 2^20; past that the reduction keeps fewer bits than the C
// library's exact one. sin and cos are the library's. NaN and an infinity
// give NaN; -0 stays -0 for sin.

// d_internal_math_d_trig
//   sin(_x) when _cosine is false, cos(_x) when it is true, in long double:
// the reduced argument kept as r + rlo, every step of the reduction an exact
// product or a two-sum, and each series summed with Kahan's compensation;
// the low part enters at the end, sin(r + rlo) = sin r + rlo cos r.
D_MATH_FN long double
d_internal_math_d_trig(
    long double _x,
    bool        _cosine
)
{
    const long double two_over_pi = 0.636619772367581343075535053490057448L;
    const long double pio2_1      = 1.57079632673412561417e+00L;
    const long double pio2_2      = 6.07710050630396597660e-11L;
    const long double pio2_3      = 2.02226624871116645580e-21L;
    const long double pio2_3t     = 8.47842766036889956997e-32L;
    // 1.5 * 2^63: adding and subtracting it rounds a long double of smaller
    // magnitude to an integer (2^62 suffices where long double is double)
    const long double magic       = 1.38350580552821637120e+19L;
    const long double turns       = _x * two_over_pi;
    const long double n           = ( (turns < 4.0e18L) &&
                                      (turns > -4.0e18L) )
                                        ? ((turns + magic) - magic)
                                        : 0.0L;
    // the reduction: x - n pi/2, three exact products, each difference's
    // error kept (two-sum: the first operand is the larger)
    const long double a           = _x - (n * pio2_1);
    const long double b           = n * pio2_2;
    const long double r1          = a - b;
    const long double e1          = (a - r1) - b;
    const long double c           = n * pio2_3;
    const long double r2          = r1 - c;
    const long double e2          = (r1 - r2) - c;
    const long double low         = (e1 + e2) - (n * pio2_3t);
    const long double r           = r2 + low;
    const long double rlo         = low - (r - r2);
    // the quadrant, n mod 4, in [0, 4)
    const long double fourths     = n / 4.0L;
    const long double whole       = ((fourths + magic) - magic);
    long double       quadrant    = n - (4.0L * whole);
    const long double r2sq        = r * r;
    long double       sin_sum     = r;
    long double       sin_comp    = 0.0L;
    long double       cos_sum     = 1.0L;
    long double       cos_comp    = 0.0L;
    long double       sin_term    = r;
    long double       cos_term    = 1.0L;
    int               k           = 1;

    // the rounding of n / 4 may land a quadrant of -1 or 4
    quadrant = (quadrant < 0.0L) ? (quadrant + 4.0L)
                                 : ((quadrant >= 4.0L) ? (quadrant - 4.0L)
                                                       : quadrant);

    // the series on [-pi/4, pi/4], twelve terms past a quad's precision,
    // each sum compensated
    for (k = 1; k < 13; ++k)
    {
        sin_term = -sin_term * r2sq /
                   (long double)((2 * k) * ((2 * k) + 1));
        cos_term = -cos_term * r2sq /
                   (long double)(((2 * k) - 1) * (2 * k));

        {
            const long double ys = sin_term - sin_comp;
            const long double ts = sin_sum + ys;
            const long double yc = cos_term - cos_comp;
            const long double tc = cos_sum + yc;

            sin_comp = (ts - sin_sum) - ys;
            sin_sum  = ts;
            cos_comp = (tc - cos_sum) - yc;
            cos_sum  = tc;
        }
    }

    // the reduced argument's low part: sin(r + rlo) = sin r + rlo cos r,
    // cos(r + rlo) = cos r - rlo sin r
    {
        const long double s = sin_sum + (rlo * cos_sum);
        const long double co = cos_sum - (rlo * sin_sum);

        // cos x = sin(x + pi/2): a quarter turn more
        if (_cosine)
        {
            quadrant = (quadrant >= 3.0L) ? (quadrant - 3.0L)
                                          : (quadrant + 1.0L);
        }

        return (quadrant == 0.0L) ?  s  :
               (quadrant == 1.0L) ?  co :
               (quadrant == 2.0L) ? -s  :
                                    -co;
    }
}

D_MATH_FN double
d_math_d_sin_c(
    double _x
)
{
    // NaN and the infinities
    if (!( (_x <= DBL_MAX) &&
           (_x >= -DBL_MAX) ))
    {
        return d_internal_math_d_nan();
    }

    // zero, of either sign, is its own sine
    if (_x == (double)0)
    {
        return _x;
    }

    return (double)d_internal_math_d_trig((long double)_x, false);
}

D_MATH_FN double
d_math_d_cos_c(
    double _x
)
{
    // NaN and the infinities
    if (!( (_x <= DBL_MAX) &&
           (_x >= -DBL_MAX) ))
    {
        return d_internal_math_d_nan();
    }

    return (double)d_internal_math_d_trig((long double)_x, true);
}

D_MATH_FN_RT double
d_math_d_sin(
    double _x
)
{
#ifdef __cplusplus
    return std::sin(_x);
#else
    return sin(_x);
#endif
}

D_MATH_FN_RT double
d_math_d_cos(
    double _x
)
{
#ifdef __cplusplus
    return std::cos(_x);
#else
    return cos(_x);
#endif
}

//==============================================================================
// 3.  THE LONG DOUBLE FAMILY (_ld)
//==============================================================================


// 3.1    Internal helpers
//------------------------------------------------------------------------------

// d_internal_math_ld_pair
//   struct: a value as an unevaluated sum, high + low, the low part below the
// high part's rounding.
struct d_internal_math_ld_pair
{
    long double high;
    long double low;
};

// d_internal_math_ld_nan
//   a quiet NaN: a constant expression where the build defines NAN.
D_MATH_FN long double
d_internal_math_ld_nan(void)
{
#if defined(NAN)
    return (long double)NAN;
#else
    return (long double)(HUGE_VAL - HUGE_VAL);
#endif
}

// d_internal_math_ld_square_exact
//   _c * _c exactly, as high + low: Dekker's product, the factors split by
// Veltkamp's constant 2^ceil(P/2) + 1. _c must be normal and its square
// finite.
D_MATH_FN struct d_internal_math_ld_pair
d_internal_math_ld_square_exact(
    long double _c
)
{
    struct d_internal_math_ld_pair result = { (long double)0, (long double)0 };
    const long double split = d_internal_math_ld_pow2((LDBL_MANT_DIG + 1) / 2) + (long double)1;
    const long double t     = split * _c;
    const long double hi    = t - (t - _c);
    const long double lo    = _c - hi;

    result.high = _c * _c;
    result.low  = (((hi * hi) - result.high) + (((long double)2 * hi) * lo)) +
                  (lo * lo);

    return result;
}

// d_internal_math_ld_wide
//   struct: an unsigned integer of two d_math_umax limbs, high * 2^bits + low.
struct d_internal_math_ld_wide
{
    d_math_umax high;
    d_math_umax low;
};

// d_internal_math_ld_limb_bits
//   the bits of d_math_umax.
D_MATH_FN int
d_internal_math_ld_limb_bits(void)
{
    return (int)(sizeof(d_math_umax) * 8u);
}

// d_internal_math_ld_wide_shift
//   _value * 2^_shift as two limbs, for 0 < _shift < the limb's bits.
D_MATH_FN struct d_internal_math_ld_wide
d_internal_math_ld_wide_shift(
    d_math_umax _value,
    int         _shift
)
{
    const int bits = d_internal_math_ld_limb_bits();
    struct d_internal_math_ld_wide result = { 0u, 0u };

    result.high = _value >> ((bits - _shift) % bits);
    result.low  = _value << (_shift % bits);

    return result;
}

// d_internal_math_ld_wide_square
//   _a * _a as two limbs: _a split into half-limbs, so each partial product
// fits one limb, and the cross term added twice with its carries.
D_MATH_FN struct d_internal_math_ld_wide
d_internal_math_ld_wide_square(
    d_math_umax _a
)
{
    const int         half  = d_internal_math_ld_limb_bits() / 2;
    const d_math_umax mask  = (((d_math_umax)1) << half) - 1u;
    const d_math_umax ah    = _a >> half;
    const d_math_umax al    = _a & mask;
    const d_math_umax cross = ah * al;
    const d_math_umax lo_in = cross << half;
    const d_math_umax hi_in = cross >> half;
    struct d_internal_math_ld_wide result = { 0u, 0u };
    int pass = 0;

    result.high = ah * ah;
    result.low  = al * al;

    // the cross term twice, each time with the carry out of the low limb
    for (pass = 0; pass < 2; ++pass)
    {
        result.low  += lo_in;
        result.high += hi_in + ((result.low < lo_in) ? 1u : 0u);
    }

    return result;
}

// d_internal_math_ld_wide_less
//   whether _a < _b.
D_MATH_FN bool
d_internal_math_ld_wide_less(
    struct d_internal_math_ld_wide _a,
    struct d_internal_math_ld_wide _b
)
{
    return ( (_a.high < _b.high) ||
             ( (_a.high == _b.high) &&
               (_a.low < _b.low) ) );
}

// d_internal_math_ld_sqrt_settle
//   the last bit of the root of _m in [1, 4), settled in integers: with S =
// 2^(P-1), the root is R / S for an integer R, the midpoint above it is
// (2R + 1) / 2S, and sqrt(m) passes it exactly when 4 S M > (2R + 1)^2, M =
// m S being an integer too. Integer arithmetic is the same under every
// floating-point evaluation method -- an x87's excess precision, which
// breaks Dekker's product, included -- and in constant evaluation.
D_MATH_FN long double
d_internal_math_ld_sqrt_settle(
    long double _m,
    long double _root
)
{
    const long double         scale = d_internal_math_ld_pow2(LDBL_MANT_DIG - 1);
    const d_math_umax s     = (d_math_umax)scale;
    const d_math_umax m     = (d_math_umax)(_m * scale);
    const struct d_internal_math_ld_wide four_s_m =
        d_internal_math_ld_wide_shift(m, LDBL_MANT_DIG + 1);
    d_math_umax       r     = (_root >= (long double)2) ? ((2u * s) - 1u)
                                                : (d_math_umax)(_root * scale);
    int               tries = 0;

    // up while the root lies past the midpoint above...
    for (tries = 0;
         ( (tries < 4) &&
           (d_internal_math_ld_wide_less(
                d_internal_math_ld_wide_square((2u * r) + 1u),
                four_s_m)) );
         ++tries)
    {
        ++r;
    }

    // ...down while it lies short of the midpoint below (from 1 it cannot)
    for (tries = 0;
         ( (tries < 4) &&
           (r > s) &&
           (d_internal_math_ld_wide_less(
                four_s_m,
                d_internal_math_ld_wide_square((2u * r) - 1u))) );
         ++tries)
    {
        --r;
    }

    return ((long double)r / scale);
}

// d_internal_math_ld_sqrt_unit
//   the correctly rounded square root of _m in [1, 4): Newton's iteration
// from a line within 6% of it -- six steps pass any precision to a quad's --
// then the last bit settled. Where two limbs hold (2^(P+1))^2 -- float, and
// double with a 64-bit d_math_umax -- it is settled in integers
// (sqrt_settle), exact however the build evaluates floating point; otherwise
// by the residual m - root^2, taken exactly by Dekker's product, against the
// midpoints with the root's neighbours (a long double: its own evaluation
// format, so no excess precision intervenes).
D_MATH_FN long double
d_internal_math_ld_sqrt_unit(
    long double _m
)
{
    long double root  = (long double)0.6 + ((long double)0.4 * _m);
    int i     = 0;
    int tries = 0;

    // Newton's iteration
    for (i = 0; i < 6; ++i)
    {
        root = (long double)0.5 * (root + (_m / root));
    }

    // the last bit, in integers where they reach
    if (((2 * LDBL_MANT_DIG) + 2) <= (2 * d_internal_math_ld_limb_bits()))
    {
        return d_internal_math_ld_sqrt_settle(_m, root);
    }

    // the last bit: up past the upper midpoint, down past the lower one
    for (tries = 0; tries < 3; ++tries)
    {
        const struct d_internal_math_ld_pair square =
            d_internal_math_ld_square_exact(root);
        const long double residual = (_m - square.high) - square.low;
        const struct d_internal_math_ld_binade b =
            d_internal_math_ld_binade_of(root);
        const long double above = b.power * LDBL_EPSILON;
        const long double below = (root == b.power) ? (above / (long double)2) : above;

        if ((residual - (root * above)) > ((above * above) / (long double)4))
        {
            root = d_math_ld_next_up(root);
        }
        else if ((residual + (root * below)) < ((below * below) / (long double)4))
        {
            root = d_math_ld_next_down(root);
        }
        else
        {
            break;
        }
    }

    return root;
}

// d_internal_math_ld_asin_small
//   arcsine of |_y| <= 1/2 by its series, sum of b_n y^(2n+1) / (2n + 1)
// with b_n = b_(n-1) (2n - 1) / (2n), summed in long double, compensated,
// until a term no longer moves the sum.
D_MATH_FN long double
d_internal_math_ld_asin_small(
    long double _y
)
{
    const long double y2   = _y * _y;
    long double       sum  = _y;
    long double       comp = 0.0L;
    long double       pw   = _y;
    long double       b    = 1.0L;
    int               n    = 1;

    // Kahan's compensated sum: each term's lost low part carried into the
    // next, so the sum's error stays near one rounding however many terms
    for (n = 1; n < 120; ++n)
    {
        const long double before = sum;

        b  *= (long double)((2 * n) - 1) / (long double)(2 * n);
        pw *= y2;

        {
            const long double term   = (b * pw) / (long double)((2 * n) + 1);
            const long double adjust = term - comp;
            const long double next   = sum + adjust;

            comp = (next - sum) - adjust;
            sum  = next;
        }

        // the term no longer reaches the sum's last digit
        if (sum == before)
        {
            break;
        }
    }

    return sum;
}

// 3.2    Square root
//------------------------------------------------------------------------------
// sqrt_c is the correctly rounded square root in pure arithmetic, so the same
// text is a constant expression from C++14, and it agrees with sqrt, the C
// library's (correctly rounded too, by IEEE 754), bit for bit: a face may use
// either and not know which ran. -0 stays -0, a negative or NaN gives NaN,
// +inf stays +inf.

D_MATH_FN long double
d_math_ld_sqrt_c(
    long double _x
)
{
    // NaN, zero (of either sign) and +inf are their own roots
    if ( (_x != _x) ||
         (_x == (long double)0) ||
         (_x > LDBL_MAX) )
    {
        return _x;
    }

    // a negative value has none
    if (_x < (long double)0)
    {
        return d_internal_math_ld_nan();
    }

    {
        // a subnormal is first scaled into the normal range by an even power
        const int lift  = (_x < LDBL_MIN) ? (((LDBL_MANT_DIG + 1) / 2) * 2) : 0;
        const long double value = (lift > 0) ? (_x * d_internal_math_ld_pow2(lift))
                                     : _x;
        const struct d_internal_math_ld_binade b =
            d_internal_math_ld_binade_of(value);
        // value = m * 4^k with m in [1, 4); k = floor(E / 2)
        const int k = (b.exponent >= 0) ? (b.exponent / 2)
                                        : -((1 - b.exponent) / 2);
        const long double m = value / d_internal_math_ld_pow2(2 * k);

        return ( d_internal_math_ld_sqrt_unit(m) *
                 d_internal_math_ld_pow2(k - (lift / 2)) );
    }
}

D_MATH_FN_RT long double
d_math_ld_sqrt(
    long double _x
)
{
#ifdef __cplusplus
    return std::sqrt(_x);
#else
    return sqrtl(_x);
#endif
}

// 3.3    Arc-cosine
//------------------------------------------------------------------------------
// acos_c is the arc-cosine in pure arithmetic, a constant expression from
// C++14: the arcsine series near 0 and the half-angle identity toward +-1,
// summed in long double, within an ulp or two of acos, the C library's. A
// value outside [-1, 1], or NaN, gives NaN, as acos does.

D_MATH_FN long double
d_math_ld_acos_c(
    long double _x
)
{
    const long double pi = 3.141592653589793238462643383279502884197L;
    const long double x  = (long double)_x;

    // outside the domain, and NaN
    if (!( (_x >= (long double)-1) &&
           (_x <= (long double)1) ))
    {
        return d_internal_math_ld_nan();
    }

    // near 0: pi/2 - asin(x)
    if ( (x <= 0.5L) &&
         (x >= -0.5L) )
    {
        return (long double)((pi / 2.0L) - d_internal_math_ld_asin_small(x));
    }

    // toward +1: 2 asin(sqrt((1 - x) / 2))
    if (x > 0.5L)
    {
        return (long double)(2.0L * d_internal_math_ld_asin_small(
                                d_math_ld_sqrt_c((1.0L - x) / 2.0L)));
    }

    // toward -1: pi - 2 asin(sqrt((1 + x) / 2))
    return (long double)(pi - (2.0L * d_internal_math_ld_asin_small(
                                  d_math_ld_sqrt_c((1.0L + x) / 2.0L))));
}

D_MATH_FN_RT long double
d_math_ld_acos(
    long double _x
)
{
#ifdef __cplusplus
    return std::acos(_x);
#else
    return acosl(_x);
#endif
}

// 3.4    Sine and cosine
//------------------------------------------------------------------------------
// sin_c and cos_c are pure arithmetic, constant expressions from C++14:
// the argument reduced by the nearest multiple of pi/2 (Cody and Waite's
// three-part pi/2, fdlibm's 33-bit pieces, exact in any format of 53 bits
// or more), then the Taylor series on [-pi/4, pi/4], in long double --
// within an ulp of sin and cos for float and double, two for long double,
// for |x| below 2^20; past that the reduction keeps fewer bits than the C
// library's exact one. sin and cos are the library's. NaN and an infinity
// give NaN; -0 stays -0 for sin.

// d_internal_math_ld_trig
//   sin(_x) when _cosine is false, cos(_x) when it is true, in long double:
// the reduced argument kept as r + rlo, every step of the reduction an exact
// product or a two-sum, and each series summed with Kahan's compensation;
// the low part enters at the end, sin(r + rlo) = sin r + rlo cos r.
D_MATH_FN long double
d_internal_math_ld_trig(
    long double _x,
    bool        _cosine
)
{
    const long double two_over_pi = 0.636619772367581343075535053490057448L;
    const long double pio2_1      = 1.57079632673412561417e+00L;
    const long double pio2_2      = 6.07710050630396597660e-11L;
    const long double pio2_3      = 2.02226624871116645580e-21L;
    const long double pio2_3t     = 8.47842766036889956997e-32L;
    // 1.5 * 2^63: adding and subtracting it rounds a long double of smaller
    // magnitude to an integer (2^62 suffices where long double is double)
    const long double magic       = 1.38350580552821637120e+19L;
    const long double turns       = _x * two_over_pi;
    const long double n           = ( (turns < 4.0e18L) &&
                                      (turns > -4.0e18L) )
                                        ? ((turns + magic) - magic)
                                        : 0.0L;
    // the reduction: x - n pi/2, three exact products, each difference's
    // error kept (two-sum: the first operand is the larger)
    const long double a           = _x - (n * pio2_1);
    const long double b           = n * pio2_2;
    const long double r1          = a - b;
    const long double e1          = (a - r1) - b;
    const long double c           = n * pio2_3;
    const long double r2          = r1 - c;
    const long double e2          = (r1 - r2) - c;
    const long double low         = (e1 + e2) - (n * pio2_3t);
    const long double r           = r2 + low;
    const long double rlo         = low - (r - r2);
    // the quadrant, n mod 4, in [0, 4)
    const long double fourths     = n / 4.0L;
    const long double whole       = ((fourths + magic) - magic);
    long double       quadrant    = n - (4.0L * whole);
    const long double r2sq        = r * r;
    long double       sin_sum     = r;
    long double       sin_comp    = 0.0L;
    long double       cos_sum     = 1.0L;
    long double       cos_comp    = 0.0L;
    long double       sin_term    = r;
    long double       cos_term    = 1.0L;
    int               k           = 1;

    // the rounding of n / 4 may land a quadrant of -1 or 4
    quadrant = (quadrant < 0.0L) ? (quadrant + 4.0L)
                                 : ((quadrant >= 4.0L) ? (quadrant - 4.0L)
                                                       : quadrant);

    // the series on [-pi/4, pi/4], twelve terms past a quad's precision,
    // each sum compensated
    for (k = 1; k < 13; ++k)
    {
        sin_term = -sin_term * r2sq /
                   (long double)((2 * k) * ((2 * k) + 1));
        cos_term = -cos_term * r2sq /
                   (long double)(((2 * k) - 1) * (2 * k));

        {
            const long double ys = sin_term - sin_comp;
            const long double ts = sin_sum + ys;
            const long double yc = cos_term - cos_comp;
            const long double tc = cos_sum + yc;

            sin_comp = (ts - sin_sum) - ys;
            sin_sum  = ts;
            cos_comp = (tc - cos_sum) - yc;
            cos_sum  = tc;
        }
    }

    // the reduced argument's low part: sin(r + rlo) = sin r + rlo cos r,
    // cos(r + rlo) = cos r - rlo sin r
    {
        const long double s = sin_sum + (rlo * cos_sum);
        const long double co = cos_sum - (rlo * sin_sum);

        // cos x = sin(x + pi/2): a quarter turn more
        if (_cosine)
        {
            quadrant = (quadrant >= 3.0L) ? (quadrant - 3.0L)
                                          : (quadrant + 1.0L);
        }

        return (quadrant == 0.0L) ?  s  :
               (quadrant == 1.0L) ?  co :
               (quadrant == 2.0L) ? -s  :
                                    -co;
    }
}

D_MATH_FN long double
d_math_ld_sin_c(
    long double _x
)
{
    // NaN and the infinities
    if (!( (_x <= LDBL_MAX) &&
           (_x >= -LDBL_MAX) ))
    {
        return d_internal_math_ld_nan();
    }

    // zero, of either sign, is its own sine
    if (_x == (long double)0)
    {
        return _x;
    }

    return (long double)d_internal_math_ld_trig((long double)_x, false);
}

D_MATH_FN long double
d_math_ld_cos_c(
    long double _x
)
{
    // NaN and the infinities
    if (!( (_x <= LDBL_MAX) &&
           (_x >= -LDBL_MAX) ))
    {
        return d_internal_math_ld_nan();
    }

    return (long double)d_internal_math_ld_trig((long double)_x, true);
}

D_MATH_FN_RT long double
d_math_ld_sin(
    long double _x
)
{
#ifdef __cplusplus
    return std::sin(_x);
#else
    return sinl(_x);
#endif
}

D_MATH_FN_RT long double
d_math_ld_cos(
    long double _x
)
{
#ifdef __cplusplus
    return std::cos(_x);
#else
    return cosl(_x);
#endif
}


#ifdef __cplusplus

//==============================================================================
// 4.  ONE NAME FOR EVERY FAMILY (C++)
//==============================================================================
// C++ only: the kernels above under one name each, chosen by argument type,
// so a C++ template serves float, double and long double alike.


D_MATH_FN float
d_math_sqrt_c(
    float _x
)
{
    return d_math_f_sqrt_c(_x);
}

D_MATH_FN_RT float
d_math_sqrt(
    float _x
)
{
    return d_math_f_sqrt(_x);
}

D_MATH_FN float
d_math_acos_c(
    float _x
)
{
    return d_math_f_acos_c(_x);
}

D_MATH_FN_RT float
d_math_acos(
    float _x
)
{
    return d_math_f_acos(_x);
}

D_MATH_FN float
d_math_sin_c(
    float _x
)
{
    return d_math_f_sin_c(_x);
}

D_MATH_FN_RT float
d_math_sin(
    float _x
)
{
    return d_math_f_sin(_x);
}

D_MATH_FN float
d_math_cos_c(
    float _x
)
{
    return d_math_f_cos_c(_x);
}

D_MATH_FN_RT float
d_math_cos(
    float _x
)
{
    return d_math_f_cos(_x);
}

D_MATH_FN double
d_math_sqrt_c(
    double _x
)
{
    return d_math_d_sqrt_c(_x);
}

D_MATH_FN_RT double
d_math_sqrt(
    double _x
)
{
    return d_math_d_sqrt(_x);
}

D_MATH_FN double
d_math_acos_c(
    double _x
)
{
    return d_math_d_acos_c(_x);
}

D_MATH_FN_RT double
d_math_acos(
    double _x
)
{
    return d_math_d_acos(_x);
}

D_MATH_FN double
d_math_sin_c(
    double _x
)
{
    return d_math_d_sin_c(_x);
}

D_MATH_FN_RT double
d_math_sin(
    double _x
)
{
    return d_math_d_sin(_x);
}

D_MATH_FN double
d_math_cos_c(
    double _x
)
{
    return d_math_d_cos_c(_x);
}

D_MATH_FN_RT double
d_math_cos(
    double _x
)
{
    return d_math_d_cos(_x);
}

D_MATH_FN long double
d_math_sqrt_c(
    long double _x
)
{
    return d_math_ld_sqrt_c(_x);
}

D_MATH_FN_RT long double
d_math_sqrt(
    long double _x
)
{
    return d_math_ld_sqrt(_x);
}

D_MATH_FN long double
d_math_acos_c(
    long double _x
)
{
    return d_math_ld_acos_c(_x);
}

D_MATH_FN_RT long double
d_math_acos(
    long double _x
)
{
    return d_math_ld_acos(_x);
}

D_MATH_FN long double
d_math_sin_c(
    long double _x
)
{
    return d_math_ld_sin_c(_x);
}

D_MATH_FN_RT long double
d_math_sin(
    long double _x
)
{
    return d_math_ld_sin(_x);
}

D_MATH_FN long double
d_math_cos_c(
    long double _x
)
{
    return d_math_ld_cos_c(_x);
}

D_MATH_FN_RT long double
d_math_cos(
    long double _x
)
{
    return d_math_ld_cos(_x);
}

#endif  // __cplusplus

#endif  // DJINTERP_C_MATH_ELEMENTARY_H
