/*******************************************************************************
* djinterp [c]                                                     float_order.h
*
* The order of a floating-point type's values: successor, predecessor,
* ordinal distance and advance, for float, double and long double.
*   GENERATED by tools/gen_c_math_float.py from one text for the three
* families: edit the generator, not this file.
*
*   Every function is pure arithmetic -- no bit pattern is read, no C
* library function called -- so the same text is constexpr from C++14,
* where a face needs a successor in a template argument. The values are
* taken as numbers, so +0 and -0 are one value; NaN is no value's
* neighbour. Subnormals are assumed (IEEE 754): a build that flushes them
* to zero sees gaps the order does not know about.
*
*
* path:      /inc/djinterp/c/math/float_order.h
* link(s):   TBA
* author(s): Samuel 'teer' Neal-Blim                         created: 2026.10.04
*                                                            revised: 2026.10.04
*******************************************************************************/

/*
TABLE OF CONTENTS
=================
1.  THE FLOAT FAMILY (_f)
    ---------------------
    1.  Internal helpers
    2.  Successor and predecessor
    3.  Ordinal distance and advance
2.  THE DOUBLE FAMILY (_d)
    ----------------------
    1.  Internal helpers
    2.  Successor and predecessor
    3.  Ordinal distance and advance
3.  THE LONG DOUBLE FAMILY (_ld)
    ----------------------------
    1.  Internal helpers
    2.  Successor and predecessor
    3.  Ordinal distance and advance
4.  ONE NAME FOR EVERY FAMILY (C++)
    -------------------------------
*/

#ifndef DJINTERP_C_MATH_FLOAT_ORDER_H
#define DJINTERP_C_MATH_FLOAT_ORDER_H 1

// std
#include <float.h>           // FLT_MANT_DIG ... LDBL_EPSILON
#include <math.h>            // HUGE_VAL
// djinterp
#include "./math_common.h"   // D_MATH_FN, d_math_umax, D_MATH_UMAX_MAX

//==============================================================================
// 1.  THE FLOAT FAMILY (_f)
//==============================================================================


// 1.1    Internal helpers
//------------------------------------------------------------------------------

// d_internal_math_f_binade
//   struct: a positive normal value's binade: the exponent E and 2^E, so that
// 2^E <= x < 2^(E + 1).
struct d_internal_math_f_binade
{
    int exponent;  // E
    float power;     // 2^E, exact
};

// d_internal_math_f_pow2
//   2^_exponent, exact, for the exponent of a normal float (from
// FLT_MIN_EXP - 1 to FLT_MAX_EXP - 1), built from the squares 2^(2^k).
D_MATH_FN float
d_internal_math_f_pow2(
    int _exponent
)
{
    float squares[16] = { 0 };
    float result      = (float)1;
    int count       = 1;
    int k           = 0;
    int left        = (_exponent < 0) ? -_exponent : _exponent;

    squares[0] = (float)2;

    // 2^(2^k) for every k with 2^k at most the largest exponent
    while ( (count < 16) &&
            ((1 << count) <= (FLT_MAX_EXP - 1)) )
    {
        squares[count] = squares[count - 1] * squares[count - 1];
        ++count;
    }

    // the exponent's bits, largest first: the result moves monotonically
    // toward 2^_exponent, so no partial product leaves the normal range
    for (k = count - 1; k >= 0; --k)
    {
        if (left >= (1 << k))
        {
            result = (_exponent < 0) ? (result / squares[k])
                                     : (result * squares[k]);
            left  -= (1 << k);
        }
    }

    return result;
}

// d_internal_math_f_binade_of
//   the binade of _x, which must be normal and positive: FLT_MIN <= _x <=
// FLT_MAX. A binary search over the squares 2^(2^k); no candidate it forms
// leaves the normal range, so every step is exact and, from C++14, a
// constant expression.
D_MATH_FN struct d_internal_math_f_binade
d_internal_math_f_binade_of(
    float _x
)
{
    struct d_internal_math_f_binade result = { 0, (float)1 };
    float squares[16] = { 0 };
    int count       = 1;
    int k           = 0;

    squares[0] = (float)2;

    // 2^(2^k) for every k with 2^k at most the largest exponent
    while ( (count < 16) &&
            ((1 << count) <= (FLT_MAX_EXP - 1)) )
    {
        squares[count] = squares[count - 1] * squares[count - 1];
        ++count;
    }

    // at or above 1: climb while the next power stays at or below _x
    if (_x >= (float)1)
    {
        for (k = count - 1; k >= 0; --k)
        {
            if ( ((result.exponent + (1 << k)) <= (FLT_MAX_EXP - 1)) &&
                 ((result.power * squares[k]) <= _x) )
            {
                result.power    *= squares[k];
                result.exponent += (1 << k);
            }
        }

        return result;
    }

    // below 1: descend while the power stays above _x, then step once more
    for (k = count - 1; k >= 0; --k)
    {
        if ( ((result.exponent - (1 << k)) >= (FLT_MIN_EXP - 1)) &&
             ((result.power / squares[k]) > _x) )
        {
            result.power    /= squares[k];
            result.exponent -= (1 << k);
        }
    }

    result.power    /= (float)2;
    result.exponent -= 1;

    return result;
}

// d_internal_math_f_true_min
//   the least positive float: the subnormal spacing,
// FLT_MIN * FLT_EPSILON.
D_MATH_FN float
d_internal_math_f_true_min(void)
{
    return (FLT_MIN * FLT_EPSILON);
}

// d_internal_math_f_place
//   a non-negative value's place in the order: binade B and offset O within
// it, so that its ordinal is B * 2^(P-1) + O. B is 0 for zero and the
// subnormals; O is an integer below 2^(P-1), held exactly in float; +inf is the
// first place past the largest binade.
struct d_internal_math_f_place
{
    int binade;  // B
    float offset;  // O
};

D_MATH_FN struct d_internal_math_f_place
d_internal_math_f_place_of(
    float _x
)
{
    struct d_internal_math_f_place result = { 0, (float)0 };

    // +inf is the order's end: one step past the largest finite value, the
    // first place of the binade after the last
    if (_x > FLT_MAX)
    {
        result.binade = (FLT_MAX_EXP - (FLT_MIN_EXP - 1)) + 1;

        return result;
    }

    // zero and the subnormals: one binade, in steps of the least value
    if (_x < FLT_MIN)
    {
        result.offset = _x / d_internal_math_f_true_min();

        return result;
    }

    {
        const struct d_internal_math_f_binade b =
            d_internal_math_f_binade_of(_x);

        result.binade = b.exponent - (FLT_MIN_EXP - 1) + 1;
        result.offset = (_x - b.power) / (b.power * FLT_EPSILON);
    }

    return result;
}

// d_internal_math_f_value_of
//   the inverse of place_of: the value at binade _binade, offset _offset.
D_MATH_FN float
d_internal_math_f_value_of(
    int _binade,
    float _offset
)
{
    // the subnormal binade
    if (_binade == 0)
    {
        return (_offset * d_internal_math_f_true_min());
    }

    {
        const float power =
            d_internal_math_f_pow2(_binade - 1 + (FLT_MIN_EXP - 1));

        return (power + (_offset * (power * FLT_EPSILON)));
    }
}

// d_internal_math_f_umax_bits
//   the bits of d_math_umax, assuming none is padding.
D_MATH_FN int
d_internal_math_f_umax_bits(void)
{
    return (int)(sizeof(d_math_umax) * 8u);
}

// d_internal_math_f_full
//   2^(P-1), the count of one binade, as d_math_umax: asked for only where it
// fits, and the shift clamped so the expression is well-formed where it does
// not (a 32-bit d_math_umax and a double's 52).
D_MATH_FN d_math_umax
d_internal_math_f_full(void)
{
    return ((d_math_umax)1)
               << ( ((FLT_MANT_DIG - 1) < (int)(sizeof(d_math_umax) * 8u))
                        ? (FLT_MANT_DIG - 1)
                        : 0 );
}

// d_internal_math_f_steps_up
//   how many values lie in [_from, _to), for finite 0 <= _from <= _to: from
// their places, so the count is exact wherever it fits d_math_umax, however
// far from zero the two lie; it saturates at D_MATH_UMAX_MAX.
D_MATH_FN d_math_umax
d_internal_math_f_steps_up(
    float _from,
    float _to
)
{
    const struct d_internal_math_f_place low  =
        d_internal_math_f_place_of(_from);
    const struct d_internal_math_f_place high =
        d_internal_math_f_place_of(_to);
    const int binades = high.binade - low.binade;

    // a binade holds more than d_math_umax counts: only within one is there
    // a count to give
    if ((FLT_MANT_DIG - 1) >= d_internal_math_f_umax_bits())
    {
        const float within = high.offset - low.offset;

        if ( (binades > 0) ||
             (!(within < (float)D_MATH_UMAX_MAX)) )
        {
            return D_MATH_UMAX_MAX;
        }

        return (d_math_umax)within;
    }

    {
        const d_math_umax full        = d_internal_math_f_full();
        const d_math_umax from_offset = (d_math_umax)low.offset;
        const d_math_umax to_offset   = (d_math_umax)high.offset;
        const d_math_umax whole       = (d_math_umax)binades;

        // whole * full + to_offset - from_offset, saturating
        if (whole > ((D_MATH_UMAX_MAX - to_offset) / full))
        {
            return D_MATH_UMAX_MAX;
        }

        return (((whole * full) + to_offset) - from_offset);
    }
}

// d_internal_math_f_climb
//   the value _steps above a non-negative finite _from; +inf past the
// largest finite value.
D_MATH_FN float
d_internal_math_f_climb(
    float         _from,
    d_math_umax _steps
)
{
    const struct d_internal_math_f_place p =
        d_internal_math_f_place_of(_from);
    // the largest binade
    const int top    = (FLT_MAX_EXP - (FLT_MIN_EXP - 1));
    int       binade = p.binade;
    float       offset = p.offset;

    // a binade holds more than d_math_umax: the steps cross at most one edge
    if ((FLT_MANT_DIG - 1) >= d_internal_math_f_umax_bits())
    {
        const float full = d_internal_math_f_pow2(FLT_MANT_DIG - 1);

        offset += (float)_steps;

        if (!(offset < full))
        {
            offset -= full;
            ++binade;
        }
    }
    else
    {
        const d_math_umax full  = d_internal_math_f_full();
        const d_math_umax whole = _steps / full;
        d_math_umax       rest  = ((d_math_umax)offset) + (_steps % full);

        // whole binades first, then what is left within one
        if (whole > (d_math_umax)top)
        {
            return (float)HUGE_VAL;
        }

        binade += (int)whole;

        if (rest >= full)
        {
            rest -= full;
            ++binade;
        }

        offset = (float)rest;
    }

    // past the largest binade lies infinity
    if (binade > top)
    {
        return (float)HUGE_VAL;
    }

    return d_internal_math_f_value_of(binade, offset);
}

// d_internal_math_f_descend
//   the value _steps below a positive finite _from; _steps must be fewer
// than the values in [0, _from).
D_MATH_FN float
d_internal_math_f_descend(
    float         _from,
    d_math_umax _steps
)
{
    const struct d_internal_math_f_place p =
        d_internal_math_f_place_of(_from);
    int binade = p.binade;
    float offset = p.offset;

    // a binade holds more than d_math_umax: at most one edge is crossed
    if ((FLT_MANT_DIG - 1) >= d_internal_math_f_umax_bits())
    {
        const float back = (float)_steps;

        if (back <= offset)
        {
            offset -= back;
        }
        else
        {
            const float full = d_internal_math_f_pow2(FLT_MANT_DIG - 1);

            offset = (offset + full) - back;
            --binade;
        }
    }
    else
    {
        const d_math_umax full  = d_internal_math_f_full();
        const d_math_umax rest  = _steps % full;
        d_math_umax       place = (d_math_umax)offset;

        // whole binades first, then what is left within one
        binade -= (int)(_steps / full);

        if (rest > place)
        {
            place = (place + full) - rest;
            --binade;
        }
        else
        {
            place -= rest;
        }

        offset = (float)place;
    }

    return d_internal_math_f_value_of(binade, offset);
}

// 1.2    Successor and predecessor
//------------------------------------------------------------------------------
// next_up is the least value above _x, next_down the greatest below:
// nextafter toward +inf and toward -inf, in pure arithmetic. +0 and -0 are
// one value, so next_up(-least) is 0. NaN stays NaN; next_up(+inf) is +inf
// and next_up(-inf) the most negative finite value.

D_MATH_FN float
d_math_f_next_up(
    float _x
)
{
    // NaN and +inf are their own successors
    if ( (_x != _x) ||
         (_x > FLT_MAX) )
    {
        return _x;
    }

    // -inf rises to the most negative finite value
    if (_x < -FLT_MAX)
    {
        return -FLT_MAX;
    }

    // the largest finite value rises to +inf
    if (_x == FLT_MAX)
    {
        return (float)HUGE_VAL;
    }

    // zero and the subnormals are evenly spaced by the least value
    if ( (_x < FLT_MIN) &&
         (_x > -FLT_MIN) )
    {
        return (_x + d_internal_math_f_true_min());
    }

    // a positive normal value: one spacing of its binade up
    if (_x > (float)0)
    {
        const struct d_internal_math_f_binade b =
            d_internal_math_f_binade_of(_x);

        return (_x + (b.power * FLT_EPSILON));
    }

    {
        // a negative normal value: toward zero by the spacing below its
        // magnitude, which below a power of two is half its own -- except
        // below the least normal value, where it is the subnormal spacing
        const float magnitude = -_x;
        const struct d_internal_math_f_binade b =
            d_internal_math_f_binade_of(magnitude);
        const float spacing =
            ( (magnitude == b.power) && (magnitude > FLT_MIN) )
                ? ((b.power * FLT_EPSILON) / (float)2)
                : (b.power * FLT_EPSILON);

        return -(magnitude - spacing);
    }
}

D_MATH_FN float
d_math_f_next_down(
    float _x
)
{
    return -d_math_f_next_up(-_x);
}

// 1.3    Ordinal distance and advance
//------------------------------------------------------------------------------
// steps is how many values lie in [_from, _to) -- for adjacent values 1 --
// for _from <= _to, saturating at D_MATH_UMAX_MAX; advance is the value
// _steps above _from, +inf past the largest finite value. The infinities are
// the order's ends, one step past the largest finite values; NaN is in no
// order. So advance(a, steps(a, b)) == b wherever steps(a, b) does not
// saturate.

D_MATH_FN d_math_umax
d_math_f_steps(
    float _from,
    float _to
)
{
    // both at or above zero
    if (_from >= (float)0)
    {
        return d_internal_math_f_steps_up(_from, _to);
    }

    // both at or below zero: the mirror image
    if (_to <= (float)0)
    {
        return d_internal_math_f_steps_up(-_to, -_from);
    }

    {
        // across zero: up to zero, then on from it, saturating
        const d_math_umax below =
            d_internal_math_f_steps_up((float)0, -_from);
        const d_math_umax above =
            d_internal_math_f_steps_up((float)0, _to);

        return (above > (D_MATH_UMAX_MAX - below)) ? D_MATH_UMAX_MAX
                                                   : (below + above);
    }
}

D_MATH_FN float
d_math_f_advance(
    float         _from,
    d_math_umax _steps
)
{
    // from zero or above: climb
    if (_from >= (float)0)
    {
        return d_internal_math_f_climb(_from, _steps);
    }

    {
        // from below zero: as many steps as reach zero, at most, stay below
        // it -- a count that saturates is more than _steps can be
        const d_math_umax to_zero =
            d_internal_math_f_steps_up((float)0, -_from);

        if ( (_steps < to_zero) ||
             (to_zero == D_MATH_UMAX_MAX) )
        {
            return -d_internal_math_f_descend(-_from, _steps);
        }

        return d_internal_math_f_climb((float)0, _steps - to_zero);
    }
}

//==============================================================================
// 2.  THE DOUBLE FAMILY (_d)
//==============================================================================


// 2.1    Internal helpers
//------------------------------------------------------------------------------

// d_internal_math_d_binade
//   struct: a positive normal value's binade: the exponent E and 2^E, so that
// 2^E <= x < 2^(E + 1).
struct d_internal_math_d_binade
{
    int exponent;  // E
    double power;     // 2^E, exact
};

// d_internal_math_d_pow2
//   2^_exponent, exact, for the exponent of a normal double (from
// DBL_MIN_EXP - 1 to DBL_MAX_EXP - 1), built from the squares 2^(2^k).
D_MATH_FN double
d_internal_math_d_pow2(
    int _exponent
)
{
    double squares[16] = { 0 };
    double result      = (double)1;
    int count       = 1;
    int k           = 0;
    int left        = (_exponent < 0) ? -_exponent : _exponent;

    squares[0] = (double)2;

    // 2^(2^k) for every k with 2^k at most the largest exponent
    while ( (count < 16) &&
            ((1 << count) <= (DBL_MAX_EXP - 1)) )
    {
        squares[count] = squares[count - 1] * squares[count - 1];
        ++count;
    }

    // the exponent's bits, largest first: the result moves monotonically
    // toward 2^_exponent, so no partial product leaves the normal range
    for (k = count - 1; k >= 0; --k)
    {
        if (left >= (1 << k))
        {
            result = (_exponent < 0) ? (result / squares[k])
                                     : (result * squares[k]);
            left  -= (1 << k);
        }
    }

    return result;
}

// d_internal_math_d_binade_of
//   the binade of _x, which must be normal and positive: DBL_MIN <= _x <=
// DBL_MAX. A binary search over the squares 2^(2^k); no candidate it forms
// leaves the normal range, so every step is exact and, from C++14, a
// constant expression.
D_MATH_FN struct d_internal_math_d_binade
d_internal_math_d_binade_of(
    double _x
)
{
    struct d_internal_math_d_binade result = { 0, (double)1 };
    double squares[16] = { 0 };
    int count       = 1;
    int k           = 0;

    squares[0] = (double)2;

    // 2^(2^k) for every k with 2^k at most the largest exponent
    while ( (count < 16) &&
            ((1 << count) <= (DBL_MAX_EXP - 1)) )
    {
        squares[count] = squares[count - 1] * squares[count - 1];
        ++count;
    }

    // at or above 1: climb while the next power stays at or below _x
    if (_x >= (double)1)
    {
        for (k = count - 1; k >= 0; --k)
        {
            if ( ((result.exponent + (1 << k)) <= (DBL_MAX_EXP - 1)) &&
                 ((result.power * squares[k]) <= _x) )
            {
                result.power    *= squares[k];
                result.exponent += (1 << k);
            }
        }

        return result;
    }

    // below 1: descend while the power stays above _x, then step once more
    for (k = count - 1; k >= 0; --k)
    {
        if ( ((result.exponent - (1 << k)) >= (DBL_MIN_EXP - 1)) &&
             ((result.power / squares[k]) > _x) )
        {
            result.power    /= squares[k];
            result.exponent -= (1 << k);
        }
    }

    result.power    /= (double)2;
    result.exponent -= 1;

    return result;
}

// d_internal_math_d_true_min
//   the least positive double: the subnormal spacing,
// DBL_MIN * DBL_EPSILON.
D_MATH_FN double
d_internal_math_d_true_min(void)
{
    return (DBL_MIN * DBL_EPSILON);
}

// d_internal_math_d_place
//   a non-negative value's place in the order: binade B and offset O within
// it, so that its ordinal is B * 2^(P-1) + O. B is 0 for zero and the
// subnormals; O is an integer below 2^(P-1), held exactly in double; +inf is the
// first place past the largest binade.
struct d_internal_math_d_place
{
    int binade;  // B
    double offset;  // O
};

D_MATH_FN struct d_internal_math_d_place
d_internal_math_d_place_of(
    double _x
)
{
    struct d_internal_math_d_place result = { 0, (double)0 };

    // +inf is the order's end: one step past the largest finite value, the
    // first place of the binade after the last
    if (_x > DBL_MAX)
    {
        result.binade = (DBL_MAX_EXP - (DBL_MIN_EXP - 1)) + 1;

        return result;
    }

    // zero and the subnormals: one binade, in steps of the least value
    if (_x < DBL_MIN)
    {
        result.offset = _x / d_internal_math_d_true_min();

        return result;
    }

    {
        const struct d_internal_math_d_binade b =
            d_internal_math_d_binade_of(_x);

        result.binade = b.exponent - (DBL_MIN_EXP - 1) + 1;
        result.offset = (_x - b.power) / (b.power * DBL_EPSILON);
    }

    return result;
}

// d_internal_math_d_value_of
//   the inverse of place_of: the value at binade _binade, offset _offset.
D_MATH_FN double
d_internal_math_d_value_of(
    int _binade,
    double _offset
)
{
    // the subnormal binade
    if (_binade == 0)
    {
        return (_offset * d_internal_math_d_true_min());
    }

    {
        const double power =
            d_internal_math_d_pow2(_binade - 1 + (DBL_MIN_EXP - 1));

        return (power + (_offset * (power * DBL_EPSILON)));
    }
}

// d_internal_math_d_umax_bits
//   the bits of d_math_umax, assuming none is padding.
D_MATH_FN int
d_internal_math_d_umax_bits(void)
{
    return (int)(sizeof(d_math_umax) * 8u);
}

// d_internal_math_d_full
//   2^(P-1), the count of one binade, as d_math_umax: asked for only where it
// fits, and the shift clamped so the expression is well-formed where it does
// not (a 32-bit d_math_umax and a double's 52).
D_MATH_FN d_math_umax
d_internal_math_d_full(void)
{
    return ((d_math_umax)1)
               << ( ((DBL_MANT_DIG - 1) < (int)(sizeof(d_math_umax) * 8u))
                        ? (DBL_MANT_DIG - 1)
                        : 0 );
}

// d_internal_math_d_steps_up
//   how many values lie in [_from, _to), for finite 0 <= _from <= _to: from
// their places, so the count is exact wherever it fits d_math_umax, however
// far from zero the two lie; it saturates at D_MATH_UMAX_MAX.
D_MATH_FN d_math_umax
d_internal_math_d_steps_up(
    double _from,
    double _to
)
{
    const struct d_internal_math_d_place low  =
        d_internal_math_d_place_of(_from);
    const struct d_internal_math_d_place high =
        d_internal_math_d_place_of(_to);
    const int binades = high.binade - low.binade;

    // a binade holds more than d_math_umax counts: only within one is there
    // a count to give
    if ((DBL_MANT_DIG - 1) >= d_internal_math_d_umax_bits())
    {
        const double within = high.offset - low.offset;

        if ( (binades > 0) ||
             (!(within < (double)D_MATH_UMAX_MAX)) )
        {
            return D_MATH_UMAX_MAX;
        }

        return (d_math_umax)within;
    }

    {
        const d_math_umax full        = d_internal_math_d_full();
        const d_math_umax from_offset = (d_math_umax)low.offset;
        const d_math_umax to_offset   = (d_math_umax)high.offset;
        const d_math_umax whole       = (d_math_umax)binades;

        // whole * full + to_offset - from_offset, saturating
        if (whole > ((D_MATH_UMAX_MAX - to_offset) / full))
        {
            return D_MATH_UMAX_MAX;
        }

        return (((whole * full) + to_offset) - from_offset);
    }
}

// d_internal_math_d_climb
//   the value _steps above a non-negative finite _from; +inf past the
// largest finite value.
D_MATH_FN double
d_internal_math_d_climb(
    double         _from,
    d_math_umax _steps
)
{
    const struct d_internal_math_d_place p =
        d_internal_math_d_place_of(_from);
    // the largest binade
    const int top    = (DBL_MAX_EXP - (DBL_MIN_EXP - 1));
    int       binade = p.binade;
    double       offset = p.offset;

    // a binade holds more than d_math_umax: the steps cross at most one edge
    if ((DBL_MANT_DIG - 1) >= d_internal_math_d_umax_bits())
    {
        const double full = d_internal_math_d_pow2(DBL_MANT_DIG - 1);

        offset += (double)_steps;

        if (!(offset < full))
        {
            offset -= full;
            ++binade;
        }
    }
    else
    {
        const d_math_umax full  = d_internal_math_d_full();
        const d_math_umax whole = _steps / full;
        d_math_umax       rest  = ((d_math_umax)offset) + (_steps % full);

        // whole binades first, then what is left within one
        if (whole > (d_math_umax)top)
        {
            return (double)HUGE_VAL;
        }

        binade += (int)whole;

        if (rest >= full)
        {
            rest -= full;
            ++binade;
        }

        offset = (double)rest;
    }

    // past the largest binade lies infinity
    if (binade > top)
    {
        return (double)HUGE_VAL;
    }

    return d_internal_math_d_value_of(binade, offset);
}

// d_internal_math_d_descend
//   the value _steps below a positive finite _from; _steps must be fewer
// than the values in [0, _from).
D_MATH_FN double
d_internal_math_d_descend(
    double         _from,
    d_math_umax _steps
)
{
    const struct d_internal_math_d_place p =
        d_internal_math_d_place_of(_from);
    int binade = p.binade;
    double offset = p.offset;

    // a binade holds more than d_math_umax: at most one edge is crossed
    if ((DBL_MANT_DIG - 1) >= d_internal_math_d_umax_bits())
    {
        const double back = (double)_steps;

        if (back <= offset)
        {
            offset -= back;
        }
        else
        {
            const double full = d_internal_math_d_pow2(DBL_MANT_DIG - 1);

            offset = (offset + full) - back;
            --binade;
        }
    }
    else
    {
        const d_math_umax full  = d_internal_math_d_full();
        const d_math_umax rest  = _steps % full;
        d_math_umax       place = (d_math_umax)offset;

        // whole binades first, then what is left within one
        binade -= (int)(_steps / full);

        if (rest > place)
        {
            place = (place + full) - rest;
            --binade;
        }
        else
        {
            place -= rest;
        }

        offset = (double)place;
    }

    return d_internal_math_d_value_of(binade, offset);
}

// 2.2    Successor and predecessor
//------------------------------------------------------------------------------
// next_up is the least value above _x, next_down the greatest below:
// nextafter toward +inf and toward -inf, in pure arithmetic. +0 and -0 are
// one value, so next_up(-least) is 0. NaN stays NaN; next_up(+inf) is +inf
// and next_up(-inf) the most negative finite value.

D_MATH_FN double
d_math_d_next_up(
    double _x
)
{
    // NaN and +inf are their own successors
    if ( (_x != _x) ||
         (_x > DBL_MAX) )
    {
        return _x;
    }

    // -inf rises to the most negative finite value
    if (_x < -DBL_MAX)
    {
        return -DBL_MAX;
    }

    // the largest finite value rises to +inf
    if (_x == DBL_MAX)
    {
        return (double)HUGE_VAL;
    }

    // zero and the subnormals are evenly spaced by the least value
    if ( (_x < DBL_MIN) &&
         (_x > -DBL_MIN) )
    {
        return (_x + d_internal_math_d_true_min());
    }

    // a positive normal value: one spacing of its binade up
    if (_x > (double)0)
    {
        const struct d_internal_math_d_binade b =
            d_internal_math_d_binade_of(_x);

        return (_x + (b.power * DBL_EPSILON));
    }

    {
        // a negative normal value: toward zero by the spacing below its
        // magnitude, which below a power of two is half its own -- except
        // below the least normal value, where it is the subnormal spacing
        const double magnitude = -_x;
        const struct d_internal_math_d_binade b =
            d_internal_math_d_binade_of(magnitude);
        const double spacing =
            ( (magnitude == b.power) && (magnitude > DBL_MIN) )
                ? ((b.power * DBL_EPSILON) / (double)2)
                : (b.power * DBL_EPSILON);

        return -(magnitude - spacing);
    }
}

D_MATH_FN double
d_math_d_next_down(
    double _x
)
{
    return -d_math_d_next_up(-_x);
}

// 2.3    Ordinal distance and advance
//------------------------------------------------------------------------------
// steps is how many values lie in [_from, _to) -- for adjacent values 1 --
// for _from <= _to, saturating at D_MATH_UMAX_MAX; advance is the value
// _steps above _from, +inf past the largest finite value. The infinities are
// the order's ends, one step past the largest finite values; NaN is in no
// order. So advance(a, steps(a, b)) == b wherever steps(a, b) does not
// saturate.

D_MATH_FN d_math_umax
d_math_d_steps(
    double _from,
    double _to
)
{
    // both at or above zero
    if (_from >= (double)0)
    {
        return d_internal_math_d_steps_up(_from, _to);
    }

    // both at or below zero: the mirror image
    if (_to <= (double)0)
    {
        return d_internal_math_d_steps_up(-_to, -_from);
    }

    {
        // across zero: up to zero, then on from it, saturating
        const d_math_umax below =
            d_internal_math_d_steps_up((double)0, -_from);
        const d_math_umax above =
            d_internal_math_d_steps_up((double)0, _to);

        return (above > (D_MATH_UMAX_MAX - below)) ? D_MATH_UMAX_MAX
                                                   : (below + above);
    }
}

D_MATH_FN double
d_math_d_advance(
    double         _from,
    d_math_umax _steps
)
{
    // from zero or above: climb
    if (_from >= (double)0)
    {
        return d_internal_math_d_climb(_from, _steps);
    }

    {
        // from below zero: as many steps as reach zero, at most, stay below
        // it -- a count that saturates is more than _steps can be
        const d_math_umax to_zero =
            d_internal_math_d_steps_up((double)0, -_from);

        if ( (_steps < to_zero) ||
             (to_zero == D_MATH_UMAX_MAX) )
        {
            return -d_internal_math_d_descend(-_from, _steps);
        }

        return d_internal_math_d_climb((double)0, _steps - to_zero);
    }
}

//==============================================================================
// 3.  THE LONG DOUBLE FAMILY (_ld)
//==============================================================================


// 3.1    Internal helpers
//------------------------------------------------------------------------------

// d_internal_math_ld_binade
//   struct: a positive normal value's binade: the exponent E and 2^E, so that
// 2^E <= x < 2^(E + 1).
struct d_internal_math_ld_binade
{
    int exponent;  // E
    long double power;     // 2^E, exact
};

// d_internal_math_ld_pow2
//   2^_exponent, exact, for the exponent of a normal long double (from
// LDBL_MIN_EXP - 1 to LDBL_MAX_EXP - 1), built from the squares 2^(2^k).
D_MATH_FN long double
d_internal_math_ld_pow2(
    int _exponent
)
{
    long double squares[16] = { 0 };
    long double result      = (long double)1;
    int count       = 1;
    int k           = 0;
    int left        = (_exponent < 0) ? -_exponent : _exponent;

    squares[0] = (long double)2;

    // 2^(2^k) for every k with 2^k at most the largest exponent
    while ( (count < 16) &&
            ((1 << count) <= (LDBL_MAX_EXP - 1)) )
    {
        squares[count] = squares[count - 1] * squares[count - 1];
        ++count;
    }

    // the exponent's bits, largest first: the result moves monotonically
    // toward 2^_exponent, so no partial product leaves the normal range
    for (k = count - 1; k >= 0; --k)
    {
        if (left >= (1 << k))
        {
            result = (_exponent < 0) ? (result / squares[k])
                                     : (result * squares[k]);
            left  -= (1 << k);
        }
    }

    return result;
}

// d_internal_math_ld_binade_of
//   the binade of _x, which must be normal and positive: LDBL_MIN <= _x <=
// LDBL_MAX. A binary search over the squares 2^(2^k); no candidate it forms
// leaves the normal range, so every step is exact and, from C++14, a
// constant expression.
D_MATH_FN struct d_internal_math_ld_binade
d_internal_math_ld_binade_of(
    long double _x
)
{
    struct d_internal_math_ld_binade result = { 0, (long double)1 };
    long double squares[16] = { 0 };
    int count       = 1;
    int k           = 0;

    squares[0] = (long double)2;

    // 2^(2^k) for every k with 2^k at most the largest exponent
    while ( (count < 16) &&
            ((1 << count) <= (LDBL_MAX_EXP - 1)) )
    {
        squares[count] = squares[count - 1] * squares[count - 1];
        ++count;
    }

    // at or above 1: climb while the next power stays at or below _x
    if (_x >= (long double)1)
    {
        for (k = count - 1; k >= 0; --k)
        {
            if ( ((result.exponent + (1 << k)) <= (LDBL_MAX_EXP - 1)) &&
                 ((result.power * squares[k]) <= _x) )
            {
                result.power    *= squares[k];
                result.exponent += (1 << k);
            }
        }

        return result;
    }

    // below 1: descend while the power stays above _x, then step once more
    for (k = count - 1; k >= 0; --k)
    {
        if ( ((result.exponent - (1 << k)) >= (LDBL_MIN_EXP - 1)) &&
             ((result.power / squares[k]) > _x) )
        {
            result.power    /= squares[k];
            result.exponent -= (1 << k);
        }
    }

    result.power    /= (long double)2;
    result.exponent -= 1;

    return result;
}

// d_internal_math_ld_true_min
//   the least positive long double: the subnormal spacing,
// LDBL_MIN * LDBL_EPSILON.
D_MATH_FN long double
d_internal_math_ld_true_min(void)
{
    return (LDBL_MIN * LDBL_EPSILON);
}

// d_internal_math_ld_place
//   a non-negative value's place in the order: binade B and offset O within
// it, so that its ordinal is B * 2^(P-1) + O. B is 0 for zero and the
// subnormals; O is an integer below 2^(P-1), held exactly in long double; +inf is the
// first place past the largest binade.
struct d_internal_math_ld_place
{
    int binade;  // B
    long double offset;  // O
};

D_MATH_FN struct d_internal_math_ld_place
d_internal_math_ld_place_of(
    long double _x
)
{
    struct d_internal_math_ld_place result = { 0, (long double)0 };

    // +inf is the order's end: one step past the largest finite value, the
    // first place of the binade after the last
    if (_x > LDBL_MAX)
    {
        result.binade = (LDBL_MAX_EXP - (LDBL_MIN_EXP - 1)) + 1;

        return result;
    }

    // zero and the subnormals: one binade, in steps of the least value
    if (_x < LDBL_MIN)
    {
        result.offset = _x / d_internal_math_ld_true_min();

        return result;
    }

    {
        const struct d_internal_math_ld_binade b =
            d_internal_math_ld_binade_of(_x);

        result.binade = b.exponent - (LDBL_MIN_EXP - 1) + 1;
        result.offset = (_x - b.power) / (b.power * LDBL_EPSILON);
    }

    return result;
}

// d_internal_math_ld_value_of
//   the inverse of place_of: the value at binade _binade, offset _offset.
D_MATH_FN long double
d_internal_math_ld_value_of(
    int _binade,
    long double _offset
)
{
    // the subnormal binade
    if (_binade == 0)
    {
        return (_offset * d_internal_math_ld_true_min());
    }

    {
        const long double power =
            d_internal_math_ld_pow2(_binade - 1 + (LDBL_MIN_EXP - 1));

        return (power + (_offset * (power * LDBL_EPSILON)));
    }
}

// d_internal_math_ld_umax_bits
//   the bits of d_math_umax, assuming none is padding.
D_MATH_FN int
d_internal_math_ld_umax_bits(void)
{
    return (int)(sizeof(d_math_umax) * 8u);
}

// d_internal_math_ld_full
//   2^(P-1), the count of one binade, as d_math_umax: asked for only where it
// fits, and the shift clamped so the expression is well-formed where it does
// not (a 32-bit d_math_umax and a double's 52).
D_MATH_FN d_math_umax
d_internal_math_ld_full(void)
{
    return ((d_math_umax)1)
               << ( ((LDBL_MANT_DIG - 1) < (int)(sizeof(d_math_umax) * 8u))
                        ? (LDBL_MANT_DIG - 1)
                        : 0 );
}

// d_internal_math_ld_steps_up
//   how many values lie in [_from, _to), for finite 0 <= _from <= _to: from
// their places, so the count is exact wherever it fits d_math_umax, however
// far from zero the two lie; it saturates at D_MATH_UMAX_MAX.
D_MATH_FN d_math_umax
d_internal_math_ld_steps_up(
    long double _from,
    long double _to
)
{
    const struct d_internal_math_ld_place low  =
        d_internal_math_ld_place_of(_from);
    const struct d_internal_math_ld_place high =
        d_internal_math_ld_place_of(_to);
    const int binades = high.binade - low.binade;

    // a binade holds more than d_math_umax counts: only within one is there
    // a count to give
    if ((LDBL_MANT_DIG - 1) >= d_internal_math_ld_umax_bits())
    {
        const long double within = high.offset - low.offset;

        if ( (binades > 0) ||
             (!(within < (long double)D_MATH_UMAX_MAX)) )
        {
            return D_MATH_UMAX_MAX;
        }

        return (d_math_umax)within;
    }

    {
        const d_math_umax full        = d_internal_math_ld_full();
        const d_math_umax from_offset = (d_math_umax)low.offset;
        const d_math_umax to_offset   = (d_math_umax)high.offset;
        const d_math_umax whole       = (d_math_umax)binades;

        // whole * full + to_offset - from_offset, saturating
        if (whole > ((D_MATH_UMAX_MAX - to_offset) / full))
        {
            return D_MATH_UMAX_MAX;
        }

        return (((whole * full) + to_offset) - from_offset);
    }
}

// d_internal_math_ld_climb
//   the value _steps above a non-negative finite _from; +inf past the
// largest finite value.
D_MATH_FN long double
d_internal_math_ld_climb(
    long double         _from,
    d_math_umax _steps
)
{
    const struct d_internal_math_ld_place p =
        d_internal_math_ld_place_of(_from);
    // the largest binade
    const int top    = (LDBL_MAX_EXP - (LDBL_MIN_EXP - 1));
    int       binade = p.binade;
    long double       offset = p.offset;

    // a binade holds more than d_math_umax: the steps cross at most one edge
    if ((LDBL_MANT_DIG - 1) >= d_internal_math_ld_umax_bits())
    {
        const long double full = d_internal_math_ld_pow2(LDBL_MANT_DIG - 1);

        offset += (long double)_steps;

        if (!(offset < full))
        {
            offset -= full;
            ++binade;
        }
    }
    else
    {
        const d_math_umax full  = d_internal_math_ld_full();
        const d_math_umax whole = _steps / full;
        d_math_umax       rest  = ((d_math_umax)offset) + (_steps % full);

        // whole binades first, then what is left within one
        if (whole > (d_math_umax)top)
        {
            return (long double)HUGE_VAL;
        }

        binade += (int)whole;

        if (rest >= full)
        {
            rest -= full;
            ++binade;
        }

        offset = (long double)rest;
    }

    // past the largest binade lies infinity
    if (binade > top)
    {
        return (long double)HUGE_VAL;
    }

    return d_internal_math_ld_value_of(binade, offset);
}

// d_internal_math_ld_descend
//   the value _steps below a positive finite _from; _steps must be fewer
// than the values in [0, _from).
D_MATH_FN long double
d_internal_math_ld_descend(
    long double         _from,
    d_math_umax _steps
)
{
    const struct d_internal_math_ld_place p =
        d_internal_math_ld_place_of(_from);
    int binade = p.binade;
    long double offset = p.offset;

    // a binade holds more than d_math_umax: at most one edge is crossed
    if ((LDBL_MANT_DIG - 1) >= d_internal_math_ld_umax_bits())
    {
        const long double back = (long double)_steps;

        if (back <= offset)
        {
            offset -= back;
        }
        else
        {
            const long double full = d_internal_math_ld_pow2(LDBL_MANT_DIG - 1);

            offset = (offset + full) - back;
            --binade;
        }
    }
    else
    {
        const d_math_umax full  = d_internal_math_ld_full();
        const d_math_umax rest  = _steps % full;
        d_math_umax       place = (d_math_umax)offset;

        // whole binades first, then what is left within one
        binade -= (int)(_steps / full);

        if (rest > place)
        {
            place = (place + full) - rest;
            --binade;
        }
        else
        {
            place -= rest;
        }

        offset = (long double)place;
    }

    return d_internal_math_ld_value_of(binade, offset);
}

// 3.2    Successor and predecessor
//------------------------------------------------------------------------------
// next_up is the least value above _x, next_down the greatest below:
// nextafter toward +inf and toward -inf, in pure arithmetic. +0 and -0 are
// one value, so next_up(-least) is 0. NaN stays NaN; next_up(+inf) is +inf
// and next_up(-inf) the most negative finite value.

D_MATH_FN long double
d_math_ld_next_up(
    long double _x
)
{
    // NaN and +inf are their own successors
    if ( (_x != _x) ||
         (_x > LDBL_MAX) )
    {
        return _x;
    }

    // -inf rises to the most negative finite value
    if (_x < -LDBL_MAX)
    {
        return -LDBL_MAX;
    }

    // the largest finite value rises to +inf
    if (_x == LDBL_MAX)
    {
        return (long double)HUGE_VAL;
    }

    // zero and the subnormals are evenly spaced by the least value
    if ( (_x < LDBL_MIN) &&
         (_x > -LDBL_MIN) )
    {
        return (_x + d_internal_math_ld_true_min());
    }

    // a positive normal value: one spacing of its binade up
    if (_x > (long double)0)
    {
        const struct d_internal_math_ld_binade b =
            d_internal_math_ld_binade_of(_x);

        return (_x + (b.power * LDBL_EPSILON));
    }

    {
        // a negative normal value: toward zero by the spacing below its
        // magnitude, which below a power of two is half its own -- except
        // below the least normal value, where it is the subnormal spacing
        const long double magnitude = -_x;
        const struct d_internal_math_ld_binade b =
            d_internal_math_ld_binade_of(magnitude);
        const long double spacing =
            ( (magnitude == b.power) && (magnitude > LDBL_MIN) )
                ? ((b.power * LDBL_EPSILON) / (long double)2)
                : (b.power * LDBL_EPSILON);

        return -(magnitude - spacing);
    }
}

D_MATH_FN long double
d_math_ld_next_down(
    long double _x
)
{
    return -d_math_ld_next_up(-_x);
}

// 3.3    Ordinal distance and advance
//------------------------------------------------------------------------------
// steps is how many values lie in [_from, _to) -- for adjacent values 1 --
// for _from <= _to, saturating at D_MATH_UMAX_MAX; advance is the value
// _steps above _from, +inf past the largest finite value. The infinities are
// the order's ends, one step past the largest finite values; NaN is in no
// order. So advance(a, steps(a, b)) == b wherever steps(a, b) does not
// saturate.

D_MATH_FN d_math_umax
d_math_ld_steps(
    long double _from,
    long double _to
)
{
    // both at or above zero
    if (_from >= (long double)0)
    {
        return d_internal_math_ld_steps_up(_from, _to);
    }

    // both at or below zero: the mirror image
    if (_to <= (long double)0)
    {
        return d_internal_math_ld_steps_up(-_to, -_from);
    }

    {
        // across zero: up to zero, then on from it, saturating
        const d_math_umax below =
            d_internal_math_ld_steps_up((long double)0, -_from);
        const d_math_umax above =
            d_internal_math_ld_steps_up((long double)0, _to);

        return (above > (D_MATH_UMAX_MAX - below)) ? D_MATH_UMAX_MAX
                                                   : (below + above);
    }
}

D_MATH_FN long double
d_math_ld_advance(
    long double         _from,
    d_math_umax _steps
)
{
    // from zero or above: climb
    if (_from >= (long double)0)
    {
        return d_internal_math_ld_climb(_from, _steps);
    }

    {
        // from below zero: as many steps as reach zero, at most, stay below
        // it -- a count that saturates is more than _steps can be
        const d_math_umax to_zero =
            d_internal_math_ld_steps_up((long double)0, -_from);

        if ( (_steps < to_zero) ||
             (to_zero == D_MATH_UMAX_MAX) )
        {
            return -d_internal_math_ld_descend(-_from, _steps);
        }

        return d_internal_math_ld_climb((long double)0, _steps - to_zero);
    }
}


#ifdef __cplusplus

//==============================================================================
// 4.  ONE NAME FOR EVERY FAMILY (C++)
//==============================================================================
// C++ only: the kernels above under one name each, chosen by argument type,
// so a C++ template serves float, double and long double alike.


D_MATH_FN float
d_math_next_up(
    float _x
)
{
    return d_math_f_next_up(_x);
}

D_MATH_FN float
d_math_next_down(
    float _x
)
{
    return d_math_f_next_down(_x);
}

D_MATH_FN d_math_umax
d_math_steps(
    float _from,
    float _to
)
{
    return d_math_f_steps(_from, _to);
}

D_MATH_FN float
d_math_advance(
    float       _from,
    d_math_umax _steps
)
{
    return d_math_f_advance(_from, _steps);
}

D_MATH_FN double
d_math_next_up(
    double _x
)
{
    return d_math_d_next_up(_x);
}

D_MATH_FN double
d_math_next_down(
    double _x
)
{
    return d_math_d_next_down(_x);
}

D_MATH_FN d_math_umax
d_math_steps(
    double _from,
    double _to
)
{
    return d_math_d_steps(_from, _to);
}

D_MATH_FN double
d_math_advance(
    double      _from,
    d_math_umax _steps
)
{
    return d_math_d_advance(_from, _steps);
}

D_MATH_FN long double
d_math_next_up(
    long double _x
)
{
    return d_math_ld_next_up(_x);
}

D_MATH_FN long double
d_math_next_down(
    long double _x
)
{
    return d_math_ld_next_down(_x);
}

D_MATH_FN d_math_umax
d_math_steps(
    long double _from,
    long double _to
)
{
    return d_math_ld_steps(_from, _to);
}

D_MATH_FN long double
d_math_advance(
    long double _from,
    d_math_umax _steps
)
{
    return d_math_ld_advance(_from, _steps);
}

#endif  // __cplusplus

#endif  // DJINTERP_C_MATH_FLOAT_ORDER_H
