/*******************************************************************************
* djinterp [c]                                                  interval_float.h
*
* Floating-point intervals: the C core of math/interval for float,
* double and long double.
*   GENERATED by tools/gen_c_math_float.py from one text for the three
* families: edit the generator, not this file.
*
*   An interval's members are the values of its type within its bounds,
* as for the integer families: here every representable value, so an open
* bound moves to the neighbouring value (float_order.h), count is how many
* values lie between the inclusive bounds, at and index_of walk them, and
* clamp lands inside an open bound on the nearest value it holds. A
* discrete interval's members are first + k * step, the product formed
* apart from the sum so no compiler fuses the two and the members are the
* same everywhere. An infinite first member or step leaves one member, the
* first; members past the largest finite value are one member, +inf. NaN
* is in no interval.
* Every kernel but formatting is pure arithmetic, so constexpr from C++14.
*
*
* path:      /inc/djinterp/c/math/interval_float.h
* link(s):   TBA
* author(s): Samuel 'teer' Neal-Blim                         created: 2026.10.04
*                                                            revised: 2026.10.04
*******************************************************************************/

/*
TABLE OF CONTENTS
=================
1.  THE FLOAT FAMILY (_f)
    ---------------------
    1.  Layout
         1.  d_interval_f
    2.  Internal helpers
    3.  Construction, validity and bounds
    4.  Size and access
    5.  Membership and clamping
    6.  Relations
    7.  Normalization
    8.  Formatting
2.  THE DOUBLE FAMILY (_d)
    ----------------------
    1.  Layout
         1.  d_interval_d
    2.  Internal helpers
    3.  Construction, validity and bounds
    4.  Size and access
    5.  Membership and clamping
    6.  Relations
    7.  Normalization
    8.  Formatting
3.  THE LONG DOUBLE FAMILY (_ld)
    ----------------------------
    1.  Layout
         1.  d_interval_ld
    2.  Internal helpers
    3.  Construction, validity and bounds
    4.  Size and access
    5.  Membership and clamping
    6.  Relations
    7.  Normalization
    8.  Formatting
4.  ONE NAME FOR EVERY FAMILY (C++)
    -------------------------------
*/

#ifndef DJINTERP_C_MATH_INTERVAL_FLOAT_H
#define DJINTERP_C_MATH_INTERVAL_FLOAT_H 1

// std
#include <stddef.h>          // size_t, NULL
#include <stdio.h>           // sprintf, sscanf
// djinterp
#include "./float_order.h"   // d_math_*_next_up, _next_down, _steps, _advance
#include "./interval.h"      // d_interval_bound, the formatting helpers
#include "./math_common.h"   // D_MATH_FN, d_math_umax, d_math_ratio

//==============================================================================
// 1.  THE FLOAT FAMILY (_f)
//==============================================================================


// 1.1    Layout
//------------------------------------------------------------------------------
// 1.1.1
// d_interval_f
//   struct: an interval over float.
struct d_interval_f
{
    float      lower;   // the lower bound
    float      upper;   // the upper bound
    float      step;    // the stride: 0 continuous, > 0 discrete
    unsigned bounds;  // D_INTERVAL_LEFT_OPEN | D_INTERVAL_RIGHT_OPEN
};

// 1.2    Internal helpers
//------------------------------------------------------------------------------

// d_internal_interval_f_member
//   a discrete interval's member _index steps past _first: _first + _index *
// _step, the product formed apart so no compiler fuses it into the sum.
D_MATH_FN float
d_internal_interval_f_member(
    float         _first,
    float         _step,
    d_math_umax _index
)
{
    // the first member is the first, whatever the step (0 * inf is NaN)
    if (_index == 0u)
    {
        return _first;
    }

    {
        const float offset = (float)_index * _step;

        return (_first + offset);
    }
}

// d_internal_interval_f_snap_finite
//   the index of the last member at or below a finite _value, for _value >=
// _first and finite _first and _step: the rounded quotient, settled by
// testing the members beside it.
D_MATH_FN d_math_umax
d_internal_interval_f_snap_finite(
    float _first,
    float _step,
    float _value
)
{
    const float   quotient = (_value - _first) / _step;
    d_math_umax index    = 0u;
    int         tries    = 0;

    // the quotient as an index: saturated, or truncated
    if (!(quotient < (float)D_MATH_UMAX_MAX))
    {
        index = D_MATH_UMAX_MAX;
    }
    else if (quotient > (float)0)
    {
        index = (d_math_umax)quotient;
    }

    // the quotient was rounded: down while the member passes _value...
    for (tries = 0;
         ( (tries < 4) &&
           (index > 0u) &&
           (d_internal_interval_f_member(_first, _step, index) > _value) );
         ++tries)
    {
        --index;
    }

    // ...and up while the next one does not
    for (tries = 0;
         ( (tries < 4) &&
           (index < D_MATH_UMAX_MAX) &&
           (d_internal_interval_f_member(_first, _step, index + 1u) <=
            _value) );
         ++tries)
    {
        ++index;
    }

    return index;
}

// d_internal_interval_f_snap
//   the index of the last member at or below _value, for _value >= _first.
// An infinite first member or step leaves one member, the first; members
// past the largest finite value round to +inf, one member, after the last
// finite one.
D_MATH_FN d_math_umax
d_internal_interval_f_snap(
    float _first,
    float _step,
    float _value
)
{
    // an infinite first member or step: the first is the only member
    if ( (_first > FLT_MAX) ||
         (_first < -FLT_MAX) ||
         (_step > FLT_MAX) )
    {
        return 0u;
    }

    // +inf: the member after the last finite one
    if (_value > FLT_MAX)
    {
        const d_math_umax last =
            d_internal_interval_f_snap_finite(_first, _step, FLT_MAX);

        return (last == D_MATH_UMAX_MAX) ? last : (last + 1u);
    }

    return d_internal_interval_f_snap_finite(_first, _step, _value);
}

// d_internal_interval_f_is_void
//   true when the interval is empty on the real line: reversed or NaN
// bounds, or one point with either bound open.
D_MATH_FN bool
d_internal_interval_f_is_void(
    struct d_interval_f _interval
)
{
    return ( (!(_interval.lower <= _interval.upper)) ||
             ( (_interval.lower == _interval.upper) &&
               (_interval.bounds != D_INTERVAL_CLOSED) ) );
}

// 1.3    Construction, validity and bounds
//------------------------------------------------------------------------------
// as for the integer families; an open bound moves to the neighbouring
// value (float_order.h's next_up and next_down), so inclusive_lower is the
// least value the interval holds and inclusive_upper the greatest.

D_MATH_FN struct d_interval_f
d_interval_f_make(
    float      _lower,
    float      _upper,
    unsigned _bounds,
    float      _step
)
{
    struct d_interval_f result = { (float)0,
                                     (float)0,
                                     (float)0,
                                     0u };

    result.lower  = _lower;
    result.upper  = _upper;
    result.step   = _step;
    result.bounds = _bounds;

    return result;
}

D_MATH_FN bool
d_interval_f_is_valid(
    struct d_interval_f _interval
)
{
    return ( (_interval.lower <= _interval.upper) &&
             (_interval.step >= (float)0) );
}

D_MATH_FN bool
d_interval_f_is_discrete(
    struct d_interval_f _interval
)
{
    return (_interval.step > (float)0);
}

D_MATH_FN float
d_interval_f_inclusive_lower(
    struct d_interval_f _interval
)
{
    return ((_interval.bounds & D_INTERVAL_LEFT_OPEN) != 0u)
               ? d_math_f_next_up(_interval.lower)
               : _interval.lower;
}

D_MATH_FN float
d_interval_f_inclusive_upper(
    struct d_interval_f _interval
)
{
    return ((_interval.bounds & D_INTERVAL_RIGHT_OPEN) != 0u)
               ? d_math_f_next_down(_interval.upper)
               : _interval.upper;
}

D_MATH_FN bool
d_interval_f_is_empty(
    struct d_interval_f _interval
)
{
    // an open bound at an infinity excludes it, and nothing lies beyond it
    if ( ( ((_interval.bounds & D_INTERVAL_LEFT_OPEN) != 0u) &&
           (_interval.lower > FLT_MAX) ) ||
         ( ((_interval.bounds & D_INTERVAL_RIGHT_OPEN) != 0u) &&
           (_interval.upper < -FLT_MAX) ) )
    {
        return true;
    }

    return !( d_interval_f_inclusive_lower(_interval) <=
              d_interval_f_inclusive_upper(_interval) );
}

// 1.4    Size and access
//------------------------------------------------------------------------------
// A continuous interval's members are every value of the type within its
// bounds, so count is their number (float_order.h's steps, plus one), at
// the value that many steps up, and index_of the steps to a value. A
// discrete interval's members are first + k * step, each product formed
// apart. Both counts saturate at D_MATH_UMAX_MAX.

D_MATH_FN float
d_interval_f_first(
    struct d_interval_f _interval
)
{
    return d_interval_f_inclusive_lower(_interval);
}

D_MATH_FN float
d_interval_f_last(
    struct d_interval_f _interval
)
{
    const float low  = d_interval_f_inclusive_lower(_interval);
    const float high = d_interval_f_inclusive_upper(_interval);

    // a discrete interval ends on its last whole step
    if ( (_interval.step > (float)0) &&
         (low <= high) )
    {
        return d_internal_interval_f_member(
                   low,
                   _interval.step,
                   d_internal_interval_f_snap(low, _interval.step, high));
    }

    return high;
}

D_MATH_FN d_math_umax
d_interval_f_count(
    struct d_interval_f _interval
)
{
    const float low  = d_interval_f_inclusive_lower(_interval);
    const float high = d_interval_f_inclusive_upper(_interval);
    d_math_umax steps = 0u;

    // an empty interval counts nothing
    if (d_interval_f_is_empty(_interval))
    {
        return 0u;
    }

    steps = (_interval.step > (float)0)
                ? d_internal_interval_f_snap(low, _interval.step, high)
                : d_math_f_steps(low, high);

    return (steps == D_MATH_UMAX_MAX) ? steps : (steps + 1u);
}

D_MATH_FN float
d_interval_f_at(
    struct d_interval_f _interval,
    d_math_umax           _index
)
{
    const float low = d_interval_f_inclusive_lower(_interval);

    // a discrete member, or the value _index steps up
    if (_interval.step > (float)0)
    {
        return d_internal_interval_f_member(low, _interval.step, _index);
    }

    return d_math_f_advance(low, _index);
}

// 1.5    Membership and clamping
//------------------------------------------------------------------------------
// contains honours both bounds exactly and, for a discrete interval, the
// members; contains_in_range the bounds alone; NaN is in no interval. clamp
// moves a value to the nearest member toward the interval -- the
// neighbouring value inside an open bound -- and, inside a discrete one,
// down to a member; clamp_nearest to the nearer member, a tie going down.
// NaN clamps to NaN.

D_MATH_FN bool
d_interval_f_contains_in_range(
    struct d_interval_f _interval,
    float                   _value
)
{
    const bool left_ok =
        ((_interval.bounds & D_INTERVAL_LEFT_OPEN) != 0u)
            ? (_value > _interval.lower)
            : (_value >= _interval.lower);
    const bool right_ok =
        ((_interval.bounds & D_INTERVAL_RIGHT_OPEN) != 0u)
            ? (_value < _interval.upper)
            : (_value <= _interval.upper);

    return (left_ok && right_ok);
}

D_MATH_FN bool
d_interval_f_contains(
    struct d_interval_f _interval,
    float                   _value
)
{
    // outside the bounds is outside the interval
    if (!d_interval_f_contains_in_range(_interval, _value))
    {
        return false;
    }

    // a discrete member is one of the computed members
    if (_interval.step > (float)0)
    {
        const float low = d_interval_f_inclusive_lower(_interval);

        return ( d_internal_interval_f_member(
                     low,
                     _interval.step,
                     d_internal_interval_f_snap(low,
                                                  _interval.step,
                                                  _value)) == _value );
    }

    return true;
}

D_MATH_FN float
d_interval_f_clamp(
    struct d_interval_f _interval,
    float                   _value
)
{
    const float low  = d_interval_f_inclusive_lower(_interval);
    const float high = d_interval_f_inclusive_upper(_interval);

    // NaN has no nearer member
    if (_value != _value)
    {
        return _value;
    }

    // below the interval: its first value
    if (_value < low)
    {
        return low;
    }

    // above the interval: its last value
    if (_value > high)
    {
        return d_interval_f_last(_interval);
    }

    // inside a discrete interval: down to a member
    if (_interval.step > (float)0)
    {
        return d_internal_interval_f_member(
                   low,
                   _interval.step,
                   d_internal_interval_f_snap(low, _interval.step, _value));
    }

    return _value;
}

D_MATH_FN float
d_interval_f_clamp_nearest(
    struct d_interval_f _interval,
    float                   _value
)
{
    // NaN, a continuous interval, and anything outside one: as clamp
    if ( (_value != _value) ||
         (!(_interval.step > (float)0)) ||
         (!d_interval_f_contains_in_range(_interval, _value)) )
    {
        return d_interval_f_clamp(_interval, _value);
    }

    const float low = d_interval_f_inclusive_lower(_interval);
    const float top = d_interval_f_last(_interval);

    // past the last member: the last member
    if ( (_value < low) ||
         (_value >= top) )
    {
        return d_interval_f_clamp(_interval, _value);
    }

    const d_math_umax index =
        d_internal_interval_f_snap(low, _interval.step, _value);
    const float below =
        d_internal_interval_f_member(low, _interval.step, index);
    const float above =
        d_internal_interval_f_member(low, _interval.step, index + 1u);

    // the member above is nearer, and still inside the interval
    if ( (above <= top) &&
         ((_value - below) > (above - _value)) )
    {
        return above;
    }

    return below;
}

D_MATH_FN d_math_umax
d_interval_f_index_of(
    struct d_interval_f _interval,
    float                   _value
)
{
    // a value that is not a member has the index one past the last
    if (!d_interval_f_contains(_interval, _value))
    {
        return d_interval_f_count(_interval);
    }

    {
        const float low = d_interval_f_inclusive_lower(_interval);

        return (_interval.step > (float)0)
                   ? d_internal_interval_f_snap(low, _interval.step, _value)
                   : d_math_f_steps(low, _value);
    }
}

// 1.6    Relations
//------------------------------------------------------------------------------
// as for the integer families: overlaps compares the inclusive ranges,
// ignoring strides; overlaps_continuous the real line; intersects asks for
// a shared member -- for two discrete intervals by testing the members of
// the sparser one within the ranges' common part, so its cost is the count
// of those.

D_MATH_FN bool
d_interval_f_overlaps(
    struct d_interval_f _left,
    struct d_interval_f _right
)
{
    // an empty interval shares a position with nothing
    if ( (d_interval_f_is_empty(_left)) ||
         (d_interval_f_is_empty(_right)) )
    {
        return false;
    }

    return !( (d_interval_f_inclusive_upper(_left) <
               d_interval_f_inclusive_lower(_right)) ||
              (d_interval_f_inclusive_lower(_left) >
               d_interval_f_inclusive_upper(_right)) );
}

D_MATH_FN bool
d_interval_f_overlaps_continuous(
    struct d_interval_f _left,
    struct d_interval_f _right
)
{
    // an interval empty on the real line meets nothing
    if ( (d_internal_interval_f_is_void(_left)) ||
         (d_internal_interval_f_is_void(_right)) )
    {
        return false;
    }

    const bool left_meets_closed =
        ( ((_left.bounds  & D_INTERVAL_LEFT_OPEN)  == 0u) &&
          ((_right.bounds & D_INTERVAL_RIGHT_OPEN) == 0u) );
    const bool right_meets_closed =
        ( ((_left.bounds  & D_INTERVAL_RIGHT_OPEN) == 0u) &&
          ((_right.bounds & D_INTERVAL_LEFT_OPEN)  == 0u) );
    const bool left_ok =
        left_meets_closed ? (_left.lower <= _right.upper)
                          : (_left.lower <  _right.upper);
    const bool right_ok =
        right_meets_closed ? (_right.lower <= _left.upper)
                           : (_right.lower <  _left.upper);

    return (left_ok && right_ok);
}

D_MATH_FN bool
d_interval_f_intersects(
    struct d_interval_f _left,
    struct d_interval_f _right
)
{
    // two continuous intervals share a value where their ranges meet
    if ( (!(_left.step > (float)0)) &&
         (!(_right.step > (float)0)) )
    {
        return d_interval_f_overlaps(_left, _right);
    }

    // an empty interval has no member to share
    if ( (d_interval_f_is_empty(_left)) ||
         (d_interval_f_is_empty(_right)) )
    {
        return false;
    }

    {
        // walk the sparser discrete one; test each member in the other
        const bool                  left_walks =
            ( (_left.step > (float)0) &&
              ( (!(_right.step > (float)0)) ||
                (_left.step >= _right.step) ) );
        const struct d_interval_f walk  = left_walks ? _left  : _right;
        const struct d_interval_f other = left_walks ? _right : _left;
        const float first = d_interval_f_inclusive_lower(walk);
        const float low   = (first > d_interval_f_inclusive_lower(other))
                              ? first
                              : d_interval_f_inclusive_lower(other);
        const float high  = (d_interval_f_last(walk) <
                           d_interval_f_inclusive_upper(other))
                              ? d_interval_f_last(walk)
                              : d_interval_f_inclusive_upper(other);
        const d_math_umax total = d_interval_f_count(walk);
        d_math_umax index = d_internal_interval_f_snap(first, walk.step, low);

        // the first member at or above the common part's start
        if (d_internal_interval_f_member(first, walk.step, index) < low)
        {
            ++index;
        }

        // every member within the common part, until one is shared
        while ( (index < total) &&
                (d_internal_interval_f_member(first, walk.step, index) <=
                 high) )
        {
            if (d_interval_f_contains(
                    other,
                    d_internal_interval_f_member(first, walk.step, index)))
            {
                return true;
            }

            ++index;
        }

        return false;
    }
}

// 1.7    Normalization
//------------------------------------------------------------------------------
// as for the integer families, the terms in long double.

D_MATH_FN struct d_math_ratio
d_internal_interval_f_terms(
    float _origin,
    float _end,
    float _value
)
{
    struct d_math_ratio result = { 0.0L, 1.0L };

    // a degenerate span maps everything to 0
    if (_end == _origin)
    {
        return result;
    }

    result.numerator   = (long double)_value - (long double)_origin;
    result.denominator = (long double)_end   - (long double)_origin;

    return result;
}

D_MATH_FN struct d_math_ratio
d_interval_f_normalize_terms(
    struct d_interval_f _interval,
    float                   _value
)
{
    return d_internal_interval_f_terms(_interval.lower,
                                         _interval.upper,
                                         _value);
}

D_MATH_FN struct d_math_ratio
d_interval_f_normalize_effective_terms(
    struct d_interval_f _interval,
    float                   _value
)
{
    return d_internal_interval_f_terms(
               d_interval_f_inclusive_lower(_interval),
               d_interval_f_inclusive_upper(_interval),
               _value);
}

D_MATH_FN struct d_math_ratio
d_interval_f_normalize_discrete_terms(
    struct d_interval_f _interval,
    float                   _value
)
{
    // a continuous interval normalizes over its inclusive bounds
    if (!(_interval.step > (float)0))
    {
        return d_interval_f_normalize_effective_terms(_interval, _value);
    }

    struct d_math_ratio result = { 0.0L, 1.0L };
    const d_math_umax   count  = d_interval_f_count(_interval);
    const float           low    =
        d_interval_f_inclusive_lower(_interval);

    // one member or none: nothing to spread over
    if (count <= 1u)
    {
        return result;
    }

    // at or above the first member: the index of the member at or below;
    // below it, the quotient truncated toward zero, a zero kept +0
    if (_value >= low)
    {
        result.numerator = (long double)d_internal_interval_f_snap(
                               low,
                               _interval.step,
                               _value);
    }
    else
    {
        const long double back = ((long double)low - (long double)_value) /
                                 (long double)_interval.step;
        const d_math_umax whole =
            (back < (long double)D_MATH_UMAX_MAX) ? (d_math_umax)back
                                                  : D_MATH_UMAX_MAX;

        result.numerator = (whole == 0u) ? 0.0L : -(long double)whole;
    }

    result.denominator = (long double)(count - 1u);

    return result;
}

// 1.8    Formatting
//------------------------------------------------------------------------------

// d_internal_interval_f_put_value
//   writes _value at _position as the fewest significant digits (from
// FLT_DIG) that read back as the same value -- 0.1, not 0.10000000000000001 --
// and returns the position after it.
D_MATH_FN_RT size_t
d_internal_interval_f_put_value(
    char*  _buffer,
    size_t _capacity,
    size_t _position,
    float    _value
)
{
    char   text[64] = { 0 };
    int    digits   = FLT_DIG;
    size_t i        = 0u;
    size_t position = _position;

    // the shortest round trip; NaN never compares equal, and keeps the last
    for (digits = FLT_DIG; digits <= (FLT_DIG + 3); ++digits)
    {
        float back = (float)0;

        (void)sprintf(text, "%.*g", digits, (double)_value);

        if ( (sscanf(text, "%g", &back) == 1) &&
             (back == _value) )
        {
            break;
        }
    }

    for (i = 0u; text[i] != '\0'; ++i)
    {
        position = d_internal_interval_put_char(_buffer,
                                                _capacity,
                                                position,
                                                text[i]);
    }

    return position;
}

/**
 * @brief Writes an interval of the float family as text, as
 *        d_interval_imax_format does, each value in the fewest digits that
 *        read back as it.
 *
 * @param[out] _buffer    where the text goes; may be NULL if _capacity is 0.
 * @param[in]  _capacity  the bytes _buffer holds.
 * @param[in]  _interval  the interval to write.
 * @return the length of the whole text, not counting the terminator.
 */
D_MATH_FN_RT size_t
d_interval_f_format(
    char*                 _buffer,
    size_t                _capacity,
    struct d_interval_f _interval
)
{
    const char left  =
        ((_interval.bounds & D_INTERVAL_LEFT_OPEN) != 0u) ? '(' : '[';
    const char right =
        ((_interval.bounds & D_INTERVAL_RIGHT_OPEN) != 0u) ? ')' : ']';
    size_t     at    = d_internal_interval_put_char(_buffer,
                                                    _capacity,
                                                    0u,
                                                    left);

    at = d_internal_interval_f_put_value(_buffer,
                                           _capacity,
                                           at,
                                           _interval.lower);

    // a discrete interval shows its stride between its bounds
    if (_interval.step > (float)0)
    {
        at = d_internal_interval_put_char(_buffer, _capacity, at, ':');
        at = d_internal_interval_f_put_value(_buffer,
                                               _capacity,
                                               at,
                                               _interval.step);
        at = d_internal_interval_put_char(_buffer, _capacity, at, ':');
    }
    else
    {
        at = d_internal_interval_put_char(_buffer, _capacity, at, ',');
        at = d_internal_interval_put_char(_buffer, _capacity, at, ' ');
    }

    at = d_internal_interval_f_put_value(_buffer,
                                           _capacity,
                                           at,
                                           _interval.upper);
    at = d_internal_interval_put_char(_buffer, _capacity, at, right);

    return d_internal_interval_finish(_buffer, _capacity, at);
}

//==============================================================================
// 2.  THE DOUBLE FAMILY (_d)
//==============================================================================


// 2.1    Layout
//------------------------------------------------------------------------------
// 2.1.1
// d_interval_d
//   struct: an interval over double.
struct d_interval_d
{
    double      lower;   // the lower bound
    double      upper;   // the upper bound
    double      step;    // the stride: 0 continuous, > 0 discrete
    unsigned bounds;  // D_INTERVAL_LEFT_OPEN | D_INTERVAL_RIGHT_OPEN
};

// 2.2    Internal helpers
//------------------------------------------------------------------------------

// d_internal_interval_d_member
//   a discrete interval's member _index steps past _first: _first + _index *
// _step, the product formed apart so no compiler fuses it into the sum.
D_MATH_FN double
d_internal_interval_d_member(
    double         _first,
    double         _step,
    d_math_umax _index
)
{
    // the first member is the first, whatever the step (0 * inf is NaN)
    if (_index == 0u)
    {
        return _first;
    }

    {
        const double offset = (double)_index * _step;

        return (_first + offset);
    }
}

// d_internal_interval_d_snap_finite
//   the index of the last member at or below a finite _value, for _value >=
// _first and finite _first and _step: the rounded quotient, settled by
// testing the members beside it.
D_MATH_FN d_math_umax
d_internal_interval_d_snap_finite(
    double _first,
    double _step,
    double _value
)
{
    const double   quotient = (_value - _first) / _step;
    d_math_umax index    = 0u;
    int         tries    = 0;

    // the quotient as an index: saturated, or truncated
    if (!(quotient < (double)D_MATH_UMAX_MAX))
    {
        index = D_MATH_UMAX_MAX;
    }
    else if (quotient > (double)0)
    {
        index = (d_math_umax)quotient;
    }

    // the quotient was rounded: down while the member passes _value...
    for (tries = 0;
         ( (tries < 4) &&
           (index > 0u) &&
           (d_internal_interval_d_member(_first, _step, index) > _value) );
         ++tries)
    {
        --index;
    }

    // ...and up while the next one does not
    for (tries = 0;
         ( (tries < 4) &&
           (index < D_MATH_UMAX_MAX) &&
           (d_internal_interval_d_member(_first, _step, index + 1u) <=
            _value) );
         ++tries)
    {
        ++index;
    }

    return index;
}

// d_internal_interval_d_snap
//   the index of the last member at or below _value, for _value >= _first.
// An infinite first member or step leaves one member, the first; members
// past the largest finite value round to +inf, one member, after the last
// finite one.
D_MATH_FN d_math_umax
d_internal_interval_d_snap(
    double _first,
    double _step,
    double _value
)
{
    // an infinite first member or step: the first is the only member
    if ( (_first > DBL_MAX) ||
         (_first < -DBL_MAX) ||
         (_step > DBL_MAX) )
    {
        return 0u;
    }

    // +inf: the member after the last finite one
    if (_value > DBL_MAX)
    {
        const d_math_umax last =
            d_internal_interval_d_snap_finite(_first, _step, DBL_MAX);

        return (last == D_MATH_UMAX_MAX) ? last : (last + 1u);
    }

    return d_internal_interval_d_snap_finite(_first, _step, _value);
}

// d_internal_interval_d_is_void
//   true when the interval is empty on the real line: reversed or NaN
// bounds, or one point with either bound open.
D_MATH_FN bool
d_internal_interval_d_is_void(
    struct d_interval_d _interval
)
{
    return ( (!(_interval.lower <= _interval.upper)) ||
             ( (_interval.lower == _interval.upper) &&
               (_interval.bounds != D_INTERVAL_CLOSED) ) );
}

// 2.3    Construction, validity and bounds
//------------------------------------------------------------------------------
// as for the integer families; an open bound moves to the neighbouring
// value (float_order.h's next_up and next_down), so inclusive_lower is the
// least value the interval holds and inclusive_upper the greatest.

D_MATH_FN struct d_interval_d
d_interval_d_make(
    double      _lower,
    double      _upper,
    unsigned _bounds,
    double      _step
)
{
    struct d_interval_d result = { (double)0,
                                     (double)0,
                                     (double)0,
                                     0u };

    result.lower  = _lower;
    result.upper  = _upper;
    result.step   = _step;
    result.bounds = _bounds;

    return result;
}

D_MATH_FN bool
d_interval_d_is_valid(
    struct d_interval_d _interval
)
{
    return ( (_interval.lower <= _interval.upper) &&
             (_interval.step >= (double)0) );
}

D_MATH_FN bool
d_interval_d_is_discrete(
    struct d_interval_d _interval
)
{
    return (_interval.step > (double)0);
}

D_MATH_FN double
d_interval_d_inclusive_lower(
    struct d_interval_d _interval
)
{
    return ((_interval.bounds & D_INTERVAL_LEFT_OPEN) != 0u)
               ? d_math_d_next_up(_interval.lower)
               : _interval.lower;
}

D_MATH_FN double
d_interval_d_inclusive_upper(
    struct d_interval_d _interval
)
{
    return ((_interval.bounds & D_INTERVAL_RIGHT_OPEN) != 0u)
               ? d_math_d_next_down(_interval.upper)
               : _interval.upper;
}

D_MATH_FN bool
d_interval_d_is_empty(
    struct d_interval_d _interval
)
{
    // an open bound at an infinity excludes it, and nothing lies beyond it
    if ( ( ((_interval.bounds & D_INTERVAL_LEFT_OPEN) != 0u) &&
           (_interval.lower > DBL_MAX) ) ||
         ( ((_interval.bounds & D_INTERVAL_RIGHT_OPEN) != 0u) &&
           (_interval.upper < -DBL_MAX) ) )
    {
        return true;
    }

    return !( d_interval_d_inclusive_lower(_interval) <=
              d_interval_d_inclusive_upper(_interval) );
}

// 2.4    Size and access
//------------------------------------------------------------------------------
// A continuous interval's members are every value of the type within its
// bounds, so count is their number (float_order.h's steps, plus one), at
// the value that many steps up, and index_of the steps to a value. A
// discrete interval's members are first + k * step, each product formed
// apart. Both counts saturate at D_MATH_UMAX_MAX.

D_MATH_FN double
d_interval_d_first(
    struct d_interval_d _interval
)
{
    return d_interval_d_inclusive_lower(_interval);
}

D_MATH_FN double
d_interval_d_last(
    struct d_interval_d _interval
)
{
    const double low  = d_interval_d_inclusive_lower(_interval);
    const double high = d_interval_d_inclusive_upper(_interval);

    // a discrete interval ends on its last whole step
    if ( (_interval.step > (double)0) &&
         (low <= high) )
    {
        return d_internal_interval_d_member(
                   low,
                   _interval.step,
                   d_internal_interval_d_snap(low, _interval.step, high));
    }

    return high;
}

D_MATH_FN d_math_umax
d_interval_d_count(
    struct d_interval_d _interval
)
{
    const double low  = d_interval_d_inclusive_lower(_interval);
    const double high = d_interval_d_inclusive_upper(_interval);
    d_math_umax steps = 0u;

    // an empty interval counts nothing
    if (d_interval_d_is_empty(_interval))
    {
        return 0u;
    }

    steps = (_interval.step > (double)0)
                ? d_internal_interval_d_snap(low, _interval.step, high)
                : d_math_d_steps(low, high);

    return (steps == D_MATH_UMAX_MAX) ? steps : (steps + 1u);
}

D_MATH_FN double
d_interval_d_at(
    struct d_interval_d _interval,
    d_math_umax           _index
)
{
    const double low = d_interval_d_inclusive_lower(_interval);

    // a discrete member, or the value _index steps up
    if (_interval.step > (double)0)
    {
        return d_internal_interval_d_member(low, _interval.step, _index);
    }

    return d_math_d_advance(low, _index);
}

// 2.5    Membership and clamping
//------------------------------------------------------------------------------
// contains honours both bounds exactly and, for a discrete interval, the
// members; contains_in_range the bounds alone; NaN is in no interval. clamp
// moves a value to the nearest member toward the interval -- the
// neighbouring value inside an open bound -- and, inside a discrete one,
// down to a member; clamp_nearest to the nearer member, a tie going down.
// NaN clamps to NaN.

D_MATH_FN bool
d_interval_d_contains_in_range(
    struct d_interval_d _interval,
    double                   _value
)
{
    const bool left_ok =
        ((_interval.bounds & D_INTERVAL_LEFT_OPEN) != 0u)
            ? (_value > _interval.lower)
            : (_value >= _interval.lower);
    const bool right_ok =
        ((_interval.bounds & D_INTERVAL_RIGHT_OPEN) != 0u)
            ? (_value < _interval.upper)
            : (_value <= _interval.upper);

    return (left_ok && right_ok);
}

D_MATH_FN bool
d_interval_d_contains(
    struct d_interval_d _interval,
    double                   _value
)
{
    // outside the bounds is outside the interval
    if (!d_interval_d_contains_in_range(_interval, _value))
    {
        return false;
    }

    // a discrete member is one of the computed members
    if (_interval.step > (double)0)
    {
        const double low = d_interval_d_inclusive_lower(_interval);

        return ( d_internal_interval_d_member(
                     low,
                     _interval.step,
                     d_internal_interval_d_snap(low,
                                                  _interval.step,
                                                  _value)) == _value );
    }

    return true;
}

D_MATH_FN double
d_interval_d_clamp(
    struct d_interval_d _interval,
    double                   _value
)
{
    const double low  = d_interval_d_inclusive_lower(_interval);
    const double high = d_interval_d_inclusive_upper(_interval);

    // NaN has no nearer member
    if (_value != _value)
    {
        return _value;
    }

    // below the interval: its first value
    if (_value < low)
    {
        return low;
    }

    // above the interval: its last value
    if (_value > high)
    {
        return d_interval_d_last(_interval);
    }

    // inside a discrete interval: down to a member
    if (_interval.step > (double)0)
    {
        return d_internal_interval_d_member(
                   low,
                   _interval.step,
                   d_internal_interval_d_snap(low, _interval.step, _value));
    }

    return _value;
}

D_MATH_FN double
d_interval_d_clamp_nearest(
    struct d_interval_d _interval,
    double                   _value
)
{
    // NaN, a continuous interval, and anything outside one: as clamp
    if ( (_value != _value) ||
         (!(_interval.step > (double)0)) ||
         (!d_interval_d_contains_in_range(_interval, _value)) )
    {
        return d_interval_d_clamp(_interval, _value);
    }

    const double low = d_interval_d_inclusive_lower(_interval);
    const double top = d_interval_d_last(_interval);

    // past the last member: the last member
    if ( (_value < low) ||
         (_value >= top) )
    {
        return d_interval_d_clamp(_interval, _value);
    }

    const d_math_umax index =
        d_internal_interval_d_snap(low, _interval.step, _value);
    const double below =
        d_internal_interval_d_member(low, _interval.step, index);
    const double above =
        d_internal_interval_d_member(low, _interval.step, index + 1u);

    // the member above is nearer, and still inside the interval
    if ( (above <= top) &&
         ((_value - below) > (above - _value)) )
    {
        return above;
    }

    return below;
}

D_MATH_FN d_math_umax
d_interval_d_index_of(
    struct d_interval_d _interval,
    double                   _value
)
{
    // a value that is not a member has the index one past the last
    if (!d_interval_d_contains(_interval, _value))
    {
        return d_interval_d_count(_interval);
    }

    {
        const double low = d_interval_d_inclusive_lower(_interval);

        return (_interval.step > (double)0)
                   ? d_internal_interval_d_snap(low, _interval.step, _value)
                   : d_math_d_steps(low, _value);
    }
}

// 2.6    Relations
//------------------------------------------------------------------------------
// as for the integer families: overlaps compares the inclusive ranges,
// ignoring strides; overlaps_continuous the real line; intersects asks for
// a shared member -- for two discrete intervals by testing the members of
// the sparser one within the ranges' common part, so its cost is the count
// of those.

D_MATH_FN bool
d_interval_d_overlaps(
    struct d_interval_d _left,
    struct d_interval_d _right
)
{
    // an empty interval shares a position with nothing
    if ( (d_interval_d_is_empty(_left)) ||
         (d_interval_d_is_empty(_right)) )
    {
        return false;
    }

    return !( (d_interval_d_inclusive_upper(_left) <
               d_interval_d_inclusive_lower(_right)) ||
              (d_interval_d_inclusive_lower(_left) >
               d_interval_d_inclusive_upper(_right)) );
}

D_MATH_FN bool
d_interval_d_overlaps_continuous(
    struct d_interval_d _left,
    struct d_interval_d _right
)
{
    // an interval empty on the real line meets nothing
    if ( (d_internal_interval_d_is_void(_left)) ||
         (d_internal_interval_d_is_void(_right)) )
    {
        return false;
    }

    const bool left_meets_closed =
        ( ((_left.bounds  & D_INTERVAL_LEFT_OPEN)  == 0u) &&
          ((_right.bounds & D_INTERVAL_RIGHT_OPEN) == 0u) );
    const bool right_meets_closed =
        ( ((_left.bounds  & D_INTERVAL_RIGHT_OPEN) == 0u) &&
          ((_right.bounds & D_INTERVAL_LEFT_OPEN)  == 0u) );
    const bool left_ok =
        left_meets_closed ? (_left.lower <= _right.upper)
                          : (_left.lower <  _right.upper);
    const bool right_ok =
        right_meets_closed ? (_right.lower <= _left.upper)
                           : (_right.lower <  _left.upper);

    return (left_ok && right_ok);
}

D_MATH_FN bool
d_interval_d_intersects(
    struct d_interval_d _left,
    struct d_interval_d _right
)
{
    // two continuous intervals share a value where their ranges meet
    if ( (!(_left.step > (double)0)) &&
         (!(_right.step > (double)0)) )
    {
        return d_interval_d_overlaps(_left, _right);
    }

    // an empty interval has no member to share
    if ( (d_interval_d_is_empty(_left)) ||
         (d_interval_d_is_empty(_right)) )
    {
        return false;
    }

    {
        // walk the sparser discrete one; test each member in the other
        const bool                  left_walks =
            ( (_left.step > (double)0) &&
              ( (!(_right.step > (double)0)) ||
                (_left.step >= _right.step) ) );
        const struct d_interval_d walk  = left_walks ? _left  : _right;
        const struct d_interval_d other = left_walks ? _right : _left;
        const double first = d_interval_d_inclusive_lower(walk);
        const double low   = (first > d_interval_d_inclusive_lower(other))
                              ? first
                              : d_interval_d_inclusive_lower(other);
        const double high  = (d_interval_d_last(walk) <
                           d_interval_d_inclusive_upper(other))
                              ? d_interval_d_last(walk)
                              : d_interval_d_inclusive_upper(other);
        const d_math_umax total = d_interval_d_count(walk);
        d_math_umax index = d_internal_interval_d_snap(first, walk.step, low);

        // the first member at or above the common part's start
        if (d_internal_interval_d_member(first, walk.step, index) < low)
        {
            ++index;
        }

        // every member within the common part, until one is shared
        while ( (index < total) &&
                (d_internal_interval_d_member(first, walk.step, index) <=
                 high) )
        {
            if (d_interval_d_contains(
                    other,
                    d_internal_interval_d_member(first, walk.step, index)))
            {
                return true;
            }

            ++index;
        }

        return false;
    }
}

// 2.7    Normalization
//------------------------------------------------------------------------------
// as for the integer families, the terms in long double.

D_MATH_FN struct d_math_ratio
d_internal_interval_d_terms(
    double _origin,
    double _end,
    double _value
)
{
    struct d_math_ratio result = { 0.0L, 1.0L };

    // a degenerate span maps everything to 0
    if (_end == _origin)
    {
        return result;
    }

    result.numerator   = (long double)_value - (long double)_origin;
    result.denominator = (long double)_end   - (long double)_origin;

    return result;
}

D_MATH_FN struct d_math_ratio
d_interval_d_normalize_terms(
    struct d_interval_d _interval,
    double                   _value
)
{
    return d_internal_interval_d_terms(_interval.lower,
                                         _interval.upper,
                                         _value);
}

D_MATH_FN struct d_math_ratio
d_interval_d_normalize_effective_terms(
    struct d_interval_d _interval,
    double                   _value
)
{
    return d_internal_interval_d_terms(
               d_interval_d_inclusive_lower(_interval),
               d_interval_d_inclusive_upper(_interval),
               _value);
}

D_MATH_FN struct d_math_ratio
d_interval_d_normalize_discrete_terms(
    struct d_interval_d _interval,
    double                   _value
)
{
    // a continuous interval normalizes over its inclusive bounds
    if (!(_interval.step > (double)0))
    {
        return d_interval_d_normalize_effective_terms(_interval, _value);
    }

    struct d_math_ratio result = { 0.0L, 1.0L };
    const d_math_umax   count  = d_interval_d_count(_interval);
    const double           low    =
        d_interval_d_inclusive_lower(_interval);

    // one member or none: nothing to spread over
    if (count <= 1u)
    {
        return result;
    }

    // at or above the first member: the index of the member at or below;
    // below it, the quotient truncated toward zero, a zero kept +0
    if (_value >= low)
    {
        result.numerator = (long double)d_internal_interval_d_snap(
                               low,
                               _interval.step,
                               _value);
    }
    else
    {
        const long double back = ((long double)low - (long double)_value) /
                                 (long double)_interval.step;
        const d_math_umax whole =
            (back < (long double)D_MATH_UMAX_MAX) ? (d_math_umax)back
                                                  : D_MATH_UMAX_MAX;

        result.numerator = (whole == 0u) ? 0.0L : -(long double)whole;
    }

    result.denominator = (long double)(count - 1u);

    return result;
}

// 2.8    Formatting
//------------------------------------------------------------------------------

// d_internal_interval_d_put_value
//   writes _value at _position as the fewest significant digits (from
// DBL_DIG) that read back as the same value -- 0.1, not 0.10000000000000001 --
// and returns the position after it.
D_MATH_FN_RT size_t
d_internal_interval_d_put_value(
    char*  _buffer,
    size_t _capacity,
    size_t _position,
    double    _value
)
{
    char   text[64] = { 0 };
    int    digits   = DBL_DIG;
    size_t i        = 0u;
    size_t position = _position;

    // the shortest round trip; NaN never compares equal, and keeps the last
    for (digits = DBL_DIG; digits <= (DBL_DIG + 3); ++digits)
    {
        double back = (double)0;

        (void)sprintf(text, "%.*g", digits, (double)_value);

        if ( (sscanf(text, "%lg", &back) == 1) &&
             (back == _value) )
        {
            break;
        }
    }

    for (i = 0u; text[i] != '\0'; ++i)
    {
        position = d_internal_interval_put_char(_buffer,
                                                _capacity,
                                                position,
                                                text[i]);
    }

    return position;
}

/**
 * @brief Writes an interval of the double family as text, as
 *        d_interval_imax_format does, each value in the fewest digits that
 *        read back as it.
 *
 * @param[out] _buffer    where the text goes; may be NULL if _capacity is 0.
 * @param[in]  _capacity  the bytes _buffer holds.
 * @param[in]  _interval  the interval to write.
 * @return the length of the whole text, not counting the terminator.
 */
D_MATH_FN_RT size_t
d_interval_d_format(
    char*                 _buffer,
    size_t                _capacity,
    struct d_interval_d _interval
)
{
    const char left  =
        ((_interval.bounds & D_INTERVAL_LEFT_OPEN) != 0u) ? '(' : '[';
    const char right =
        ((_interval.bounds & D_INTERVAL_RIGHT_OPEN) != 0u) ? ')' : ']';
    size_t     at    = d_internal_interval_put_char(_buffer,
                                                    _capacity,
                                                    0u,
                                                    left);

    at = d_internal_interval_d_put_value(_buffer,
                                           _capacity,
                                           at,
                                           _interval.lower);

    // a discrete interval shows its stride between its bounds
    if (_interval.step > (double)0)
    {
        at = d_internal_interval_put_char(_buffer, _capacity, at, ':');
        at = d_internal_interval_d_put_value(_buffer,
                                               _capacity,
                                               at,
                                               _interval.step);
        at = d_internal_interval_put_char(_buffer, _capacity, at, ':');
    }
    else
    {
        at = d_internal_interval_put_char(_buffer, _capacity, at, ',');
        at = d_internal_interval_put_char(_buffer, _capacity, at, ' ');
    }

    at = d_internal_interval_d_put_value(_buffer,
                                           _capacity,
                                           at,
                                           _interval.upper);
    at = d_internal_interval_put_char(_buffer, _capacity, at, right);

    return d_internal_interval_finish(_buffer, _capacity, at);
}

//==============================================================================
// 3.  THE LONG DOUBLE FAMILY (_ld)
//==============================================================================


// 3.1    Layout
//------------------------------------------------------------------------------
// 3.1.1
// d_interval_ld
//   struct: an interval over long double.
struct d_interval_ld
{
    long double      lower;   // the lower bound
    long double      upper;   // the upper bound
    long double      step;    // the stride: 0 continuous, > 0 discrete
    unsigned bounds;  // D_INTERVAL_LEFT_OPEN | D_INTERVAL_RIGHT_OPEN
};

// 3.2    Internal helpers
//------------------------------------------------------------------------------

// d_internal_interval_ld_member
//   a discrete interval's member _index steps past _first: _first + _index *
// _step, the product formed apart so no compiler fuses it into the sum.
D_MATH_FN long double
d_internal_interval_ld_member(
    long double         _first,
    long double         _step,
    d_math_umax _index
)
{
    // the first member is the first, whatever the step (0 * inf is NaN)
    if (_index == 0u)
    {
        return _first;
    }

    {
        const long double offset = (long double)_index * _step;

        return (_first + offset);
    }
}

// d_internal_interval_ld_snap_finite
//   the index of the last member at or below a finite _value, for _value >=
// _first and finite _first and _step: the rounded quotient, settled by
// testing the members beside it.
D_MATH_FN d_math_umax
d_internal_interval_ld_snap_finite(
    long double _first,
    long double _step,
    long double _value
)
{
    const long double   quotient = (_value - _first) / _step;
    d_math_umax index    = 0u;
    int         tries    = 0;

    // the quotient as an index: saturated, or truncated
    if (!(quotient < (long double)D_MATH_UMAX_MAX))
    {
        index = D_MATH_UMAX_MAX;
    }
    else if (quotient > (long double)0)
    {
        index = (d_math_umax)quotient;
    }

    // the quotient was rounded: down while the member passes _value...
    for (tries = 0;
         ( (tries < 4) &&
           (index > 0u) &&
           (d_internal_interval_ld_member(_first, _step, index) > _value) );
         ++tries)
    {
        --index;
    }

    // ...and up while the next one does not
    for (tries = 0;
         ( (tries < 4) &&
           (index < D_MATH_UMAX_MAX) &&
           (d_internal_interval_ld_member(_first, _step, index + 1u) <=
            _value) );
         ++tries)
    {
        ++index;
    }

    return index;
}

// d_internal_interval_ld_snap
//   the index of the last member at or below _value, for _value >= _first.
// An infinite first member or step leaves one member, the first; members
// past the largest finite value round to +inf, one member, after the last
// finite one.
D_MATH_FN d_math_umax
d_internal_interval_ld_snap(
    long double _first,
    long double _step,
    long double _value
)
{
    // an infinite first member or step: the first is the only member
    if ( (_first > LDBL_MAX) ||
         (_first < -LDBL_MAX) ||
         (_step > LDBL_MAX) )
    {
        return 0u;
    }

    // +inf: the member after the last finite one
    if (_value > LDBL_MAX)
    {
        const d_math_umax last =
            d_internal_interval_ld_snap_finite(_first, _step, LDBL_MAX);

        return (last == D_MATH_UMAX_MAX) ? last : (last + 1u);
    }

    return d_internal_interval_ld_snap_finite(_first, _step, _value);
}

// d_internal_interval_ld_is_void
//   true when the interval is empty on the real line: reversed or NaN
// bounds, or one point with either bound open.
D_MATH_FN bool
d_internal_interval_ld_is_void(
    struct d_interval_ld _interval
)
{
    return ( (!(_interval.lower <= _interval.upper)) ||
             ( (_interval.lower == _interval.upper) &&
               (_interval.bounds != D_INTERVAL_CLOSED) ) );
}

// 3.3    Construction, validity and bounds
//------------------------------------------------------------------------------
// as for the integer families; an open bound moves to the neighbouring
// value (float_order.h's next_up and next_down), so inclusive_lower is the
// least value the interval holds and inclusive_upper the greatest.

D_MATH_FN struct d_interval_ld
d_interval_ld_make(
    long double      _lower,
    long double      _upper,
    unsigned _bounds,
    long double      _step
)
{
    struct d_interval_ld result = { (long double)0,
                                     (long double)0,
                                     (long double)0,
                                     0u };

    result.lower  = _lower;
    result.upper  = _upper;
    result.step   = _step;
    result.bounds = _bounds;

    return result;
}

D_MATH_FN bool
d_interval_ld_is_valid(
    struct d_interval_ld _interval
)
{
    return ( (_interval.lower <= _interval.upper) &&
             (_interval.step >= (long double)0) );
}

D_MATH_FN bool
d_interval_ld_is_discrete(
    struct d_interval_ld _interval
)
{
    return (_interval.step > (long double)0);
}

D_MATH_FN long double
d_interval_ld_inclusive_lower(
    struct d_interval_ld _interval
)
{
    return ((_interval.bounds & D_INTERVAL_LEFT_OPEN) != 0u)
               ? d_math_ld_next_up(_interval.lower)
               : _interval.lower;
}

D_MATH_FN long double
d_interval_ld_inclusive_upper(
    struct d_interval_ld _interval
)
{
    return ((_interval.bounds & D_INTERVAL_RIGHT_OPEN) != 0u)
               ? d_math_ld_next_down(_interval.upper)
               : _interval.upper;
}

D_MATH_FN bool
d_interval_ld_is_empty(
    struct d_interval_ld _interval
)
{
    // an open bound at an infinity excludes it, and nothing lies beyond it
    if ( ( ((_interval.bounds & D_INTERVAL_LEFT_OPEN) != 0u) &&
           (_interval.lower > LDBL_MAX) ) ||
         ( ((_interval.bounds & D_INTERVAL_RIGHT_OPEN) != 0u) &&
           (_interval.upper < -LDBL_MAX) ) )
    {
        return true;
    }

    return !( d_interval_ld_inclusive_lower(_interval) <=
              d_interval_ld_inclusive_upper(_interval) );
}

// 3.4    Size and access
//------------------------------------------------------------------------------
// A continuous interval's members are every value of the type within its
// bounds, so count is their number (float_order.h's steps, plus one), at
// the value that many steps up, and index_of the steps to a value. A
// discrete interval's members are first + k * step, each product formed
// apart. Both counts saturate at D_MATH_UMAX_MAX.

D_MATH_FN long double
d_interval_ld_first(
    struct d_interval_ld _interval
)
{
    return d_interval_ld_inclusive_lower(_interval);
}

D_MATH_FN long double
d_interval_ld_last(
    struct d_interval_ld _interval
)
{
    const long double low  = d_interval_ld_inclusive_lower(_interval);
    const long double high = d_interval_ld_inclusive_upper(_interval);

    // a discrete interval ends on its last whole step
    if ( (_interval.step > (long double)0) &&
         (low <= high) )
    {
        return d_internal_interval_ld_member(
                   low,
                   _interval.step,
                   d_internal_interval_ld_snap(low, _interval.step, high));
    }

    return high;
}

D_MATH_FN d_math_umax
d_interval_ld_count(
    struct d_interval_ld _interval
)
{
    const long double low  = d_interval_ld_inclusive_lower(_interval);
    const long double high = d_interval_ld_inclusive_upper(_interval);
    d_math_umax steps = 0u;

    // an empty interval counts nothing
    if (d_interval_ld_is_empty(_interval))
    {
        return 0u;
    }

    steps = (_interval.step > (long double)0)
                ? d_internal_interval_ld_snap(low, _interval.step, high)
                : d_math_ld_steps(low, high);

    return (steps == D_MATH_UMAX_MAX) ? steps : (steps + 1u);
}

D_MATH_FN long double
d_interval_ld_at(
    struct d_interval_ld _interval,
    d_math_umax           _index
)
{
    const long double low = d_interval_ld_inclusive_lower(_interval);

    // a discrete member, or the value _index steps up
    if (_interval.step > (long double)0)
    {
        return d_internal_interval_ld_member(low, _interval.step, _index);
    }

    return d_math_ld_advance(low, _index);
}

// 3.5    Membership and clamping
//------------------------------------------------------------------------------
// contains honours both bounds exactly and, for a discrete interval, the
// members; contains_in_range the bounds alone; NaN is in no interval. clamp
// moves a value to the nearest member toward the interval -- the
// neighbouring value inside an open bound -- and, inside a discrete one,
// down to a member; clamp_nearest to the nearer member, a tie going down.
// NaN clamps to NaN.

D_MATH_FN bool
d_interval_ld_contains_in_range(
    struct d_interval_ld _interval,
    long double                   _value
)
{
    const bool left_ok =
        ((_interval.bounds & D_INTERVAL_LEFT_OPEN) != 0u)
            ? (_value > _interval.lower)
            : (_value >= _interval.lower);
    const bool right_ok =
        ((_interval.bounds & D_INTERVAL_RIGHT_OPEN) != 0u)
            ? (_value < _interval.upper)
            : (_value <= _interval.upper);

    return (left_ok && right_ok);
}

D_MATH_FN bool
d_interval_ld_contains(
    struct d_interval_ld _interval,
    long double                   _value
)
{
    // outside the bounds is outside the interval
    if (!d_interval_ld_contains_in_range(_interval, _value))
    {
        return false;
    }

    // a discrete member is one of the computed members
    if (_interval.step > (long double)0)
    {
        const long double low = d_interval_ld_inclusive_lower(_interval);

        return ( d_internal_interval_ld_member(
                     low,
                     _interval.step,
                     d_internal_interval_ld_snap(low,
                                                  _interval.step,
                                                  _value)) == _value );
    }

    return true;
}

D_MATH_FN long double
d_interval_ld_clamp(
    struct d_interval_ld _interval,
    long double                   _value
)
{
    const long double low  = d_interval_ld_inclusive_lower(_interval);
    const long double high = d_interval_ld_inclusive_upper(_interval);

    // NaN has no nearer member
    if (_value != _value)
    {
        return _value;
    }

    // below the interval: its first value
    if (_value < low)
    {
        return low;
    }

    // above the interval: its last value
    if (_value > high)
    {
        return d_interval_ld_last(_interval);
    }

    // inside a discrete interval: down to a member
    if (_interval.step > (long double)0)
    {
        return d_internal_interval_ld_member(
                   low,
                   _interval.step,
                   d_internal_interval_ld_snap(low, _interval.step, _value));
    }

    return _value;
}

D_MATH_FN long double
d_interval_ld_clamp_nearest(
    struct d_interval_ld _interval,
    long double                   _value
)
{
    // NaN, a continuous interval, and anything outside one: as clamp
    if ( (_value != _value) ||
         (!(_interval.step > (long double)0)) ||
         (!d_interval_ld_contains_in_range(_interval, _value)) )
    {
        return d_interval_ld_clamp(_interval, _value);
    }

    const long double low = d_interval_ld_inclusive_lower(_interval);
    const long double top = d_interval_ld_last(_interval);

    // past the last member: the last member
    if ( (_value < low) ||
         (_value >= top) )
    {
        return d_interval_ld_clamp(_interval, _value);
    }

    const d_math_umax index =
        d_internal_interval_ld_snap(low, _interval.step, _value);
    const long double below =
        d_internal_interval_ld_member(low, _interval.step, index);
    const long double above =
        d_internal_interval_ld_member(low, _interval.step, index + 1u);

    // the member above is nearer, and still inside the interval
    if ( (above <= top) &&
         ((_value - below) > (above - _value)) )
    {
        return above;
    }

    return below;
}

D_MATH_FN d_math_umax
d_interval_ld_index_of(
    struct d_interval_ld _interval,
    long double                   _value
)
{
    // a value that is not a member has the index one past the last
    if (!d_interval_ld_contains(_interval, _value))
    {
        return d_interval_ld_count(_interval);
    }

    {
        const long double low = d_interval_ld_inclusive_lower(_interval);

        return (_interval.step > (long double)0)
                   ? d_internal_interval_ld_snap(low, _interval.step, _value)
                   : d_math_ld_steps(low, _value);
    }
}

// 3.6    Relations
//------------------------------------------------------------------------------
// as for the integer families: overlaps compares the inclusive ranges,
// ignoring strides; overlaps_continuous the real line; intersects asks for
// a shared member -- for two discrete intervals by testing the members of
// the sparser one within the ranges' common part, so its cost is the count
// of those.

D_MATH_FN bool
d_interval_ld_overlaps(
    struct d_interval_ld _left,
    struct d_interval_ld _right
)
{
    // an empty interval shares a position with nothing
    if ( (d_interval_ld_is_empty(_left)) ||
         (d_interval_ld_is_empty(_right)) )
    {
        return false;
    }

    return !( (d_interval_ld_inclusive_upper(_left) <
               d_interval_ld_inclusive_lower(_right)) ||
              (d_interval_ld_inclusive_lower(_left) >
               d_interval_ld_inclusive_upper(_right)) );
}

D_MATH_FN bool
d_interval_ld_overlaps_continuous(
    struct d_interval_ld _left,
    struct d_interval_ld _right
)
{
    // an interval empty on the real line meets nothing
    if ( (d_internal_interval_ld_is_void(_left)) ||
         (d_internal_interval_ld_is_void(_right)) )
    {
        return false;
    }

    const bool left_meets_closed =
        ( ((_left.bounds  & D_INTERVAL_LEFT_OPEN)  == 0u) &&
          ((_right.bounds & D_INTERVAL_RIGHT_OPEN) == 0u) );
    const bool right_meets_closed =
        ( ((_left.bounds  & D_INTERVAL_RIGHT_OPEN) == 0u) &&
          ((_right.bounds & D_INTERVAL_LEFT_OPEN)  == 0u) );
    const bool left_ok =
        left_meets_closed ? (_left.lower <= _right.upper)
                          : (_left.lower <  _right.upper);
    const bool right_ok =
        right_meets_closed ? (_right.lower <= _left.upper)
                           : (_right.lower <  _left.upper);

    return (left_ok && right_ok);
}

D_MATH_FN bool
d_interval_ld_intersects(
    struct d_interval_ld _left,
    struct d_interval_ld _right
)
{
    // two continuous intervals share a value where their ranges meet
    if ( (!(_left.step > (long double)0)) &&
         (!(_right.step > (long double)0)) )
    {
        return d_interval_ld_overlaps(_left, _right);
    }

    // an empty interval has no member to share
    if ( (d_interval_ld_is_empty(_left)) ||
         (d_interval_ld_is_empty(_right)) )
    {
        return false;
    }

    {
        // walk the sparser discrete one; test each member in the other
        const bool                  left_walks =
            ( (_left.step > (long double)0) &&
              ( (!(_right.step > (long double)0)) ||
                (_left.step >= _right.step) ) );
        const struct d_interval_ld walk  = left_walks ? _left  : _right;
        const struct d_interval_ld other = left_walks ? _right : _left;
        const long double first = d_interval_ld_inclusive_lower(walk);
        const long double low   = (first > d_interval_ld_inclusive_lower(other))
                              ? first
                              : d_interval_ld_inclusive_lower(other);
        const long double high  = (d_interval_ld_last(walk) <
                           d_interval_ld_inclusive_upper(other))
                              ? d_interval_ld_last(walk)
                              : d_interval_ld_inclusive_upper(other);
        const d_math_umax total = d_interval_ld_count(walk);
        d_math_umax index = d_internal_interval_ld_snap(first, walk.step, low);

        // the first member at or above the common part's start
        if (d_internal_interval_ld_member(first, walk.step, index) < low)
        {
            ++index;
        }

        // every member within the common part, until one is shared
        while ( (index < total) &&
                (d_internal_interval_ld_member(first, walk.step, index) <=
                 high) )
        {
            if (d_interval_ld_contains(
                    other,
                    d_internal_interval_ld_member(first, walk.step, index)))
            {
                return true;
            }

            ++index;
        }

        return false;
    }
}

// 3.7    Normalization
//------------------------------------------------------------------------------
// as for the integer families, the terms in long double.

D_MATH_FN struct d_math_ratio
d_internal_interval_ld_terms(
    long double _origin,
    long double _end,
    long double _value
)
{
    struct d_math_ratio result = { 0.0L, 1.0L };

    // a degenerate span maps everything to 0
    if (_end == _origin)
    {
        return result;
    }

    result.numerator   = (long double)_value - (long double)_origin;
    result.denominator = (long double)_end   - (long double)_origin;

    return result;
}

D_MATH_FN struct d_math_ratio
d_interval_ld_normalize_terms(
    struct d_interval_ld _interval,
    long double                   _value
)
{
    return d_internal_interval_ld_terms(_interval.lower,
                                         _interval.upper,
                                         _value);
}

D_MATH_FN struct d_math_ratio
d_interval_ld_normalize_effective_terms(
    struct d_interval_ld _interval,
    long double                   _value
)
{
    return d_internal_interval_ld_terms(
               d_interval_ld_inclusive_lower(_interval),
               d_interval_ld_inclusive_upper(_interval),
               _value);
}

D_MATH_FN struct d_math_ratio
d_interval_ld_normalize_discrete_terms(
    struct d_interval_ld _interval,
    long double                   _value
)
{
    // a continuous interval normalizes over its inclusive bounds
    if (!(_interval.step > (long double)0))
    {
        return d_interval_ld_normalize_effective_terms(_interval, _value);
    }

    struct d_math_ratio result = { 0.0L, 1.0L };
    const d_math_umax   count  = d_interval_ld_count(_interval);
    const long double           low    =
        d_interval_ld_inclusive_lower(_interval);

    // one member or none: nothing to spread over
    if (count <= 1u)
    {
        return result;
    }

    // at or above the first member: the index of the member at or below;
    // below it, the quotient truncated toward zero, a zero kept +0
    if (_value >= low)
    {
        result.numerator = (long double)d_internal_interval_ld_snap(
                               low,
                               _interval.step,
                               _value);
    }
    else
    {
        const long double back = ((long double)low - (long double)_value) /
                                 (long double)_interval.step;
        const d_math_umax whole =
            (back < (long double)D_MATH_UMAX_MAX) ? (d_math_umax)back
                                                  : D_MATH_UMAX_MAX;

        result.numerator = (whole == 0u) ? 0.0L : -(long double)whole;
    }

    result.denominator = (long double)(count - 1u);

    return result;
}

// 3.8    Formatting
//------------------------------------------------------------------------------

// d_internal_interval_ld_put_value
//   writes _value at _position as the fewest significant digits (from
// LDBL_DIG) that read back as the same value -- 0.1, not 0.10000000000000001 --
// and returns the position after it.
D_MATH_FN_RT size_t
d_internal_interval_ld_put_value(
    char*  _buffer,
    size_t _capacity,
    size_t _position,
    long double    _value
)
{
    char   text[64] = { 0 };
    int    digits   = LDBL_DIG;
    size_t i        = 0u;
    size_t position = _position;

    // the shortest round trip; NaN never compares equal, and keeps the last
    for (digits = LDBL_DIG; digits <= (LDBL_DIG + 3); ++digits)
    {
        long double back = (long double)0;

        (void)sprintf(text, "%.*Lg", digits, (long double)_value);

        if ( (sscanf(text, "%Lg", &back) == 1) &&
             (back == _value) )
        {
            break;
        }
    }

    for (i = 0u; text[i] != '\0'; ++i)
    {
        position = d_internal_interval_put_char(_buffer,
                                                _capacity,
                                                position,
                                                text[i]);
    }

    return position;
}

/**
 * @brief Writes an interval of the long double family as text, as
 *        d_interval_imax_format does, each value in the fewest digits that
 *        read back as it.
 *
 * @param[out] _buffer    where the text goes; may be NULL if _capacity is 0.
 * @param[in]  _capacity  the bytes _buffer holds.
 * @param[in]  _interval  the interval to write.
 * @return the length of the whole text, not counting the terminator.
 */
D_MATH_FN_RT size_t
d_interval_ld_format(
    char*                 _buffer,
    size_t                _capacity,
    struct d_interval_ld _interval
)
{
    const char left  =
        ((_interval.bounds & D_INTERVAL_LEFT_OPEN) != 0u) ? '(' : '[';
    const char right =
        ((_interval.bounds & D_INTERVAL_RIGHT_OPEN) != 0u) ? ')' : ']';
    size_t     at    = d_internal_interval_put_char(_buffer,
                                                    _capacity,
                                                    0u,
                                                    left);

    at = d_internal_interval_ld_put_value(_buffer,
                                           _capacity,
                                           at,
                                           _interval.lower);

    // a discrete interval shows its stride between its bounds
    if (_interval.step > (long double)0)
    {
        at = d_internal_interval_put_char(_buffer, _capacity, at, ':');
        at = d_internal_interval_ld_put_value(_buffer,
                                               _capacity,
                                               at,
                                               _interval.step);
        at = d_internal_interval_put_char(_buffer, _capacity, at, ':');
    }
    else
    {
        at = d_internal_interval_put_char(_buffer, _capacity, at, ',');
        at = d_internal_interval_put_char(_buffer, _capacity, at, ' ');
    }

    at = d_internal_interval_ld_put_value(_buffer,
                                           _capacity,
                                           at,
                                           _interval.upper);
    at = d_internal_interval_put_char(_buffer, _capacity, at, right);

    return d_internal_interval_finish(_buffer, _capacity, at);
}


#ifdef __cplusplus

//==============================================================================
// 4.  ONE NAME FOR EVERY FAMILY (C++)
//==============================================================================
// C++ only: the kernels above under one name each, chosen by argument type,
// so a C++ template serves float, double and long double alike.


D_MATH_FN struct d_interval_f
d_interval_make(
    float    _lower,
    float    _upper,
    unsigned _bounds,
    float    _step
)
{
    return d_interval_f_make(_lower, _upper, _bounds, _step);
}

D_MATH_FN bool
d_interval_is_valid(
    struct d_interval_f _interval
)
{
    return d_interval_f_is_valid(_interval);
}

D_MATH_FN bool
d_interval_is_discrete(
    struct d_interval_f _interval
)
{
    return d_interval_f_is_discrete(_interval);
}

D_MATH_FN bool
d_interval_is_empty(
    struct d_interval_f _interval
)
{
    return d_interval_f_is_empty(_interval);
}

D_MATH_FN float
d_interval_inclusive_lower(
    struct d_interval_f _interval
)
{
    return d_interval_f_inclusive_lower(_interval);
}

D_MATH_FN float
d_interval_inclusive_upper(
    struct d_interval_f _interval
)
{
    return d_interval_f_inclusive_upper(_interval);
}

D_MATH_FN float
d_interval_first(
    struct d_interval_f _interval
)
{
    return d_interval_f_first(_interval);
}

D_MATH_FN float
d_interval_last(
    struct d_interval_f _interval
)
{
    return d_interval_f_last(_interval);
}

D_MATH_FN d_math_umax
d_interval_count(
    struct d_interval_f _interval
)
{
    return d_interval_f_count(_interval);
}

D_MATH_FN float
d_interval_at(
    struct d_interval_f _interval,
    d_math_umax         _index
)
{
    return d_interval_f_at(_interval, _index);
}

D_MATH_FN bool
d_interval_contains_in_range(
    struct d_interval_f _interval,
    float               _value
)
{
    return d_interval_f_contains_in_range(_interval, _value);
}

D_MATH_FN bool
d_interval_contains(
    struct d_interval_f _interval,
    float               _value
)
{
    return d_interval_f_contains(_interval, _value);
}

D_MATH_FN float
d_interval_clamp(
    struct d_interval_f _interval,
    float               _value
)
{
    return d_interval_f_clamp(_interval, _value);
}

D_MATH_FN float
d_interval_clamp_nearest(
    struct d_interval_f _interval,
    float               _value
)
{
    return d_interval_f_clamp_nearest(_interval, _value);
}

D_MATH_FN d_math_umax
d_interval_index_of(
    struct d_interval_f _interval,
    float               _value
)
{
    return d_interval_f_index_of(_interval, _value);
}

D_MATH_FN bool
d_interval_overlaps(
    struct d_interval_f _left,
    struct d_interval_f _right
)
{
    return d_interval_f_overlaps(_left, _right);
}

D_MATH_FN bool
d_interval_overlaps_continuous(
    struct d_interval_f _left,
    struct d_interval_f _right
)
{
    return d_interval_f_overlaps_continuous(_left, _right);
}

D_MATH_FN bool
d_interval_intersects(
    struct d_interval_f _left,
    struct d_interval_f _right
)
{
    return d_interval_f_intersects(_left, _right);
}

D_MATH_FN struct d_math_ratio
d_interval_normalize_terms(
    struct d_interval_f _interval,
    float               _value
)
{
    return d_interval_f_normalize_terms(_interval, _value);
}

D_MATH_FN struct d_math_ratio
d_interval_normalize_effective_terms(
    struct d_interval_f _interval,
    float               _value
)
{
    return d_interval_f_normalize_effective_terms(_interval, _value);
}

D_MATH_FN struct d_math_ratio
d_interval_normalize_discrete_terms(
    struct d_interval_f _interval,
    float               _value
)
{
    return d_interval_f_normalize_discrete_terms(_interval, _value);
}

D_MATH_FN_RT size_t
d_interval_format(
    char*               _buffer,
    size_t              _capacity,
    struct d_interval_f _interval
)
{
    return d_interval_f_format(_buffer, _capacity, _interval);
}

D_MATH_FN struct d_interval_d
d_interval_make(
    double   _lower,
    double   _upper,
    unsigned _bounds,
    double   _step
)
{
    return d_interval_d_make(_lower, _upper, _bounds, _step);
}

D_MATH_FN bool
d_interval_is_valid(
    struct d_interval_d _interval
)
{
    return d_interval_d_is_valid(_interval);
}

D_MATH_FN bool
d_interval_is_discrete(
    struct d_interval_d _interval
)
{
    return d_interval_d_is_discrete(_interval);
}

D_MATH_FN bool
d_interval_is_empty(
    struct d_interval_d _interval
)
{
    return d_interval_d_is_empty(_interval);
}

D_MATH_FN double
d_interval_inclusive_lower(
    struct d_interval_d _interval
)
{
    return d_interval_d_inclusive_lower(_interval);
}

D_MATH_FN double
d_interval_inclusive_upper(
    struct d_interval_d _interval
)
{
    return d_interval_d_inclusive_upper(_interval);
}

D_MATH_FN double
d_interval_first(
    struct d_interval_d _interval
)
{
    return d_interval_d_first(_interval);
}

D_MATH_FN double
d_interval_last(
    struct d_interval_d _interval
)
{
    return d_interval_d_last(_interval);
}

D_MATH_FN d_math_umax
d_interval_count(
    struct d_interval_d _interval
)
{
    return d_interval_d_count(_interval);
}

D_MATH_FN double
d_interval_at(
    struct d_interval_d _interval,
    d_math_umax         _index
)
{
    return d_interval_d_at(_interval, _index);
}

D_MATH_FN bool
d_interval_contains_in_range(
    struct d_interval_d _interval,
    double              _value
)
{
    return d_interval_d_contains_in_range(_interval, _value);
}

D_MATH_FN bool
d_interval_contains(
    struct d_interval_d _interval,
    double              _value
)
{
    return d_interval_d_contains(_interval, _value);
}

D_MATH_FN double
d_interval_clamp(
    struct d_interval_d _interval,
    double              _value
)
{
    return d_interval_d_clamp(_interval, _value);
}

D_MATH_FN double
d_interval_clamp_nearest(
    struct d_interval_d _interval,
    double              _value
)
{
    return d_interval_d_clamp_nearest(_interval, _value);
}

D_MATH_FN d_math_umax
d_interval_index_of(
    struct d_interval_d _interval,
    double              _value
)
{
    return d_interval_d_index_of(_interval, _value);
}

D_MATH_FN bool
d_interval_overlaps(
    struct d_interval_d _left,
    struct d_interval_d _right
)
{
    return d_interval_d_overlaps(_left, _right);
}

D_MATH_FN bool
d_interval_overlaps_continuous(
    struct d_interval_d _left,
    struct d_interval_d _right
)
{
    return d_interval_d_overlaps_continuous(_left, _right);
}

D_MATH_FN bool
d_interval_intersects(
    struct d_interval_d _left,
    struct d_interval_d _right
)
{
    return d_interval_d_intersects(_left, _right);
}

D_MATH_FN struct d_math_ratio
d_interval_normalize_terms(
    struct d_interval_d _interval,
    double              _value
)
{
    return d_interval_d_normalize_terms(_interval, _value);
}

D_MATH_FN struct d_math_ratio
d_interval_normalize_effective_terms(
    struct d_interval_d _interval,
    double              _value
)
{
    return d_interval_d_normalize_effective_terms(_interval, _value);
}

D_MATH_FN struct d_math_ratio
d_interval_normalize_discrete_terms(
    struct d_interval_d _interval,
    double              _value
)
{
    return d_interval_d_normalize_discrete_terms(_interval, _value);
}

D_MATH_FN_RT size_t
d_interval_format(
    char*               _buffer,
    size_t              _capacity,
    struct d_interval_d _interval
)
{
    return d_interval_d_format(_buffer, _capacity, _interval);
}

D_MATH_FN struct d_interval_ld
d_interval_make(
    long double _lower,
    long double _upper,
    unsigned    _bounds,
    long double _step
)
{
    return d_interval_ld_make(_lower, _upper, _bounds, _step);
}

D_MATH_FN bool
d_interval_is_valid(
    struct d_interval_ld _interval
)
{
    return d_interval_ld_is_valid(_interval);
}

D_MATH_FN bool
d_interval_is_discrete(
    struct d_interval_ld _interval
)
{
    return d_interval_ld_is_discrete(_interval);
}

D_MATH_FN bool
d_interval_is_empty(
    struct d_interval_ld _interval
)
{
    return d_interval_ld_is_empty(_interval);
}

D_MATH_FN long double
d_interval_inclusive_lower(
    struct d_interval_ld _interval
)
{
    return d_interval_ld_inclusive_lower(_interval);
}

D_MATH_FN long double
d_interval_inclusive_upper(
    struct d_interval_ld _interval
)
{
    return d_interval_ld_inclusive_upper(_interval);
}

D_MATH_FN long double
d_interval_first(
    struct d_interval_ld _interval
)
{
    return d_interval_ld_first(_interval);
}

D_MATH_FN long double
d_interval_last(
    struct d_interval_ld _interval
)
{
    return d_interval_ld_last(_interval);
}

D_MATH_FN d_math_umax
d_interval_count(
    struct d_interval_ld _interval
)
{
    return d_interval_ld_count(_interval);
}

D_MATH_FN long double
d_interval_at(
    struct d_interval_ld _interval,
    d_math_umax          _index
)
{
    return d_interval_ld_at(_interval, _index);
}

D_MATH_FN bool
d_interval_contains_in_range(
    struct d_interval_ld _interval,
    long double          _value
)
{
    return d_interval_ld_contains_in_range(_interval, _value);
}

D_MATH_FN bool
d_interval_contains(
    struct d_interval_ld _interval,
    long double          _value
)
{
    return d_interval_ld_contains(_interval, _value);
}

D_MATH_FN long double
d_interval_clamp(
    struct d_interval_ld _interval,
    long double          _value
)
{
    return d_interval_ld_clamp(_interval, _value);
}

D_MATH_FN long double
d_interval_clamp_nearest(
    struct d_interval_ld _interval,
    long double          _value
)
{
    return d_interval_ld_clamp_nearest(_interval, _value);
}

D_MATH_FN d_math_umax
d_interval_index_of(
    struct d_interval_ld _interval,
    long double          _value
)
{
    return d_interval_ld_index_of(_interval, _value);
}

D_MATH_FN bool
d_interval_overlaps(
    struct d_interval_ld _left,
    struct d_interval_ld _right
)
{
    return d_interval_ld_overlaps(_left, _right);
}

D_MATH_FN bool
d_interval_overlaps_continuous(
    struct d_interval_ld _left,
    struct d_interval_ld _right
)
{
    return d_interval_ld_overlaps_continuous(_left, _right);
}

D_MATH_FN bool
d_interval_intersects(
    struct d_interval_ld _left,
    struct d_interval_ld _right
)
{
    return d_interval_ld_intersects(_left, _right);
}

D_MATH_FN struct d_math_ratio
d_interval_normalize_terms(
    struct d_interval_ld _interval,
    long double          _value
)
{
    return d_interval_ld_normalize_terms(_interval, _value);
}

D_MATH_FN struct d_math_ratio
d_interval_normalize_effective_terms(
    struct d_interval_ld _interval,
    long double          _value
)
{
    return d_interval_ld_normalize_effective_terms(_interval, _value);
}

D_MATH_FN struct d_math_ratio
d_interval_normalize_discrete_terms(
    struct d_interval_ld _interval,
    long double          _value
)
{
    return d_interval_ld_normalize_discrete_terms(_interval, _value);
}

D_MATH_FN_RT size_t
d_interval_format(
    char*                _buffer,
    size_t               _capacity,
    struct d_interval_ld _interval
)
{
    return d_interval_ld_format(_buffer, _capacity, _interval);
}

#endif  // __cplusplus

#endif  // DJINTERP_C_MATH_INTERVAL_FLOAT_H
