/*******************************************************************************
* djinterp [c]                                                             mat.h
*
* Fixed-size matrices: the C core of math/linear_algebra/matrix.hpp, for
* float, double and long double.
*   GENERATED by tools/gen_c_math_float.py from one text for the three
* families: edit the generator, not this file.
*
*   A matrix here is a caller's row-major array of rows * cols entries, as
* BLAS takes them; the C++ face's storage is that array. What is entry-wise
* -- sums, scaling, norms, comparison -- is vec.h's over the entries; this
* header has what knows the shape. Every kernel is a constant expression
* from C++14.
*
*
* path:      /inc/djinterp/c/math/mat.h
* link(s):   TBA
* author(s): Samuel 'teer' Neal-Blim                         created: 2026.10.04
*                                                            revised: 2026.10.04
*******************************************************************************/

/*
TABLE OF CONTENTS
=================
1.  THE FLOAT FAMILY (_f)
    ---------------------
    1.  Construction
    2.  Rows, columns and the transpose
    3.  Products
    4.  Square-matrix queries
    5.  Determinant, inverse and cofactors
    6.  Rotations
2.  THE DOUBLE FAMILY (_d)
    ----------------------
    1.  Construction
    2.  Rows, columns and the transpose
    3.  Products
    4.  Square-matrix queries
    5.  Determinant, inverse and cofactors
    6.  Rotations
3.  THE LONG DOUBLE FAMILY (_ld)
    ----------------------------
    1.  Construction
    2.  Rows, columns and the transpose
    3.  Products
    4.  Square-matrix queries
    5.  Determinant, inverse and cofactors
    6.  Rotations
4.  ONE NAME FOR EVERY FAMILY (C++)
    -------------------------------
*/

#ifndef DJINTERP_C_MATH_MAT_H
#define DJINTERP_C_MATH_MAT_H 1

// std
#include <stddef.h>          // size_t
// djinterp
#include "./math_common.h"   // D_MATH_FN
#include "./vec.h"           // d_vec_*_fill, _dot: the entry-wise kernels

//==============================================================================
// 1.  THE FLOAT FAMILY (_f)
//==============================================================================
// Row-major: entry (i, j) of a matrix with _cols columns is [i * _cols + j].
// A product's output must not be either input; every other output may be.
// Entry-wise operations are vec.h's over the rows * cols entries.


// 1.1    Construction
//------------------------------------------------------------------------------

D_MATH_FN void
d_mat_f_identity(
    float*   _out,
    size_t _n
)
{
    size_t i = 0u;

    d_vec_f_fill(_out, _n * _n, (float)0);

    for (i = 0u; i < _n; ++i)
    {
        _out[(i * _n) + i] = (float)1;
    }

    return;
}

D_MATH_FN void
d_mat_f_diagonal(
    float*       _out,
    const float* _diagonal,
    size_t     _n
)
{
    size_t i = 0u;

    d_vec_f_fill(_out, _n * _n, (float)0);

    for (i = 0u; i < _n; ++i)
    {
        _out[(i * _n) + i] = _diagonal[i];
    }

    return;
}

// 1.2    Rows, columns and the transpose
//------------------------------------------------------------------------------

D_MATH_FN void
d_mat_f_row(
    float*       _out,
    const float* _a,
    size_t     _i,
    size_t     _cols
)
{
    size_t j = 0u;

    for (j = 0u; j < _cols; ++j)
    {
        _out[j] = _a[(_i * _cols) + j];
    }

    return;
}

D_MATH_FN void
d_mat_f_col(
    float*       _out,
    const float* _a,
    size_t     _j,
    size_t     _rows,
    size_t     _cols
)
{
    size_t i = 0u;

    for (i = 0u; i < _rows; ++i)
    {
        _out[i] = _a[(i * _cols) + _j];
    }

    return;
}

// d_mat_f_transpose
//   _out (_cols x _rows) is _a (_rows x _cols) transposed; _out must not be
// _a.
D_MATH_FN void
d_mat_f_transpose(
    float*       _out,
    const float* _a,
    size_t     _rows,
    size_t     _cols
)
{
    size_t i = 0u;

    for (i = 0u; i < _rows; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < _cols; ++j)
        {
            _out[(j * _rows) + i] = _a[(i * _cols) + j];
        }
    }

    return;
}

// 1.3    Products
//------------------------------------------------------------------------------
// Each entry is its dot product in order of k, each product rounded before it
// is summed. _out must not be an input.

// d_mat_f_multiply
//   _out (_rows x _cols) = _a (_rows x _inner) * _b (_inner x _cols).
D_MATH_FN void
d_mat_f_multiply(
    float*       _out,
    const float* _a,
    const float* _b,
    size_t     _rows,
    size_t     _inner,
    size_t     _cols
)
{
    size_t i = 0u;

    for (i = 0u; i < _rows; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < _cols; ++j)
        {
            float    acc = (float)0;
            size_t k   = 0u;

            for (k = 0u; k < _inner; ++k)
            {
                const float product = _a[(i * _inner) + k] * _b[(k * _cols) + j];

                acc += product;
            }

            _out[(i * _cols) + j] = acc;
        }
    }

    return;
}

// d_mat_f_multiply_vector
//   _out (_rows) = _a (_rows x _cols) * _v (_cols).
D_MATH_FN void
d_mat_f_multiply_vector(
    float*       _out,
    const float* _a,
    const float* _v,
    size_t     _rows,
    size_t     _cols
)
{
    size_t i = 0u;

    for (i = 0u; i < _rows; ++i)
    {
        _out[i] = d_vec_f_dot(_a + (i * _cols), _v, _cols);
    }

    return;
}

// d_mat_f_power
//   _out = _a^_exponent for an _n x _n matrix, the identity for 0: _a times
// the power below, as A^k = A * A^(k-1) composes, _exponent products.
// _scratch holds _n * _n entries; neither it nor _out may be _a.
D_MATH_FN void
d_mat_f_power(
    float*       _out,
    float*       _scratch,
    const float* _a,
    size_t     _n,
    size_t     _exponent
)
{
    size_t k = 0u;

    d_mat_f_identity(_out, _n);

    for (k = 0u; k < _exponent; ++k)
    {
        size_t i = 0u;

        d_mat_f_multiply(_scratch, _a, _out, _n, _n, _n);

        for (i = 0u; i < (_n * _n); ++i)
        {
            _out[i] = _scratch[i];
        }
    }

    return;
}

// 1.4    Square-matrix queries
//------------------------------------------------------------------------------
// trace sums the diagonal; is_symmetric and is_identity allow each entry
// _tolerance.

D_MATH_FN float
d_mat_f_trace(
    const float* _a,
    size_t     _n
)
{
    float    acc = (float)0;
    size_t i   = 0u;

    for (i = 0u; i < _n; ++i)
    {
        acc += _a[(i * _n) + i];
    }

    return acc;
}

D_MATH_FN bool
d_mat_f_is_symmetric(
    const float* _a,
    size_t     _n,
    float        _tolerance
)
{
    size_t i = 0u;

    for (i = 0u; i < _n; ++i)
    {
        size_t j = i + 1u;

        for (j = i + 1u; j < _n; ++j)
        {
            const float d = _a[(i * _n) + j] - _a[(j * _n) + i];

            if (((d < (float)0) ? -d : d) > _tolerance)
            {
                return false;
            }
        }
    }

    return true;
}

D_MATH_FN bool
d_mat_f_is_identity(
    const float* _a,
    size_t     _n,
    float        _tolerance
)
{
    size_t i = 0u;

    for (i = 0u; i < _n; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < _n; ++j)
        {
            const float d = _a[(i * _n) + j] - ((i == j) ? (float)1 : (float)0);

            if (((d < (float)0) ? -d : d) > _tolerance)
            {
                return false;
            }
        }
    }

    return true;
}

// 1.5    Determinant, inverse and cofactors
//------------------------------------------------------------------------------
// The square matrix's algebra, as linear_algebra/square.hpp computes it: the
// determinant by Bareiss's fraction-free elimination (exact for integers,
// and the subframework's algorithm), the inverse by Gauss-Jordan with
// partial pivoting. Each product is rounded before it is combined. Every
// kernel takes the scratch it needs from the caller.

// d_mat_f_determinant
//   the determinant of the _n x _n matrix _a; _scratch holds _n * _n
// entries. Bareiss: a row with a zero pivot is swapped for the first below
// it with a non-zero entry in the column, flipping the sign; none means 0.
D_MATH_FN float
d_mat_f_determinant(
    const float* _a,
    float*       _scratch,
    size_t     _n
)
{
    float    prev = (float)1;
    float    sign = (float)1;
    size_t k    = 0u;

    for (k = 0u; k < (_n * _n); ++k)
    {
        _scratch[k] = _a[k];
    }

    for (k = 0u; k < _n; ++k)
    {
        size_t i = 0u;

        // a zero pivot: swap in the first row below with a non-zero entry
        if (_scratch[(k * _n) + k] == (float)0)
        {
            size_t swap_row = k;
            size_t r        = k + 1u;
            size_t c        = 0u;

            for (r = k + 1u; r < _n; ++r)
            {
                if (_scratch[(r * _n) + k] != (float)0)
                {
                    swap_row = r;
                    break;
                }
            }

            // the column is zero below the diagonal: the matrix is singular
            if (swap_row == k)
            {
                return (float)0;
            }

            for (c = 0u; c < _n; ++c)
            {
                const float t = _scratch[(k * _n) + c];

                _scratch[(k * _n) + c]        = _scratch[(swap_row * _n) + c];
                _scratch[(swap_row * _n) + c] = t;
            }

            sign = -sign;
        }

        // the fraction-free update of the block below and right
        for (i = k + 1u; i < _n; ++i)
        {
            size_t j = k + 1u;

            for (j = k + 1u; j < _n; ++j)
            {
                const float keep  = _scratch[(k * _n) + k] *
                                  _scratch[(i * _n) + j];
                const float cross = _scratch[(i * _n) + k] *
                                  _scratch[(k * _n) + j];
                // one operation per statement: an x87 evaluates a whole
                // expression at 64 bits and rounds once, at the end
                const float diff  = keep - cross;

                _scratch[(i * _n) + j] = diff / prev;
            }
        }

        prev = _scratch[(k * _n) + k];
    }

    return sign * prev;
}

// d_mat_f_inverse
//   _out = the inverse of the _n x _n matrix _a, true; or, for a singular
// one, the zero matrix and false. _scratch holds _n * _n entries; neither it
// nor _out may be _a. Gauss-Jordan: the pivot is the first entry of largest
// magnitude at or below the diagonal.
D_MATH_FN bool
d_mat_f_inverse(
    float*       _out,
    float*       _scratch,
    const float* _a,
    size_t     _n
)
{
    size_t col = 0u;
    size_t k   = 0u;

    for (k = 0u; k < (_n * _n); ++k)
    {
        _scratch[k] = _a[k];
    }

    d_mat_f_identity(_out, _n);

    for (col = 0u; col < _n; ++col)
    {
        size_t    pivot = col;
        float       maxv  = (_scratch[(col * _n) + col] < (float)0)
                              ? -_scratch[(col * _n) + col]
                              : _scratch[(col * _n) + col];
        size_t    r     = col + 1u;
        size_t    c     = 0u;
        float       d     = (float)0;

        // the first entry of largest magnitude at or below the diagonal
        for (r = col + 1u; r < _n; ++r)
        {
            const float v = (_scratch[(r * _n) + col] < (float)0)
                              ? -_scratch[(r * _n) + col]
                              : _scratch[(r * _n) + col];

            if (v > maxv)
            {
                maxv  = v;
                pivot = r;
            }
        }

        // no pivot: singular
        if (_scratch[(pivot * _n) + col] == (float)0)
        {
            d_vec_f_fill(_out, _n * _n, (float)0);

            return false;
        }

        // the pivot row up into place, in both
        if (pivot != col)
        {
            for (c = 0u; c < _n; ++c)
            {
                const float ta = _scratch[(col * _n) + c];
                const float ti = _out[(col * _n) + c];

                _scratch[(col * _n) + c]   = _scratch[(pivot * _n) + c];
                _scratch[(pivot * _n) + c] = ta;
                _out[(col * _n) + c]       = _out[(pivot * _n) + c];
                _out[(pivot * _n) + c]     = ti;
            }
        }

        d = _scratch[(col * _n) + col];

        // the pivot row divided through
        for (c = 0u; c < _n; ++c)
        {
            _scratch[(col * _n) + c] = _scratch[(col * _n) + c] / d;
            _out[(col * _n) + c]     = _out[(col * _n) + c] / d;
        }

        // every other row cleared in the pivot's column
        for (r = 0u; r < _n; ++r)
        {
            if (r != col)
            {
                const float f = _scratch[(r * _n) + col];

                for (c = 0u; c < _n; ++c)
                {
                    const float fa = f * _scratch[(col * _n) + c];
                    const float fi = f * _out[(col * _n) + c];

                    _scratch[(r * _n) + c] = _scratch[(r * _n) + c] - fa;
                    _out[(r * _n) + c]     = _out[(r * _n) + c] - fi;
                }
            }
        }
    }

    return true;
}

// d_mat_f_submatrix
//   _out ((_n - 1) x (_n - 1)) = _a without row _row and column _col.
D_MATH_FN void
d_mat_f_submatrix(
    float*       _out,
    const float* _a,
    size_t     _n,
    size_t     _row,
    size_t     _col
)
{
    size_t rr = 0u;
    size_t r  = 0u;

    for (r = 0u; r < _n; ++r)
    {
        if (r != _row)
        {
            size_t cc = 0u;
            size_t c  = 0u;

            for (c = 0u; c < _n; ++c)
            {
                if (c != _col)
                {
                    _out[(rr * (_n - 1u)) + cc] = _a[(r * _n) + c];
                    ++cc;
                }
            }

            ++rr;
        }
    }

    return;
}

// d_mat_f_cofactor
//   (-1)^(_row + _col) times the minor, the determinant of the submatrix
// without _row and _col; _scratch holds 2 (_n - 1)^2 entries.
D_MATH_FN float
d_mat_f_cofactor(
    const float* _a,
    float*       _scratch,
    size_t     _n,
    size_t     _row,
    size_t     _col
)
{
    const size_t m    = _n - 1u;
    const float    sign = (((_row + _col) % 2u) == 0u) ? (float)1 : (float)-1;

    d_mat_f_submatrix(_scratch, _a, _n, _row, _col);

    return sign * d_mat_f_determinant(_scratch, _scratch + (m * m), m);
}

// d_mat_f_cofactor_matrix
//   _out (_n x _n) = every cofactor of _a, in place; _scratch holds
// 2 (_n - 1)^2 entries. _adjugate set writes the transpose instead: the
// adjugate.
D_MATH_FN void
d_mat_f_cofactor_matrix(
    float*       _out,
    const float* _a,
    float*       _scratch,
    size_t     _n,
    bool       _adjugate
)
{
    size_t i = 0u;

    for (i = 0u; i < _n; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < _n; ++j)
        {
            const float c = d_mat_f_cofactor(_a, _scratch, _n, i, j);

            _out[_adjugate ? ((j * _n) + i) : ((i * _n) + j)] = c;
        }
    }

    return;
}

// 1.6    Rotations
//------------------------------------------------------------------------------
// The rotation matrices of linear_algebra/transform.hpp, from an angle's
// cosine _c and sine _s, which the face computes as its level allows.
// Counter-clockwise; one operation per statement.

// d_mat_f_rotation_2d
//   _out (2 x 2) = [c -s; s c].
D_MATH_FN void
d_mat_f_rotation_2d(
    float* _out,
    float  _c,
    float  _s
)
{
    _out[0] = _c;
    _out[1] = -_s;
    _out[2] = _s;
    _out[3] = _c;

    return;
}

// d_mat_f_rotation_3d
//   _out (3 x 3) = the rotation about axis _axis (0 x, 1 y, 2 z).
D_MATH_FN void
d_mat_f_rotation_3d(
    float*   _out,
    size_t _axis,
    float    _c,
    float    _s
)
{
    // the two axes the rotation turns, in right-handed order
    const size_t a = (_axis + 1u) % 3u;
    const size_t b = (_axis + 2u) % 3u;

    d_mat_f_identity(_out, 3u);

    _out[(a * 3u) + a] = _c;
    _out[(a * 3u) + b] = -_s;
    _out[(b * 3u) + a] = _s;
    _out[(b * 3u) + b] = _c;

    return;
}

// d_mat_f_rotation_axis
//   _out (3 x 3) = the rotation about the unit axis _k by the angle whose
// cosine and sine are _c and _s, Rodrigues's formula: c I + (1 - c) k k^T +
// s [k]x, each entry formed in the order c + (k_i k_j) t, (k_i k_j) t -+
// k_l s.
D_MATH_FN void
d_mat_f_rotation_axis(
    float*       _out,
    const float* _k,
    float        _c,
    float        _s
)
{
    const float t = (float)1 - _c;
    size_t    i = 0u;

    for (i = 0u; i < 3u; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < 3u; ++j)
        {
            const float kk    = _k[i] * _k[j];
            const float along = kk * t;

            // the diagonal: c + k_i^2 t
            if (i == j)
            {
                _out[(i * 3u) + j] = _c + along;
            }
            // off the diagonal: k_i k_j t -+ k_l s, l the third axis
            else
            {
                const size_t l    = 3u - i - j;
                const float    turn = _k[l] * _s;
                // the cross term's sign: +s where (i, j, l) is an even
                // permutation's (i, j) = (1, 0), (0, 2), (2, 1)
                const bool   plus = ( ((i == 1u) && (j == 0u)) ||
                                      ((i == 0u) && (j == 2u)) ||
                                      ((i == 2u) && (j == 1u)) );

                _out[(i * 3u) + j] = plus ? (along + turn) : (along - turn);
            }
        }
    }

    return;
}

//==============================================================================
// 2.  THE DOUBLE FAMILY (_d)
//==============================================================================
// Row-major: entry (i, j) of a matrix with _cols columns is [i * _cols + j].
// A product's output must not be either input; every other output may be.
// Entry-wise operations are vec.h's over the rows * cols entries.


// 2.1    Construction
//------------------------------------------------------------------------------

D_MATH_FN void
d_mat_d_identity(
    double*   _out,
    size_t _n
)
{
    size_t i = 0u;

    d_vec_d_fill(_out, _n * _n, (double)0);

    for (i = 0u; i < _n; ++i)
    {
        _out[(i * _n) + i] = (double)1;
    }

    return;
}

D_MATH_FN void
d_mat_d_diagonal(
    double*       _out,
    const double* _diagonal,
    size_t     _n
)
{
    size_t i = 0u;

    d_vec_d_fill(_out, _n * _n, (double)0);

    for (i = 0u; i < _n; ++i)
    {
        _out[(i * _n) + i] = _diagonal[i];
    }

    return;
}

// 2.2    Rows, columns and the transpose
//------------------------------------------------------------------------------

D_MATH_FN void
d_mat_d_row(
    double*       _out,
    const double* _a,
    size_t     _i,
    size_t     _cols
)
{
    size_t j = 0u;

    for (j = 0u; j < _cols; ++j)
    {
        _out[j] = _a[(_i * _cols) + j];
    }

    return;
}

D_MATH_FN void
d_mat_d_col(
    double*       _out,
    const double* _a,
    size_t     _j,
    size_t     _rows,
    size_t     _cols
)
{
    size_t i = 0u;

    for (i = 0u; i < _rows; ++i)
    {
        _out[i] = _a[(i * _cols) + _j];
    }

    return;
}

// d_mat_d_transpose
//   _out (_cols x _rows) is _a (_rows x _cols) transposed; _out must not be
// _a.
D_MATH_FN void
d_mat_d_transpose(
    double*       _out,
    const double* _a,
    size_t     _rows,
    size_t     _cols
)
{
    size_t i = 0u;

    for (i = 0u; i < _rows; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < _cols; ++j)
        {
            _out[(j * _rows) + i] = _a[(i * _cols) + j];
        }
    }

    return;
}

// 2.3    Products
//------------------------------------------------------------------------------
// Each entry is its dot product in order of k, each product rounded before it
// is summed. _out must not be an input.

// d_mat_d_multiply
//   _out (_rows x _cols) = _a (_rows x _inner) * _b (_inner x _cols).
D_MATH_FN void
d_mat_d_multiply(
    double*       _out,
    const double* _a,
    const double* _b,
    size_t     _rows,
    size_t     _inner,
    size_t     _cols
)
{
    size_t i = 0u;

    for (i = 0u; i < _rows; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < _cols; ++j)
        {
            double    acc = (double)0;
            size_t k   = 0u;

            for (k = 0u; k < _inner; ++k)
            {
                const double product = _a[(i * _inner) + k] * _b[(k * _cols) + j];

                acc += product;
            }

            _out[(i * _cols) + j] = acc;
        }
    }

    return;
}

// d_mat_d_multiply_vector
//   _out (_rows) = _a (_rows x _cols) * _v (_cols).
D_MATH_FN void
d_mat_d_multiply_vector(
    double*       _out,
    const double* _a,
    const double* _v,
    size_t     _rows,
    size_t     _cols
)
{
    size_t i = 0u;

    for (i = 0u; i < _rows; ++i)
    {
        _out[i] = d_vec_d_dot(_a + (i * _cols), _v, _cols);
    }

    return;
}

// d_mat_d_power
//   _out = _a^_exponent for an _n x _n matrix, the identity for 0: _a times
// the power below, as A^k = A * A^(k-1) composes, _exponent products.
// _scratch holds _n * _n entries; neither it nor _out may be _a.
D_MATH_FN void
d_mat_d_power(
    double*       _out,
    double*       _scratch,
    const double* _a,
    size_t     _n,
    size_t     _exponent
)
{
    size_t k = 0u;

    d_mat_d_identity(_out, _n);

    for (k = 0u; k < _exponent; ++k)
    {
        size_t i = 0u;

        d_mat_d_multiply(_scratch, _a, _out, _n, _n, _n);

        for (i = 0u; i < (_n * _n); ++i)
        {
            _out[i] = _scratch[i];
        }
    }

    return;
}

// 2.4    Square-matrix queries
//------------------------------------------------------------------------------
// trace sums the diagonal; is_symmetric and is_identity allow each entry
// _tolerance.

D_MATH_FN double
d_mat_d_trace(
    const double* _a,
    size_t     _n
)
{
    double    acc = (double)0;
    size_t i   = 0u;

    for (i = 0u; i < _n; ++i)
    {
        acc += _a[(i * _n) + i];
    }

    return acc;
}

D_MATH_FN bool
d_mat_d_is_symmetric(
    const double* _a,
    size_t     _n,
    double        _tolerance
)
{
    size_t i = 0u;

    for (i = 0u; i < _n; ++i)
    {
        size_t j = i + 1u;

        for (j = i + 1u; j < _n; ++j)
        {
            const double d = _a[(i * _n) + j] - _a[(j * _n) + i];

            if (((d < (double)0) ? -d : d) > _tolerance)
            {
                return false;
            }
        }
    }

    return true;
}

D_MATH_FN bool
d_mat_d_is_identity(
    const double* _a,
    size_t     _n,
    double        _tolerance
)
{
    size_t i = 0u;

    for (i = 0u; i < _n; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < _n; ++j)
        {
            const double d = _a[(i * _n) + j] - ((i == j) ? (double)1 : (double)0);

            if (((d < (double)0) ? -d : d) > _tolerance)
            {
                return false;
            }
        }
    }

    return true;
}

// 2.5    Determinant, inverse and cofactors
//------------------------------------------------------------------------------
// The square matrix's algebra, as linear_algebra/square.hpp computes it: the
// determinant by Bareiss's fraction-free elimination (exact for integers,
// and the subframework's algorithm), the inverse by Gauss-Jordan with
// partial pivoting. Each product is rounded before it is combined. Every
// kernel takes the scratch it needs from the caller.

// d_mat_d_determinant
//   the determinant of the _n x _n matrix _a; _scratch holds _n * _n
// entries. Bareiss: a row with a zero pivot is swapped for the first below
// it with a non-zero entry in the column, flipping the sign; none means 0.
D_MATH_FN double
d_mat_d_determinant(
    const double* _a,
    double*       _scratch,
    size_t     _n
)
{
    double    prev = (double)1;
    double    sign = (double)1;
    size_t k    = 0u;

    for (k = 0u; k < (_n * _n); ++k)
    {
        _scratch[k] = _a[k];
    }

    for (k = 0u; k < _n; ++k)
    {
        size_t i = 0u;

        // a zero pivot: swap in the first row below with a non-zero entry
        if (_scratch[(k * _n) + k] == (double)0)
        {
            size_t swap_row = k;
            size_t r        = k + 1u;
            size_t c        = 0u;

            for (r = k + 1u; r < _n; ++r)
            {
                if (_scratch[(r * _n) + k] != (double)0)
                {
                    swap_row = r;
                    break;
                }
            }

            // the column is zero below the diagonal: the matrix is singular
            if (swap_row == k)
            {
                return (double)0;
            }

            for (c = 0u; c < _n; ++c)
            {
                const double t = _scratch[(k * _n) + c];

                _scratch[(k * _n) + c]        = _scratch[(swap_row * _n) + c];
                _scratch[(swap_row * _n) + c] = t;
            }

            sign = -sign;
        }

        // the fraction-free update of the block below and right
        for (i = k + 1u; i < _n; ++i)
        {
            size_t j = k + 1u;

            for (j = k + 1u; j < _n; ++j)
            {
                const double keep  = _scratch[(k * _n) + k] *
                                  _scratch[(i * _n) + j];
                const double cross = _scratch[(i * _n) + k] *
                                  _scratch[(k * _n) + j];
                // one operation per statement: an x87 evaluates a whole
                // expression at 64 bits and rounds once, at the end
                const double diff  = keep - cross;

                _scratch[(i * _n) + j] = diff / prev;
            }
        }

        prev = _scratch[(k * _n) + k];
    }

    return sign * prev;
}

// d_mat_d_inverse
//   _out = the inverse of the _n x _n matrix _a, true; or, for a singular
// one, the zero matrix and false. _scratch holds _n * _n entries; neither it
// nor _out may be _a. Gauss-Jordan: the pivot is the first entry of largest
// magnitude at or below the diagonal.
D_MATH_FN bool
d_mat_d_inverse(
    double*       _out,
    double*       _scratch,
    const double* _a,
    size_t     _n
)
{
    size_t col = 0u;
    size_t k   = 0u;

    for (k = 0u; k < (_n * _n); ++k)
    {
        _scratch[k] = _a[k];
    }

    d_mat_d_identity(_out, _n);

    for (col = 0u; col < _n; ++col)
    {
        size_t    pivot = col;
        double       maxv  = (_scratch[(col * _n) + col] < (double)0)
                              ? -_scratch[(col * _n) + col]
                              : _scratch[(col * _n) + col];
        size_t    r     = col + 1u;
        size_t    c     = 0u;
        double       d     = (double)0;

        // the first entry of largest magnitude at or below the diagonal
        for (r = col + 1u; r < _n; ++r)
        {
            const double v = (_scratch[(r * _n) + col] < (double)0)
                              ? -_scratch[(r * _n) + col]
                              : _scratch[(r * _n) + col];

            if (v > maxv)
            {
                maxv  = v;
                pivot = r;
            }
        }

        // no pivot: singular
        if (_scratch[(pivot * _n) + col] == (double)0)
        {
            d_vec_d_fill(_out, _n * _n, (double)0);

            return false;
        }

        // the pivot row up into place, in both
        if (pivot != col)
        {
            for (c = 0u; c < _n; ++c)
            {
                const double ta = _scratch[(col * _n) + c];
                const double ti = _out[(col * _n) + c];

                _scratch[(col * _n) + c]   = _scratch[(pivot * _n) + c];
                _scratch[(pivot * _n) + c] = ta;
                _out[(col * _n) + c]       = _out[(pivot * _n) + c];
                _out[(pivot * _n) + c]     = ti;
            }
        }

        d = _scratch[(col * _n) + col];

        // the pivot row divided through
        for (c = 0u; c < _n; ++c)
        {
            _scratch[(col * _n) + c] = _scratch[(col * _n) + c] / d;
            _out[(col * _n) + c]     = _out[(col * _n) + c] / d;
        }

        // every other row cleared in the pivot's column
        for (r = 0u; r < _n; ++r)
        {
            if (r != col)
            {
                const double f = _scratch[(r * _n) + col];

                for (c = 0u; c < _n; ++c)
                {
                    const double fa = f * _scratch[(col * _n) + c];
                    const double fi = f * _out[(col * _n) + c];

                    _scratch[(r * _n) + c] = _scratch[(r * _n) + c] - fa;
                    _out[(r * _n) + c]     = _out[(r * _n) + c] - fi;
                }
            }
        }
    }

    return true;
}

// d_mat_d_submatrix
//   _out ((_n - 1) x (_n - 1)) = _a without row _row and column _col.
D_MATH_FN void
d_mat_d_submatrix(
    double*       _out,
    const double* _a,
    size_t     _n,
    size_t     _row,
    size_t     _col
)
{
    size_t rr = 0u;
    size_t r  = 0u;

    for (r = 0u; r < _n; ++r)
    {
        if (r != _row)
        {
            size_t cc = 0u;
            size_t c  = 0u;

            for (c = 0u; c < _n; ++c)
            {
                if (c != _col)
                {
                    _out[(rr * (_n - 1u)) + cc] = _a[(r * _n) + c];
                    ++cc;
                }
            }

            ++rr;
        }
    }

    return;
}

// d_mat_d_cofactor
//   (-1)^(_row + _col) times the minor, the determinant of the submatrix
// without _row and _col; _scratch holds 2 (_n - 1)^2 entries.
D_MATH_FN double
d_mat_d_cofactor(
    const double* _a,
    double*       _scratch,
    size_t     _n,
    size_t     _row,
    size_t     _col
)
{
    const size_t m    = _n - 1u;
    const double    sign = (((_row + _col) % 2u) == 0u) ? (double)1 : (double)-1;

    d_mat_d_submatrix(_scratch, _a, _n, _row, _col);

    return sign * d_mat_d_determinant(_scratch, _scratch + (m * m), m);
}

// d_mat_d_cofactor_matrix
//   _out (_n x _n) = every cofactor of _a, in place; _scratch holds
// 2 (_n - 1)^2 entries. _adjugate set writes the transpose instead: the
// adjugate.
D_MATH_FN void
d_mat_d_cofactor_matrix(
    double*       _out,
    const double* _a,
    double*       _scratch,
    size_t     _n,
    bool       _adjugate
)
{
    size_t i = 0u;

    for (i = 0u; i < _n; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < _n; ++j)
        {
            const double c = d_mat_d_cofactor(_a, _scratch, _n, i, j);

            _out[_adjugate ? ((j * _n) + i) : ((i * _n) + j)] = c;
        }
    }

    return;
}

// 2.6    Rotations
//------------------------------------------------------------------------------
// The rotation matrices of linear_algebra/transform.hpp, from an angle's
// cosine _c and sine _s, which the face computes as its level allows.
// Counter-clockwise; one operation per statement.

// d_mat_d_rotation_2d
//   _out (2 x 2) = [c -s; s c].
D_MATH_FN void
d_mat_d_rotation_2d(
    double* _out,
    double  _c,
    double  _s
)
{
    _out[0] = _c;
    _out[1] = -_s;
    _out[2] = _s;
    _out[3] = _c;

    return;
}

// d_mat_d_rotation_3d
//   _out (3 x 3) = the rotation about axis _axis (0 x, 1 y, 2 z).
D_MATH_FN void
d_mat_d_rotation_3d(
    double*   _out,
    size_t _axis,
    double    _c,
    double    _s
)
{
    // the two axes the rotation turns, in right-handed order
    const size_t a = (_axis + 1u) % 3u;
    const size_t b = (_axis + 2u) % 3u;

    d_mat_d_identity(_out, 3u);

    _out[(a * 3u) + a] = _c;
    _out[(a * 3u) + b] = -_s;
    _out[(b * 3u) + a] = _s;
    _out[(b * 3u) + b] = _c;

    return;
}

// d_mat_d_rotation_axis
//   _out (3 x 3) = the rotation about the unit axis _k by the angle whose
// cosine and sine are _c and _s, Rodrigues's formula: c I + (1 - c) k k^T +
// s [k]x, each entry formed in the order c + (k_i k_j) t, (k_i k_j) t -+
// k_l s.
D_MATH_FN void
d_mat_d_rotation_axis(
    double*       _out,
    const double* _k,
    double        _c,
    double        _s
)
{
    const double t = (double)1 - _c;
    size_t    i = 0u;

    for (i = 0u; i < 3u; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < 3u; ++j)
        {
            const double kk    = _k[i] * _k[j];
            const double along = kk * t;

            // the diagonal: c + k_i^2 t
            if (i == j)
            {
                _out[(i * 3u) + j] = _c + along;
            }
            // off the diagonal: k_i k_j t -+ k_l s, l the third axis
            else
            {
                const size_t l    = 3u - i - j;
                const double    turn = _k[l] * _s;
                // the cross term's sign: +s where (i, j, l) is an even
                // permutation's (i, j) = (1, 0), (0, 2), (2, 1)
                const bool   plus = ( ((i == 1u) && (j == 0u)) ||
                                      ((i == 0u) && (j == 2u)) ||
                                      ((i == 2u) && (j == 1u)) );

                _out[(i * 3u) + j] = plus ? (along + turn) : (along - turn);
            }
        }
    }

    return;
}

//==============================================================================
// 3.  THE LONG DOUBLE FAMILY (_ld)
//==============================================================================
// Row-major: entry (i, j) of a matrix with _cols columns is [i * _cols + j].
// A product's output must not be either input; every other output may be.
// Entry-wise operations are vec.h's over the rows * cols entries.


// 3.1    Construction
//------------------------------------------------------------------------------

D_MATH_FN void
d_mat_ld_identity(
    long double*   _out,
    size_t _n
)
{
    size_t i = 0u;

    d_vec_ld_fill(_out, _n * _n, (long double)0);

    for (i = 0u; i < _n; ++i)
    {
        _out[(i * _n) + i] = (long double)1;
    }

    return;
}

D_MATH_FN void
d_mat_ld_diagonal(
    long double*       _out,
    const long double* _diagonal,
    size_t     _n
)
{
    size_t i = 0u;

    d_vec_ld_fill(_out, _n * _n, (long double)0);

    for (i = 0u; i < _n; ++i)
    {
        _out[(i * _n) + i] = _diagonal[i];
    }

    return;
}

// 3.2    Rows, columns and the transpose
//------------------------------------------------------------------------------

D_MATH_FN void
d_mat_ld_row(
    long double*       _out,
    const long double* _a,
    size_t     _i,
    size_t     _cols
)
{
    size_t j = 0u;

    for (j = 0u; j < _cols; ++j)
    {
        _out[j] = _a[(_i * _cols) + j];
    }

    return;
}

D_MATH_FN void
d_mat_ld_col(
    long double*       _out,
    const long double* _a,
    size_t     _j,
    size_t     _rows,
    size_t     _cols
)
{
    size_t i = 0u;

    for (i = 0u; i < _rows; ++i)
    {
        _out[i] = _a[(i * _cols) + _j];
    }

    return;
}

// d_mat_ld_transpose
//   _out (_cols x _rows) is _a (_rows x _cols) transposed; _out must not be
// _a.
D_MATH_FN void
d_mat_ld_transpose(
    long double*       _out,
    const long double* _a,
    size_t     _rows,
    size_t     _cols
)
{
    size_t i = 0u;

    for (i = 0u; i < _rows; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < _cols; ++j)
        {
            _out[(j * _rows) + i] = _a[(i * _cols) + j];
        }
    }

    return;
}

// 3.3    Products
//------------------------------------------------------------------------------
// Each entry is its dot product in order of k, each product rounded before it
// is summed. _out must not be an input.

// d_mat_ld_multiply
//   _out (_rows x _cols) = _a (_rows x _inner) * _b (_inner x _cols).
D_MATH_FN void
d_mat_ld_multiply(
    long double*       _out,
    const long double* _a,
    const long double* _b,
    size_t     _rows,
    size_t     _inner,
    size_t     _cols
)
{
    size_t i = 0u;

    for (i = 0u; i < _rows; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < _cols; ++j)
        {
            long double    acc = (long double)0;
            size_t k   = 0u;

            for (k = 0u; k < _inner; ++k)
            {
                const long double product = _a[(i * _inner) + k] * _b[(k * _cols) + j];

                acc += product;
            }

            _out[(i * _cols) + j] = acc;
        }
    }

    return;
}

// d_mat_ld_multiply_vector
//   _out (_rows) = _a (_rows x _cols) * _v (_cols).
D_MATH_FN void
d_mat_ld_multiply_vector(
    long double*       _out,
    const long double* _a,
    const long double* _v,
    size_t     _rows,
    size_t     _cols
)
{
    size_t i = 0u;

    for (i = 0u; i < _rows; ++i)
    {
        _out[i] = d_vec_ld_dot(_a + (i * _cols), _v, _cols);
    }

    return;
}

// d_mat_ld_power
//   _out = _a^_exponent for an _n x _n matrix, the identity for 0: _a times
// the power below, as A^k = A * A^(k-1) composes, _exponent products.
// _scratch holds _n * _n entries; neither it nor _out may be _a.
D_MATH_FN void
d_mat_ld_power(
    long double*       _out,
    long double*       _scratch,
    const long double* _a,
    size_t     _n,
    size_t     _exponent
)
{
    size_t k = 0u;

    d_mat_ld_identity(_out, _n);

    for (k = 0u; k < _exponent; ++k)
    {
        size_t i = 0u;

        d_mat_ld_multiply(_scratch, _a, _out, _n, _n, _n);

        for (i = 0u; i < (_n * _n); ++i)
        {
            _out[i] = _scratch[i];
        }
    }

    return;
}

// 3.4    Square-matrix queries
//------------------------------------------------------------------------------
// trace sums the diagonal; is_symmetric and is_identity allow each entry
// _tolerance.

D_MATH_FN long double
d_mat_ld_trace(
    const long double* _a,
    size_t     _n
)
{
    long double    acc = (long double)0;
    size_t i   = 0u;

    for (i = 0u; i < _n; ++i)
    {
        acc += _a[(i * _n) + i];
    }

    return acc;
}

D_MATH_FN bool
d_mat_ld_is_symmetric(
    const long double* _a,
    size_t     _n,
    long double        _tolerance
)
{
    size_t i = 0u;

    for (i = 0u; i < _n; ++i)
    {
        size_t j = i + 1u;

        for (j = i + 1u; j < _n; ++j)
        {
            const long double d = _a[(i * _n) + j] - _a[(j * _n) + i];

            if (((d < (long double)0) ? -d : d) > _tolerance)
            {
                return false;
            }
        }
    }

    return true;
}

D_MATH_FN bool
d_mat_ld_is_identity(
    const long double* _a,
    size_t     _n,
    long double        _tolerance
)
{
    size_t i = 0u;

    for (i = 0u; i < _n; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < _n; ++j)
        {
            const long double d = _a[(i * _n) + j] - ((i == j) ? (long double)1 : (long double)0);

            if (((d < (long double)0) ? -d : d) > _tolerance)
            {
                return false;
            }
        }
    }

    return true;
}

// 3.5    Determinant, inverse and cofactors
//------------------------------------------------------------------------------
// The square matrix's algebra, as linear_algebra/square.hpp computes it: the
// determinant by Bareiss's fraction-free elimination (exact for integers,
// and the subframework's algorithm), the inverse by Gauss-Jordan with
// partial pivoting. Each product is rounded before it is combined. Every
// kernel takes the scratch it needs from the caller.

// d_mat_ld_determinant
//   the determinant of the _n x _n matrix _a; _scratch holds _n * _n
// entries. Bareiss: a row with a zero pivot is swapped for the first below
// it with a non-zero entry in the column, flipping the sign; none means 0.
D_MATH_FN long double
d_mat_ld_determinant(
    const long double* _a,
    long double*       _scratch,
    size_t     _n
)
{
    long double    prev = (long double)1;
    long double    sign = (long double)1;
    size_t k    = 0u;

    for (k = 0u; k < (_n * _n); ++k)
    {
        _scratch[k] = _a[k];
    }

    for (k = 0u; k < _n; ++k)
    {
        size_t i = 0u;

        // a zero pivot: swap in the first row below with a non-zero entry
        if (_scratch[(k * _n) + k] == (long double)0)
        {
            size_t swap_row = k;
            size_t r        = k + 1u;
            size_t c        = 0u;

            for (r = k + 1u; r < _n; ++r)
            {
                if (_scratch[(r * _n) + k] != (long double)0)
                {
                    swap_row = r;
                    break;
                }
            }

            // the column is zero below the diagonal: the matrix is singular
            if (swap_row == k)
            {
                return (long double)0;
            }

            for (c = 0u; c < _n; ++c)
            {
                const long double t = _scratch[(k * _n) + c];

                _scratch[(k * _n) + c]        = _scratch[(swap_row * _n) + c];
                _scratch[(swap_row * _n) + c] = t;
            }

            sign = -sign;
        }

        // the fraction-free update of the block below and right
        for (i = k + 1u; i < _n; ++i)
        {
            size_t j = k + 1u;

            for (j = k + 1u; j < _n; ++j)
            {
                const long double keep  = _scratch[(k * _n) + k] *
                                  _scratch[(i * _n) + j];
                const long double cross = _scratch[(i * _n) + k] *
                                  _scratch[(k * _n) + j];
                // one operation per statement: an x87 evaluates a whole
                // expression at 64 bits and rounds once, at the end
                const long double diff  = keep - cross;

                _scratch[(i * _n) + j] = diff / prev;
            }
        }

        prev = _scratch[(k * _n) + k];
    }

    return sign * prev;
}

// d_mat_ld_inverse
//   _out = the inverse of the _n x _n matrix _a, true; or, for a singular
// one, the zero matrix and false. _scratch holds _n * _n entries; neither it
// nor _out may be _a. Gauss-Jordan: the pivot is the first entry of largest
// magnitude at or below the diagonal.
D_MATH_FN bool
d_mat_ld_inverse(
    long double*       _out,
    long double*       _scratch,
    const long double* _a,
    size_t     _n
)
{
    size_t col = 0u;
    size_t k   = 0u;

    for (k = 0u; k < (_n * _n); ++k)
    {
        _scratch[k] = _a[k];
    }

    d_mat_ld_identity(_out, _n);

    for (col = 0u; col < _n; ++col)
    {
        size_t    pivot = col;
        long double       maxv  = (_scratch[(col * _n) + col] < (long double)0)
                              ? -_scratch[(col * _n) + col]
                              : _scratch[(col * _n) + col];
        size_t    r     = col + 1u;
        size_t    c     = 0u;
        long double       d     = (long double)0;

        // the first entry of largest magnitude at or below the diagonal
        for (r = col + 1u; r < _n; ++r)
        {
            const long double v = (_scratch[(r * _n) + col] < (long double)0)
                              ? -_scratch[(r * _n) + col]
                              : _scratch[(r * _n) + col];

            if (v > maxv)
            {
                maxv  = v;
                pivot = r;
            }
        }

        // no pivot: singular
        if (_scratch[(pivot * _n) + col] == (long double)0)
        {
            d_vec_ld_fill(_out, _n * _n, (long double)0);

            return false;
        }

        // the pivot row up into place, in both
        if (pivot != col)
        {
            for (c = 0u; c < _n; ++c)
            {
                const long double ta = _scratch[(col * _n) + c];
                const long double ti = _out[(col * _n) + c];

                _scratch[(col * _n) + c]   = _scratch[(pivot * _n) + c];
                _scratch[(pivot * _n) + c] = ta;
                _out[(col * _n) + c]       = _out[(pivot * _n) + c];
                _out[(pivot * _n) + c]     = ti;
            }
        }

        d = _scratch[(col * _n) + col];

        // the pivot row divided through
        for (c = 0u; c < _n; ++c)
        {
            _scratch[(col * _n) + c] = _scratch[(col * _n) + c] / d;
            _out[(col * _n) + c]     = _out[(col * _n) + c] / d;
        }

        // every other row cleared in the pivot's column
        for (r = 0u; r < _n; ++r)
        {
            if (r != col)
            {
                const long double f = _scratch[(r * _n) + col];

                for (c = 0u; c < _n; ++c)
                {
                    const long double fa = f * _scratch[(col * _n) + c];
                    const long double fi = f * _out[(col * _n) + c];

                    _scratch[(r * _n) + c] = _scratch[(r * _n) + c] - fa;
                    _out[(r * _n) + c]     = _out[(r * _n) + c] - fi;
                }
            }
        }
    }

    return true;
}

// d_mat_ld_submatrix
//   _out ((_n - 1) x (_n - 1)) = _a without row _row and column _col.
D_MATH_FN void
d_mat_ld_submatrix(
    long double*       _out,
    const long double* _a,
    size_t     _n,
    size_t     _row,
    size_t     _col
)
{
    size_t rr = 0u;
    size_t r  = 0u;

    for (r = 0u; r < _n; ++r)
    {
        if (r != _row)
        {
            size_t cc = 0u;
            size_t c  = 0u;

            for (c = 0u; c < _n; ++c)
            {
                if (c != _col)
                {
                    _out[(rr * (_n - 1u)) + cc] = _a[(r * _n) + c];
                    ++cc;
                }
            }

            ++rr;
        }
    }

    return;
}

// d_mat_ld_cofactor
//   (-1)^(_row + _col) times the minor, the determinant of the submatrix
// without _row and _col; _scratch holds 2 (_n - 1)^2 entries.
D_MATH_FN long double
d_mat_ld_cofactor(
    const long double* _a,
    long double*       _scratch,
    size_t     _n,
    size_t     _row,
    size_t     _col
)
{
    const size_t m    = _n - 1u;
    const long double    sign = (((_row + _col) % 2u) == 0u) ? (long double)1 : (long double)-1;

    d_mat_ld_submatrix(_scratch, _a, _n, _row, _col);

    return sign * d_mat_ld_determinant(_scratch, _scratch + (m * m), m);
}

// d_mat_ld_cofactor_matrix
//   _out (_n x _n) = every cofactor of _a, in place; _scratch holds
// 2 (_n - 1)^2 entries. _adjugate set writes the transpose instead: the
// adjugate.
D_MATH_FN void
d_mat_ld_cofactor_matrix(
    long double*       _out,
    const long double* _a,
    long double*       _scratch,
    size_t     _n,
    bool       _adjugate
)
{
    size_t i = 0u;

    for (i = 0u; i < _n; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < _n; ++j)
        {
            const long double c = d_mat_ld_cofactor(_a, _scratch, _n, i, j);

            _out[_adjugate ? ((j * _n) + i) : ((i * _n) + j)] = c;
        }
    }

    return;
}

// 3.6    Rotations
//------------------------------------------------------------------------------
// The rotation matrices of linear_algebra/transform.hpp, from an angle's
// cosine _c and sine _s, which the face computes as its level allows.
// Counter-clockwise; one operation per statement.

// d_mat_ld_rotation_2d
//   _out (2 x 2) = [c -s; s c].
D_MATH_FN void
d_mat_ld_rotation_2d(
    long double* _out,
    long double  _c,
    long double  _s
)
{
    _out[0] = _c;
    _out[1] = -_s;
    _out[2] = _s;
    _out[3] = _c;

    return;
}

// d_mat_ld_rotation_3d
//   _out (3 x 3) = the rotation about axis _axis (0 x, 1 y, 2 z).
D_MATH_FN void
d_mat_ld_rotation_3d(
    long double*   _out,
    size_t _axis,
    long double    _c,
    long double    _s
)
{
    // the two axes the rotation turns, in right-handed order
    const size_t a = (_axis + 1u) % 3u;
    const size_t b = (_axis + 2u) % 3u;

    d_mat_ld_identity(_out, 3u);

    _out[(a * 3u) + a] = _c;
    _out[(a * 3u) + b] = -_s;
    _out[(b * 3u) + a] = _s;
    _out[(b * 3u) + b] = _c;

    return;
}

// d_mat_ld_rotation_axis
//   _out (3 x 3) = the rotation about the unit axis _k by the angle whose
// cosine and sine are _c and _s, Rodrigues's formula: c I + (1 - c) k k^T +
// s [k]x, each entry formed in the order c + (k_i k_j) t, (k_i k_j) t -+
// k_l s.
D_MATH_FN void
d_mat_ld_rotation_axis(
    long double*       _out,
    const long double* _k,
    long double        _c,
    long double        _s
)
{
    const long double t = (long double)1 - _c;
    size_t    i = 0u;

    for (i = 0u; i < 3u; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < 3u; ++j)
        {
            const long double kk    = _k[i] * _k[j];
            const long double along = kk * t;

            // the diagonal: c + k_i^2 t
            if (i == j)
            {
                _out[(i * 3u) + j] = _c + along;
            }
            // off the diagonal: k_i k_j t -+ k_l s, l the third axis
            else
            {
                const size_t l    = 3u - i - j;
                const long double    turn = _k[l] * _s;
                // the cross term's sign: +s where (i, j, l) is an even
                // permutation's (i, j) = (1, 0), (0, 2), (2, 1)
                const bool   plus = ( ((i == 1u) && (j == 0u)) ||
                                      ((i == 0u) && (j == 2u)) ||
                                      ((i == 2u) && (j == 1u)) );

                _out[(i * 3u) + j] = plus ? (along + turn) : (along - turn);
            }
        }
    }

    return;
}


#ifdef __cplusplus

//==============================================================================
// 4.  ONE NAME FOR EVERY FAMILY (C++)
//==============================================================================
// C++ only: the kernels above under one name each, chosen by argument type,
// so a C++ template serves float, double and long double alike.


D_MATH_FN void
d_mat_identity(
    float* _out,
    size_t _n
)
{
    return d_mat_f_identity(_out, _n);
}

D_MATH_FN void
d_mat_diagonal(
    float*       _out,
    const float* _diagonal,
    size_t       _n
)
{
    return d_mat_f_diagonal(_out, _diagonal, _n);
}

D_MATH_FN void
d_mat_row(
    float*       _out,
    const float* _a,
    size_t       _i,
    size_t       _cols
)
{
    return d_mat_f_row(_out, _a, _i, _cols);
}

D_MATH_FN void
d_mat_col(
    float*       _out,
    const float* _a,
    size_t       _j,
    size_t       _rows,
    size_t       _cols
)
{
    return d_mat_f_col(_out, _a, _j, _rows, _cols);
}

D_MATH_FN void
d_mat_transpose(
    float*       _out,
    const float* _a,
    size_t       _rows,
    size_t       _cols
)
{
    return d_mat_f_transpose(_out, _a, _rows, _cols);
}

D_MATH_FN void
d_mat_multiply(
    float*       _out,
    const float* _a,
    const float* _b,
    size_t       _rows,
    size_t       _inner,
    size_t       _cols
)
{
    return d_mat_f_multiply(_out, _a, _b, _rows, _inner, _cols);
}

D_MATH_FN void
d_mat_multiply_vector(
    float*       _out,
    const float* _a,
    const float* _v,
    size_t       _rows,
    size_t       _cols
)
{
    return d_mat_f_multiply_vector(_out, _a, _v, _rows, _cols);
}

D_MATH_FN void
d_mat_power(
    float*       _out,
    float*       _scratch,
    const float* _a,
    size_t       _n,
    size_t       _exponent
)
{
    return d_mat_f_power(_out, _scratch, _a, _n, _exponent);
}

D_MATH_FN float
d_mat_trace(
    const float* _a,
    size_t       _n
)
{
    return d_mat_f_trace(_a, _n);
}

D_MATH_FN bool
d_mat_is_symmetric(
    const float* _a,
    size_t       _n,
    float        _tolerance
)
{
    return d_mat_f_is_symmetric(_a, _n, _tolerance);
}

D_MATH_FN bool
d_mat_is_identity(
    const float* _a,
    size_t       _n,
    float        _tolerance
)
{
    return d_mat_f_is_identity(_a, _n, _tolerance);
}

D_MATH_FN float
d_mat_determinant(
    const float* _a,
    float*       _scratch,
    size_t       _n
)
{
    return d_mat_f_determinant(_a, _scratch, _n);
}

D_MATH_FN bool
d_mat_inverse(
    float*       _out,
    float*       _scratch,
    const float* _a,
    size_t       _n
)
{
    return d_mat_f_inverse(_out, _scratch, _a, _n);
}

D_MATH_FN void
d_mat_submatrix(
    float*       _out,
    const float* _a,
    size_t       _n,
    size_t       _row,
    size_t       _col
)
{
    return d_mat_f_submatrix(_out, _a, _n, _row, _col);
}

D_MATH_FN float
d_mat_cofactor(
    const float* _a,
    float*       _scratch,
    size_t       _n,
    size_t       _row,
    size_t       _col
)
{
    return d_mat_f_cofactor(_a, _scratch, _n, _row, _col);
}

D_MATH_FN void
d_mat_cofactor_matrix(
    float*       _out,
    const float* _a,
    float*       _scratch,
    size_t       _n,
    bool         _adjugate
)
{
    return d_mat_f_cofactor_matrix(_out, _a, _scratch, _n, _adjugate);
}

D_MATH_FN void
d_mat_rotation_2d(
    float* _out,
    float  _c,
    float  _s
)
{
    return d_mat_f_rotation_2d(_out, _c, _s);
}

D_MATH_FN void
d_mat_rotation_3d(
    float* _out,
    size_t _axis,
    float  _c,
    float  _s
)
{
    return d_mat_f_rotation_3d(_out, _axis, _c, _s);
}

D_MATH_FN void
d_mat_rotation_axis(
    float*       _out,
    const float* _k,
    float        _c,
    float        _s
)
{
    return d_mat_f_rotation_axis(_out, _k, _c, _s);
}

D_MATH_FN void
d_mat_identity(
    double* _out,
    size_t  _n
)
{
    return d_mat_d_identity(_out, _n);
}

D_MATH_FN void
d_mat_diagonal(
    double*       _out,
    const double* _diagonal,
    size_t        _n
)
{
    return d_mat_d_diagonal(_out, _diagonal, _n);
}

D_MATH_FN void
d_mat_row(
    double*       _out,
    const double* _a,
    size_t        _i,
    size_t        _cols
)
{
    return d_mat_d_row(_out, _a, _i, _cols);
}

D_MATH_FN void
d_mat_col(
    double*       _out,
    const double* _a,
    size_t        _j,
    size_t        _rows,
    size_t        _cols
)
{
    return d_mat_d_col(_out, _a, _j, _rows, _cols);
}

D_MATH_FN void
d_mat_transpose(
    double*       _out,
    const double* _a,
    size_t        _rows,
    size_t        _cols
)
{
    return d_mat_d_transpose(_out, _a, _rows, _cols);
}

D_MATH_FN void
d_mat_multiply(
    double*       _out,
    const double* _a,
    const double* _b,
    size_t        _rows,
    size_t        _inner,
    size_t        _cols
)
{
    return d_mat_d_multiply(_out, _a, _b, _rows, _inner, _cols);
}

D_MATH_FN void
d_mat_multiply_vector(
    double*       _out,
    const double* _a,
    const double* _v,
    size_t        _rows,
    size_t        _cols
)
{
    return d_mat_d_multiply_vector(_out, _a, _v, _rows, _cols);
}

D_MATH_FN void
d_mat_power(
    double*       _out,
    double*       _scratch,
    const double* _a,
    size_t        _n,
    size_t        _exponent
)
{
    return d_mat_d_power(_out, _scratch, _a, _n, _exponent);
}

D_MATH_FN double
d_mat_trace(
    const double* _a,
    size_t        _n
)
{
    return d_mat_d_trace(_a, _n);
}

D_MATH_FN bool
d_mat_is_symmetric(
    const double* _a,
    size_t        _n,
    double        _tolerance
)
{
    return d_mat_d_is_symmetric(_a, _n, _tolerance);
}

D_MATH_FN bool
d_mat_is_identity(
    const double* _a,
    size_t        _n,
    double        _tolerance
)
{
    return d_mat_d_is_identity(_a, _n, _tolerance);
}

D_MATH_FN double
d_mat_determinant(
    const double* _a,
    double*       _scratch,
    size_t        _n
)
{
    return d_mat_d_determinant(_a, _scratch, _n);
}

D_MATH_FN bool
d_mat_inverse(
    double*       _out,
    double*       _scratch,
    const double* _a,
    size_t        _n
)
{
    return d_mat_d_inverse(_out, _scratch, _a, _n);
}

D_MATH_FN void
d_mat_submatrix(
    double*       _out,
    const double* _a,
    size_t        _n,
    size_t        _row,
    size_t        _col
)
{
    return d_mat_d_submatrix(_out, _a, _n, _row, _col);
}

D_MATH_FN double
d_mat_cofactor(
    const double* _a,
    double*       _scratch,
    size_t        _n,
    size_t        _row,
    size_t        _col
)
{
    return d_mat_d_cofactor(_a, _scratch, _n, _row, _col);
}

D_MATH_FN void
d_mat_cofactor_matrix(
    double*       _out,
    const double* _a,
    double*       _scratch,
    size_t        _n,
    bool          _adjugate
)
{
    return d_mat_d_cofactor_matrix(_out, _a, _scratch, _n, _adjugate);
}

D_MATH_FN void
d_mat_rotation_2d(
    double* _out,
    double  _c,
    double  _s
)
{
    return d_mat_d_rotation_2d(_out, _c, _s);
}

D_MATH_FN void
d_mat_rotation_3d(
    double* _out,
    size_t  _axis,
    double  _c,
    double  _s
)
{
    return d_mat_d_rotation_3d(_out, _axis, _c, _s);
}

D_MATH_FN void
d_mat_rotation_axis(
    double*       _out,
    const double* _k,
    double        _c,
    double        _s
)
{
    return d_mat_d_rotation_axis(_out, _k, _c, _s);
}

D_MATH_FN void
d_mat_identity(
    long double* _out,
    size_t       _n
)
{
    return d_mat_ld_identity(_out, _n);
}

D_MATH_FN void
d_mat_diagonal(
    long double*       _out,
    const long double* _diagonal,
    size_t             _n
)
{
    return d_mat_ld_diagonal(_out, _diagonal, _n);
}

D_MATH_FN void
d_mat_row(
    long double*       _out,
    const long double* _a,
    size_t             _i,
    size_t             _cols
)
{
    return d_mat_ld_row(_out, _a, _i, _cols);
}

D_MATH_FN void
d_mat_col(
    long double*       _out,
    const long double* _a,
    size_t             _j,
    size_t             _rows,
    size_t             _cols
)
{
    return d_mat_ld_col(_out, _a, _j, _rows, _cols);
}

D_MATH_FN void
d_mat_transpose(
    long double*       _out,
    const long double* _a,
    size_t             _rows,
    size_t             _cols
)
{
    return d_mat_ld_transpose(_out, _a, _rows, _cols);
}

D_MATH_FN void
d_mat_multiply(
    long double*       _out,
    const long double* _a,
    const long double* _b,
    size_t             _rows,
    size_t             _inner,
    size_t             _cols
)
{
    return d_mat_ld_multiply(_out, _a, _b, _rows, _inner, _cols);
}

D_MATH_FN void
d_mat_multiply_vector(
    long double*       _out,
    const long double* _a,
    const long double* _v,
    size_t             _rows,
    size_t             _cols
)
{
    return d_mat_ld_multiply_vector(_out, _a, _v, _rows, _cols);
}

D_MATH_FN void
d_mat_power(
    long double*       _out,
    long double*       _scratch,
    const long double* _a,
    size_t             _n,
    size_t             _exponent
)
{
    return d_mat_ld_power(_out, _scratch, _a, _n, _exponent);
}

D_MATH_FN long double
d_mat_trace(
    const long double* _a,
    size_t             _n
)
{
    return d_mat_ld_trace(_a, _n);
}

D_MATH_FN bool
d_mat_is_symmetric(
    const long double* _a,
    size_t             _n,
    long double        _tolerance
)
{
    return d_mat_ld_is_symmetric(_a, _n, _tolerance);
}

D_MATH_FN bool
d_mat_is_identity(
    const long double* _a,
    size_t             _n,
    long double        _tolerance
)
{
    return d_mat_ld_is_identity(_a, _n, _tolerance);
}

D_MATH_FN long double
d_mat_determinant(
    const long double* _a,
    long double*       _scratch,
    size_t             _n
)
{
    return d_mat_ld_determinant(_a, _scratch, _n);
}

D_MATH_FN bool
d_mat_inverse(
    long double*       _out,
    long double*       _scratch,
    const long double* _a,
    size_t             _n
)
{
    return d_mat_ld_inverse(_out, _scratch, _a, _n);
}

D_MATH_FN void
d_mat_submatrix(
    long double*       _out,
    const long double* _a,
    size_t             _n,
    size_t             _row,
    size_t             _col
)
{
    return d_mat_ld_submatrix(_out, _a, _n, _row, _col);
}

D_MATH_FN long double
d_mat_cofactor(
    const long double* _a,
    long double*       _scratch,
    size_t             _n,
    size_t             _row,
    size_t             _col
)
{
    return d_mat_ld_cofactor(_a, _scratch, _n, _row, _col);
}

D_MATH_FN void
d_mat_cofactor_matrix(
    long double*       _out,
    const long double* _a,
    long double*       _scratch,
    size_t             _n,
    bool               _adjugate
)
{
    return d_mat_ld_cofactor_matrix(_out, _a, _scratch, _n, _adjugate);
}

D_MATH_FN void
d_mat_rotation_2d(
    long double* _out,
    long double  _c,
    long double  _s
)
{
    return d_mat_ld_rotation_2d(_out, _c, _s);
}

D_MATH_FN void
d_mat_rotation_3d(
    long double* _out,
    size_t       _axis,
    long double  _c,
    long double  _s
)
{
    return d_mat_ld_rotation_3d(_out, _axis, _c, _s);
}

D_MATH_FN void
d_mat_rotation_axis(
    long double*       _out,
    const long double* _k,
    long double        _c,
    long double        _s
)
{
    return d_mat_ld_rotation_axis(_out, _k, _c, _s);
}

#endif  // __cplusplus

#endif  // DJINTERP_C_MATH_MAT_H
