/*******************************************************************************
* djinterp [c]                                                            quat.h
*
* Quaternions: the C core of math/quaternion.hpp and
* math/linear_algebra/quaternion.hpp, for float, double and long double.
*   GENERATED by tools/gen_c_math_float.py from one text for the three
* families: edit the generator, not this file.
*
*   A quaternion here is a caller's array [x, y, z, w]; the faces copy
* their four members in and out, which inlining removes. What needs a sine
* or a cosine comes twice, as the elementary functions do: the _c form a
* constant expression from C++14, the plain one on the C library's.
*
*
* path:      /inc/djinterp/c/math/quat.h
* link(s):   TBA
* author(s): Samuel 'teer' Neal-Blim                         created: 2026.10.04
*                                                            revised: 2026.10.04
*******************************************************************************/

/*
TABLE OF CONTENTS
=================
1.  THE FLOAT FAMILY (_f)
    ---------------------
    1.  Algebra
    2.  Rotation
    3.  Construction and interpolation
2.  THE DOUBLE FAMILY (_d)
    ----------------------
    1.  Algebra
    2.  Rotation
    3.  Construction and interpolation
3.  THE LONG DOUBLE FAMILY (_ld)
    ----------------------------
    1.  Algebra
    2.  Rotation
    3.  Construction and interpolation
4.  ONE NAME FOR EVERY FAMILY (C++)
    -------------------------------
*/

#ifndef DJINTERP_C_MATH_QUAT_H
#define DJINTERP_C_MATH_QUAT_H 1

// std
#include <stddef.h>          // size_t
// djinterp
#include "./elementary.h"    // d_math_*_sin, _cos, _acos and their _c forms
#include "./mat.h"           // d_mat_*_identity
#include "./math_common.h"   // D_MATH_FN
#include "./vec.h"           // d_vec_*_cross, _dot, _norm_c, _scale, _add

//==============================================================================
// 1.  THE FLOAT FAMILY (_f)
//==============================================================================
// A quaternion is a caller's array [x, y, z, w]: x i + y j + z k + w. The
// formulas are the quaternion headers' former ones, in their order, one
// operation per statement. _out may be an input except where a kernel says.


// 1.1    Algebra
//------------------------------------------------------------------------------

// d_quat_f_multiply
//   _out = _a _b, the Hamilton product: the rotation _b, then _a. _out may
// be _a or _b.
D_MATH_FN void
d_quat_f_multiply(
    float*       _out,
    const float* _a,
    const float* _b
)
{
    const float ax = _a[0], ay = _a[1], az = _a[2], aw = _a[3];
    const float bx = _b[0], by = _b[1], bz = _b[2], bw = _b[3];
    // x: wx' + xw' + yz' - zy'
    const float x1 = aw * bx;
    const float x2 = ax * bw;
    const float x3 = ay * bz;
    const float x4 = az * by;
    const float x12 = x1 + x2;
    const float x123 = x12 + x3;
    // y: wy' - xz' + yw' + zx'
    const float y1 = aw * by;
    const float y2 = ax * bz;
    const float y3 = ay * bw;
    const float y4 = az * bx;
    const float y12 = y1 - y2;
    const float y123 = y12 + y3;
    // z: wz' + xy' - yx' + zw'
    const float z1 = aw * bz;
    const float z2 = ax * by;
    const float z3 = ay * bx;
    const float z4 = az * bw;
    const float z12 = z1 + z2;
    const float z123 = z12 - z3;
    // w: ww' - xx' - yy' - zz'
    const float w1 = aw * bw;
    const float w2 = ax * bx;
    const float w3 = ay * by;
    const float w4 = az * bz;
    const float w12 = w1 - w2;
    const float w123 = w12 - w3;

    _out[0] = x123 - x4;
    _out[1] = y123 + y4;
    _out[2] = z123 + z4;
    _out[3] = w123 - w4;

    return;
}

// d_quat_f_conjugate
//   _out = (-x, -y, -z, w): the inverse of a unit quaternion.
D_MATH_FN void
d_quat_f_conjugate(
    float*       _out,
    const float* _q
)
{
    _out[0] = -_q[0];
    _out[1] = -_q[1];
    _out[2] = -_q[2];
    _out[3] = _q[3];

    return;
}

// d_quat_f_normalize
//   _out = _q over its norm, the root _norm the caller computed as its
// level allows (the two roots are the same); a zero quaternion is left as it
// is, signs of zero included.
D_MATH_FN void
d_quat_f_normalize(
    float*       _out,
    const float* _q,
    float        _norm
)
{
    size_t i = 0u;

    for (i = 0u; i < 4u; ++i)
    {
        _out[i] = (_norm == (float)0) ? _q[i] : (_q[i] / _norm);
    }

    return;
}

// 1.2    Rotation
//------------------------------------------------------------------------------

// d_quat_f_rotate
//   _out = _v rotated by the unit quaternion _q, v + w t + u x t with u the
// vector part and t = 2 (u x v), without building a matrix. _out may be _v.
D_MATH_FN void
d_quat_f_rotate(
    float*       _out,
    const float* _q,
    const float* _v
)
{
    float t[3]  = { (float)0, (float)0, (float)0 };
    float wt[3] = { (float)0, (float)0, (float)0 };
    float ut[3] = { (float)0, (float)0, (float)0 };

    d_vec_f_cross(t, _q, _v);
    d_vec_f_scale(t, t, (float)2, 3u);
    d_vec_f_scale(wt, t, _q[3], 3u);
    d_vec_f_cross(ut, _q, t);
    d_vec_f_add(_out, _v, wt, 3u);
    d_vec_f_add(_out, _out, ut, 3u);

    return;
}

// d_quat_f_to_matrix3
//   _out (3 x 3) = the rotation matrix of the unit quaternion _q.
D_MATH_FN void
d_quat_f_to_matrix3(
    float*       _out,
    const float* _q
)
{
    const float x  = _q[0];
    const float y  = _q[1];
    const float z  = _q[2];
    const float w  = _q[3];
    const float xx = x * x;
    const float yy = y * y;
    const float zz = z * z;
    const float xy = x * y;
    const float xz = x * z;
    const float yz = y * z;
    const float wx = w * x;
    const float wy = w * y;
    const float wz = w * z;
    // the sums and differences the entries double
    const float yy_zz = yy + zz;
    const float xx_zz = xx + zz;
    const float xx_yy = xx + yy;
    const float xy_m  = xy - wz;
    const float xy_p  = xy + wz;
    const float xz_p  = xz + wy;
    const float xz_m  = xz - wy;
    const float yz_m  = yz - wx;
    const float yz_p  = yz + wx;
    const float d00   = (float)2 * yy_zz;
    const float d11   = (float)2 * xx_zz;
    const float d22   = (float)2 * xx_yy;

    _out[0] = (float)1 - d00;
    _out[1] = (float)2 * xy_m;
    _out[2] = (float)2 * xz_p;
    _out[3] = (float)2 * xy_p;
    _out[4] = (float)1 - d11;
    _out[5] = (float)2 * yz_m;
    _out[6] = (float)2 * xz_m;
    _out[7] = (float)2 * yz_p;
    _out[8] = (float)1 - d22;

    return;
}

// d_quat_f_to_matrix4
//   _out (4 x 4) = the homogeneous rotation matrix of the unit quaternion.
D_MATH_FN void
d_quat_f_to_matrix4(
    float*       _out,
    const float* _q
)
{
    float    r[9] = { (float)0, (float)0, (float)0, (float)0, (float)0,
                    (float)0, (float)0, (float)0, (float)0 };
    size_t i    = 0u;

    d_quat_f_to_matrix3(r, _q);
    d_mat_f_identity(_out, 4u);

    for (i = 0u; i < 3u; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < 3u; ++j)
        {
            _out[(i * 4u) + j] = r[(i * 3u) + j];
        }
    }

    return;
}

// 1.3    Construction and interpolation
//------------------------------------------------------------------------------
// Each needs a sine or a cosine, and so comes twice, as the elementary
// functions do: the _c form a constant expression from C++14, the plain
// one on the C library's.

// d_quat_f_from_axis_angle_c
//   _out = the rotation of _angle radians about _axis, which need not be a
// unit vector: (axis sin(a/2) / |axis|, cos(a/2)). A zero axis names no
// rotation: the identity.
D_MATH_FN void
d_quat_f_from_axis_angle_c(
    float*       _out,
    const float* _axis,
    float        _angle
)
{
    const float length = d_vec_f_norm_c(_axis, 3u);

    // a zero axis names no rotation
    if (length == (float)0)
    {
        _out[0] = (float)0;
        _out[1] = (float)0;
        _out[2] = (float)0;
        _out[3] = (float)1;
    }
    else
    {
        const float half = _angle / (float)2;
        const float sine = d_math_f_sin_c(half);
        const float s    = sine / length;

        _out[0] = _axis[0] * s;
        _out[1] = _axis[1] * s;
        _out[2] = _axis[2] * s;
        _out[3] = d_math_f_cos_c(half);
    }

    return;
}

// d_quat_f_from_unit_axis_angle_c
//   _out = (axis sin(a/2), cos(a/2)) for an axis the caller normalized (a
// zero one gives (0, 0, 0, cos(a/2))).
D_MATH_FN void
d_quat_f_from_unit_axis_angle_c(
    float*       _out,
    const float* _axis,
    float        _angle
)
{
    const float half = _angle / (float)2;
    const float s    = d_math_f_sin_c(half);

    _out[0] = _axis[0] * s;
    _out[1] = _axis[1] * s;
    _out[2] = _axis[2] * s;
    _out[3] = d_math_f_cos_c(half);

    return;
}

// d_quat_f_slerp_c
//   _out = the spherical linear interpolation from _a (t = 0) to _b (t =
// 1), both unit quaternions, along the shorter arc; where the two are
// nearly parallel (dot above 0.9995), the arc is a line, renormalized.
D_MATH_FN void
d_quat_f_slerp_c(
    float*       _out,
    const float* _a,
    const float* _b,
    float        _t
)
{
    float    b[4] = { _b[0], _b[1], _b[2], _b[3] };
    float    d    = d_vec_f_dot(_a, _b, 4u);
    size_t i    = 0u;

    // q and -q are the same rotation: take the one on the shorter arc
    if (d < (float)0)
    {
        d_vec_f_negate(b, b, 4u);
        d = -d;
    }

    // nearly parallel: the arc is a line, and sin(theta) would vanish
    if (d > (float)0.9995)
    {
        float l[4] = { (float)0, (float)0, (float)0, (float)0 };

        for (i = 0u; i < 4u; ++i)
        {
            const float diff = b[i] - _a[i];
            const float step = _t * diff;

            l[i] = _a[i] + step;
        }

        d_quat_f_normalize(_out, l, d_vec_f_norm_c(l, 4u));
    }
    else
    {
        const float theta_0 = d_math_f_acos_c(d);
        const float theta   = theta_0 * _t;
        const float sin_0   = d_math_f_sin_c(theta_0);
        const float rest    = theta_0 - theta;
        const float s_a     = d_math_f_sin_c(rest) / sin_0;
        const float s_b     = d_math_f_sin_c(theta) / sin_0;

        for (i = 0u; i < 4u; ++i)
        {
            const float from = s_a * _a[i];
            const float to   = s_b * b[i];

            _out[i] = from + to;
        }
    }

    return;
}

// d_quat_f_from_axis_angle
//   _out = the rotation of _angle radians about _axis, which need not be a
// unit vector: (axis sin(a/2) / |axis|, cos(a/2)). A zero axis names no
// rotation: the identity.
D_MATH_FN_RT void
d_quat_f_from_axis_angle(
    float*       _out,
    const float* _axis,
    float        _angle
)
{
    const float length = d_vec_f_norm_c(_axis, 3u);

    // a zero axis names no rotation
    if (length == (float)0)
    {
        _out[0] = (float)0;
        _out[1] = (float)0;
        _out[2] = (float)0;
        _out[3] = (float)1;
    }
    else
    {
        const float half = _angle / (float)2;
        const float sine = d_math_f_sin(half);
        const float s    = sine / length;

        _out[0] = _axis[0] * s;
        _out[1] = _axis[1] * s;
        _out[2] = _axis[2] * s;
        _out[3] = d_math_f_cos(half);
    }

    return;
}

// d_quat_f_from_unit_axis_angle
//   _out = (axis sin(a/2), cos(a/2)) for an axis the caller normalized (a
// zero one gives (0, 0, 0, cos(a/2))).
D_MATH_FN_RT void
d_quat_f_from_unit_axis_angle(
    float*       _out,
    const float* _axis,
    float        _angle
)
{
    const float half = _angle / (float)2;
    const float s    = d_math_f_sin(half);

    _out[0] = _axis[0] * s;
    _out[1] = _axis[1] * s;
    _out[2] = _axis[2] * s;
    _out[3] = d_math_f_cos(half);

    return;
}

// d_quat_f_slerp
//   _out = the spherical linear interpolation from _a (t = 0) to _b (t =
// 1), both unit quaternions, along the shorter arc; where the two are
// nearly parallel (dot above 0.9995), the arc is a line, renormalized.
D_MATH_FN_RT void
d_quat_f_slerp(
    float*       _out,
    const float* _a,
    const float* _b,
    float        _t
)
{
    float    b[4] = { _b[0], _b[1], _b[2], _b[3] };
    float    d    = d_vec_f_dot(_a, _b, 4u);
    size_t i    = 0u;

    // q and -q are the same rotation: take the one on the shorter arc
    if (d < (float)0)
    {
        d_vec_f_negate(b, b, 4u);
        d = -d;
    }

    // nearly parallel: the arc is a line, and sin(theta) would vanish
    if (d > (float)0.9995)
    {
        float l[4] = { (float)0, (float)0, (float)0, (float)0 };

        for (i = 0u; i < 4u; ++i)
        {
            const float diff = b[i] - _a[i];
            const float step = _t * diff;

            l[i] = _a[i] + step;
        }

        d_quat_f_normalize(_out, l, d_vec_f_norm_c(l, 4u));
    }
    else
    {
        const float theta_0 = d_math_f_acos(d);
        const float theta   = theta_0 * _t;
        const float sin_0   = d_math_f_sin(theta_0);
        const float rest    = theta_0 - theta;
        const float s_a     = d_math_f_sin(rest) / sin_0;
        const float s_b     = d_math_f_sin(theta) / sin_0;

        for (i = 0u; i < 4u; ++i)
        {
            const float from = s_a * _a[i];
            const float to   = s_b * b[i];

            _out[i] = from + to;
        }
    }

    return;
}

//==============================================================================
// 2.  THE DOUBLE FAMILY (_d)
//==============================================================================
// A quaternion is a caller's array [x, y, z, w]: x i + y j + z k + w. The
// formulas are the quaternion headers' former ones, in their order, one
// operation per statement. _out may be an input except where a kernel says.


// 2.1    Algebra
//------------------------------------------------------------------------------

// d_quat_d_multiply
//   _out = _a _b, the Hamilton product: the rotation _b, then _a. _out may
// be _a or _b.
D_MATH_FN void
d_quat_d_multiply(
    double*       _out,
    const double* _a,
    const double* _b
)
{
    const double ax = _a[0], ay = _a[1], az = _a[2], aw = _a[3];
    const double bx = _b[0], by = _b[1], bz = _b[2], bw = _b[3];
    // x: wx' + xw' + yz' - zy'
    const double x1 = aw * bx;
    const double x2 = ax * bw;
    const double x3 = ay * bz;
    const double x4 = az * by;
    const double x12 = x1 + x2;
    const double x123 = x12 + x3;
    // y: wy' - xz' + yw' + zx'
    const double y1 = aw * by;
    const double y2 = ax * bz;
    const double y3 = ay * bw;
    const double y4 = az * bx;
    const double y12 = y1 - y2;
    const double y123 = y12 + y3;
    // z: wz' + xy' - yx' + zw'
    const double z1 = aw * bz;
    const double z2 = ax * by;
    const double z3 = ay * bx;
    const double z4 = az * bw;
    const double z12 = z1 + z2;
    const double z123 = z12 - z3;
    // w: ww' - xx' - yy' - zz'
    const double w1 = aw * bw;
    const double w2 = ax * bx;
    const double w3 = ay * by;
    const double w4 = az * bz;
    const double w12 = w1 - w2;
    const double w123 = w12 - w3;

    _out[0] = x123 - x4;
    _out[1] = y123 + y4;
    _out[2] = z123 + z4;
    _out[3] = w123 - w4;

    return;
}

// d_quat_d_conjugate
//   _out = (-x, -y, -z, w): the inverse of a unit quaternion.
D_MATH_FN void
d_quat_d_conjugate(
    double*       _out,
    const double* _q
)
{
    _out[0] = -_q[0];
    _out[1] = -_q[1];
    _out[2] = -_q[2];
    _out[3] = _q[3];

    return;
}

// d_quat_d_normalize
//   _out = _q over its norm, the root _norm the caller computed as its
// level allows (the two roots are the same); a zero quaternion is left as it
// is, signs of zero included.
D_MATH_FN void
d_quat_d_normalize(
    double*       _out,
    const double* _q,
    double        _norm
)
{
    size_t i = 0u;

    for (i = 0u; i < 4u; ++i)
    {
        _out[i] = (_norm == (double)0) ? _q[i] : (_q[i] / _norm);
    }

    return;
}

// 2.2    Rotation
//------------------------------------------------------------------------------

// d_quat_d_rotate
//   _out = _v rotated by the unit quaternion _q, v + w t + u x t with u the
// vector part and t = 2 (u x v), without building a matrix. _out may be _v.
D_MATH_FN void
d_quat_d_rotate(
    double*       _out,
    const double* _q,
    const double* _v
)
{
    double t[3]  = { (double)0, (double)0, (double)0 };
    double wt[3] = { (double)0, (double)0, (double)0 };
    double ut[3] = { (double)0, (double)0, (double)0 };

    d_vec_d_cross(t, _q, _v);
    d_vec_d_scale(t, t, (double)2, 3u);
    d_vec_d_scale(wt, t, _q[3], 3u);
    d_vec_d_cross(ut, _q, t);
    d_vec_d_add(_out, _v, wt, 3u);
    d_vec_d_add(_out, _out, ut, 3u);

    return;
}

// d_quat_d_to_matrix3
//   _out (3 x 3) = the rotation matrix of the unit quaternion _q.
D_MATH_FN void
d_quat_d_to_matrix3(
    double*       _out,
    const double* _q
)
{
    const double x  = _q[0];
    const double y  = _q[1];
    const double z  = _q[2];
    const double w  = _q[3];
    const double xx = x * x;
    const double yy = y * y;
    const double zz = z * z;
    const double xy = x * y;
    const double xz = x * z;
    const double yz = y * z;
    const double wx = w * x;
    const double wy = w * y;
    const double wz = w * z;
    // the sums and differences the entries double
    const double yy_zz = yy + zz;
    const double xx_zz = xx + zz;
    const double xx_yy = xx + yy;
    const double xy_m  = xy - wz;
    const double xy_p  = xy + wz;
    const double xz_p  = xz + wy;
    const double xz_m  = xz - wy;
    const double yz_m  = yz - wx;
    const double yz_p  = yz + wx;
    const double d00   = (double)2 * yy_zz;
    const double d11   = (double)2 * xx_zz;
    const double d22   = (double)2 * xx_yy;

    _out[0] = (double)1 - d00;
    _out[1] = (double)2 * xy_m;
    _out[2] = (double)2 * xz_p;
    _out[3] = (double)2 * xy_p;
    _out[4] = (double)1 - d11;
    _out[5] = (double)2 * yz_m;
    _out[6] = (double)2 * xz_m;
    _out[7] = (double)2 * yz_p;
    _out[8] = (double)1 - d22;

    return;
}

// d_quat_d_to_matrix4
//   _out (4 x 4) = the homogeneous rotation matrix of the unit quaternion.
D_MATH_FN void
d_quat_d_to_matrix4(
    double*       _out,
    const double* _q
)
{
    double    r[9] = { (double)0, (double)0, (double)0, (double)0, (double)0,
                    (double)0, (double)0, (double)0, (double)0 };
    size_t i    = 0u;

    d_quat_d_to_matrix3(r, _q);
    d_mat_d_identity(_out, 4u);

    for (i = 0u; i < 3u; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < 3u; ++j)
        {
            _out[(i * 4u) + j] = r[(i * 3u) + j];
        }
    }

    return;
}

// 2.3    Construction and interpolation
//------------------------------------------------------------------------------
// Each needs a sine or a cosine, and so comes twice, as the elementary
// functions do: the _c form a constant expression from C++14, the plain
// one on the C library's.

// d_quat_d_from_axis_angle_c
//   _out = the rotation of _angle radians about _axis, which need not be a
// unit vector: (axis sin(a/2) / |axis|, cos(a/2)). A zero axis names no
// rotation: the identity.
D_MATH_FN void
d_quat_d_from_axis_angle_c(
    double*       _out,
    const double* _axis,
    double        _angle
)
{
    const double length = d_vec_d_norm_c(_axis, 3u);

    // a zero axis names no rotation
    if (length == (double)0)
    {
        _out[0] = (double)0;
        _out[1] = (double)0;
        _out[2] = (double)0;
        _out[3] = (double)1;
    }
    else
    {
        const double half = _angle / (double)2;
        const double sine = d_math_d_sin_c(half);
        const double s    = sine / length;

        _out[0] = _axis[0] * s;
        _out[1] = _axis[1] * s;
        _out[2] = _axis[2] * s;
        _out[3] = d_math_d_cos_c(half);
    }

    return;
}

// d_quat_d_from_unit_axis_angle_c
//   _out = (axis sin(a/2), cos(a/2)) for an axis the caller normalized (a
// zero one gives (0, 0, 0, cos(a/2))).
D_MATH_FN void
d_quat_d_from_unit_axis_angle_c(
    double*       _out,
    const double* _axis,
    double        _angle
)
{
    const double half = _angle / (double)2;
    const double s    = d_math_d_sin_c(half);

    _out[0] = _axis[0] * s;
    _out[1] = _axis[1] * s;
    _out[2] = _axis[2] * s;
    _out[3] = d_math_d_cos_c(half);

    return;
}

// d_quat_d_slerp_c
//   _out = the spherical linear interpolation from _a (t = 0) to _b (t =
// 1), both unit quaternions, along the shorter arc; where the two are
// nearly parallel (dot above 0.9995), the arc is a line, renormalized.
D_MATH_FN void
d_quat_d_slerp_c(
    double*       _out,
    const double* _a,
    const double* _b,
    double        _t
)
{
    double    b[4] = { _b[0], _b[1], _b[2], _b[3] };
    double    d    = d_vec_d_dot(_a, _b, 4u);
    size_t i    = 0u;

    // q and -q are the same rotation: take the one on the shorter arc
    if (d < (double)0)
    {
        d_vec_d_negate(b, b, 4u);
        d = -d;
    }

    // nearly parallel: the arc is a line, and sin(theta) would vanish
    if (d > (double)0.9995)
    {
        double l[4] = { (double)0, (double)0, (double)0, (double)0 };

        for (i = 0u; i < 4u; ++i)
        {
            const double diff = b[i] - _a[i];
            const double step = _t * diff;

            l[i] = _a[i] + step;
        }

        d_quat_d_normalize(_out, l, d_vec_d_norm_c(l, 4u));
    }
    else
    {
        const double theta_0 = d_math_d_acos_c(d);
        const double theta   = theta_0 * _t;
        const double sin_0   = d_math_d_sin_c(theta_0);
        const double rest    = theta_0 - theta;
        const double s_a     = d_math_d_sin_c(rest) / sin_0;
        const double s_b     = d_math_d_sin_c(theta) / sin_0;

        for (i = 0u; i < 4u; ++i)
        {
            const double from = s_a * _a[i];
            const double to   = s_b * b[i];

            _out[i] = from + to;
        }
    }

    return;
}

// d_quat_d_from_axis_angle
//   _out = the rotation of _angle radians about _axis, which need not be a
// unit vector: (axis sin(a/2) / |axis|, cos(a/2)). A zero axis names no
// rotation: the identity.
D_MATH_FN_RT void
d_quat_d_from_axis_angle(
    double*       _out,
    const double* _axis,
    double        _angle
)
{
    const double length = d_vec_d_norm_c(_axis, 3u);

    // a zero axis names no rotation
    if (length == (double)0)
    {
        _out[0] = (double)0;
        _out[1] = (double)0;
        _out[2] = (double)0;
        _out[3] = (double)1;
    }
    else
    {
        const double half = _angle / (double)2;
        const double sine = d_math_d_sin(half);
        const double s    = sine / length;

        _out[0] = _axis[0] * s;
        _out[1] = _axis[1] * s;
        _out[2] = _axis[2] * s;
        _out[3] = d_math_d_cos(half);
    }

    return;
}

// d_quat_d_from_unit_axis_angle
//   _out = (axis sin(a/2), cos(a/2)) for an axis the caller normalized (a
// zero one gives (0, 0, 0, cos(a/2))).
D_MATH_FN_RT void
d_quat_d_from_unit_axis_angle(
    double*       _out,
    const double* _axis,
    double        _angle
)
{
    const double half = _angle / (double)2;
    const double s    = d_math_d_sin(half);

    _out[0] = _axis[0] * s;
    _out[1] = _axis[1] * s;
    _out[2] = _axis[2] * s;
    _out[3] = d_math_d_cos(half);

    return;
}

// d_quat_d_slerp
//   _out = the spherical linear interpolation from _a (t = 0) to _b (t =
// 1), both unit quaternions, along the shorter arc; where the two are
// nearly parallel (dot above 0.9995), the arc is a line, renormalized.
D_MATH_FN_RT void
d_quat_d_slerp(
    double*       _out,
    const double* _a,
    const double* _b,
    double        _t
)
{
    double    b[4] = { _b[0], _b[1], _b[2], _b[3] };
    double    d    = d_vec_d_dot(_a, _b, 4u);
    size_t i    = 0u;

    // q and -q are the same rotation: take the one on the shorter arc
    if (d < (double)0)
    {
        d_vec_d_negate(b, b, 4u);
        d = -d;
    }

    // nearly parallel: the arc is a line, and sin(theta) would vanish
    if (d > (double)0.9995)
    {
        double l[4] = { (double)0, (double)0, (double)0, (double)0 };

        for (i = 0u; i < 4u; ++i)
        {
            const double diff = b[i] - _a[i];
            const double step = _t * diff;

            l[i] = _a[i] + step;
        }

        d_quat_d_normalize(_out, l, d_vec_d_norm_c(l, 4u));
    }
    else
    {
        const double theta_0 = d_math_d_acos(d);
        const double theta   = theta_0 * _t;
        const double sin_0   = d_math_d_sin(theta_0);
        const double rest    = theta_0 - theta;
        const double s_a     = d_math_d_sin(rest) / sin_0;
        const double s_b     = d_math_d_sin(theta) / sin_0;

        for (i = 0u; i < 4u; ++i)
        {
            const double from = s_a * _a[i];
            const double to   = s_b * b[i];

            _out[i] = from + to;
        }
    }

    return;
}

//==============================================================================
// 3.  THE LONG DOUBLE FAMILY (_ld)
//==============================================================================
// A quaternion is a caller's array [x, y, z, w]: x i + y j + z k + w. The
// formulas are the quaternion headers' former ones, in their order, one
// operation per statement. _out may be an input except where a kernel says.


// 3.1    Algebra
//------------------------------------------------------------------------------

// d_quat_ld_multiply
//   _out = _a _b, the Hamilton product: the rotation _b, then _a. _out may
// be _a or _b.
D_MATH_FN void
d_quat_ld_multiply(
    long double*       _out,
    const long double* _a,
    const long double* _b
)
{
    const long double ax = _a[0], ay = _a[1], az = _a[2], aw = _a[3];
    const long double bx = _b[0], by = _b[1], bz = _b[2], bw = _b[3];
    // x: wx' + xw' + yz' - zy'
    const long double x1 = aw * bx;
    const long double x2 = ax * bw;
    const long double x3 = ay * bz;
    const long double x4 = az * by;
    const long double x12 = x1 + x2;
    const long double x123 = x12 + x3;
    // y: wy' - xz' + yw' + zx'
    const long double y1 = aw * by;
    const long double y2 = ax * bz;
    const long double y3 = ay * bw;
    const long double y4 = az * bx;
    const long double y12 = y1 - y2;
    const long double y123 = y12 + y3;
    // z: wz' + xy' - yx' + zw'
    const long double z1 = aw * bz;
    const long double z2 = ax * by;
    const long double z3 = ay * bx;
    const long double z4 = az * bw;
    const long double z12 = z1 + z2;
    const long double z123 = z12 - z3;
    // w: ww' - xx' - yy' - zz'
    const long double w1 = aw * bw;
    const long double w2 = ax * bx;
    const long double w3 = ay * by;
    const long double w4 = az * bz;
    const long double w12 = w1 - w2;
    const long double w123 = w12 - w3;

    _out[0] = x123 - x4;
    _out[1] = y123 + y4;
    _out[2] = z123 + z4;
    _out[3] = w123 - w4;

    return;
}

// d_quat_ld_conjugate
//   _out = (-x, -y, -z, w): the inverse of a unit quaternion.
D_MATH_FN void
d_quat_ld_conjugate(
    long double*       _out,
    const long double* _q
)
{
    _out[0] = -_q[0];
    _out[1] = -_q[1];
    _out[2] = -_q[2];
    _out[3] = _q[3];

    return;
}

// d_quat_ld_normalize
//   _out = _q over its norm, the root _norm the caller computed as its
// level allows (the two roots are the same); a zero quaternion is left as it
// is, signs of zero included.
D_MATH_FN void
d_quat_ld_normalize(
    long double*       _out,
    const long double* _q,
    long double        _norm
)
{
    size_t i = 0u;

    for (i = 0u; i < 4u; ++i)
    {
        _out[i] = (_norm == (long double)0) ? _q[i] : (_q[i] / _norm);
    }

    return;
}

// 3.2    Rotation
//------------------------------------------------------------------------------

// d_quat_ld_rotate
//   _out = _v rotated by the unit quaternion _q, v + w t + u x t with u the
// vector part and t = 2 (u x v), without building a matrix. _out may be _v.
D_MATH_FN void
d_quat_ld_rotate(
    long double*       _out,
    const long double* _q,
    const long double* _v
)
{
    long double t[3]  = { (long double)0, (long double)0, (long double)0 };
    long double wt[3] = { (long double)0, (long double)0, (long double)0 };
    long double ut[3] = { (long double)0, (long double)0, (long double)0 };

    d_vec_ld_cross(t, _q, _v);
    d_vec_ld_scale(t, t, (long double)2, 3u);
    d_vec_ld_scale(wt, t, _q[3], 3u);
    d_vec_ld_cross(ut, _q, t);
    d_vec_ld_add(_out, _v, wt, 3u);
    d_vec_ld_add(_out, _out, ut, 3u);

    return;
}

// d_quat_ld_to_matrix3
//   _out (3 x 3) = the rotation matrix of the unit quaternion _q.
D_MATH_FN void
d_quat_ld_to_matrix3(
    long double*       _out,
    const long double* _q
)
{
    const long double x  = _q[0];
    const long double y  = _q[1];
    const long double z  = _q[2];
    const long double w  = _q[3];
    const long double xx = x * x;
    const long double yy = y * y;
    const long double zz = z * z;
    const long double xy = x * y;
    const long double xz = x * z;
    const long double yz = y * z;
    const long double wx = w * x;
    const long double wy = w * y;
    const long double wz = w * z;
    // the sums and differences the entries double
    const long double yy_zz = yy + zz;
    const long double xx_zz = xx + zz;
    const long double xx_yy = xx + yy;
    const long double xy_m  = xy - wz;
    const long double xy_p  = xy + wz;
    const long double xz_p  = xz + wy;
    const long double xz_m  = xz - wy;
    const long double yz_m  = yz - wx;
    const long double yz_p  = yz + wx;
    const long double d00   = (long double)2 * yy_zz;
    const long double d11   = (long double)2 * xx_zz;
    const long double d22   = (long double)2 * xx_yy;

    _out[0] = (long double)1 - d00;
    _out[1] = (long double)2 * xy_m;
    _out[2] = (long double)2 * xz_p;
    _out[3] = (long double)2 * xy_p;
    _out[4] = (long double)1 - d11;
    _out[5] = (long double)2 * yz_m;
    _out[6] = (long double)2 * xz_m;
    _out[7] = (long double)2 * yz_p;
    _out[8] = (long double)1 - d22;

    return;
}

// d_quat_ld_to_matrix4
//   _out (4 x 4) = the homogeneous rotation matrix of the unit quaternion.
D_MATH_FN void
d_quat_ld_to_matrix4(
    long double*       _out,
    const long double* _q
)
{
    long double    r[9] = { (long double)0, (long double)0, (long double)0, (long double)0, (long double)0,
                    (long double)0, (long double)0, (long double)0, (long double)0 };
    size_t i    = 0u;

    d_quat_ld_to_matrix3(r, _q);
    d_mat_ld_identity(_out, 4u);

    for (i = 0u; i < 3u; ++i)
    {
        size_t j = 0u;

        for (j = 0u; j < 3u; ++j)
        {
            _out[(i * 4u) + j] = r[(i * 3u) + j];
        }
    }

    return;
}

// 3.3    Construction and interpolation
//------------------------------------------------------------------------------
// Each needs a sine or a cosine, and so comes twice, as the elementary
// functions do: the _c form a constant expression from C++14, the plain
// one on the C library's.

// d_quat_ld_from_axis_angle_c
//   _out = the rotation of _angle radians about _axis, which need not be a
// unit vector: (axis sin(a/2) / |axis|, cos(a/2)). A zero axis names no
// rotation: the identity.
D_MATH_FN void
d_quat_ld_from_axis_angle_c(
    long double*       _out,
    const long double* _axis,
    long double        _angle
)
{
    const long double length = d_vec_ld_norm_c(_axis, 3u);

    // a zero axis names no rotation
    if (length == (long double)0)
    {
        _out[0] = (long double)0;
        _out[1] = (long double)0;
        _out[2] = (long double)0;
        _out[3] = (long double)1;
    }
    else
    {
        const long double half = _angle / (long double)2;
        const long double sine = d_math_ld_sin_c(half);
        const long double s    = sine / length;

        _out[0] = _axis[0] * s;
        _out[1] = _axis[1] * s;
        _out[2] = _axis[2] * s;
        _out[3] = d_math_ld_cos_c(half);
    }

    return;
}

// d_quat_ld_from_unit_axis_angle_c
//   _out = (axis sin(a/2), cos(a/2)) for an axis the caller normalized (a
// zero one gives (0, 0, 0, cos(a/2))).
D_MATH_FN void
d_quat_ld_from_unit_axis_angle_c(
    long double*       _out,
    const long double* _axis,
    long double        _angle
)
{
    const long double half = _angle / (long double)2;
    const long double s    = d_math_ld_sin_c(half);

    _out[0] = _axis[0] * s;
    _out[1] = _axis[1] * s;
    _out[2] = _axis[2] * s;
    _out[3] = d_math_ld_cos_c(half);

    return;
}

// d_quat_ld_slerp_c
//   _out = the spherical linear interpolation from _a (t = 0) to _b (t =
// 1), both unit quaternions, along the shorter arc; where the two are
// nearly parallel (dot above 0.9995), the arc is a line, renormalized.
D_MATH_FN void
d_quat_ld_slerp_c(
    long double*       _out,
    const long double* _a,
    const long double* _b,
    long double        _t
)
{
    long double    b[4] = { _b[0], _b[1], _b[2], _b[3] };
    long double    d    = d_vec_ld_dot(_a, _b, 4u);
    size_t i    = 0u;

    // q and -q are the same rotation: take the one on the shorter arc
    if (d < (long double)0)
    {
        d_vec_ld_negate(b, b, 4u);
        d = -d;
    }

    // nearly parallel: the arc is a line, and sin(theta) would vanish
    if (d > (long double)0.9995)
    {
        long double l[4] = { (long double)0, (long double)0, (long double)0, (long double)0 };

        for (i = 0u; i < 4u; ++i)
        {
            const long double diff = b[i] - _a[i];
            const long double step = _t * diff;

            l[i] = _a[i] + step;
        }

        d_quat_ld_normalize(_out, l, d_vec_ld_norm_c(l, 4u));
    }
    else
    {
        const long double theta_0 = d_math_ld_acos_c(d);
        const long double theta   = theta_0 * _t;
        const long double sin_0   = d_math_ld_sin_c(theta_0);
        const long double rest    = theta_0 - theta;
        const long double s_a     = d_math_ld_sin_c(rest) / sin_0;
        const long double s_b     = d_math_ld_sin_c(theta) / sin_0;

        for (i = 0u; i < 4u; ++i)
        {
            const long double from = s_a * _a[i];
            const long double to   = s_b * b[i];

            _out[i] = from + to;
        }
    }

    return;
}

// d_quat_ld_from_axis_angle
//   _out = the rotation of _angle radians about _axis, which need not be a
// unit vector: (axis sin(a/2) / |axis|, cos(a/2)). A zero axis names no
// rotation: the identity.
D_MATH_FN_RT void
d_quat_ld_from_axis_angle(
    long double*       _out,
    const long double* _axis,
    long double        _angle
)
{
    const long double length = d_vec_ld_norm_c(_axis, 3u);

    // a zero axis names no rotation
    if (length == (long double)0)
    {
        _out[0] = (long double)0;
        _out[1] = (long double)0;
        _out[2] = (long double)0;
        _out[3] = (long double)1;
    }
    else
    {
        const long double half = _angle / (long double)2;
        const long double sine = d_math_ld_sin(half);
        const long double s    = sine / length;

        _out[0] = _axis[0] * s;
        _out[1] = _axis[1] * s;
        _out[2] = _axis[2] * s;
        _out[3] = d_math_ld_cos(half);
    }

    return;
}

// d_quat_ld_from_unit_axis_angle
//   _out = (axis sin(a/2), cos(a/2)) for an axis the caller normalized (a
// zero one gives (0, 0, 0, cos(a/2))).
D_MATH_FN_RT void
d_quat_ld_from_unit_axis_angle(
    long double*       _out,
    const long double* _axis,
    long double        _angle
)
{
    const long double half = _angle / (long double)2;
    const long double s    = d_math_ld_sin(half);

    _out[0] = _axis[0] * s;
    _out[1] = _axis[1] * s;
    _out[2] = _axis[2] * s;
    _out[3] = d_math_ld_cos(half);

    return;
}

// d_quat_ld_slerp
//   _out = the spherical linear interpolation from _a (t = 0) to _b (t =
// 1), both unit quaternions, along the shorter arc; where the two are
// nearly parallel (dot above 0.9995), the arc is a line, renormalized.
D_MATH_FN_RT void
d_quat_ld_slerp(
    long double*       _out,
    const long double* _a,
    const long double* _b,
    long double        _t
)
{
    long double    b[4] = { _b[0], _b[1], _b[2], _b[3] };
    long double    d    = d_vec_ld_dot(_a, _b, 4u);
    size_t i    = 0u;

    // q and -q are the same rotation: take the one on the shorter arc
    if (d < (long double)0)
    {
        d_vec_ld_negate(b, b, 4u);
        d = -d;
    }

    // nearly parallel: the arc is a line, and sin(theta) would vanish
    if (d > (long double)0.9995)
    {
        long double l[4] = { (long double)0, (long double)0, (long double)0, (long double)0 };

        for (i = 0u; i < 4u; ++i)
        {
            const long double diff = b[i] - _a[i];
            const long double step = _t * diff;

            l[i] = _a[i] + step;
        }

        d_quat_ld_normalize(_out, l, d_vec_ld_norm_c(l, 4u));
    }
    else
    {
        const long double theta_0 = d_math_ld_acos(d);
        const long double theta   = theta_0 * _t;
        const long double sin_0   = d_math_ld_sin(theta_0);
        const long double rest    = theta_0 - theta;
        const long double s_a     = d_math_ld_sin(rest) / sin_0;
        const long double s_b     = d_math_ld_sin(theta) / sin_0;

        for (i = 0u; i < 4u; ++i)
        {
            const long double from = s_a * _a[i];
            const long double to   = s_b * b[i];

            _out[i] = from + to;
        }
    }

    return;
}


#ifdef __cplusplus

//==============================================================================
// 4.  ONE NAME FOR EVERY FAMILY (C++)
//==============================================================================
// C++ only: the kernels above under one name each, chosen by argument type,
// so a C++ template serves float, double and long double alike.


D_MATH_FN void
d_quat_multiply(
    float*       _out,
    const float* _a,
    const float* _b
)
{
    return d_quat_f_multiply(_out, _a, _b);
}

D_MATH_FN void
d_quat_conjugate(
    float*       _out,
    const float* _q
)
{
    return d_quat_f_conjugate(_out, _q);
}

D_MATH_FN void
d_quat_normalize(
    float*       _out,
    const float* _q,
    float        _norm
)
{
    return d_quat_f_normalize(_out, _q, _norm);
}

D_MATH_FN void
d_quat_rotate(
    float*       _out,
    const float* _q,
    const float* _v
)
{
    return d_quat_f_rotate(_out, _q, _v);
}

D_MATH_FN void
d_quat_to_matrix3(
    float*       _out,
    const float* _q
)
{
    return d_quat_f_to_matrix3(_out, _q);
}

D_MATH_FN void
d_quat_to_matrix4(
    float*       _out,
    const float* _q
)
{
    return d_quat_f_to_matrix4(_out, _q);
}

D_MATH_FN void
d_quat_from_axis_angle_c(
    float*       _out,
    const float* _axis,
    float        _angle
)
{
    return d_quat_f_from_axis_angle_c(_out, _axis, _angle);
}

D_MATH_FN void
d_quat_from_unit_axis_angle_c(
    float*       _out,
    const float* _axis,
    float        _angle
)
{
    return d_quat_f_from_unit_axis_angle_c(_out, _axis, _angle);
}

D_MATH_FN void
d_quat_slerp_c(
    float*       _out,
    const float* _a,
    const float* _b,
    float        _t
)
{
    return d_quat_f_slerp_c(_out, _a, _b, _t);
}

D_MATH_FN_RT void
d_quat_from_axis_angle(
    float*       _out,
    const float* _axis,
    float        _angle
)
{
    return d_quat_f_from_axis_angle(_out, _axis, _angle);
}

D_MATH_FN_RT void
d_quat_from_unit_axis_angle(
    float*       _out,
    const float* _axis,
    float        _angle
)
{
    return d_quat_f_from_unit_axis_angle(_out, _axis, _angle);
}

D_MATH_FN_RT void
d_quat_slerp(
    float*       _out,
    const float* _a,
    const float* _b,
    float        _t
)
{
    return d_quat_f_slerp(_out, _a, _b, _t);
}

D_MATH_FN void
d_quat_multiply(
    double*       _out,
    const double* _a,
    const double* _b
)
{
    return d_quat_d_multiply(_out, _a, _b);
}

D_MATH_FN void
d_quat_conjugate(
    double*       _out,
    const double* _q
)
{
    return d_quat_d_conjugate(_out, _q);
}

D_MATH_FN void
d_quat_normalize(
    double*       _out,
    const double* _q,
    double        _norm
)
{
    return d_quat_d_normalize(_out, _q, _norm);
}

D_MATH_FN void
d_quat_rotate(
    double*       _out,
    const double* _q,
    const double* _v
)
{
    return d_quat_d_rotate(_out, _q, _v);
}

D_MATH_FN void
d_quat_to_matrix3(
    double*       _out,
    const double* _q
)
{
    return d_quat_d_to_matrix3(_out, _q);
}

D_MATH_FN void
d_quat_to_matrix4(
    double*       _out,
    const double* _q
)
{
    return d_quat_d_to_matrix4(_out, _q);
}

D_MATH_FN void
d_quat_from_axis_angle_c(
    double*       _out,
    const double* _axis,
    double        _angle
)
{
    return d_quat_d_from_axis_angle_c(_out, _axis, _angle);
}

D_MATH_FN void
d_quat_from_unit_axis_angle_c(
    double*       _out,
    const double* _axis,
    double        _angle
)
{
    return d_quat_d_from_unit_axis_angle_c(_out, _axis, _angle);
}

D_MATH_FN void
d_quat_slerp_c(
    double*       _out,
    const double* _a,
    const double* _b,
    double        _t
)
{
    return d_quat_d_slerp_c(_out, _a, _b, _t);
}

D_MATH_FN_RT void
d_quat_from_axis_angle(
    double*       _out,
    const double* _axis,
    double        _angle
)
{
    return d_quat_d_from_axis_angle(_out, _axis, _angle);
}

D_MATH_FN_RT void
d_quat_from_unit_axis_angle(
    double*       _out,
    const double* _axis,
    double        _angle
)
{
    return d_quat_d_from_unit_axis_angle(_out, _axis, _angle);
}

D_MATH_FN_RT void
d_quat_slerp(
    double*       _out,
    const double* _a,
    const double* _b,
    double        _t
)
{
    return d_quat_d_slerp(_out, _a, _b, _t);
}

D_MATH_FN void
d_quat_multiply(
    long double*       _out,
    const long double* _a,
    const long double* _b
)
{
    return d_quat_ld_multiply(_out, _a, _b);
}

D_MATH_FN void
d_quat_conjugate(
    long double*       _out,
    const long double* _q
)
{
    return d_quat_ld_conjugate(_out, _q);
}

D_MATH_FN void
d_quat_normalize(
    long double*       _out,
    const long double* _q,
    long double        _norm
)
{
    return d_quat_ld_normalize(_out, _q, _norm);
}

D_MATH_FN void
d_quat_rotate(
    long double*       _out,
    const long double* _q,
    const long double* _v
)
{
    return d_quat_ld_rotate(_out, _q, _v);
}

D_MATH_FN void
d_quat_to_matrix3(
    long double*       _out,
    const long double* _q
)
{
    return d_quat_ld_to_matrix3(_out, _q);
}

D_MATH_FN void
d_quat_to_matrix4(
    long double*       _out,
    const long double* _q
)
{
    return d_quat_ld_to_matrix4(_out, _q);
}

D_MATH_FN void
d_quat_from_axis_angle_c(
    long double*       _out,
    const long double* _axis,
    long double        _angle
)
{
    return d_quat_ld_from_axis_angle_c(_out, _axis, _angle);
}

D_MATH_FN void
d_quat_from_unit_axis_angle_c(
    long double*       _out,
    const long double* _axis,
    long double        _angle
)
{
    return d_quat_ld_from_unit_axis_angle_c(_out, _axis, _angle);
}

D_MATH_FN void
d_quat_slerp_c(
    long double*       _out,
    const long double* _a,
    const long double* _b,
    long double        _t
)
{
    return d_quat_ld_slerp_c(_out, _a, _b, _t);
}

D_MATH_FN_RT void
d_quat_from_axis_angle(
    long double*       _out,
    const long double* _axis,
    long double        _angle
)
{
    return d_quat_ld_from_axis_angle(_out, _axis, _angle);
}

D_MATH_FN_RT void
d_quat_from_unit_axis_angle(
    long double*       _out,
    const long double* _axis,
    long double        _angle
)
{
    return d_quat_ld_from_unit_axis_angle(_out, _axis, _angle);
}

D_MATH_FN_RT void
d_quat_slerp(
    long double*       _out,
    const long double* _a,
    const long double* _b,
    long double        _t
)
{
    return d_quat_ld_slerp(_out, _a, _b, _t);
}

#endif  // __cplusplus

#endif  // DJINTERP_C_MATH_QUAT_H
