/*******************************************************************************
* djinterp [c]                                                             vec.h
*
* Fixed-size vectors: the C core of math/linear_algebra/vector.hpp, for
* float, double and long double.
*   GENERATED by tools/gen_c_math_float.py from one text for the three
* families: edit the generator, not this file.
*
*   A vector here is an array of _count components the caller owns, as
* BLAS takes them; the C++ face's storage is that array. Each kernel is a
* loop the face's constant dimension unrolls, a constant expression from
* C++14 but for the plain root forms, which call the C library.
*
*
* path:      /inc/djinterp/c/math/vec.h
* link(s):   TBA
* author(s): Samuel 'teer' Neal-Blim                         created: 2026.10.04
*                                                            revised: 2026.10.04
*******************************************************************************/

/*
TABLE OF CONTENTS
=================
1.  THE FLOAT FAMILY (_f)
    ---------------------
    1.  Element-wise arithmetic
    2.  Products and reductions
    3.  Norms and distances
    4.  Projection and angle
    5.  Comparison
2.  THE DOUBLE FAMILY (_d)
    ----------------------
    1.  Element-wise arithmetic
    2.  Products and reductions
    3.  Norms and distances
    4.  Projection and angle
    5.  Comparison
3.  THE LONG DOUBLE FAMILY (_ld)
    ----------------------------
    1.  Element-wise arithmetic
    2.  Products and reductions
    3.  Norms and distances
    4.  Projection and angle
    5.  Comparison
4.  ONE NAME FOR EVERY FAMILY (C++)
    -------------------------------
*/

#ifndef DJINTERP_C_MATH_VEC_H
#define DJINTERP_C_MATH_VEC_H 1

// std
#include <stddef.h>          // size_t
// djinterp
#include "./elementary.h"    // d_math_*_sqrt, _sqrt_c, _acos, _acos_c
#include "./math_common.h"   // D_MATH_FN

//==============================================================================
// 1.  THE FLOAT FAMILY (_f)
//==============================================================================
// _count components each; _out may be _a or _b.


// 1.1    Element-wise arithmetic
//------------------------------------------------------------------------------

D_MATH_FN void
d_vec_f_fill(
    float*   _out,
    size_t _count,
    float    _value
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _value;
    }

    return;
}

D_MATH_FN void
d_vec_f_add(
    float*       _out,
    const float* _a,
    const float* _b,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _a[i] + _b[i];
    }

    return;
}

D_MATH_FN void
d_vec_f_sub(
    float*       _out,
    const float* _a,
    const float* _b,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _a[i] - _b[i];
    }

    return;
}

D_MATH_FN void
d_vec_f_scale(
    float*       _out,
    const float* _a,
    float        _s,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _a[i] * _s;
    }

    return;
}

D_MATH_FN void
d_vec_f_divide(
    float*       _out,
    const float* _a,
    float        _s,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _a[i] / _s;
    }

    return;
}

D_MATH_FN void
d_vec_f_negate(
    float*       _out,
    const float* _a,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = -_a[i];
    }

    return;
}

D_MATH_FN void
d_vec_f_hadamard(
    float*       _out,
    const float* _a,
    const float* _b,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _a[i] * _b[i];
    }

    return;
}

D_MATH_FN void
d_vec_f_lerp(
    float*       _out,
    const float* _a,
    const float* _b,
    float        _t,
    size_t     _count
)
{
    const float keep = (float)1 - _t;
    size_t    i    = 0u;

    // each product rounded apart, then summed: a(1 - t) + bt
    for (i = 0u; i < _count; ++i)
    {
        const float from = _a[i] * keep;
        const float to   = _b[i] * _t;

        _out[i] = from + to;
    }

    return;
}

// 1.2    Products and reductions
//------------------------------------------------------------------------------
// Each product is rounded before it is summed, so no compiler can fuse the
// two and a result is the same on every target.

D_MATH_FN float
d_vec_f_dot(
    const float* _a,
    const float* _b,
    size_t     _count
)
{
    float    acc = (float)0;
    size_t i   = 0u;

    for (i = 0u; i < _count; ++i)
    {
        const float product = _a[i] * _b[i];

        acc += product;
    }

    return acc;
}

D_MATH_FN void
d_vec_f_cross(
    float*       _out,
    const float* _a,
    const float* _b
)
{
    // all three from the inputs before any output is written
    const float x1 = _a[1] * _b[2];
    const float x2 = _a[2] * _b[1];
    const float y1 = _a[2] * _b[0];
    const float y2 = _a[0] * _b[2];
    const float z1 = _a[0] * _b[1];
    const float z2 = _a[1] * _b[0];

    _out[0] = x1 - x2;
    _out[1] = y1 - y2;
    _out[2] = z1 - z2;

    return;
}

D_MATH_FN float
d_vec_f_sum(
    const float* _a,
    size_t     _count
)
{
    float    acc = (float)0;
    size_t i   = 0u;

    for (i = 0u; i < _count; ++i)
    {
        acc += _a[i];
    }

    return acc;
}

D_MATH_FN float
d_vec_f_product(
    const float* _a,
    size_t     _count
)
{
    float    acc = (float)1;
    size_t i   = 0u;

    for (i = 0u; i < _count; ++i)
    {
        acc *= _a[i];
    }

    return acc;
}

D_MATH_FN float
d_vec_f_min(
    const float* _a,
    size_t     _count
)
{
    float    m = _a[0];
    size_t i = 1u;

    for (i = 1u; i < _count; ++i)
    {
        if (_a[i] < m)
        {
            m = _a[i];
        }
    }

    return m;
}

D_MATH_FN float
d_vec_f_max(
    const float* _a,
    size_t     _count
)
{
    float    m = _a[0];
    size_t i = 1u;

    for (i = 1u; i < _count; ++i)
    {
        if (_a[i] > m)
        {
            m = _a[i];
        }
    }

    return m;
}

// 1.3    Norms and distances
//------------------------------------------------------------------------------
// Each root comes in two forms, the same value bit for bit (elementary.h's
// two square roots are both correctly rounded): the _c form a constant
// expression from C++14, the plain one the C library's root.

D_MATH_FN float
d_vec_f_norm_squared(
    const float* _a,
    size_t     _count
)
{
    return d_vec_f_dot(_a, _a, _count);
}

D_MATH_FN float
d_vec_f_norm_c(
    const float* _a,
    size_t     _count
)
{
    return d_math_f_sqrt_c(d_vec_f_norm_squared(_a, _count));
}

D_MATH_FN_RT float
d_vec_f_norm(
    const float* _a,
    size_t     _count
)
{
    return d_math_f_sqrt(d_vec_f_norm_squared(_a, _count));
}

D_MATH_FN float
d_vec_f_distance_squared(
    const float* _a,
    const float* _b,
    size_t     _count
)
{
    float    acc = (float)0;
    size_t i   = 0u;

    // the difference's own square, as |a - b|^2 is
    for (i = 0u; i < _count; ++i)
    {
        const float d      = _a[i] - _b[i];
        const float square = d * d;

        acc += square;
    }

    return acc;
}

D_MATH_FN float
d_vec_f_distance_c(
    const float* _a,
    const float* _b,
    size_t     _count
)
{
    return d_math_f_sqrt_c(d_vec_f_distance_squared(_a, _b, _count));
}

D_MATH_FN_RT float
d_vec_f_distance(
    const float* _a,
    const float* _b,
    size_t     _count
)
{
    return d_math_f_sqrt(d_vec_f_distance_squared(_a, _b, _count));
}

D_MATH_FN void
d_vec_f_normalize_c(
    float*       _out,
    const float* _a,
    size_t     _count
)
{
    const float n = d_vec_f_norm_c(_a, _count);

    // the zero vector stays zero
    if (n > (float)0)
    {
        d_vec_f_divide(_out, _a, n, _count);
    }
    else
    {
        d_vec_f_fill(_out, _count, (float)0);
    }

    return;
}

D_MATH_FN_RT void
d_vec_f_normalize(
    float*       _out,
    const float* _a,
    size_t     _count
)
{
    const float n = d_vec_f_norm(_a, _count);

    // the zero vector stays zero
    if (n > (float)0)
    {
        d_vec_f_divide(_out, _a, n, _count);
    }
    else
    {
        d_vec_f_fill(_out, _count, (float)0);
    }

    return;
}

// 1.4    Projection and angle
//------------------------------------------------------------------------------
// project is _a's component along _onto, reject what is left; the zero
// vector projects to zero. cos_angle is 0 when either vector is zero; angle
// clamps it into [-1, 1] first, so rounding past 1 gives 0, not NaN.

D_MATH_FN void
d_vec_f_project(
    float*       _out,
    const float* _a,
    const float* _onto,
    size_t     _count
)
{
    const float d = d_vec_f_norm_squared(_onto, _count);

    // onto the zero vector there is nothing to project
    if (d > (float)0)
    {
        d_vec_f_scale(_out,
                        _onto,
                        d_vec_f_dot(_a, _onto, _count) / d,
                        _count);
    }
    else
    {
        d_vec_f_fill(_out, _count, (float)0);
    }

    return;
}

D_MATH_FN void
d_vec_f_reject(
    float*       _out,
    const float* _a,
    const float* _from,
    size_t     _count
)
{
    size_t i = 0u;

    // _a less its projection, formed component by component so _out may be
    // either input
    {
        const float d     = d_vec_f_norm_squared(_from, _count);
        const float ratio = (d > (float)0)
                              ? (d_vec_f_dot(_a, _from, _count) / d)
                              : (float)0;

        for (i = 0u; i < _count; ++i)
        {
            const float along = _from[i] * ratio;

            _out[i] = _a[i] - along;
        }
    }

    return;
}

D_MATH_FN float
d_vec_f_cos_angle_c(
    const float* _a,
    const float* _b,
    size_t     _count
)
{
    const float d = d_vec_f_norm_c(_a, _count) * d_vec_f_norm_c(_b, _count);

    return (d > (float)0) ? (d_vec_f_dot(_a, _b, _count) / d) : (float)0;
}

D_MATH_FN_RT float
d_vec_f_cos_angle(
    const float* _a,
    const float* _b,
    size_t     _count
)
{
    const float d = d_vec_f_norm(_a, _count) * d_vec_f_norm(_b, _count);

    return (d > (float)0) ? (d_vec_f_dot(_a, _b, _count) / d) : (float)0;
}

D_MATH_FN float
d_vec_f_angle_c(
    const float* _a,
    const float* _b,
    size_t     _count
)
{
    const float c = d_vec_f_cos_angle_c(_a, _b, _count);

    return d_math_f_acos_c( (c > (float)1)  ? (float)1  :
                              (c < (float)-1) ? (float)-1 : c );
}

D_MATH_FN_RT float
d_vec_f_angle(
    const float* _a,
    const float* _b,
    size_t     _count
)
{
    const float c = d_vec_f_cos_angle(_a, _b, _count);

    return d_math_f_acos( (c > (float)1)  ? (float)1  :
                            (c < (float)-1) ? (float)-1 : c );
}

// 1.5    Comparison
//------------------------------------------------------------------------------
// equal is component-wise ==; equals allows each component _tolerance.

D_MATH_FN bool
d_vec_f_equal(
    const float* _a,
    const float* _b,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        if (!(_a[i] == _b[i]))
        {
            return false;
        }
    }

    return true;
}

D_MATH_FN bool
d_vec_f_equals(
    const float* _a,
    const float* _b,
    float        _tolerance,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        const float d = _a[i] - _b[i];

        if (((d < (float)0) ? -d : d) > _tolerance)
        {
            return false;
        }
    }

    return true;
}

//==============================================================================
// 2.  THE DOUBLE FAMILY (_d)
//==============================================================================
// _count components each; _out may be _a or _b.


// 2.1    Element-wise arithmetic
//------------------------------------------------------------------------------

D_MATH_FN void
d_vec_d_fill(
    double*   _out,
    size_t _count,
    double    _value
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _value;
    }

    return;
}

D_MATH_FN void
d_vec_d_add(
    double*       _out,
    const double* _a,
    const double* _b,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _a[i] + _b[i];
    }

    return;
}

D_MATH_FN void
d_vec_d_sub(
    double*       _out,
    const double* _a,
    const double* _b,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _a[i] - _b[i];
    }

    return;
}

D_MATH_FN void
d_vec_d_scale(
    double*       _out,
    const double* _a,
    double        _s,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _a[i] * _s;
    }

    return;
}

D_MATH_FN void
d_vec_d_divide(
    double*       _out,
    const double* _a,
    double        _s,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _a[i] / _s;
    }

    return;
}

D_MATH_FN void
d_vec_d_negate(
    double*       _out,
    const double* _a,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = -_a[i];
    }

    return;
}

D_MATH_FN void
d_vec_d_hadamard(
    double*       _out,
    const double* _a,
    const double* _b,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _a[i] * _b[i];
    }

    return;
}

D_MATH_FN void
d_vec_d_lerp(
    double*       _out,
    const double* _a,
    const double* _b,
    double        _t,
    size_t     _count
)
{
    const double keep = (double)1 - _t;
    size_t    i    = 0u;

    // each product rounded apart, then summed: a(1 - t) + bt
    for (i = 0u; i < _count; ++i)
    {
        const double from = _a[i] * keep;
        const double to   = _b[i] * _t;

        _out[i] = from + to;
    }

    return;
}

// 2.2    Products and reductions
//------------------------------------------------------------------------------
// Each product is rounded before it is summed, so no compiler can fuse the
// two and a result is the same on every target.

D_MATH_FN double
d_vec_d_dot(
    const double* _a,
    const double* _b,
    size_t     _count
)
{
    double    acc = (double)0;
    size_t i   = 0u;

    for (i = 0u; i < _count; ++i)
    {
        const double product = _a[i] * _b[i];

        acc += product;
    }

    return acc;
}

D_MATH_FN void
d_vec_d_cross(
    double*       _out,
    const double* _a,
    const double* _b
)
{
    // all three from the inputs before any output is written
    const double x1 = _a[1] * _b[2];
    const double x2 = _a[2] * _b[1];
    const double y1 = _a[2] * _b[0];
    const double y2 = _a[0] * _b[2];
    const double z1 = _a[0] * _b[1];
    const double z2 = _a[1] * _b[0];

    _out[0] = x1 - x2;
    _out[1] = y1 - y2;
    _out[2] = z1 - z2;

    return;
}

D_MATH_FN double
d_vec_d_sum(
    const double* _a,
    size_t     _count
)
{
    double    acc = (double)0;
    size_t i   = 0u;

    for (i = 0u; i < _count; ++i)
    {
        acc += _a[i];
    }

    return acc;
}

D_MATH_FN double
d_vec_d_product(
    const double* _a,
    size_t     _count
)
{
    double    acc = (double)1;
    size_t i   = 0u;

    for (i = 0u; i < _count; ++i)
    {
        acc *= _a[i];
    }

    return acc;
}

D_MATH_FN double
d_vec_d_min(
    const double* _a,
    size_t     _count
)
{
    double    m = _a[0];
    size_t i = 1u;

    for (i = 1u; i < _count; ++i)
    {
        if (_a[i] < m)
        {
            m = _a[i];
        }
    }

    return m;
}

D_MATH_FN double
d_vec_d_max(
    const double* _a,
    size_t     _count
)
{
    double    m = _a[0];
    size_t i = 1u;

    for (i = 1u; i < _count; ++i)
    {
        if (_a[i] > m)
        {
            m = _a[i];
        }
    }

    return m;
}

// 2.3    Norms and distances
//------------------------------------------------------------------------------
// Each root comes in two forms, the same value bit for bit (elementary.h's
// two square roots are both correctly rounded): the _c form a constant
// expression from C++14, the plain one the C library's root.

D_MATH_FN double
d_vec_d_norm_squared(
    const double* _a,
    size_t     _count
)
{
    return d_vec_d_dot(_a, _a, _count);
}

D_MATH_FN double
d_vec_d_norm_c(
    const double* _a,
    size_t     _count
)
{
    return d_math_d_sqrt_c(d_vec_d_norm_squared(_a, _count));
}

D_MATH_FN_RT double
d_vec_d_norm(
    const double* _a,
    size_t     _count
)
{
    return d_math_d_sqrt(d_vec_d_norm_squared(_a, _count));
}

D_MATH_FN double
d_vec_d_distance_squared(
    const double* _a,
    const double* _b,
    size_t     _count
)
{
    double    acc = (double)0;
    size_t i   = 0u;

    // the difference's own square, as |a - b|^2 is
    for (i = 0u; i < _count; ++i)
    {
        const double d      = _a[i] - _b[i];
        const double square = d * d;

        acc += square;
    }

    return acc;
}

D_MATH_FN double
d_vec_d_distance_c(
    const double* _a,
    const double* _b,
    size_t     _count
)
{
    return d_math_d_sqrt_c(d_vec_d_distance_squared(_a, _b, _count));
}

D_MATH_FN_RT double
d_vec_d_distance(
    const double* _a,
    const double* _b,
    size_t     _count
)
{
    return d_math_d_sqrt(d_vec_d_distance_squared(_a, _b, _count));
}

D_MATH_FN void
d_vec_d_normalize_c(
    double*       _out,
    const double* _a,
    size_t     _count
)
{
    const double n = d_vec_d_norm_c(_a, _count);

    // the zero vector stays zero
    if (n > (double)0)
    {
        d_vec_d_divide(_out, _a, n, _count);
    }
    else
    {
        d_vec_d_fill(_out, _count, (double)0);
    }

    return;
}

D_MATH_FN_RT void
d_vec_d_normalize(
    double*       _out,
    const double* _a,
    size_t     _count
)
{
    const double n = d_vec_d_norm(_a, _count);

    // the zero vector stays zero
    if (n > (double)0)
    {
        d_vec_d_divide(_out, _a, n, _count);
    }
    else
    {
        d_vec_d_fill(_out, _count, (double)0);
    }

    return;
}

// 2.4    Projection and angle
//------------------------------------------------------------------------------
// project is _a's component along _onto, reject what is left; the zero
// vector projects to zero. cos_angle is 0 when either vector is zero; angle
// clamps it into [-1, 1] first, so rounding past 1 gives 0, not NaN.

D_MATH_FN void
d_vec_d_project(
    double*       _out,
    const double* _a,
    const double* _onto,
    size_t     _count
)
{
    const double d = d_vec_d_norm_squared(_onto, _count);

    // onto the zero vector there is nothing to project
    if (d > (double)0)
    {
        d_vec_d_scale(_out,
                        _onto,
                        d_vec_d_dot(_a, _onto, _count) / d,
                        _count);
    }
    else
    {
        d_vec_d_fill(_out, _count, (double)0);
    }

    return;
}

D_MATH_FN void
d_vec_d_reject(
    double*       _out,
    const double* _a,
    const double* _from,
    size_t     _count
)
{
    size_t i = 0u;

    // _a less its projection, formed component by component so _out may be
    // either input
    {
        const double d     = d_vec_d_norm_squared(_from, _count);
        const double ratio = (d > (double)0)
                              ? (d_vec_d_dot(_a, _from, _count) / d)
                              : (double)0;

        for (i = 0u; i < _count; ++i)
        {
            const double along = _from[i] * ratio;

            _out[i] = _a[i] - along;
        }
    }

    return;
}

D_MATH_FN double
d_vec_d_cos_angle_c(
    const double* _a,
    const double* _b,
    size_t     _count
)
{
    const double d = d_vec_d_norm_c(_a, _count) * d_vec_d_norm_c(_b, _count);

    return (d > (double)0) ? (d_vec_d_dot(_a, _b, _count) / d) : (double)0;
}

D_MATH_FN_RT double
d_vec_d_cos_angle(
    const double* _a,
    const double* _b,
    size_t     _count
)
{
    const double d = d_vec_d_norm(_a, _count) * d_vec_d_norm(_b, _count);

    return (d > (double)0) ? (d_vec_d_dot(_a, _b, _count) / d) : (double)0;
}

D_MATH_FN double
d_vec_d_angle_c(
    const double* _a,
    const double* _b,
    size_t     _count
)
{
    const double c = d_vec_d_cos_angle_c(_a, _b, _count);

    return d_math_d_acos_c( (c > (double)1)  ? (double)1  :
                              (c < (double)-1) ? (double)-1 : c );
}

D_MATH_FN_RT double
d_vec_d_angle(
    const double* _a,
    const double* _b,
    size_t     _count
)
{
    const double c = d_vec_d_cos_angle(_a, _b, _count);

    return d_math_d_acos( (c > (double)1)  ? (double)1  :
                            (c < (double)-1) ? (double)-1 : c );
}

// 2.5    Comparison
//------------------------------------------------------------------------------
// equal is component-wise ==; equals allows each component _tolerance.

D_MATH_FN bool
d_vec_d_equal(
    const double* _a,
    const double* _b,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        if (!(_a[i] == _b[i]))
        {
            return false;
        }
    }

    return true;
}

D_MATH_FN bool
d_vec_d_equals(
    const double* _a,
    const double* _b,
    double        _tolerance,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        const double d = _a[i] - _b[i];

        if (((d < (double)0) ? -d : d) > _tolerance)
        {
            return false;
        }
    }

    return true;
}

//==============================================================================
// 3.  THE LONG DOUBLE FAMILY (_ld)
//==============================================================================
// _count components each; _out may be _a or _b.


// 3.1    Element-wise arithmetic
//------------------------------------------------------------------------------

D_MATH_FN void
d_vec_ld_fill(
    long double*   _out,
    size_t _count,
    long double    _value
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _value;
    }

    return;
}

D_MATH_FN void
d_vec_ld_add(
    long double*       _out,
    const long double* _a,
    const long double* _b,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _a[i] + _b[i];
    }

    return;
}

D_MATH_FN void
d_vec_ld_sub(
    long double*       _out,
    const long double* _a,
    const long double* _b,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _a[i] - _b[i];
    }

    return;
}

D_MATH_FN void
d_vec_ld_scale(
    long double*       _out,
    const long double* _a,
    long double        _s,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _a[i] * _s;
    }

    return;
}

D_MATH_FN void
d_vec_ld_divide(
    long double*       _out,
    const long double* _a,
    long double        _s,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _a[i] / _s;
    }

    return;
}

D_MATH_FN void
d_vec_ld_negate(
    long double*       _out,
    const long double* _a,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = -_a[i];
    }

    return;
}

D_MATH_FN void
d_vec_ld_hadamard(
    long double*       _out,
    const long double* _a,
    const long double* _b,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        _out[i] = _a[i] * _b[i];
    }

    return;
}

D_MATH_FN void
d_vec_ld_lerp(
    long double*       _out,
    const long double* _a,
    const long double* _b,
    long double        _t,
    size_t     _count
)
{
    const long double keep = (long double)1 - _t;
    size_t    i    = 0u;

    // each product rounded apart, then summed: a(1 - t) + bt
    for (i = 0u; i < _count; ++i)
    {
        const long double from = _a[i] * keep;
        const long double to   = _b[i] * _t;

        _out[i] = from + to;
    }

    return;
}

// 3.2    Products and reductions
//------------------------------------------------------------------------------
// Each product is rounded before it is summed, so no compiler can fuse the
// two and a result is the same on every target.

D_MATH_FN long double
d_vec_ld_dot(
    const long double* _a,
    const long double* _b,
    size_t     _count
)
{
    long double    acc = (long double)0;
    size_t i   = 0u;

    for (i = 0u; i < _count; ++i)
    {
        const long double product = _a[i] * _b[i];

        acc += product;
    }

    return acc;
}

D_MATH_FN void
d_vec_ld_cross(
    long double*       _out,
    const long double* _a,
    const long double* _b
)
{
    // all three from the inputs before any output is written
    const long double x1 = _a[1] * _b[2];
    const long double x2 = _a[2] * _b[1];
    const long double y1 = _a[2] * _b[0];
    const long double y2 = _a[0] * _b[2];
    const long double z1 = _a[0] * _b[1];
    const long double z2 = _a[1] * _b[0];

    _out[0] = x1 - x2;
    _out[1] = y1 - y2;
    _out[2] = z1 - z2;

    return;
}

D_MATH_FN long double
d_vec_ld_sum(
    const long double* _a,
    size_t     _count
)
{
    long double    acc = (long double)0;
    size_t i   = 0u;

    for (i = 0u; i < _count; ++i)
    {
        acc += _a[i];
    }

    return acc;
}

D_MATH_FN long double
d_vec_ld_product(
    const long double* _a,
    size_t     _count
)
{
    long double    acc = (long double)1;
    size_t i   = 0u;

    for (i = 0u; i < _count; ++i)
    {
        acc *= _a[i];
    }

    return acc;
}

D_MATH_FN long double
d_vec_ld_min(
    const long double* _a,
    size_t     _count
)
{
    long double    m = _a[0];
    size_t i = 1u;

    for (i = 1u; i < _count; ++i)
    {
        if (_a[i] < m)
        {
            m = _a[i];
        }
    }

    return m;
}

D_MATH_FN long double
d_vec_ld_max(
    const long double* _a,
    size_t     _count
)
{
    long double    m = _a[0];
    size_t i = 1u;

    for (i = 1u; i < _count; ++i)
    {
        if (_a[i] > m)
        {
            m = _a[i];
        }
    }

    return m;
}

// 3.3    Norms and distances
//------------------------------------------------------------------------------
// Each root comes in two forms, the same value bit for bit (elementary.h's
// two square roots are both correctly rounded): the _c form a constant
// expression from C++14, the plain one the C library's root.

D_MATH_FN long double
d_vec_ld_norm_squared(
    const long double* _a,
    size_t     _count
)
{
    return d_vec_ld_dot(_a, _a, _count);
}

D_MATH_FN long double
d_vec_ld_norm_c(
    const long double* _a,
    size_t     _count
)
{
    return d_math_ld_sqrt_c(d_vec_ld_norm_squared(_a, _count));
}

D_MATH_FN_RT long double
d_vec_ld_norm(
    const long double* _a,
    size_t     _count
)
{
    return d_math_ld_sqrt(d_vec_ld_norm_squared(_a, _count));
}

D_MATH_FN long double
d_vec_ld_distance_squared(
    const long double* _a,
    const long double* _b,
    size_t     _count
)
{
    long double    acc = (long double)0;
    size_t i   = 0u;

    // the difference's own square, as |a - b|^2 is
    for (i = 0u; i < _count; ++i)
    {
        const long double d      = _a[i] - _b[i];
        const long double square = d * d;

        acc += square;
    }

    return acc;
}

D_MATH_FN long double
d_vec_ld_distance_c(
    const long double* _a,
    const long double* _b,
    size_t     _count
)
{
    return d_math_ld_sqrt_c(d_vec_ld_distance_squared(_a, _b, _count));
}

D_MATH_FN_RT long double
d_vec_ld_distance(
    const long double* _a,
    const long double* _b,
    size_t     _count
)
{
    return d_math_ld_sqrt(d_vec_ld_distance_squared(_a, _b, _count));
}

D_MATH_FN void
d_vec_ld_normalize_c(
    long double*       _out,
    const long double* _a,
    size_t     _count
)
{
    const long double n = d_vec_ld_norm_c(_a, _count);

    // the zero vector stays zero
    if (n > (long double)0)
    {
        d_vec_ld_divide(_out, _a, n, _count);
    }
    else
    {
        d_vec_ld_fill(_out, _count, (long double)0);
    }

    return;
}

D_MATH_FN_RT void
d_vec_ld_normalize(
    long double*       _out,
    const long double* _a,
    size_t     _count
)
{
    const long double n = d_vec_ld_norm(_a, _count);

    // the zero vector stays zero
    if (n > (long double)0)
    {
        d_vec_ld_divide(_out, _a, n, _count);
    }
    else
    {
        d_vec_ld_fill(_out, _count, (long double)0);
    }

    return;
}

// 3.4    Projection and angle
//------------------------------------------------------------------------------
// project is _a's component along _onto, reject what is left; the zero
// vector projects to zero. cos_angle is 0 when either vector is zero; angle
// clamps it into [-1, 1] first, so rounding past 1 gives 0, not NaN.

D_MATH_FN void
d_vec_ld_project(
    long double*       _out,
    const long double* _a,
    const long double* _onto,
    size_t     _count
)
{
    const long double d = d_vec_ld_norm_squared(_onto, _count);

    // onto the zero vector there is nothing to project
    if (d > (long double)0)
    {
        d_vec_ld_scale(_out,
                        _onto,
                        d_vec_ld_dot(_a, _onto, _count) / d,
                        _count);
    }
    else
    {
        d_vec_ld_fill(_out, _count, (long double)0);
    }

    return;
}

D_MATH_FN void
d_vec_ld_reject(
    long double*       _out,
    const long double* _a,
    const long double* _from,
    size_t     _count
)
{
    size_t i = 0u;

    // _a less its projection, formed component by component so _out may be
    // either input
    {
        const long double d     = d_vec_ld_norm_squared(_from, _count);
        const long double ratio = (d > (long double)0)
                              ? (d_vec_ld_dot(_a, _from, _count) / d)
                              : (long double)0;

        for (i = 0u; i < _count; ++i)
        {
            const long double along = _from[i] * ratio;

            _out[i] = _a[i] - along;
        }
    }

    return;
}

D_MATH_FN long double
d_vec_ld_cos_angle_c(
    const long double* _a,
    const long double* _b,
    size_t     _count
)
{
    const long double d = d_vec_ld_norm_c(_a, _count) * d_vec_ld_norm_c(_b, _count);

    return (d > (long double)0) ? (d_vec_ld_dot(_a, _b, _count) / d) : (long double)0;
}

D_MATH_FN_RT long double
d_vec_ld_cos_angle(
    const long double* _a,
    const long double* _b,
    size_t     _count
)
{
    const long double d = d_vec_ld_norm(_a, _count) * d_vec_ld_norm(_b, _count);

    return (d > (long double)0) ? (d_vec_ld_dot(_a, _b, _count) / d) : (long double)0;
}

D_MATH_FN long double
d_vec_ld_angle_c(
    const long double* _a,
    const long double* _b,
    size_t     _count
)
{
    const long double c = d_vec_ld_cos_angle_c(_a, _b, _count);

    return d_math_ld_acos_c( (c > (long double)1)  ? (long double)1  :
                              (c < (long double)-1) ? (long double)-1 : c );
}

D_MATH_FN_RT long double
d_vec_ld_angle(
    const long double* _a,
    const long double* _b,
    size_t     _count
)
{
    const long double c = d_vec_ld_cos_angle(_a, _b, _count);

    return d_math_ld_acos( (c > (long double)1)  ? (long double)1  :
                            (c < (long double)-1) ? (long double)-1 : c );
}

// 3.5    Comparison
//------------------------------------------------------------------------------
// equal is component-wise ==; equals allows each component _tolerance.

D_MATH_FN bool
d_vec_ld_equal(
    const long double* _a,
    const long double* _b,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        if (!(_a[i] == _b[i]))
        {
            return false;
        }
    }

    return true;
}

D_MATH_FN bool
d_vec_ld_equals(
    const long double* _a,
    const long double* _b,
    long double        _tolerance,
    size_t     _count
)
{
    size_t i = 0u;

    for (i = 0u; i < _count; ++i)
    {
        const long double d = _a[i] - _b[i];

        if (((d < (long double)0) ? -d : d) > _tolerance)
        {
            return false;
        }
    }

    return true;
}


#ifdef __cplusplus

//==============================================================================
// 4.  ONE NAME FOR EVERY FAMILY (C++)
//==============================================================================
// C++ only: the kernels above under one name each, chosen by argument type,
// so a C++ template serves float, double and long double alike.


D_MATH_FN void
d_vec_fill(
    float* _out,
    size_t _count,
    float  _value
)
{
    return d_vec_f_fill(_out, _count, _value);
}

D_MATH_FN void
d_vec_add(
    float*       _out,
    const float* _a,
    const float* _b,
    size_t       _count
)
{
    return d_vec_f_add(_out, _a, _b, _count);
}

D_MATH_FN void
d_vec_sub(
    float*       _out,
    const float* _a,
    const float* _b,
    size_t       _count
)
{
    return d_vec_f_sub(_out, _a, _b, _count);
}

D_MATH_FN void
d_vec_scale(
    float*       _out,
    const float* _a,
    float        _s,
    size_t       _count
)
{
    return d_vec_f_scale(_out, _a, _s, _count);
}

D_MATH_FN void
d_vec_divide(
    float*       _out,
    const float* _a,
    float        _s,
    size_t       _count
)
{
    return d_vec_f_divide(_out, _a, _s, _count);
}

D_MATH_FN void
d_vec_negate(
    float*       _out,
    const float* _a,
    size_t       _count
)
{
    return d_vec_f_negate(_out, _a, _count);
}

D_MATH_FN void
d_vec_hadamard(
    float*       _out,
    const float* _a,
    const float* _b,
    size_t       _count
)
{
    return d_vec_f_hadamard(_out, _a, _b, _count);
}

D_MATH_FN void
d_vec_lerp(
    float*       _out,
    const float* _a,
    const float* _b,
    float        _t,
    size_t       _count
)
{
    return d_vec_f_lerp(_out, _a, _b, _t, _count);
}

D_MATH_FN float
d_vec_dot(
    const float* _a,
    const float* _b,
    size_t       _count
)
{
    return d_vec_f_dot(_a, _b, _count);
}

D_MATH_FN void
d_vec_cross(
    float*       _out,
    const float* _a,
    const float* _b
)
{
    return d_vec_f_cross(_out, _a, _b);
}

D_MATH_FN float
d_vec_sum(
    const float* _a,
    size_t       _count
)
{
    return d_vec_f_sum(_a, _count);
}

D_MATH_FN float
d_vec_product(
    const float* _a,
    size_t       _count
)
{
    return d_vec_f_product(_a, _count);
}

D_MATH_FN float
d_vec_min(
    const float* _a,
    size_t       _count
)
{
    return d_vec_f_min(_a, _count);
}

D_MATH_FN float
d_vec_max(
    const float* _a,
    size_t       _count
)
{
    return d_vec_f_max(_a, _count);
}

D_MATH_FN float
d_vec_norm_squared(
    const float* _a,
    size_t       _count
)
{
    return d_vec_f_norm_squared(_a, _count);
}

D_MATH_FN float
d_vec_norm_c(
    const float* _a,
    size_t       _count
)
{
    return d_vec_f_norm_c(_a, _count);
}

D_MATH_FN_RT float
d_vec_norm(
    const float* _a,
    size_t       _count
)
{
    return d_vec_f_norm(_a, _count);
}

D_MATH_FN float
d_vec_distance_squared(
    const float* _a,
    const float* _b,
    size_t       _count
)
{
    return d_vec_f_distance_squared(_a, _b, _count);
}

D_MATH_FN float
d_vec_distance_c(
    const float* _a,
    const float* _b,
    size_t       _count
)
{
    return d_vec_f_distance_c(_a, _b, _count);
}

D_MATH_FN_RT float
d_vec_distance(
    const float* _a,
    const float* _b,
    size_t       _count
)
{
    return d_vec_f_distance(_a, _b, _count);
}

D_MATH_FN void
d_vec_normalize_c(
    float*       _out,
    const float* _a,
    size_t       _count
)
{
    return d_vec_f_normalize_c(_out, _a, _count);
}

D_MATH_FN_RT void
d_vec_normalize(
    float*       _out,
    const float* _a,
    size_t       _count
)
{
    return d_vec_f_normalize(_out, _a, _count);
}

D_MATH_FN void
d_vec_project(
    float*       _out,
    const float* _a,
    const float* _onto,
    size_t       _count
)
{
    return d_vec_f_project(_out, _a, _onto, _count);
}

D_MATH_FN void
d_vec_reject(
    float*       _out,
    const float* _a,
    const float* _from,
    size_t       _count
)
{
    return d_vec_f_reject(_out, _a, _from, _count);
}

D_MATH_FN float
d_vec_cos_angle_c(
    const float* _a,
    const float* _b,
    size_t       _count
)
{
    return d_vec_f_cos_angle_c(_a, _b, _count);
}

D_MATH_FN_RT float
d_vec_cos_angle(
    const float* _a,
    const float* _b,
    size_t       _count
)
{
    return d_vec_f_cos_angle(_a, _b, _count);
}

D_MATH_FN float
d_vec_angle_c(
    const float* _a,
    const float* _b,
    size_t       _count
)
{
    return d_vec_f_angle_c(_a, _b, _count);
}

D_MATH_FN_RT float
d_vec_angle(
    const float* _a,
    const float* _b,
    size_t       _count
)
{
    return d_vec_f_angle(_a, _b, _count);
}

D_MATH_FN bool
d_vec_equal(
    const float* _a,
    const float* _b,
    size_t       _count
)
{
    return d_vec_f_equal(_a, _b, _count);
}

D_MATH_FN bool
d_vec_equals(
    const float* _a,
    const float* _b,
    float        _tolerance,
    size_t       _count
)
{
    return d_vec_f_equals(_a, _b, _tolerance, _count);
}

D_MATH_FN void
d_vec_fill(
    double* _out,
    size_t  _count,
    double  _value
)
{
    return d_vec_d_fill(_out, _count, _value);
}

D_MATH_FN void
d_vec_add(
    double*       _out,
    const double* _a,
    const double* _b,
    size_t        _count
)
{
    return d_vec_d_add(_out, _a, _b, _count);
}

D_MATH_FN void
d_vec_sub(
    double*       _out,
    const double* _a,
    const double* _b,
    size_t        _count
)
{
    return d_vec_d_sub(_out, _a, _b, _count);
}

D_MATH_FN void
d_vec_scale(
    double*       _out,
    const double* _a,
    double        _s,
    size_t        _count
)
{
    return d_vec_d_scale(_out, _a, _s, _count);
}

D_MATH_FN void
d_vec_divide(
    double*       _out,
    const double* _a,
    double        _s,
    size_t        _count
)
{
    return d_vec_d_divide(_out, _a, _s, _count);
}

D_MATH_FN void
d_vec_negate(
    double*       _out,
    const double* _a,
    size_t        _count
)
{
    return d_vec_d_negate(_out, _a, _count);
}

D_MATH_FN void
d_vec_hadamard(
    double*       _out,
    const double* _a,
    const double* _b,
    size_t        _count
)
{
    return d_vec_d_hadamard(_out, _a, _b, _count);
}

D_MATH_FN void
d_vec_lerp(
    double*       _out,
    const double* _a,
    const double* _b,
    double        _t,
    size_t        _count
)
{
    return d_vec_d_lerp(_out, _a, _b, _t, _count);
}

D_MATH_FN double
d_vec_dot(
    const double* _a,
    const double* _b,
    size_t        _count
)
{
    return d_vec_d_dot(_a, _b, _count);
}

D_MATH_FN void
d_vec_cross(
    double*       _out,
    const double* _a,
    const double* _b
)
{
    return d_vec_d_cross(_out, _a, _b);
}

D_MATH_FN double
d_vec_sum(
    const double* _a,
    size_t        _count
)
{
    return d_vec_d_sum(_a, _count);
}

D_MATH_FN double
d_vec_product(
    const double* _a,
    size_t        _count
)
{
    return d_vec_d_product(_a, _count);
}

D_MATH_FN double
d_vec_min(
    const double* _a,
    size_t        _count
)
{
    return d_vec_d_min(_a, _count);
}

D_MATH_FN double
d_vec_max(
    const double* _a,
    size_t        _count
)
{
    return d_vec_d_max(_a, _count);
}

D_MATH_FN double
d_vec_norm_squared(
    const double* _a,
    size_t        _count
)
{
    return d_vec_d_norm_squared(_a, _count);
}

D_MATH_FN double
d_vec_norm_c(
    const double* _a,
    size_t        _count
)
{
    return d_vec_d_norm_c(_a, _count);
}

D_MATH_FN_RT double
d_vec_norm(
    const double* _a,
    size_t        _count
)
{
    return d_vec_d_norm(_a, _count);
}

D_MATH_FN double
d_vec_distance_squared(
    const double* _a,
    const double* _b,
    size_t        _count
)
{
    return d_vec_d_distance_squared(_a, _b, _count);
}

D_MATH_FN double
d_vec_distance_c(
    const double* _a,
    const double* _b,
    size_t        _count
)
{
    return d_vec_d_distance_c(_a, _b, _count);
}

D_MATH_FN_RT double
d_vec_distance(
    const double* _a,
    const double* _b,
    size_t        _count
)
{
    return d_vec_d_distance(_a, _b, _count);
}

D_MATH_FN void
d_vec_normalize_c(
    double*       _out,
    const double* _a,
    size_t        _count
)
{
    return d_vec_d_normalize_c(_out, _a, _count);
}

D_MATH_FN_RT void
d_vec_normalize(
    double*       _out,
    const double* _a,
    size_t        _count
)
{
    return d_vec_d_normalize(_out, _a, _count);
}

D_MATH_FN void
d_vec_project(
    double*       _out,
    const double* _a,
    const double* _onto,
    size_t        _count
)
{
    return d_vec_d_project(_out, _a, _onto, _count);
}

D_MATH_FN void
d_vec_reject(
    double*       _out,
    const double* _a,
    const double* _from,
    size_t        _count
)
{
    return d_vec_d_reject(_out, _a, _from, _count);
}

D_MATH_FN double
d_vec_cos_angle_c(
    const double* _a,
    const double* _b,
    size_t        _count
)
{
    return d_vec_d_cos_angle_c(_a, _b, _count);
}

D_MATH_FN_RT double
d_vec_cos_angle(
    const double* _a,
    const double* _b,
    size_t        _count
)
{
    return d_vec_d_cos_angle(_a, _b, _count);
}

D_MATH_FN double
d_vec_angle_c(
    const double* _a,
    const double* _b,
    size_t        _count
)
{
    return d_vec_d_angle_c(_a, _b, _count);
}

D_MATH_FN_RT double
d_vec_angle(
    const double* _a,
    const double* _b,
    size_t        _count
)
{
    return d_vec_d_angle(_a, _b, _count);
}

D_MATH_FN bool
d_vec_equal(
    const double* _a,
    const double* _b,
    size_t        _count
)
{
    return d_vec_d_equal(_a, _b, _count);
}

D_MATH_FN bool
d_vec_equals(
    const double* _a,
    const double* _b,
    double        _tolerance,
    size_t        _count
)
{
    return d_vec_d_equals(_a, _b, _tolerance, _count);
}

D_MATH_FN void
d_vec_fill(
    long double* _out,
    size_t       _count,
    long double  _value
)
{
    return d_vec_ld_fill(_out, _count, _value);
}

D_MATH_FN void
d_vec_add(
    long double*       _out,
    const long double* _a,
    const long double* _b,
    size_t             _count
)
{
    return d_vec_ld_add(_out, _a, _b, _count);
}

D_MATH_FN void
d_vec_sub(
    long double*       _out,
    const long double* _a,
    const long double* _b,
    size_t             _count
)
{
    return d_vec_ld_sub(_out, _a, _b, _count);
}

D_MATH_FN void
d_vec_scale(
    long double*       _out,
    const long double* _a,
    long double        _s,
    size_t             _count
)
{
    return d_vec_ld_scale(_out, _a, _s, _count);
}

D_MATH_FN void
d_vec_divide(
    long double*       _out,
    const long double* _a,
    long double        _s,
    size_t             _count
)
{
    return d_vec_ld_divide(_out, _a, _s, _count);
}

D_MATH_FN void
d_vec_negate(
    long double*       _out,
    const long double* _a,
    size_t             _count
)
{
    return d_vec_ld_negate(_out, _a, _count);
}

D_MATH_FN void
d_vec_hadamard(
    long double*       _out,
    const long double* _a,
    const long double* _b,
    size_t             _count
)
{
    return d_vec_ld_hadamard(_out, _a, _b, _count);
}

D_MATH_FN void
d_vec_lerp(
    long double*       _out,
    const long double* _a,
    const long double* _b,
    long double        _t,
    size_t             _count
)
{
    return d_vec_ld_lerp(_out, _a, _b, _t, _count);
}

D_MATH_FN long double
d_vec_dot(
    const long double* _a,
    const long double* _b,
    size_t             _count
)
{
    return d_vec_ld_dot(_a, _b, _count);
}

D_MATH_FN void
d_vec_cross(
    long double*       _out,
    const long double* _a,
    const long double* _b
)
{
    return d_vec_ld_cross(_out, _a, _b);
}

D_MATH_FN long double
d_vec_sum(
    const long double* _a,
    size_t             _count
)
{
    return d_vec_ld_sum(_a, _count);
}

D_MATH_FN long double
d_vec_product(
    const long double* _a,
    size_t             _count
)
{
    return d_vec_ld_product(_a, _count);
}

D_MATH_FN long double
d_vec_min(
    const long double* _a,
    size_t             _count
)
{
    return d_vec_ld_min(_a, _count);
}

D_MATH_FN long double
d_vec_max(
    const long double* _a,
    size_t             _count
)
{
    return d_vec_ld_max(_a, _count);
}

D_MATH_FN long double
d_vec_norm_squared(
    const long double* _a,
    size_t             _count
)
{
    return d_vec_ld_norm_squared(_a, _count);
}

D_MATH_FN long double
d_vec_norm_c(
    const long double* _a,
    size_t             _count
)
{
    return d_vec_ld_norm_c(_a, _count);
}

D_MATH_FN_RT long double
d_vec_norm(
    const long double* _a,
    size_t             _count
)
{
    return d_vec_ld_norm(_a, _count);
}

D_MATH_FN long double
d_vec_distance_squared(
    const long double* _a,
    const long double* _b,
    size_t             _count
)
{
    return d_vec_ld_distance_squared(_a, _b, _count);
}

D_MATH_FN long double
d_vec_distance_c(
    const long double* _a,
    const long double* _b,
    size_t             _count
)
{
    return d_vec_ld_distance_c(_a, _b, _count);
}

D_MATH_FN_RT long double
d_vec_distance(
    const long double* _a,
    const long double* _b,
    size_t             _count
)
{
    return d_vec_ld_distance(_a, _b, _count);
}

D_MATH_FN void
d_vec_normalize_c(
    long double*       _out,
    const long double* _a,
    size_t             _count
)
{
    return d_vec_ld_normalize_c(_out, _a, _count);
}

D_MATH_FN_RT void
d_vec_normalize(
    long double*       _out,
    const long double* _a,
    size_t             _count
)
{
    return d_vec_ld_normalize(_out, _a, _count);
}

D_MATH_FN void
d_vec_project(
    long double*       _out,
    const long double* _a,
    const long double* _onto,
    size_t             _count
)
{
    return d_vec_ld_project(_out, _a, _onto, _count);
}

D_MATH_FN void
d_vec_reject(
    long double*       _out,
    const long double* _a,
    const long double* _from,
    size_t             _count
)
{
    return d_vec_ld_reject(_out, _a, _from, _count);
}

D_MATH_FN long double
d_vec_cos_angle_c(
    const long double* _a,
    const long double* _b,
    size_t             _count
)
{
    return d_vec_ld_cos_angle_c(_a, _b, _count);
}

D_MATH_FN_RT long double
d_vec_cos_angle(
    const long double* _a,
    const long double* _b,
    size_t             _count
)
{
    return d_vec_ld_cos_angle(_a, _b, _count);
}

D_MATH_FN long double
d_vec_angle_c(
    const long double* _a,
    const long double* _b,
    size_t             _count
)
{
    return d_vec_ld_angle_c(_a, _b, _count);
}

D_MATH_FN_RT long double
d_vec_angle(
    const long double* _a,
    const long double* _b,
    size_t             _count
)
{
    return d_vec_ld_angle(_a, _b, _count);
}

D_MATH_FN bool
d_vec_equal(
    const long double* _a,
    const long double* _b,
    size_t             _count
)
{
    return d_vec_ld_equal(_a, _b, _count);
}

D_MATH_FN bool
d_vec_equals(
    const long double* _a,
    const long double* _b,
    long double        _tolerance,
    size_t             _count
)
{
    return d_vec_ld_equals(_a, _b, _tolerance, _count);
}

#endif  // __cplusplus

#endif  // DJINTERP_C_MATH_VEC_H
