/*******************************************************************************
* djinterp [c]                                             number_to_string_en.h
*
*
* path:      /inc/djinterp/c/text/number_to_string_en.h
* link(s):   TBA
* author(s): TBA                                                    created: TBA
*                                                            revised: 2026.10.03
*******************************************************************************/
#ifndef DJINTERP_C_TEXT_NUMBER_TO_STRING_EN_H
#define DJINTERP_C_TEXT_NUMBER_TO_STRING_EN_H

// std
#include <stddef.h>
// re_std
#include "../../../re_std/cstdint/dstdint.h"  // int64_t

// 64-bit floor: this header needs a 64-bit integer type, which dstdint.h
// declares only where the build can spell one. Below it -- ISO strict
// C++98 on a 32-bit target -- the header compiles to nothing (the owner's
// ruling of 2026.10.03 on round 3's question 1, (a)).
#if defined(INT64_MAX)

#ifdef __cplusplus
extern "C" {
#endif

enum
{
    NTS_FLAG_NONE    = 0u,
    NTS_FLAG_HYPHENS = 1u << 0,
    NTS_FLAG_COMMAS  = 1u << 1,
    NTS_FLAG_AND     = 1u << 2
};

#define NTS_FLAGS_DEFAULT (NTS_FLAG_HYPHENS | NTS_FLAG_COMMAS | NTS_FLAG_AND)

/*
 * Large enough for any signed 64-bit English output generated by this module,
 * including a terminating null character.
 */
#define NTS_I64_BUFFER_SIZE 256u

/*
 * Writes the English cardinal form of value into dst.
 *
 * Examples:
 *   21   -> "twenty-one"
 *   101  -> "one hundred and one"
 *   1234 -> "one thousand, two hundred and thirty-four"
 *
 * Returns the number of characters that would have been written, excluding the
 * terminating null character. If dst is NULL or dst_cap is 0, no bytes are
 * written and the required length is still returned.
 */
size_t
nts_cardinal_i64(
    char*       dst,
    size_t      dst_cap,
    int64_t     value,
    unsigned    flags
);

/*
 * Writes the English ordinal word form of value into dst.
 *
 * Examples:
 *   21   -> "twenty-first"
 *   101  -> "one hundred and first"
 *   1234 -> "one thousand, two hundred and thirty-fourth"
 *
 * Returns the number of characters that would have been written, excluding the
 * terminating null character. If dst is NULL or dst_cap is 0, no bytes are
 * written and the required length is still returned.
 */
size_t
nts_ordinal_i64(
    char*       dst,
    size_t      dst_cap,
    int64_t     value,
    unsigned    flags
);

/*
 * Writes the abbreviated English ordinal form of value into dst.
 *
 * Examples:
 *   1    -> "1st"
 *   2    -> "2nd"
 *   3    -> "3rd"
 *   11   -> "11th"
 *   1234 -> "1,234th"  (when NTS_FLAG_COMMAS is set)
 *
 * Returns the number of characters that would have been written, excluding the
 * terminating null character. If dst is NULL or dst_cap is 0, no bytes are
 * written and the required length is still returned.
 */
size_t
nts_ordinal_abbrev_i64(
    char*       dst,
    size_t      dst_cap,
    int64_t     value,
    unsigned    flags
);

#ifdef __cplusplus
}
#endif

#endif  // defined(INT64_MAX)

#endif /* DJINTERP_C_TEXT_NUMBER_TO_STRING_EN_H */
