/******************************************************************************
* djinterp [tests]                              test_compress_options_tests.hpp
*
*   Suite header for test_compress_options.hpp - the comparison, pristine and
* diff surface for the compression OPTION vocabulary.  Declares every test
* body, supplies the fixtures the bodies need, and (in DTEST_SPEC_MODE) exposes
* the spec provider the runner hands to run_module.
*
*   BUILD PREREQUISITE - THE RUNNER NEEDS D_TEST_REPORT_ENABLE_ARCHIVE.
*   This is a property of the framework, not of the module under test, and it
* applies to EVERY DTest runner rather than to this suite alone.  A runner
* includes test_defaults.hpp to reach run_module; test_defaults.hpp includes
* output/test_report_runner.hpp; and that header spells `byte_buffer` in two
* places - pending_doc::bytes and write_bytes_to_file's parameter - which is a
* typedef reachable only through the archive include guarded by
* D_TEST_REPORT_ENABLE_ARCHIVE.  Without the macro the runner does not compile
* at C++17 or higher (eight errors).  The leaf CMakeLists therefore defines it
* on the target.  The SECTION translation units do not need it: they include
* the module under test directly and never reach the report machinery.
*
*   The fix belongs in test_report_runner.hpp - spell those two uses
* std::string, or include compress.hpp unconditionally - not here; per the
* authoring guide a broken dependency is reported rather than patched.
*
*   HOW THIS SUITE REACHES 100% FIELD COVERAGE.
*   compress_options carries FIFTY fields: the generic `level` plus forty-nine
* advanced knobs spread over six per-codec blocks.  Every comparator in the
* module is a long conjunction over those fields, and describe_compress_option_
* diff is a matching ladder of fifty tests.  Asserting each by hand would be
* fifty near-identical bodies and would still not prove the two ladders agree.
*
*   So the suite carries ONE table - co_all_mutators() - with one row per
* field.  Each row pairs the exact label the module's diff is required to emit
* ("zstd.window_log") with a mutator that moves that field and nothing else.
* Every row is generated by mutating relative to the current value (+1 for a
* number, negation for a flag, the next enumerator for an enum), so no row
* depends on knowing a field's default, and every mutation is guaranteed to
* differ from a pristine set.
*
*   That single table then drives the whole suite: the comparators must reject
* each mutation, compress_options_are_default must reject each mutation, and
* the diff must name exactly the paired label for each.  A field added to
* compress_options without a matching row shows up as a coverage gap in
* tests_compress_options_mutator_table_is_complete, which pins the count.
*
*   PORTABILITY:
*   The module is C++98-clean; this suite is written to the same baseline
* except for the fixture table, which uses std::vector.  Built at C++20 by the
* DTest CMake helper.
*
*
* TABLE OF CONTENTS
* =================
* I.    BLOCKS       (test_compress_options_tests_blocks.cpp)
* II.   AGGREGATE    (test_compress_options_tests_aggregate.cpp)
* III.  PRISTINE     (test_compress_options_tests_pristine.cpp)
* IV.   DIFF         (test_compress_options_tests_diff.cpp)
* V.    BUILDERS     (test_compress_options_tests_builders.cpp)
*
*
* path:      /tests/djinterp/test/test_compress_options_tests.hpp
* link(s):   TBA
* author(s): DTest contributors                            created: 2026.07.23
******************************************************************************/

#ifndef DJINTERP_TESTS_TEST_COMPRESS_OPTIONS_TESTS_
#define DJINTERP_TESTS_TEST_COMPRESS_OPTIONS_TESTS_ 1

// std
#include <cstddef>
#include <cstdio>
#include <string>
#include <vector>

// -- (part 1) mode-gated includes ------------------------------------------
#include <djinterp/core/djinterp.hpp>
#ifndef DTEST_SPEC_MODE
#include "test_compress_options.hpp"
#endif
#ifdef DTEST_SPEC_MODE
#include "djinterp/test/test_defaults.hpp"
#endif


NS_DJINTERP
NS_TESTING

// dt
//   type: names the entities under test (djinterp::test).  Unconditional,
// because the spec provider needs dt::module_spec in spec mode.
namespace dt = ::djinterp::test;


// compress_options_check
//   function: reports a failed assertion and returns the condition, so the
// D_CO_CHECK macro can early-return on the first failure.
//
// Parameter(s):
//   _cond: the asserted condition.
//   _expr: the stringized expression.
//   _file: the source file of the assertion.
//   _line: the source line of the assertion.
// Return:
//   _cond, unchanged.
inline bool
compress_options_check(
    bool        _cond,
    const char* _expr,
    const char* _file,
    int         _line
)
{
    if (!_cond)
    {
        std::printf("    [FAIL] %s:%d: %s\n", _file, _line, _expr);
    }

    return _cond;
}

// D_CO_CHECK
//   macro: assert _cond, printing the expression and its location and
// returning false from the enclosing test body on failure.  Variadic so a
// top-level comma inside the expression passes through whole.
#define D_CO_CHECK(...)                                                       \
    do                                                                        \
    {                                                                         \
        if (!::djinterp::testing::compress_options_check(                     \
                (__VA_ARGS__), #__VA_ARGS__, __FILE__, __LINE__))             \
        {                                                                     \
            return false;                                                     \
        }                                                                     \
    }                                                                         \
    while (0)


#ifndef DTEST_SPEC_MODE  // (part 1 cont.) fixtures - normal mode only

// dj
//   type: names the foundation namespace the option vocabulary lives in.
namespace dj = ::djinterp;


// co_bump
//   function: the next value of a numeric or enumerated field.  Adding one to
// the CURRENT value keeps every mutator independent of the field's default, so
// a row never has to name a magic constant that a later default change would
// silently invalidate.
template<typename _T>
inline _T
co_bump(
    _T _v
)
{
    return static_cast<_T>(static_cast<int>(_v) + 1);
}

// co_bump_size
//   function: the size_t counterpart of co_bump, kept separate so the cast
// never narrows a 64-bit width through int.
inline std::size_t
co_bump_size(
    std::size_t _v
)
{
    return (_v + 1u);
}


// co_mutator_fn
//   type: moves exactly one field of an option set.
typedef void (*co_mutator_fn)(dj::compress_options&);

// co_field
//   struct: one row of the field table - the diff label the module must emit
// for this field, the codec block it belongs to, and the mutator that moves
// it.  `block` lets a per-block test filter the table without a second copy.
struct co_field
{
    const char*   label;
    const char*   block;
    co_mutator_fn apply;

    co_field(
        const char*   _label,
        const char*   _block,
        co_mutator_fn _apply
    )
        : label(_label),
          block(_block),
          apply(_apply)
    {}
};


// -- the fifty mutators ----------------------------------------------------
//   One per field of compress_options, named after the field it moves.

inline void co_m_level(dj::compress_options& o) { o.level = co_bump(o.level); }

// deflate (3)
inline void co_m_deflate_window_bits(dj::compress_options& o)
    { o.deflate.window_bits = co_bump(o.deflate.window_bits); }
inline void co_m_deflate_mem_level(dj::compress_options& o)
    { o.deflate.mem_level = co_bump(o.deflate.mem_level); }
inline void co_m_deflate_strategy(dj::compress_options& o)
    { o.deflate.strategy = co_bump(o.deflate.strategy); }

// bzip2 (4)
inline void co_m_bzip2_block_size(dj::compress_options& o)
    { o.bzip2.block_size_100k = co_bump(o.bzip2.block_size_100k); }
inline void co_m_bzip2_work_factor(dj::compress_options& o)
    { o.bzip2.work_factor = co_bump(o.bzip2.work_factor); }
inline void co_m_bzip2_verbosity(dj::compress_options& o)
    { o.bzip2.verbosity = co_bump(o.bzip2.verbosity); }
inline void co_m_bzip2_small_decompress(dj::compress_options& o)
    { o.bzip2.small_decompress = !o.bzip2.small_decompress; }

// lzma (11)
inline void co_m_lzma_extreme(dj::compress_options& o)
    { o.lzma.extreme = !o.lzma.extreme; }
inline void co_m_lzma_check(dj::compress_options& o)
    { o.lzma.check = co_bump(o.lzma.check); }
inline void co_m_lzma_dict_size(dj::compress_options& o)
    { o.lzma.dict_size = co_bump_size(o.lzma.dict_size); }
inline void co_m_lzma_lc(dj::compress_options& o)
    { o.lzma.lc = co_bump(o.lzma.lc); }
inline void co_m_lzma_lp(dj::compress_options& o)
    { o.lzma.lp = co_bump(o.lzma.lp); }
inline void co_m_lzma_pb(dj::compress_options& o)
    { o.lzma.pb = co_bump(o.lzma.pb); }
inline void co_m_lzma_mode(dj::compress_options& o)
    { o.lzma.mode = co_bump(o.lzma.mode); }
inline void co_m_lzma_nice_len(dj::compress_options& o)
    { o.lzma.nice_len = co_bump(o.lzma.nice_len); }
inline void co_m_lzma_mf(dj::compress_options& o)
    { o.lzma.mf = co_bump(o.lzma.mf); }
inline void co_m_lzma_depth(dj::compress_options& o)
    { o.lzma.depth = co_bump(o.lzma.depth); }
inline void co_m_lzma_threads(dj::compress_options& o)
    { o.lzma.threads = (o.lzma.threads + 1u); }

// zstd (19)
inline void co_m_zstd_level(dj::compress_options& o)
    { o.zstd.level = co_bump(o.zstd.level); }
inline void co_m_zstd_window_log(dj::compress_options& o)
    { o.zstd.window_log = co_bump(o.zstd.window_log); }
inline void co_m_zstd_hash_log(dj::compress_options& o)
    { o.zstd.hash_log = co_bump(o.zstd.hash_log); }
inline void co_m_zstd_chain_log(dj::compress_options& o)
    { o.zstd.chain_log = co_bump(o.zstd.chain_log); }
inline void co_m_zstd_search_log(dj::compress_options& o)
    { o.zstd.search_log = co_bump(o.zstd.search_log); }
inline void co_m_zstd_min_match(dj::compress_options& o)
    { o.zstd.min_match = co_bump(o.zstd.min_match); }
inline void co_m_zstd_target_length(dj::compress_options& o)
    { o.zstd.target_length = co_bump(o.zstd.target_length); }
inline void co_m_zstd_strategy(dj::compress_options& o)
    { o.zstd.strategy = co_bump(o.zstd.strategy); }
inline void co_m_zstd_ldm(dj::compress_options& o)
    { o.zstd.long_distance_matching = !o.zstd.long_distance_matching; }
inline void co_m_zstd_ldm_hash_log(dj::compress_options& o)
    { o.zstd.ldm_hash_log = co_bump(o.zstd.ldm_hash_log); }
inline void co_m_zstd_ldm_min_match(dj::compress_options& o)
    { o.zstd.ldm_min_match = co_bump(o.zstd.ldm_min_match); }
inline void co_m_zstd_ldm_bucket(dj::compress_options& o)
    { o.zstd.ldm_bucket_size_log = co_bump(o.zstd.ldm_bucket_size_log); }
inline void co_m_zstd_ldm_rate(dj::compress_options& o)
    { o.zstd.ldm_hash_rate_log = co_bump(o.zstd.ldm_hash_rate_log); }
inline void co_m_zstd_content_size(dj::compress_options& o)
    { o.zstd.content_size_flag = !o.zstd.content_size_flag; }
inline void co_m_zstd_checksum(dj::compress_options& o)
    { o.zstd.checksum_flag = !o.zstd.checksum_flag; }
inline void co_m_zstd_dict_id(dj::compress_options& o)
    { o.zstd.dict_id_flag = !o.zstd.dict_id_flag; }
inline void co_m_zstd_workers(dj::compress_options& o)
    { o.zstd.workers = co_bump(o.zstd.workers); }
inline void co_m_zstd_job_size(dj::compress_options& o)
    { o.zstd.job_size = co_bump_size(o.zstd.job_size); }
inline void co_m_zstd_overlap_log(dj::compress_options& o)
    { o.zstd.overlap_log = co_bump(o.zstd.overlap_log); }

// lz4 (7)
inline void co_m_lz4_level(dj::compress_options& o)
    { o.lz4.level = co_bump(o.lz4.level); }
inline void co_m_lz4_block_size(dj::compress_options& o)
    { o.lz4.block_size = co_bump(o.lz4.block_size); }
inline void co_m_lz4_block_mode(dj::compress_options& o)
    { o.lz4.block_mode = co_bump(o.lz4.block_mode); }
inline void co_m_lz4_content_checksum(dj::compress_options& o)
    { o.lz4.content_checksum = !o.lz4.content_checksum; }
inline void co_m_lz4_block_checksum(dj::compress_options& o)
    { o.lz4.block_checksum = !o.lz4.block_checksum; }
inline void co_m_lz4_store_content_size(dj::compress_options& o)
    { o.lz4.store_content_size = !o.lz4.store_content_size; }
inline void co_m_lz4_favor_dec_speed(dj::compress_options& o)
    { o.lz4.favor_dec_speed = !o.lz4.favor_dec_speed; }

// brotli (5)
inline void co_m_brotli_quality(dj::compress_options& o)
    { o.brotli.quality = co_bump(o.brotli.quality); }
inline void co_m_brotli_window_bits(dj::compress_options& o)
    { o.brotli.window_bits = co_bump(o.brotli.window_bits); }
inline void co_m_brotli_block_bits(dj::compress_options& o)
    { o.brotli.block_bits = co_bump(o.brotli.block_bits); }
inline void co_m_brotli_mode(dj::compress_options& o)
    { o.brotli.mode = co_bump(o.brotli.mode); }
inline void co_m_brotli_large_window(dj::compress_options& o)
    { o.brotli.large_window = !o.brotli.large_window; }


// co_all_mutators
//   function: the complete field table - one row per field of
// compress_options, in the order describe_compress_option_diff walks them.
// The order matters: the diff test asserts the emitted list follows it.
inline std::vector<co_field>
co_all_mutators()
{
    std::vector<co_field> t;

    t.push_back(co_field("level", "", &co_m_level));

    t.push_back(co_field("deflate.window_bits", "deflate",
                         &co_m_deflate_window_bits));
    t.push_back(co_field("deflate.mem_level", "deflate",
                         &co_m_deflate_mem_level));
    t.push_back(co_field("deflate.strategy", "deflate",
                         &co_m_deflate_strategy));

    t.push_back(co_field("bzip2.block_size_100k", "bzip2",
                         &co_m_bzip2_block_size));
    t.push_back(co_field("bzip2.work_factor", "bzip2",
                         &co_m_bzip2_work_factor));
    t.push_back(co_field("bzip2.verbosity", "bzip2", &co_m_bzip2_verbosity));
    t.push_back(co_field("bzip2.small_decompress", "bzip2",
                         &co_m_bzip2_small_decompress));

    t.push_back(co_field("lzma.extreme", "lzma", &co_m_lzma_extreme));
    t.push_back(co_field("lzma.check", "lzma", &co_m_lzma_check));
    t.push_back(co_field("lzma.dict_size", "lzma", &co_m_lzma_dict_size));
    t.push_back(co_field("lzma.lc", "lzma", &co_m_lzma_lc));
    t.push_back(co_field("lzma.lp", "lzma", &co_m_lzma_lp));
    t.push_back(co_field("lzma.pb", "lzma", &co_m_lzma_pb));
    t.push_back(co_field("lzma.mode", "lzma", &co_m_lzma_mode));
    t.push_back(co_field("lzma.nice_len", "lzma", &co_m_lzma_nice_len));
    t.push_back(co_field("lzma.mf", "lzma", &co_m_lzma_mf));
    t.push_back(co_field("lzma.depth", "lzma", &co_m_lzma_depth));
    t.push_back(co_field("lzma.threads", "lzma", &co_m_lzma_threads));

    t.push_back(co_field("zstd.level", "zstd", &co_m_zstd_level));
    t.push_back(co_field("zstd.window_log", "zstd", &co_m_zstd_window_log));
    t.push_back(co_field("zstd.hash_log", "zstd", &co_m_zstd_hash_log));
    t.push_back(co_field("zstd.chain_log", "zstd", &co_m_zstd_chain_log));
    t.push_back(co_field("zstd.search_log", "zstd", &co_m_zstd_search_log));
    t.push_back(co_field("zstd.min_match", "zstd", &co_m_zstd_min_match));
    t.push_back(co_field("zstd.target_length", "zstd",
                         &co_m_zstd_target_length));
    t.push_back(co_field("zstd.strategy", "zstd", &co_m_zstd_strategy));
    t.push_back(co_field("zstd.long_distance_matching", "zstd",
                         &co_m_zstd_ldm));
    t.push_back(co_field("zstd.ldm_hash_log", "zstd",
                         &co_m_zstd_ldm_hash_log));
    t.push_back(co_field("zstd.ldm_min_match", "zstd",
                         &co_m_zstd_ldm_min_match));
    t.push_back(co_field("zstd.ldm_bucket_size_log", "zstd",
                         &co_m_zstd_ldm_bucket));
    t.push_back(co_field("zstd.ldm_hash_rate_log", "zstd",
                         &co_m_zstd_ldm_rate));
    t.push_back(co_field("zstd.content_size_flag", "zstd",
                         &co_m_zstd_content_size));
    t.push_back(co_field("zstd.checksum_flag", "zstd", &co_m_zstd_checksum));
    t.push_back(co_field("zstd.dict_id_flag", "zstd", &co_m_zstd_dict_id));
    t.push_back(co_field("zstd.workers", "zstd", &co_m_zstd_workers));
    t.push_back(co_field("zstd.job_size", "zstd", &co_m_zstd_job_size));
    t.push_back(co_field("zstd.overlap_log", "zstd", &co_m_zstd_overlap_log));

    t.push_back(co_field("lz4.level", "lz4", &co_m_lz4_level));
    t.push_back(co_field("lz4.block_size", "lz4", &co_m_lz4_block_size));
    t.push_back(co_field("lz4.block_mode", "lz4", &co_m_lz4_block_mode));
    t.push_back(co_field("lz4.content_checksum", "lz4",
                         &co_m_lz4_content_checksum));
    t.push_back(co_field("lz4.block_checksum", "lz4",
                         &co_m_lz4_block_checksum));
    t.push_back(co_field("lz4.store_content_size", "lz4",
                         &co_m_lz4_store_content_size));
    t.push_back(co_field("lz4.favor_dec_speed", "lz4",
                         &co_m_lz4_favor_dec_speed));

    t.push_back(co_field("brotli.quality", "brotli", &co_m_brotli_quality));
    t.push_back(co_field("brotli.window_bits", "brotli",
                         &co_m_brotli_window_bits));
    t.push_back(co_field("brotli.block_bits", "brotli",
                         &co_m_brotli_block_bits));
    t.push_back(co_field("brotli.mode", "brotli", &co_m_brotli_mode));
    t.push_back(co_field("brotli.large_window", "brotli",
                         &co_m_brotli_large_window));

    return t;
}


// co_mutated
//   function: a pristine option set with row _i of the table applied.
inline dj::compress_options
co_mutated(
    std::size_t _i
)
{
    const std::vector<co_field> t = co_all_mutators();
    dj::compress_options        o;

    if (_i < t.size())
    {
        t[_i].apply(o);
    }

    return o;
}

// co_block_equal
//   function: dispatches to the module's comparator for the named block, so a
// table-driven test can ask "does THIS block's comparator see the change?"
// without a switch at every call site.
inline bool
co_block_equal(
    const char*                 _block,
    const dj::compress_options& _a,
    const dj::compress_options& _b
)
{
    const std::string b(_block);

    if (b == "deflate")
    {
        return dt::deflate_options_equal(_a.deflate, _b.deflate);
    }
    if (b == "bzip2") { return dt::bzip2_options_equal(_a.bzip2, _b.bzip2); }
    if (b == "lzma")  { return dt::lzma_options_equal(_a.lzma, _b.lzma); }
    if (b == "zstd")  { return dt::zstd_options_equal(_a.zstd, _b.zstd); }
    if (b == "lz4")   { return dt::lz4_options_equal(_a.lz4, _b.lz4); }
    if (b == "brotli")
    {
        return dt::brotli_options_equal(_a.brotli, _b.brotli);
    }

    // "" is the generic level, which no per-block comparator owns
    return true;
}

// co_contains
//   function: true iff _hay contains _needle as a substring.
inline bool
co_contains(
    const std::string& _hay,
    const std::string& _needle
)
{
    return (_hay.find(_needle) != std::string::npos);
}

// co_split_csv
//   function: splits a ", "-separated diff string into its field names, so a
// test can assert on exact membership and order rather than substrings (which
// would let "zstd.level" match inside "zstd.level_extra").
inline std::vector<std::string>
co_split_csv(
    const std::string& _s
)
{
    std::vector<std::string> out;
    std::size_t              start = 0;

    if (_s.empty())
    {
        return out;
    }

    for (;;)
    {
        const std::size_t at = _s.find(", ", start);

        if (at == std::string::npos)
        {
            out.push_back(_s.substr(start));
            break;
        }

        out.push_back(_s.substr(start, at - start));
        start = (at + 2u);
    }

    return out;
}

#endif  // !DTEST_SPEC_MODE  (fixtures)


// -- (part 2) declarations - visible in BOTH modes -------------------------

// I.   BLOCKS   (test_compress_options_tests_blocks.cpp)
bool tests_compress_options_deflate_equal_reflexive();
bool tests_compress_options_deflate_equal_all_fields();
bool tests_compress_options_bzip2_equal_all_fields();
bool tests_compress_options_lzma_equal_all_fields();
bool tests_compress_options_zstd_equal_all_fields();
bool tests_compress_options_lz4_equal_all_fields();
bool tests_compress_options_brotli_equal_all_fields();
bool tests_compress_options_blocks_are_independent();
bool tests_compress_options_blocks_ignore_level();

// II.  AGGREGATE   (test_compress_options_tests_aggregate.cpp)
bool tests_compress_options_equal_reflexive();
bool tests_compress_options_equal_symmetric();
bool tests_compress_options_equal_detects_generic_level();
bool tests_compress_options_equal_detects_every_field();
bool tests_compress_options_equal_multi_change();
bool tests_compress_options_equal_survives_copy();

// III. PRISTINE   (test_compress_options_tests_pristine.cpp)
bool tests_compress_options_default_is_pristine();
bool tests_compress_options_default_returns_fresh_value();
bool tests_compress_options_are_default_rejects_all();
bool tests_compress_options_are_default_after_revert();
bool tests_compress_options_mutator_table_is_complete();

// IV.  DIFF   (test_compress_options_tests_diff.cpp)
bool tests_compress_options_diff_empty_when_equal();
bool tests_compress_options_diff_names_every_field();
bool tests_compress_options_diff_is_field_level();
bool tests_compress_options_diff_separator_and_order();
bool tests_compress_options_diff_lists_all_fields_at_once();
bool tests_compress_options_diff_is_symmetric();
bool tests_compress_options_diff_from_default_matches();
bool tests_compress_options_diff_from_default_empty();

// V.   BUILDERS   (test_compress_options_tests_builders.cpp)
bool tests_compress_options_level_builder_scope();
bool tests_compress_options_level_builder_any_value();
bool tests_compress_options_deflate_builder_scope();
bool tests_compress_options_deflate_builder_args();
bool tests_compress_options_zstd_builder_scope();
bool tests_compress_options_zstd_vs_generic_level();


// -- (part 3) the spec provider - spec mode only ---------------------------
#ifdef DTEST_SPEC_MODE

// compress_options_spec
//   function: the suite's authoritative description - one block per section
// TU, one row per test body, each carrying the descriptor the report renders.
inline dt::module_spec
compress_options_spec()
{
    return dt::module_spec{
        "test_compress_options",
        "The data-layer companion to test_compress.hpp: deep equality over "
        "the fifty-field compression option vocabulary, a pristine-default "
        "predicate, a field-level diff description, and the small builders a "
        "suite reaches for when it needs one knob moved.",
        {
            dt::block_spec{
                "blocks",
                "The six per-codec comparators, each checked field by field "
                "from the suite's mutation table, and against one another for "
                "independence.",
                {
                    { "tests_compress_options_deflate_equal_reflexive",
                      "a block compares equal to itself and to an "
                      "independently constructed pristine block",
                      &tests_compress_options_deflate_equal_reflexive },
                    { "tests_compress_options_deflate_equal_all_fields",
                      "all three DEFLATE fields are compared, so moving any "
                      "one of them is detected",
                      &tests_compress_options_deflate_equal_all_fields },
                    { "tests_compress_options_bzip2_equal_all_fields",
                      "all four bzip2 fields are compared",
                      &tests_compress_options_bzip2_equal_all_fields },
                    { "tests_compress_options_lzma_equal_all_fields",
                      "all eleven lzma fields are compared",
                      &tests_compress_options_lzma_equal_all_fields },
                    { "tests_compress_options_zstd_equal_all_fields",
                      "all nineteen zstd fields are compared",
                      &tests_compress_options_zstd_equal_all_fields },
                    { "tests_compress_options_lz4_equal_all_fields",
                      "all seven lz4 fields are compared",
                      &tests_compress_options_lz4_equal_all_fields },
                    { "tests_compress_options_brotli_equal_all_fields",
                      "all five brotli fields are compared",
                      &tests_compress_options_brotli_equal_all_fields },
                    { "tests_compress_options_blocks_are_independent",
                      "moving a field in one block leaves the other five "
                      "comparators reporting equal",
                      &tests_compress_options_blocks_are_independent },
                    { "tests_compress_options_blocks_ignore_level",
                      "the generic level belongs to no block, so moving it "
                      "leaves every block comparator equal",
                      &tests_compress_options_blocks_ignore_level },
                }
            },
            dt::block_spec{
                "aggregate",
                "compress_options_equal over the whole surface: the generic "
                "level plus delegation to all six block comparators.",
                {
                    { "tests_compress_options_equal_reflexive",
                      "a set equals itself, and two independently constructed "
                      "pristine sets are equal",
                      &tests_compress_options_equal_reflexive },
                    { "tests_compress_options_equal_symmetric",
                      "the comparison gives the same answer whichever way "
                      "round its operands are passed",
                      &tests_compress_options_equal_symmetric },
                    { "tests_compress_options_equal_detects_generic_level",
                      "the generic level is compared in its own right, not "
                      "only through a block",
                      &tests_compress_options_equal_detects_generic_level },
                    { "tests_compress_options_equal_detects_every_field",
                      "every one of the fifty fields is reachable by the "
                      "aggregate comparator",
                      &tests_compress_options_equal_detects_every_field },
                    { "tests_compress_options_equal_multi_change",
                      "several simultaneous changes are still detected, and "
                      "reverting all of them restores equality",
                      &tests_compress_options_equal_multi_change },
                    { "tests_compress_options_equal_survives_copy",
                      "a copied option set compares equal to its source, "
                      "field for field",
                      &tests_compress_options_equal_survives_copy },
                }
            },
            dt::block_spec{
                "pristine",
                "The default baseline and the nothing-has-moved predicate, "
                "plus the table-completeness pin that keeps this suite honest "
                "as the vocabulary grows.",
                {
                    { "tests_compress_options_default_is_pristine",
                      "a default-constructed set reports as pristine and "
                      "carries an empty diff",
                      &tests_compress_options_default_is_pristine },
                    { "tests_compress_options_default_returns_fresh_value",
                      "default_compress_options returns a value, so mutating "
                      "the result cannot poison a later call",
                      &tests_compress_options_default_returns_fresh_value },
                    { "tests_compress_options_are_default_rejects_all",
                      "moving any one of the fifty fields makes the pristine "
                      "predicate report false",
                      &tests_compress_options_are_default_rejects_all },
                    { "tests_compress_options_are_default_after_revert",
                      "a set moved and then moved back reports pristine "
                      "again",
                      &tests_compress_options_are_default_after_revert },
                    { "tests_compress_options_mutator_table_is_complete",
                      "the suite's table carries exactly fifty rows with "
                      "unique labels, one per documented field",
                      &tests_compress_options_mutator_table_is_complete },
                }
            },
            dt::block_spec{
                "diff",
                "describe_compress_option_diff: the field-level name it "
                "emits for each of the fifty fields, its separator and "
                "ordering, and the against-pristine convenience.",
                {
                    { "tests_compress_options_diff_empty_when_equal",
                      "two identical sets produce an empty diff string",
                      &tests_compress_options_diff_empty_when_equal },
                    { "tests_compress_options_diff_names_every_field",
                      "each single-field change produces exactly that field's "
                      "documented name and nothing else",
                      &tests_compress_options_diff_names_every_field },
                    { "tests_compress_options_diff_is_field_level",
                      "a codec knob is named down to the field, qualified by "
                      "its block, never collapsed to the block alone",
                      &tests_compress_options_diff_is_field_level },
                    { "tests_compress_options_diff_separator_and_order",
                      "several changed fields are joined by a comma and a "
                      "space, in the module's declaration order",
                      &tests_compress_options_diff_separator_and_order },
                    { "tests_compress_options_diff_lists_all_fields_at_once",
                      "a set with every field moved names all fifty, once "
                      "each",
                      &tests_compress_options_diff_lists_all_fields_at_once },
                    { "tests_compress_options_diff_is_symmetric",
                      "the diff names the same fields whichever way round the "
                      "two sets are passed",
                      &tests_compress_options_diff_is_symmetric },
                    { "tests_compress_options_diff_from_default_matches",
                      "the against-pristine convenience agrees with an "
                      "explicit comparison against a fresh set",
                      &tests_compress_options_diff_from_default_matches },
                    { "tests_compress_options_diff_from_default_empty",
                      "a pristine set reports no change from default",
                      &tests_compress_options_diff_from_default_empty },
                }
            },
            dt::block_spec{
                "builders",
                "The one-knob presets: each must move exactly what it names "
                "and leave the rest of the fifty-field surface pristine.",
                {
                    { "tests_compress_options_level_builder_scope",
                      "the generic-level preset moves level and nothing else",
                      &tests_compress_options_level_builder_scope },
                    { "tests_compress_options_level_builder_any_value",
                      "the preset carries negative, zero and large efforts "
                      "through unclamped",
                      &tests_compress_options_level_builder_any_value },
                    { "tests_compress_options_deflate_builder_scope",
                      "the DEFLATE preset leaves the other five blocks and "
                      "the generic level pristine",
                      &tests_compress_options_deflate_builder_scope },
                    { "tests_compress_options_deflate_builder_args",
                      "all three DEFLATE arguments reach their fields "
                      "unchanged",
                      &tests_compress_options_deflate_builder_args },
                    { "tests_compress_options_zstd_builder_scope",
                      "the zstd preset moves zstd.level alone, leaving the "
                      "other eighteen zstd knobs pristine",
                      &tests_compress_options_zstd_builder_scope },
                    { "tests_compress_options_zstd_vs_generic_level",
                      "the generic and zstd levels are separate fields, so "
                      "the two presets produce different sets",
                      &tests_compress_options_zstd_vs_generic_level },
                }
            },
        }
    };
}

#endif  // DTEST_SPEC_MODE


NS_END  // testing
NS_END  // djinterp


#endif  // DJINTERP_TESTS_TEST_COMPRESS_OPTIONS_TESTS_
