/*******************************************************************************
* djinterp [parse]                                                 lex_unicode.h
*
* UTF-8 decoding and the identifier character classes of C and C++.
*   Which code points may appear in an identifier is a fact about the
* standard, and the standards disagree: C99 and C11 each published a closed
* table in an annex, and C23 and C++ replaced both with UAX #31's XID_Start
* and XID_Continue, which move with every Unicode release.  The set a dialect
* uses is one of the D_LEX_IDSET_* constants below, and every test here takes
* it, so the scanner asks one question whatever the language.
*   C++ uses UAX #31 at every level.  P1949 was adopted for C++23 as a defect
* report against the earlier standards, and both major compilers apply it
* retroactively; C, which made no such change, keeps its annexes until C23.
*   The tables are generated by tools/gen_unicode.py from the Unicode
* Character Database and are never edited by hand; d_lex_unicode_version
* names the release they came from.
*
*
* path:      /inc/djinterp/parse/lex/lex_unicode.h
* link(s):   TBA
* author(s): Samuel 'teer' Neal-Blim                         created: 2026.09.22
*                                                            revised: 2026.10.02
*******************************************************************************/

/*
TABLE OF CONTENTS
=================
1.  CONSTANTS
    ---------
    1.  Identifier sets
         1.  D_LEX_IDSET_NONE
         2.  D_LEX_IDSET_C99
         3.  D_LEX_IDSET_C11
         4.  D_LEX_IDSET_XID
    2.  Normalization
         1.  d_lex_nfc_check
2.  OPERATIONS
    ----------
    1.  UTF-8
    2.  Code points
    3.  Identifier classes
    4.  Normalization
*/

#ifndef DJINTERP_PARSE_LEX_LEX_UNICODE_H
#define DJINTERP_PARSE_LEX_LEX_UNICODE_H 1

// std
#include <stdbool.h>  // bool
#include <stddef.h>   // size_t
// re_std
#include "../../../re_std/cstdint/dstdint.h"  // uint32_t


//==============================================================================
// 1.  CONSTANTS
//==============================================================================


// 1.1    Identifier sets
//------------------------------------------------------------------------------
// 1.1.1
// D_LEX_IDSET_NONE
//   constant: only the basic identifier characters; C89 has no other.
#define D_LEX_IDSET_NONE  0u

// 1.1.2
// D_LEX_IDSET_C99
//   constant: ISO/IEC 9899:1999 Annex D, whose digits may not begin a name.
#define D_LEX_IDSET_C99   1u

// 1.1.3
// D_LEX_IDSET_C11
//   constant: ISO/IEC 9899:2011 Annex D, shared by C17; D.2 may not begin a
// name.
#define D_LEX_IDSET_C11   2u

// 1.1.4
// D_LEX_IDSET_XID
//   constant: UAX #31 XID_Start and XID_Continue, for C23 and all of C++.
#define D_LEX_IDSET_XID   3u

// 1.2    Normalization
//------------------------------------------------------------------------------
// 1.2.1
// d_lex_nfc_check
//   enum: the UAX #15 quick-check answer for one code point.  NO is final: a
// name containing the character is not in NFC.  MAYBE means the character may
// compose with the one before it, so only a full normalization can decide.
enum d_lex_nfc_check
{
    D_LEX_NFC_YES   = 0,
    D_LEX_NFC_MAYBE = 1,
    D_LEX_NFC_NO    = 2
};


//==============================================================================
// 2.  OPERATIONS
//==============================================================================


// 2.1    UTF-8
//------------------------------------------------------------------------------
// decoding is phase 1's and lives in source_reader.h as d_source_utf8_decode;
// the encoded length of a code point, 0 for one that is not a scalar value
size_t       d_lex_utf8_length(uint32_t _code_point);

// 2.2    Code points
//------------------------------------------------------------------------------
// a Unicode scalar value: at most U+10FFFF and not a surrogate
bool         d_lex_unicode_is_scalar(uint32_t _code_point);

// 2.3    Identifier classes
//------------------------------------------------------------------------------
// both answer false for an unknown set and for ASCII, whose identifier
// characters the scanner tests directly; `_set` is a D_LEX_IDSET_* value
bool         d_lex_unicode_is_id_start(unsigned _set,
                                       uint32_t _code_point);
bool         d_lex_unicode_is_id_continue(unsigned _set,
                                          uint32_t _code_point);

// 2.4    Normalization
//------------------------------------------------------------------------------
// the quick check and the release the tables were generated from
int          d_lex_unicode_nfc_check(uint32_t _code_point);
/**
 * @brief Decides whether a sequence of code points is in NFC.
 *
 * @note Exact when `_complete`: the sequence is decomposed, reordered and
 *       recomposed by UAX #15 and compared with itself.  When the caller
 *       holds only part of a name, only the quick check's definite answers --
 *       a NO character, or combining marks out of canonical order -- count,
 *       so the result can miss a violation but never invents one.
 *
 * @param[in] _code_points  the sequence.
 * @param[in] _count        its length.
 * @param[in] _complete     whether the sequence is the whole name.
 * @return `true` if the sequence is in NFC, or could not be shown not to be.
 */
bool         d_lex_unicode_is_nfc(const uint32_t* _code_points,
                                  size_t          _count,
                                  bool            _complete);
const char*  d_lex_unicode_version(void);


#endif  // DJINTERP_PARSE_LEX_LEX_UNICODE_H
